### ISSUE TITLE
Delay time before apply filter (3.9.0)

### ISSUE THREAD

**Issue by Aermec** [sqlitebrowser/sqlitebrowser#490] opened 2016-01-11 07:51 UTC
Is it possible to set to 0 this delay time (it's a bit annoying waiting the app refresh the list)?
Or create a preference item where insert the delay time...

**Comment by justinclift** [comment] 2016-01-11 10:47
From memory, there's a key combination you can press to refresh it manually too, if that helps.  Trying to remember what the key combination is though... drawing a blank.  F5 on Windows, ⌘-R on OSX maybe? (not idea for Linux... may be window manager dependent?)

**Comment by MKleusberg** [comment] 2016-01-27 21:29
Thanks for the suggestion. The filters were applied after a delay time of 300 ms for users editing large tables. You could leave the filter e.g. by hitting Tab or you could hit Return to apply the filter instantaneously.
To improve this behaviour I've introduced a new option in the Preferences dialog for setting the delay time. You can disable the delay altogether as well by setting it to 0. I've also reduced the default waiting time to 200 ms. Please let me know if the changes work for you :smile: You can test them by downloading the next nightly build :smile:

**Comment by MKleusberg** [comment] 2016-02-04 19:57
@Aermec Did you have the time to try the nightly build yet? :smile:

**Comment by Aermec** [comment] 2016-02-05 09:28
Sorry for the delay (busy time).
I just tryed and it works well.
But I noticed that app is very very slow if showing very large table (with or without the delay time)

**Comment by justinclift** [comment] 2016-02-05 16:22
Not sure, but it might be due to this commit.  That one is a first tentative attempt to fix a different problem: https://github.com/sqlitebrowser/sqlitebrowser/commit/6784a6a854813bc6577f81c4300d8983abb3cee9

If that one really is the cause of the slow down, we'll need to find a different solution for that one. :wink:

**Comment by MKleusberg** [comment] 2017-01-06 18:26
Yes, that was the commit that caused the application to slow down, effectively disabling the block prefetch feature. That performance bug got fixed in the meantime, so it should all be fine now :smiley:

Also, I'm going to close this issue because the filter delay seems to work fine :smiley:

**Closed by MKleusberg** 2017-01-06 18:26 UTC
Labels: enhancement

**Comment by revolter** [comment] 2017-01-09 16:02
Wow, I always thought it takes a little because the table is large, didn't know there was a delay there. A big thanks from me, too, @MKleusberg!

**Comment by MKleusberg** [comment] 2017-01-11 19:17
Thanks :smile_cat:
