### ISSUE TITLE
DB Browser for Sqlite does not open correctly through HTTPS Proxy

### ISSUE THREAD

**Issue by josephbui** [sqlitebrowser/sqlitebrowser#1311] opened 2018-01-31 19:04 UTC
### Details for the issue

When initially installed on MacOS, the checkversion.enabled preference defaults to true. This causes DB4S to attempt to connect to githubusercontent.com to check for a newer version. If you are working at a place with a man-in-the-middle HTTPS proxy, the proxy returns an SSL certificate that is not valid for githubusercontent.com, which causes an error in DB4S that causes it to immediately close. Users in such a situation can not get DB4S to start, so they are unable to change the setting from within DB4S. The workaround for this is to use the command line preferences editor on MacOS. This command will disable the version check:

`defaults write "com.sqlitebrowser.sqlitebrowser" checkversion.enabled -bool false`

DB4S should catch the SSL certificate error and ignore it. Optionally, when there is an SSL certificate error open a dialog to warn the user and give instructions to disable the new version check.

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( 10.11.6 El Capitan )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2018-01-31 22:02
Thanks for reporting this @josephbui, that does sound pretty lousy.  We should definitely fail gracefully (eg with warning and option to disable the check) instead of crashing. :smile:

**Comment by chrisjlocke** [comment] 2018-01-31 22:09
Actually, a similar thing happens on Windows. When I run a nightly, Avast runs it in a sandbox environment first, which always crashes. Avast then allows it, and it runs normally. I always put it down to Avast, but @josephbui's detailed explaination kinda casts a different light on it. I'll have to try again with no network connection, or limiting it's connection.

**Comment by chrisjlocke** [comment] 2018-02-01 16:15
Disabling the network card in Windows gives a graceful (sort of...) error:

![image](https://user-images.githubusercontent.com/7872218/35689126-b1626b8e-076a-11e8-889c-6b21aa820a4c.png)

If I block 'raw.githubusercontent.com' in Windows so it can't find it (well, map it to 127.0.0.1) then I get the same error as @josephbui and the same crash.

![image](https://user-images.githubusercontent.com/7872218/35689232-e7fefad6-076a-11e8-9ece-7beac9ed061f.png)

![image](https://user-images.githubusercontent.com/7872218/35689265-f72d553e-076a-11e8-8acc-06998d788a8f.png)

So easily re-producable.  I've winDbg on this machine, but presume 'someone' doesn't need further details at this stage.....

**Comment by mgrojo** [comment] 2018-02-01 19:37
@chrisjlocke I cannot reproduce the same error under Linux:
![imagen](https://user-images.githubusercontent.com/13812910/35698820-81525aac-078e-11e8-9507-794b9659b0da.png)

Does your localhost have an https server?

**Comment by mgrojo** [comment] 2018-02-01 19:51
I've mapped  'raw.githubusercontent.com' to another https host and I've reproduced the error, but not the crash :confused:

![imagen](https://user-images.githubusercontent.com/13812910/35699343-0c1a4176-0790-11e8-8e32-ff068ff03dbb.png)

**Comment by jungle-boogie** [comment] 2018-02-01 19:54
How are remote databases added to the browser, anyhow?

**Comment by justinclift** [comment] 2018-02-01 20:00
Using the "Remote" panel.

Hmmm, rough memory says that still needs work too.  I **think** that although downloading them works, there were some bugs in re-uploading or re-downloading.  I'd need to check (very overdue). :wink:

**Comment by jungle-boogie** [comment] 2018-02-01 20:18
Hi @justinclift,

I do see the remote tab, but I don't see any way to add a new connection. Right-clicking on the text area doesn't show any menu; clicking the gear doesn't generate any dialogue; the identity field is empty.

**Comment by justinclift** [comment] 2018-02-01 20:34
Ahhh, that's right.  We haven't gotten around to anonymous access yet.

It's **fairly** easy to add an identity, though could still be streamlined somewhat. :smile:

1. Login to the dbhub.io website (use your GitHub credentials or whatever you want)
2. Click the button to create a DB4S certificate (that's your identify).  That'll give you a certificate file (save it somewhere).
3. In DB4S Preferences there's a remote tab, in the lower half there's a button to add a new cert.  Click that, and give it the certificate file.

Now the Remote panel should work. :smile:

**Comment by mgrojo** [comment] 2018-02-01 20:54
@justinclift I think we can add that instructions to the 'What's This' information of the Remote pane. We should use that feature more often, since it gives contextual help. In this case @jungle-boogie would have discover the instructions through the context menu option ('What's This?'). What about this (please, correct the wording and style):

> This pane is for adding remote databases from the dbhub.io website to DB4S. First you need to get an identity:
>1. Login to the dbhub.io website (use your GitHub credentials or whatever you want)
>2. Click the button to create a DB4S certificate (that's your identity). That'll give you a certificate file (save it to your local disk).
>3. Go to the Remote tab in DB4S Preferences. Click the button to add a new certificate and choose the just downloaded certificate file.
>Now the Remote panel shows your identity and you can add remote databases.

The only drawback is more work for translators, but they can left those help parts untranslated if they want. For the average user that is better than nothing.

**Comment by mgrojo** [comment] 2018-02-01 20:58
Ups, I'm followed the instructions and:

![imagen](https://user-images.githubusercontent.com/13812910/35703018-04c976ac-079b-11e8-8c16-20a689903dab.png)

**Comment by justinclift** [comment] 2018-02-01 21:01
Oops, I probably need to regenerate one of the cert bits on the server.

I've been meaning to move the server to the main "dbhub.io" domain, and was going to get it all done at the same time.

Gimme a minute, and I'll see if I can get the need cert change bit done right away.  If not, I'll get the whole servername move and cert change update done later on today. (am doing something else atm)

**Comment by justinclift** [comment] 2018-02-01 21:02
@jungle-boogie You'll probably have the same problem too. :smile:

**Comment by jungle-boogie** [comment] 2018-02-01 21:07
Hi @justinclift, yep, I added it, but it's expired. That'll give me to time find a database and upload to your website, though.

**Comment by jungle-boogie** [comment] 2018-02-01 21:16
hi @mgrojo, my only recommendation with the instructions would be to change this part:
>  Click the button to add a new certificate

It seems you actually want to generate a new cert. I understand you copied and pasted from Justin, so I'm only pointing out for clarification.

**Comment by justinclift** [comment] 2018-02-01 21:38
@mgrojo Good point.   Help text like that would be useful.  :smile:

Just noticed the first line is missing a full stop on the end.  Might as well adjust that for consistency.

@jungle-boogie The button in the DB4S interface adds the certificate generated by the dbhub.io website in the previous step.  So kind of thinking the wording proposed by @mgrojo seems ok?

**Comment by justinclift** [comment] 2018-02-01 21:47
Ahhh yep.  The intermediate certificate generation used for creating the DB4S identity certificates expired on 27th Jan.

That's going to take a bit of work to re-update for everything, so I'll get it done later on today.

**Comment by jungle-boogie** [comment] 2018-02-01 22:02
Good with me, @justinclift

**Comment by justinclift** [comment] 2018-02-02 08:33
@jungle-boogie @mgrojo Haven't got the intermediate cert redone yet, and I need sleep, so it'll have to wait until tomorrow.  Sorry for the delay. 👼

**Comment by justinclift** [comment] 2018-02-08 14:48
@jungle-boogie @mgrojo Finally got time to look into the cert problem properly.  It wasn't an expired intermediate certificate, instead it was a different expired certificate.  I've just recreated it (with a 1 year validity this time), and verified it's now creating working certificates.

You'll need to regenerate the certificate in the DBHub.io web interface.  There's a dropdown to "Generate DB4S certificate" on the main page once you login.  That'll create a brand new (working) one, etc.

Sorry for the delay with this.  More urgent stuff popped up (this being a non-production server and all. :smile:

**Comment by jungle-boogie** [comment] 2018-02-08 15:46
Hi @justinclift, fantastic job! I'm able to connect and browse the repos.
Very neat, thank you!

**Comment by justinclift** [comment] 2018-02-08 15:54
Excellent.  At some point we'll probably want to figure out how to add categories or something to the Remote panel.  Especially if lots of reference data gets uploaded, to the point where it becomes hard to find things.

**Comment by MKleusberg** [comment] 2018-03-07 18:20
@chrisjlocke Since you've mentioned it, can you check where exactly it crashes using WinDbg? I get the same error as @mgrojo but can't reproduce the crash.

**Comment by mgrojo** [comment] 2018-05-08 18:54
Could we add an option in the Windows installer so users without internet connection can set the automatic update off from the beginning? At least would improve the situation a bit.

**Comment by justinclift** [comment] 2018-05-21 11:12
That sounds like a good idea, however I have absolutely no idea how to get it done.

We'd need to generate some kind of extra page or dialog in the installer with associated code to run for the "turn off automatic updates?" answer.

**Comment by ceresith** [comment] 2019-02-08 09:28
For everyone else who got stuck by this issue on Windows:

**Go to regedit, HKCU/Software/sqlitebrowser/sqlitebrowser/checkversion
Create a DWORD "enabled" with value 0**

Fixing the crash would be great though, as without editing the value in the registry you have no chance to get to the preferences window.

**Comment by justinclift** [comment] 2019-02-08 09:50
Oh, there's a command line switch approach to setting options now too.

But yeah, not crashing when the remote server can't be found would be better.

**Comment by chrisjlocke** [comment] 2019-02-08 10:20
@ceresith - or update to the latest 3.11 version, which shouldn't have this issue anymore...

**Comment by MKleusberg** [comment] 2019-05-09 13:18
Since it is related to this issue I thought I would mention it here too: Starting with tomorrow's nightly build there is a new button in the Remote tab of the Preferences dialog which allows you to configure the proxy to use. By default we'll also try to use the system settings for proxies.

So while we still don't detect systems without a network connection and I still don't know where and why it crashes for some users, the chances of running into a problem are a lot smaller now :smile:

**Comment by justinclift** [comment] 2019-05-09 13:45
Oh wow.  This is **huge**.

Had been thinking about this the other day, knowing it's important... just didn't know what kind of effort it'd take to get done.

What kind of proxies should work?  eg HTTPS/SOCK4/SOCK5/etc?

**Comment by justinclift** [comment] 2019-05-09 13:47
Ahhh, I should have looked first.  HTTP and SOCKS5 are mentioned in the initial commit (https://github.com/sqlitebrowser/sqlitebrowser/commit/38ece2ea425c9c9000b4cddb381a60287cec1efa). :smile:

**Comment by justinclift** [comment] 2019-05-10 11:35
It's working with the HTTP mode. :smile:

Tested just now with a close-to-defaults Squid proxy server on CentOS 7 x64.

Did need to add port 5550 to the list of `SSL_ports` in the Squid configuration file (`/etc/squid/squid.conf`), so the traffic was allowed through.

On that note, we should probably have the DB4S end point code (db4s.dbhub.io), listen on port 443 too.  That should let most places be able to connect to it without needing to open special ports (etc).

**Comment by MKleusberg** [comment] 2020-02-14 10:34
Closing this because we had proxy support in DB4S for some time now. So in theory this crash should be gone :smile: Digging into the causes of the crash itself is probably not worth it right now because so much of our code changed and the libraries we use were updated too. But if this is still causing any sorts of problem with the latest version, please just re-open this issue :smile:

**Closed by MKleusberg** 2020-02-14 10:34 UTC
Labels: crash
