### ISSUE TITLE
Export/import problem

### ISSUE THREAD

**Issue by Rocky640** [sqlitebrowser/sqlitebrowser#352] opened 2015-06-11 18:40 UTC
When a table is empty an you export, (suing the first 2 checkbox)
it will export an additional ); just after the create table.
Consequently, It makes an error  when you import,

**Comment by justinclift** [comment] 2015-06-11 18:46
Would you be ok to try out the latest nightly build? (download locations are listed on the front page of our repo)

To me, this sounds like a duplicate of a bug fixed yesterday: https://github.com/sqlitebrowser/sqlitebrowser/issues/349.

If you try the latest nightly, and it still happens though... it's a new bug we need to look at. :wink:

**Comment by Rocky640** [comment] 2015-06-11 18:57
It works with the latest nightly build.
Thanks !!!!

**Comment by justinclift** [comment] 2015-06-11 19:02
You're welcome.  Thanks for taking the time to write up a bug report.  Without bug reports stuff just wouldn't get fixed. :wink:

**Closed by justinclift** 2015-06-11 19:02 UTC
