### ISSUE TITLE
Column with INTEGER Data Type, accepts insert of text.

### ISSUE THREAD

**Issue by cehstephen** [sqlitebrowser/sqlitebrowser#1832] opened 2019-04-01 09:41 UTC
Details for the issue
--------------------

#### What did you do?
I defined StudentID as INTEGER 

#### What did you expect to see?
I expected it to accept only INTEGERS

#### What did you see instead?
I accepted TEXT, and INTEGERS 

Useful extra information
-------------------------
> DB4S v3.11.1 [built for i386-little_endian-ilp32] on Windows 10 (winnt/10.0.17134) [x86_64]
> using SQLite Version 3.27.1
> and Qt 5.7.1

**Comment by justinclift** [comment] 2019-04-01 09:56
Ahhh, yeah this is one of the key differences between SQLite and most other databases:

&nbsp; &nbsp; https://www.sqlite.org/datatype3.html

For lots of situations, it's a useful thing.  But, if you're unaware of it + relying on enforcement of data types it'll feel like a bug. :man_shrugging:

**Comment by chrisjlocke** [comment] 2019-04-01 09:58
This is more to do with SQLite than DB4S.  
While you can define a column to have a specific affinity, SQLite doesn't 'honour' this (it does, but not in the sense of what you can put in it)
SQLite will happily let you put text in a column with numeric affinity, numbers in a column with text affinity, etc.  This is by design.
https://www.sqlite.org/datatype3.html

"Any column in an SQLite version 3 database, except an INTEGER PRIMARY KEY column, may be used to store a value of any storage class."
"The type affinity of a column is the recommended type for data stored in that column. The important idea here is that the type is recommended, not required. Any column can still store any type of data."

It would therefore be wrong of DB4S to restrict data input based on the column affinity.  

So again, this isn't an issue with DB4S.

If you require more information, please yell.

**Comment by cehstephen** [comment] 2019-04-02 07:26
Alright, noted. 
**It can lead to lots issues, if data is not well checked and cleaned before storage in the SQLite version 3 database.**

**Comment by justinclift** [comment] 2019-04-02 07:57
Yep, pretty much. :smile:

Is it ok if we close this issue?  Am thinking there's not really much we can do to "fix" this :wink:, and you've got an understanding of the problem now. :smile:

**Comment by chrisjlocke** [comment] 2019-04-02 08:17
> It can lead to lots of issues, if data is not well checked 

SQLite is just a container.  Its up to the application to put data in that container.  Think of a soda bottle.  The label could have "Lemonade" on it, but there's nothing stopping you putting orange juice in it.  Or squashed bananas.  Or paperclips.  The label doesn't prevent, stop or control what goes into that container.

**Closed** 2019-04-02 09:15 UTC
