### ISSUE TITLE
Apparent Error Message on Command Line when Editing Table Properties

### ISSUE THREAD

**Issue by scottfurry** [sqlitebrowser/sqlitebrowser#1868] opened 2019-05-01 18:39 UTC
Details for the issue
--------------------
#### What did you do?
Program called from command line.
Existing valid database file opened successfully.
Select, via menu or toolbar, "Modify Table"
Program produces Edit Table Dialog properly populated with table details.
For both "OKAY" or "CANCEL" choice, the following warning message is printed:

    "didn't receive any output from PRAGMA \"main\".foreign_key_check"

#### What did you expect to see?
No warning or error like message during normal usage

Useful extra information
-------------------------
Documenting found behaviour.
Intent is to track down function producing this call.
An error message of this type should not appear during normal usage.

#### What operating system are you using?
- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro: Funtoo LTS )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [X] Other: git HEAD a1b43bca

#### Did you also
- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2019-05-01 19:15
Sounds like it'll probably have a similar root cause to #1867. :smile:

**Comment by MKleusberg** [comment] 2019-05-01 20:15
Thanks! I noticed that a while ago too but always forgot to fix it. It's a completely harmless error message - but that's kind of the problem here: When there is no error, why print an error message? Should be fixed now :smile:

**Comment by scottfurry** [comment] 2019-05-01 20:20
@MKleusberg  - and now it's a numbered issued easily referenced in other conversations, and/or searchable by an unsuspecting user. One of us will get to this soon.... (probably me this week maybe).

**Comment by justinclift** [comment] 2019-05-01 20:35
@scottfurry It seems like it's fixed already? :smile:

**Comment by scottfurry** [comment] 2019-05-01 20:42
@MKleusberg  - are we masking out a possible error change w/ last commit?
`else` clause also handled case where return value was SQLITE_ERROR, right?
https://www.sqlite.org/c3ref/step.html

**Comment by MKleusberg** [comment] 2019-05-01 20:46
@scottfurry It still does handle the case of SQLITE_ERROR in the else path (because SQLITE_ERROR != SQLITE_DONE). The only change is to do nothing when we got a SQLITE_DONE result - neither trying to get a value nor printing an error message.

**Comment by scottfurry** [comment] 2019-05-01 20:48
... but only for the prepare statement...

**Closed** 2019-05-01 20:55 UTC
Labels: bug

**Comment by MKleusberg** [comment] 2019-05-01 21:03
Did you figure it out? I'm happy to explain my understanding here and answer any questions :smile:

**Comment by scottfurry** [comment] 2019-05-01 21:07
@MKleusberg  - I think I got. Gist is return value of SQLITE_ROW( got valid data), SQLITE_DONE(statement query returned all available data), or something else. Using (!SQLITE_DONE) handles the latter. Had to read the underlying API docs.

Maybe scope creep, but see that DB4S uses 'v2'. There's now a 'v3' variant available. ;-)

**Comment by MKleusberg** [comment] 2019-05-01 21:17
Awesome :smile: That was exactly the intention here.

And you're right, we're only always using ```v2```. We're also using e.g. ```sqlite3_create_collation``` instead of ```sqlite3_create_collation_v2```. SQLite has some of these ```*_v2``` or ```*_v3``` functions. They are introduced whenever the parameters of a function change in a way which breaks backwards compatibility. So the "old" versions are likely to stay forever. And as long as you don't need the extra parameters (for ```sqlite_prepare_v3``` it's the ```prepFlags``` parameter which provides [some flags](https://sqlite.org/c3ref/c_prepare_normalize.html) which we don't want to set here anyway) you're safe to use the "old" version of the function.

**Comment by justinclift** [comment] 2019-05-01 21:28
As a general concept, sometimes keeping with the older API versions helps cater to our users with older operating systems.  eg it's not a "must always use oldest versions of everything!" rule, as that would probably suck from a development point of view.  There's a balance to it.  Sort of. :smile:
