### ISSUE TITLE
Add search - replace option into the Browse Data panel

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1608] opened 2018-11-11 22:24 UTC
Describe the new feature
--------------------------
At present, it is not possible, as regards the BROWSE DATA panel, to search in ALL columns in one shot.
You are forced to search, by way of a filter, into every single column until you find what your looking for.
In short, you apply your filter "only " per colum which means you type your word in many follwoing columns, at random, until you are done searching.

On the contrary, this feature is available with Microsoft Excel or LibreOffice Calc in that you are able to find a word in all columns no matter where the text is located.
With some browsers such as Mozilla Firefox or Google Chrome there is a shortcut, that is CTR+F which allows you to do so. A little underneath panel appears and you can start looking for anything in the current web page (backward and forward).

Needless to say, the final icing on the cake would be to have an extra option to search AND replace your text in the Browse Data panel albeit I suppose this extra option would be extremely hard to code :-)

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
There is also #147 (global search, it could be done with the find panel/dialog if it does not stop at the current table) and #1338 (it seems basically also a request for a global search).

#### Does this feature exist in another product or project? Please provide a link.
This feature is currently present in SqliteStudio, an open source software.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Here is a screenie from SqliteStudio:

![sqlistudio png](https://user-images.githubusercontent.com/33007383/48319012-79a84d80-e608-11e8-8423-4b15486916d6.jpg)

**Comment by SilvioGrosso** [comment] 2018-11-13 12:05
Hello @chrisjlocke,

> Goodness knows how a search and replace would work

Just tried this "search feature" on SqliteStudio (Windows 10 - 64 bit) where it is already available :-)
My computer has got an Intel I7 CPU and 8 gb RAM.
My table has 74 columns and 7350 rows (but many records are NULL...).
It takes only a few milliseconds to get my results, that is rows, with SqliteStudio.

But yep, I do agree this same search might takes a lot with HUGE databases.
But, in all truth, I am not 100% sure I would work with Sqlite with such big monsters: probably I would opt for PostgreSQL 11 instead.

In the end, IMHO, it all depends on the target of users related to Db Sqlite Browser. 
For instance, if these users already work with spreadsheets (Excel, Calc etc), which usually are not huge as size, they might find handy this option whenever they decide to export their data as CSV into Db Sqlite Browser. At present, you are forced to write an SQL query to get the same result (OR | OR | OR etc).

Thanks a lot for your reply!

**Comment by MKleusberg** [comment] 2019-09-16 20:46
Maybe to prove some point about motivation or so (see issue #1992), I started looking into this :wink: There's still no search and replace but I have added a "global" filter bar to the toolbar:
![Screenshot_20190916_224111](https://user-images.githubusercontent.com/3153504/64992077-712d3d00-d8d3-11e9-960d-4483645e4970.png)
If there are multiple words separated by spaces in the new field all of them have to match. The usual filter operators should work too, so you can type in stuff like "=NULL test". As usual, can you check tomorrow's nightly build and see if it's working for you as expected?

**Comment by SilvioGrosso** [comment] 2019-09-17 19:01
Hello @MKleusberg 

It works extremely well, as expcted!
Here is a screenie on Windows 10:
<img width="456" alt="2019-09-17" src="https://user-images.githubusercontent.com/33007383/65071066-21f81280-d98e-11e9-9192-72f8e4fb4684.png">

**Comment by mgrojo** [comment] 2019-09-17 22:07
Martin, that was efficiency!

I've seen that the filter is also applied to the rowid. It might be unexpected for the user. Should it only be used for the global filter when visible?

**Comment by mgrojo** [comment] 2019-09-17 22:10
> E.g. > 1600 in the screenshot does not work (2 rows should be filtered instead, in the salary column):

Maybe the text vs. numeric sort is taking here some part, and the filter is positive for the birth column and not for the salary one.

**Comment by SilvioGrosso** [comment] 2019-09-18 03:46
> Maybe the text vs. numeric sort is taking here some part, and the filter is positive for the birth column and not for the salary one.

Yes. In all truth, I don't know whether it is really a "bug" or the way Sqlite acts interneally (no strictly datatype associated).

It looks strange though because the standar filter work in the Browse data, both with number and date, but in this case we are doing a filter on a single column *not* on the whole databases (such as the "global filter" instead).

To recap if I filter the last "salary" column with the standard filter >1600 works, and I get 2 rows as a result. On the contrary, If I use the  new "global filter" no filter is applied (same occurs with date)

**Comment by MKleusberg** [comment] 2019-09-26 14:27
I think the problem with the ```>, >=, <=, <, ...``` operators isn't really worth avoiding at the moment. It looks like it is caused by the text columns - you can check by typing ```>1600``` into the filter field for ```name```. And of course if it matches one column, the row is shown. We could detect the operators and convert the contents of the cells to numbers to avoid this, but a string would then probably convert to 0 which again matches for some combinations.

As for the rowid: The current idea is to look in all columns, including the rowid and the hidden columns. Originally I implemented it this way because it's simpler to program :wink: But I think it has one big advantage too. Let's say you have a global filter and you see only a part of the rows. Sorting, changing display formats, setting the encoding, etc. all don't change the displayed rows. So as a user I wouldn't expect that hiding/unhiding a column or toggling the visibility of the rowid column change the displayed rows either - after all that's just changing the visualisation of the data, not the filters. And that's why I would leave it this way :smile:

**Comment by MKleusberg** [comment] 2019-09-26 14:33
@SilvioGrosso I have just added a find toolbar to the Browse Data tab. So we are making progress. Now only the replace bits are missing. Can you try the find functionality in the next nightly? :smile: There is a new button to open it, or you can just press <kbd>Ctrl</kbd>+<kbd>F</kbd>.
![Screenshot_20190926_162901](https://user-images.githubusercontent.com/3153504/65697416-2c479a00-e07b-11e9-9f99-4a288ff53da9.png)

Unlike the global filter, the find toolbar only looks in visible cells. So the rowid column (if not shown) and the hidden columns are ignored.

**Comment by SilvioGrosso** [comment] 2019-09-26 18:03
Hello @MKleusberg,

I am going to test this last new feature as soon as it is available (I work on Windows 10).
As regards your comments (problem with the >, >=, <=, <, ... operators  AND rowid search) I fully agree with you.

As regards my feature request, it "only" lacks the replace part since the find part it is now implemented in the Browse Data tab. As usual, it is entirely up to you to decide how to implement it... :-)

**Comment by SilvioGrosso** [comment] 2019-10-02 06:30
Hello @MKleusberg 

Just tested the new toolbar (ctr+f) on Windows 10 (64 bit)
It works great.

Just a very minor glitch. 
I had a hard time to understand the option "Whole Cell"). 
IMHO, it might be easier to grasp it for an user if you rename this feature as the one available with Firefox, where it is labelled as  "Whole Words".

Here is the screenshot of Firefox (ctr+f toolbar):
![FIREFOX-TOOLBAR png](https://user-images.githubusercontent.com/33007383/66022391-26740d80-e4ee-11e9-9cef-1df7c1725c41.jpg)

Now it "only" remains to implement in the Browse Data the most difficult part of this work which is the (find and) *replace* part :-)

**Comment by MKleusberg** [comment] 2019-10-03 19:01
Hmm, "whole cell" and "whole words" aren't the same thing. So I can't just rename it. At least as far as I understand them :wink:

In a text editor or on a website "whole words" effectively means that you surround your search string by word separator characters. So if I search for "hello" and tick "whole words" I effectively search for "[space, newline, tab, start of line, ...]hello[space, newline, tab, end of line, ...]" because this way I make sure that I get no partial matches. Right?

In the data view I would expect "whole words" to do the same: Avoid matching partial words. "Whole cell" on the other hand compares the search string to the entire cell contents, from first to last character.

Example:

Searching in this table

id | text
--- | ---
1 | hello
2 | hello there

yields

Whole words checked | Whole cell checked | Search for | Matches
--- | --- | --- | ---
no | no | hel | rows 1 and 2
yes | no | hel | nothing
no | yes | hel | nothing
no | no | hello | rows 1 and 2
yes | no | hello | rows 1 and 2
no | yes | hello | row 1 only

So for "hel" whole cells and whole words work the same, but for "hello" they don't.

Just to be clear: I initially thought "whole cells" is more useful in the table view. But I don't want to defend it here. I can easily change that. For now I just wanted to point out the difference :smile:

**Comment by SilvioGrosso** [comment] 2019-10-04 06:26
Hello @MKleusberg 

> Just to be clear: I initially thought "whole cells" is more useful in the table view. But I don't want to defend it here. 

OK!  You are right. 
Now it is clear how I am supposed to test this new option :-)

P.s: it is entirely up to you to decide how to implement the new features :-)

**Comment by MKleusberg** [comment] 2019-11-10 17:45
Quick update: I have almost completed the replace part. I expect it to be ready for committing tomorrow :smile:

**Comment by SilvioGrosso** [comment] 2019-11-10 21:55
Great!
It is going to be a very interesting new feature for the upcoming stable version...
Especially for Spreadsheet users I mean, who are generally NOT used to write some SQL code to achieve this same goal :-)
Usually, they only work with small tables and this new option should not be very time-consuming for them...

**Comment by MKleusberg** [comment] 2019-11-10 23:47
And it's done - I think :smile: Are you ok to give it a try in tomorrow's nightly build and check for any corner cases I might have missed?

The only annoying thing I noticed is that replacing text in columns with a foreign key can lead to lots of message boxes with errors. But in my opinion changing this would be part of a separate issue because it affects many functions.

**Comment by SilvioGrosso** [comment] 2019-11-11 17:39
Hello @MKleusberg 

Just tested this new awesome feature on Windows 10.
It works great! 
No complaints whatsoever from my end 😄

Here is the screenshot (CTR+H to activate the toolbar, at the bottom of the GUI)

<img width="960" alt="replace" src="https://user-images.githubusercontent.com/33007383/68607984-2a625a80-04b2-11ea-92dc-b5a72cd61df1.png">

**Comment by MKleusberg** [comment] 2019-11-13 19:49
Cool :smile: I guess we can close this issue then.

**Closed by MKleusberg** 2019-11-13 19:49 UTC
Labels: enhancement

**Comment by mickeyl** [comment] 2023-02-08 15:26
Great feature, thanks a lot. Is there an easy way to limit this to a single column or a selection of columns only?
