### ISSUE TITLE
Add comment-uncomment code option (Execute SQL tab) 

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1614] opened 2018-11-15 19:34 UTC
Describe the new feature
--------------------------
Add an option to comment-uncomment your SQL code whenever you work into the Execute SQL panel. 
Needless to say, this feature does require a nice shortcut too :-)

At present, it takes a lot of time to comment *every line* of your SQL code whenever your are testing it (a shortcut would be handy). 
I generally comment out my code instead of deleting it. I only delete it,  in the Execut SQL panel, when It is indeed no longer needed.

In short it would be useful to have a shortcut to temporarily *comment out* many lines of SQL code in one shot, after selecting them. Later on, one might decide to delete this code or to uncomment it again.
For instance, below I comment out these lines:
--select * 
--from table
--where ....

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.

Nope, at least did not find it...

#### Does this feature exist in another product or project? Please provide a link.

Yep. This option is available in every text editor.
The shortcut to comment-uncomment (comment out) your SQL code is different depending on the text editor.
You can activate this shortcut either when you select you code (usually more lines of it) or simply whenever your mouse's cursor is in a certain line (no code selected).

#### Do you have a screenshot? Please add screenshots to help explain your idea.

I don't attach any screenshot becasue I suppose my above-mentioned suggestion is self-explanatory :-)

**Comment by mgrojo** [comment] 2018-11-18 00:52
That's nice to have. I've implemented it and bound to "Ctrl+/" ("Ctrl+-" would make more sense for SQL, but it is already used for Zoom out).

It's in the master branch and eventually it will enter in a nightly. Would you want to try it?

**Comment by SilvioGrosso** [comment] 2018-11-18 08:45
Hello @mgrojo 

I will definitely try it as soon as it is available.

I have just downloaded today's build (---win64.msi) and I have noticed that, currently, when I press CTR+/ the number 7 is added in the Execute SQL panel.  I suppose that with your upcoming improvement this 7 won't be added anymore when I press this new shortcut (ctr+/) :-)

Thanks a lot indeed!

**Comment by mgrojo** [comment] 2018-11-18 12:08
Did you use this one: 
`DB.Browser.for.SQLite-win64.msi                    18-Nov-2018 07:51            12632064`

According to the date and [this comment](https://github.com/sqlitebrowser/sqlitebrowser/issues/1612#issuecomment-439670246) by @justinclift, it should include the feature. Maybe the QScintilla version in the Windows nightly is different to the one I've used (copy from repository)? @justinclift, which version is using the Windows build?

**Comment by SilvioGrosso** [comment] 2018-11-18 13:04
@mgrojo 

Just tested again on Windows 10 (64 bit)

My today's version is:
DB.Browser.for.SQLite-win64
Version 3.11.99 (Nov 18 2018)
Qt Version 5.10.1
SQLite Version 3.25.3

Whenever I select my SQL code to comment it out and I press CTR+/ my prior selection is deleted and the number 7 appears :-)
I suppose this new shortcut is no available yet.

**Comment by mgrojo** [comment] 2018-11-18 13:32
I just tested under Windows with the same nightly and it's (almost) working for me. I've discovered a bug, but the feature and the shortcut is definitely there, so I guess there is some platform issue affecting us. Before adding the new shortcut, Ctrl+/ was bound under QScintilla to "extend selection one word backwards". So it should still be doing that for you if the version wasn't the correct.

My Spanish keyboard is the same, the slash is over the 7. Do you have a numeric keypad? What happens if you use the / that it's there. In my case both slashes (for the one over the 7 you have to actually press Ctrl+Shift+7, and the one in the numeric keypad) are working.

**Comment by justinclift** [comment] 2018-11-18 13:49
@mgrojo The QScintilla version the nightlies use is the one in our git `master` branch. :smile:

**Comment by SilvioGrosso** [comment] 2018-11-18 13:49
Hello @mgrojo 

I am  testing this feature on my laptop which does not have the numeric keypad
As a consequence some Db Browser shortcuts don't work on this hardware. For instance, CTR + does not zoom in into the Execute SQL tab but this same shortcut works smoothelesly when I deploy it on a keyboard with the numeric keypad :-)

At present, today's build, by pressing CTR+/:
- when there is NO prior selection the number 7 is added;
- when instead I have selected my SQL code this one is deleted and the number 7 is added.
BTW, when I press: CTR+SHIFT+/ nothing occurs.

As already mentioned, my current computer does not have an extra numeric keypad but I can test this feature tomorrows on another computer where these additional keys are present :-)

**Comment by SilvioGrosso** [comment] 2018-11-18 15:45
Hello @mgrojo 

Just tried again  on Windows 10 - 64 bit, with different text editor softwares , such as: 
- Notepad;
- Notepad++;
- Atom text editor;
- Sublime 3.
Whenever I press CTR + SHIFT + / nothing shows up.
The same CTR + SHIFT behaviour occurs with the others keys (1, 2, 3, 4 etc): nothing appears.
To get, for instance, the symbol / I must press SHIFT+7.

At present, in the Execute SQL tab, today's build, whenever I press CTR + SHIFT + 7 the text is selected (it is similar to pressing CTR+A).

With Db Browser I have got some problems related to its shortcuts (e.g CTR ++ or CTR + - : to zoom in-out into the Execute SQL tab) because I don't have the numeric keypad on my current laptop.
However, it suffices to change computer - keyboard to solve them.

**Comment by mgrojo** [comment] 2018-11-18 17:07
Yes, the usual behaviour for Ctrl+Key when not bound to a command is to do nothing, but Scintilla seems to behave different (although Notepad++ is supposed to be based on Scintilla, so I don't know) and inserts the character without modifier.

I've updated QScintilla to the latest version, but it didn't solve the problem about Windows lines, so I've reported it in the mailing list. I don't expect either, that it solves your problems with shortcuts, but at least you can use now Ctrl+MouseWheel for zooming.

**Comment by SilvioGrosso** [comment] 2018-11-18 18:51
Hello  @mgrojo,

Thanks a lot indeed for your help!

> I don't expect either, that it solves your problems with shortcuts, but at least you can use now Ctrl+MouseWheel for zooming.

Do not worry about this!
Actually, even with Notepad++ I don't have a shortcut to zoom in - out in the panel. To do so there are two buttons in the GUIs. This shortcut is not even available in its "Preferences" or, at least, I was unable to find it.
With Sublime 3 and Atom text editor zooming in-out works fine on my laptop though (both CTR++ and CTR+-).

**Comment by chrisjlocke** [comment] 2018-11-19 14:56
In the 19 Nov nightly (WIndows 10) pressing Ctrl+/ comments the line, but also removes the character on the following line.

Starts with:

    line 1
    line 2
    line 3

Press Ctrl+/ on line 2, and end up with:

    line 1
    -- line 2
    ine 3

I tried adding semi colons to the ends of the lines, in case it was something wacky detecting lines vs SQL lines, but that didn't improve anything.

Pressing Ctrl+/ on line 1, ends up with

    -- line 1;
    - line 2;
    ine 3;

Also note, pressing Ctrl+/ on line 3 does not do anything.  Actually, technically not true.  The line is highlighted, but no change occurs - no characters are added or removed.  Adding a blank line under line 3 'corrects' this issue - line 3 is commented/uncommented.

**Comment by chrisjlocke** [comment] 2018-11-19 15:17
Sorry - just to add, if a single line is highlighted, no change occurs.  
The above issue was conducted when the cursor was at the beginning of the line to be commented.  The cursor can be at the beginning, middle or end of a line.
If two lines are highlighted, only line 1 is edited, with character 1 of line 2 eaten.  
If two lines are highlighted with the 'end' character selected (so the cursor is at the beginning of line 3) then the first characters of line 2 **and** line 3 are eaten.

End result:

    -- line 1;
    -- ine 2;
    ine 3;

If you require screenshots or a screencast to show this more clearly, please let me know.

**Comment by SilvioGrosso** [comment] 2018-11-19 18:06
Hello @mgrojo 

I have just checked others softwares to test how smoothly they have implemented this feature (comment - uncomment). 
As usual I am working on Windows 10 - 64 bit
Every software works like a charm. on my SQL code

1) ATOM TEXT EDITOR (open source)
The shortcut is CTR+ù (to both comment and uncomment the code)
It works both when you previously select a group of SQL lines of code and  even when the your cursor is blinkig on the line (no selection activated)

2) 
SPYDER (PYTHON GUIs - opensource)
The shorctus is: CTR+1 (to both comment and uncomment the code)
It works both when you previously select a group of SQL lines of code and even when the cursor is blinkig on the line (no selection activated)

3)
NOTEPAD++ TEXT EDITOR (open source) 
It is based on Scintilla
There are a bunch of shortcuts (this feature is extremely fine-tuned)!
The most general is CTR + Q (to both comment and uncomment the code)
As usual, it works both on some selected lines of SQL code and even when the cursor is blinking on the line (no selection applied).

**Comment by mgrojo** [comment] 2018-11-19 21:21
These are symptons of the bug that I said I detected under Windows. In fact they're occurring for Windows files (end of lines having CR+LF). I'm discussing them in the QScintilla mailing list, but the main developer couldn't reproduce them, so I don't have still a solution. You'll have to wait a bit, sorry.

**Comment by mgrojo** [comment] 2018-11-19 23:21
I've finally (more or less) understand how is QScintilla behaving and I've adapted the code to that behaviour, so the detected problems with Windows files should no longer exist in the next nightly build.

**Comment by chrisjlocke** [comment] 2018-11-19 23:39
> These are symptoms of the bug that I said I detected under Windows. 

Aah, sorry - must have missed that.  Appreciate your efforts with this though - thanks.  👍

**Comment by chrisjlocke** [comment] 2018-11-21 11:30
The 'eating the characters from the next line' is fixed, but if the last line is selected/has the cursor in it, pressing Ctrl+/ has no effect apart from simply highlighting the line.

**Comment by mgrojo** [comment] 2018-11-21 20:41
@chrisjlocke You have explained it perfectly and I agree that it isn't very consistent. Now that I understand the behaviour of QScintilla for Unix and Windows files, getting the right behaviour is possible. I think I've fixed all the quirks that you had detected: last line, all lines in selection (even partial) count, and whether the selection ends after the last character of a line or the first of the next one doesn't matter.

Additionally I've joined all the replacements in a single history action, so `undo` after commenting a block would undo all the block, and not line by line, as before.

Unless there's some hidden bug, the only thing I think might missing is a nice button. Shall I add one? Possible icons from our usual Silk icon set:
![imagen](https://user-images.githubusercontent.com/13812910/48867183-a95c1000-edd5-11e8-8e61-7e4a65bc2cff.png) Editing it, so it has two lines in green.
![imagen](https://user-images.githubusercontent.com/13812910/48867129-7b76cb80-edd5-11e8-9e8d-6daf43b76ee3.png) Maybe it wouldn't be understood.

**Comment by SilvioGrosso** [comment] 2018-11-21 21:52
Hello @mgrojo @chrisjlocke 

Just out of curiosity, I have checked Notepad++, Sublime 3, Atom text editor. None of these text editors have an icon to comment - uncomment (or at least it looks so...).
IMHO, adding a button (icon) in the Execute SQL tab together with a nice tooltip containing also its shortcut (CTR+/) wouldn't hurt :-)
Needless to say, this same shortcut needs to be added in the wiki as well.

In Spyder (a Python GUIs)  this is icon for commenting - uncommenting:

![comment_icon png](https://user-images.githubusercontent.com/33007383/48870092-b8e05680-eddf-11e8-8a6d-7476281d1a68.jpg)

**Comment by chrisjlocke** [comment] 2018-11-21 21:56
Never knew that icon had green lines in it!  Never noticed it before, and I use Visual Studio all day!  By default, the icon isn't on the toolbar, and isn't in the context menu (when you right click a selection) either. Having a toolbar icon is a good idea.  I've vote for the first icon.  Bizarrely, Visual Studio has the same icon but right aligned, which when you think about it doesn't make sense - code isn't right aligned.  Guess its just to separate it from the left align icon...

**Comment by justinclift** [comment] 2018-11-21 22:20
I've just enabled the wireless connection for the nightly build server again.  In theory the OSX and Win builds should automatically get built in a few hours. :smile:

**Comment by chrisjlocke** [comment] 2018-11-22 10:31
Thanks @mgrojo - can confirm it works great now in Windows.  Thanks for your efforts tweaking this!

**Comment by mgrojo** [comment] 2018-11-23 17:42
Thanks, @chrisjlocke. I've just pushed the change with the new button using your edited icon.

If this is working well for everybody, I think we can close this issue.

**Comment by ROPIMASI** [comment] 2019-02-04 17:16
> I just tested under Windows with the same nightly and it's (almost) working for me. I've discovered a bug, but the feature and the shortcut is definitely there, so I guess there is some platform issue affecting us. Before adding the new shortcut, Ctrl+/ was bound under QScintilla to "extend selection one word backwards". So it should still be doing that for you if the version wasn't the correct.
> 
> My Spanish keyboard is the same, the slash is over the 7. Do you have a numeric keypad? What happens if you use the / that it's there. In my case both slashes (for the one over the 7 you have to actually press Ctrl+Shift+7, and the one in the numeric keypad) are working.

Hello, everyone.
I'm also looking for these shortcut keys in DB-Browser-SQLite: Zoom in, Zoom OUT, and comment, uncomment.

Thanks guys, I took a look at the code, I liked it. 

Please help me: I also had the same problem: [Ctrl] + [/,?]  and [Ctrl] + [=, +] do not work.

Where should I (on Github) look for a solution?

**Comment by chrisjlocke** [comment] 2019-02-04 17:37
What version of DB Browser for SQLite are you using?  The shortcut keys for the comment should be <kbd>Ctrl</kbd> and <kbd>/</kbd> but I'm not sure its implemented yet - it doesn't appear to be working in the latest nightly.
DB Browser for SQLite has no shortcut keys for zooming in or out.  What exactly are you hoping to zoom in and out - the browse data table?  Execute SQL pane?  The database structure?  Plot window?  Pragma settings?  About screen?

**Comment by mgrojo** [comment] 2019-02-04 19:40
@ROPIMASI, thanks for reporting. I see that the shortcut was currently rejected by our GUI library becuase it was ambiguous due to a successive change that I made for other feature. It should be [fixed in tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/) (check that the date is correct before testing).

Regarding zoom, if you mean the SQL editor, I don't reproduce the problem. I can zoom in&out using either <kbd>Ctrl</kbd>+<kbd>+</kbd> and  <kbd>Ctrl</kbd>+<kbd>-</kbd> (both regular keys and numeric keypad work for me, Spanish keyboard) or using the <kbd>Ctrl</kbd>+<kbd>mouse wheel</kbd>. As @chrisjlocke has already asked, which version are you using? Keys should work in any v3.11 beta and the mouse wheel in recent nightlies.

**Comment by justinclift** [comment] 2019-02-05 03:46
The new nightly builds have just finished running, and are online:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by mgrojo** [comment] 2019-08-10 12:45
Closing this due to already being confirmed by @SilvioGrosso and lack of response of @ROPIMASI.

**Closed by mgrojo** 2019-08-10 12:45 UTC
Labels: enhancement, response requested

**Comment by Directmailmart-dot** [comment] 2020-12-23 09:31
I really informative article its to helpful i really enjoyed its reading this post enough to search high quality clothing manufacturers to helpful post thanks for sharing. https://www.directmailmart.com/
