### ISSUE TITLE
Browse Data table returns ascending order by _rowid_ first time but descending order afterwards

### ISSUE THREAD

**Issue by ejohn54** [sqlitebrowser/sqlitebrowser#641] opened 2016-07-08 17:10 UTC
When opening the "Browse Data" tab the first time, then selecting a table from the drop down, it automatically shows the data for the table in ascending order by '_rowid_'.

I can tell by watching the SQL log window, it shows these SQL statements:
SELECT COUNT(_) FROM (SELECT `_rowid_`,_ FROM `ConfigInfo` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,\* FROM `ConfigInfo` ORDER BY `_rowid_` ASC LIMIT 0, 50000;

If I then click on the "Execute SQL" tab, then click back to the "Browse Data" tab, it shows the data for the table in descending order by '_rowid_'

The SQL log window now shows these five new statements:

SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(_) FROM (SELECT `_rowid_`,_ FROM `ConfigInfo` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,\* FROM `ConfigInfo` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(_) FROM (SELECT `_rowid_`,_ FROM `ConfigInfo` ORDER BY `_rowid_` DESC);
SELECT `_rowid_`,\* FROM `ConfigInfo` ORDER BY `_rowid_` DESC LIMIT 0, 50000;

You can see the last one was ordering 'DESC'.

I believe it should not be changing the order like this, and just use 'ASC' order.

**Comment by justinclift** [comment] 2016-07-08 17:16
Well, that definitely sounds like a bug. :wink:

**Comment by ejohn54** [comment] 2016-07-08 18:51
It was with version 3.8.0, 64 bit version for Windows.  Sorry I haven't tried any nightly build.

**Comment by revolter** [comment] 2016-07-15 19:15
I can't reproduce this with the latest build.

@justinclift, Wasn't it fixed after `3.8.0`?
@ejohn54, Could you please try [the latest nightly build](http://sqlitebrowser.oldsch00l.com/sqlitebrowser.exe.zip)?

**Comment by justinclift** [comment] 2016-07-15 21:36
@revolter Just tried here with the latest build too, loading a table, then going to Browse Data, then running a UNION SELECT query on it via the Execute SQL tab, then going back to Browse Data.

The ordering is keeping constant for me.

@ejohn54 If you can spare the time to check the latest nightly build, it would really help.  If you need a Win64 package, then this one from earlier today (solving a different issue, but it's good) has our latest code:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/win64-onceoffs/sqlitebrowser-win64-issue621v3-201607151423.exe

**Comment by ejohn54** [comment] 2016-07-15 21:47
Hi I just tried these two nightly versions.

The Win64 version from http://nightlies.sqlitebrowser.org/win64-onceoffs/  still has this issue occur.
The Win32 version from http://sqlitebrowser.oldsch00l.com/sqlitebrowser.exe.zip seems to work fine.

Again I can see it changing the order by to DESC in the SQL log window.

SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `BinaryFile` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `BinaryFile` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `BinaryFile` ORDER BY `_rowid_` DESC);
SELECT `_rowid_`,* FROM `BinaryFile` ORDER BY `_rowid_` DESC LIMIT 0, 50000;


The Win32 version just does not execute these last two SQL statements, but the Win64 version does.

**Comment by justinclift** [comment] 2016-07-15 21:50
@ejohn54 Thanks! :smile:

@revolter Looks like we still have the problem then. 😦

**Comment by revolter** [comment] 2016-07-15 21:53
Is it a 64bit related issue? I have no idea what 64 implies (and breaks) related to code.

**Comment by justinclift** [comment] 2016-07-15 21:54
Yeah... same here. 😦

**Comment by revolter** [comment] 2016-07-15 21:56
@innermous Any idea / hints with this one?

**Comment by innermous** [comment] 2016-07-15 22:07
@revolter I am working on another rowid issue right now, can't help much.

**Comment by chrisjlocke** [comment] 2022-08-25 18:25
Closing as this issue has been resolved.

**Closed by chrisjlocke** 2022-08-25 18:25 UTC
Labels: bug
