### ISSUE TITLE
Please do some steps to make this error resolve

### ISSUE THREAD

**Issue by geronimo123321** [sqlitebrowser/sqlitebrowser#1362] opened 2018-04-11 07:41 UTC
#### I'm opening this issue because:

- [x] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2018-04-11 08:54
Closing as there are no details for this issue.
@geronimo123321 - Please reopen explaining what the issue is.  "Please resolve" is not sufficient to diagnose what the error is.

**Closed by chrisjlocke** 2018-04-11 08:54 UTC
