### ISSUE TITLE
[Bug]: Can't open rc2 on macOS 12.7.5

### ISSUE THREAD

**Issue by richb-hanover** [sqlitebrowser/sqlitebrowser#3659] opened 2024-06-12 01:13 UTC
### What did you do?

I'm running macOS 12.7.5 on a 2019 intel MacBook Pro. RC1 has been working perfectly for months on this machine. Download 3.13.0-rc2 (DB.Browser.for.SQLite-v3.13.0-rc2.dmg)  from https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.0-rc2

Double-click the .dmg file, see the app icon and the Applications folder. Drag the app to the Applications folder.

Double-click the app icon in /Applications, I see the window below and click **Open**:
<img width="372" alt="image" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/1094930/5c20b12c-6505-49ca-aab8-e0ff45e02ef2">

I see the app icon bounce once or twice in the dock, then exit. Double-clicking the app icon again causes a single bounce in the dock, then nothing else. 

Troubleshooting so far:
- I checked System Preferences : Security, and DB Browser isn't listed as needing to be approved.
- I re-downloaded RC1 and got the same dialog. Clicking Open caused RC1 to start up as desired.

What other information could I provide? Many thanks.

### What did you expect to see?

I expected the app to launch

### What did you see instead?

See description above.

### DB4S Version

Other

### What OS are you seeing the problem on?

MacOS

### OS version

macOS 12.7.5

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment] 2024-06-12 01:23
Thank you for reporting this. I was not able to reproduce the issue on my Mac<sup>1</sup>
Can you provide us with the execution logs to help us determine the cause?
If you run it directly in the terminal, it should be logged in the terminal:
```bash
cd [Path where 'DB Browser for SQLite-v3.13.0-rc2.app' is located]
cd DB\ Browser\ for\ SQLite-v3.13.0-rc2.app/Contents/MacOS/
./DB\ Browser\ for\ SQLite-v3.13.0-rc2
```

FYI:
<img width="1589" alt="Screenshot 2024-06-12 at 10 20 53" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/64626662/c2212cd8-27af-46f7-a82c-3bf4a0816391">

><sup>1</sup>: macOS Sonoma 14.5 (23F79) with Mac 14,3<sup>2</sup>
><sup>2</sup>: https://everymac.com/systems/apple/mac_mini/specs/mac-mini-m2-8-core-cpu-10-core-gpu-2023-specs.html

**Comment by lucydodo** [comment] 2024-06-12 11:02
Hi @richb-hanover, I've just checked in on another report(#3654) of RC2 version not running on macOS 12 and have confirmed that the current RC2 version does not run on macOS 12.

I'm looking into the cause, which I believe to be a recent CI migration, and I'll fix it before the release final version scheduled for next week. Until then, I'd appreciate it if you could use the 05/31 nightly build or RC1 version. Thank you.

**Comment by richb-hanover** [comment] 2024-06-12 11:18
Thanks for the speedy response. I saw that report, but it seemed they could get RC2 started, and then it threw an error.

I continue to be completely happy running RC1 - I just like to check out test/RC versions of software, just to make sure they work. (Because sometimes, like today, I find a problem...) Thanks again.

**Comment by lucydodo** [comment] 2024-06-12 11:21
Thanks to you, we were able to identity a critical issue just before the stable version.

**Comment by richb-hanover** [comment] 2024-06-12 11:23
PS: I just saw your previous note. Here's the output from the command line:

```
134 MacOS % cd /Applications

√ /Applications % cd DB\ Browser\ for\ SQLite-v3.13.0-rc2.app/Contents/MacOS/

√ MacOS % ./DB\ Browser\ for\ SQLite-v3.13.0-rc2
dyld[14629]: Symbol not found: (__ZTVNSt3__13pmr25monotonic_buffer_resourceE)
  Referenced from: '/Applications/DB Browser for SQLite-v3.13.0-rc2.app/Contents/Frameworks/QtXml.framework/Versions/5/QtXml'
  Expected in: '/usr/lib/libc++.1.dylib'
zsh: abort      ./DB\ Browser\ for\ SQLite-v3.13.0-rc2
?134 MacOS %
```

PS Please feel free to keep me in this final-testing loop. I really depend on DB4S and want to help you push it over the finish line. Thanks again

**Comment by lucydodo** [comment] 2024-06-12 11:28
Thank you for the kind words. I'll fix the issue and send you a build for you to test. :)

**Comment by lucydodo** [comment] 2024-06-17 01:32
https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.0-rc3
Hi @richb-hanover, We have released a new RC3 version that fixes this issue. :rocket:
We have confirmed that it works on macOS Monterey 12.6 (21G115). Test it out and let us know :) Thank you.

**Closed** 2024-06-17 15:20 UTC
Labels: crash, release blocker, macOS
