### ISSUE TITLE
Cannot create table with primary key without autoincrement

### ISSUE THREAD

**Issue by prutz1311** [sqlitebrowser/sqlitebrowser#872] opened 2016-11-16 21:49 UTC
### Details for the issue

When trying to fill in 'PK' checkbox in 'Create Table' window, sqlitebrowser does not add `PRIMARY KEY` to the DDL statement:
![image](https://cloud.githubusercontent.com/assets/6525383/20367098/0ede1276-ac5f-11e6-9884-5af6ce00693a.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Xubuntu 14.04.5 LTS)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: master HEAD c6f1373

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2016-11-18 10:26
Weird.  Works fine for me on 3.9.1 (so not from HEAD...)
http://screencast-o-matic.com/watch/cDXF6TQnDT

Can you try 3.9.1 and the latest nightly?  IN fact, I'll try the nightly...

**Comment by chrisjlocke** [comment] 2016-11-18 10:37
Confirmed.  The nightly does not work.  It be broken.  Try 3.9.1, or a slightly older nightly...

**Comment by chrisjlocke** [comment] 2016-11-18 11:21
Installed every nightly (up to Oct 17) but each one exhibits that behaviour.  The only version that was working was 3.9.1, so unsure when it stopped working.
Bizarre it hasn't been picked up before now!

**Comment by innermous** [comment] 2016-11-19 01:45
Wrong. Works only in august builds.

**Comment by chrisjlocke** [comment] 2016-11-19 08:45
OK.  So are the nightlies a separate build from the 3.9.1 release, because, as I said, it works (as per my screencast ... unless thats wrong too?) in 3.9,1, and thats dated 3 Oct.  Unless its working for me for some other reason...?

**Comment by innermous** [comment] 2016-11-19 14:28
It stops working after 5c17115 commit.

**Comment by justanotherarchuser** [comment] 2016-12-23 16:16
@MKleusberg I need help with this. You messed up a bit when you changed some code 😄 So only person who understands what's going on is you.
I can provide more details on Gitter. I have some thoughts too.
I think fixing this issue is very urgent task.

**Comment by justinclift** [comment] 2016-12-23 21:27
Ahhh, somehow I didn't notice these comments.

Some data points, which might help clarify:

* The nightlies build from master
* When 3.9.0 was getting made (~August), I created a new branch from master-at-the-time called "v3.9.x".  3.9.0 came from that branch, and so did 3.9.1.  3.9.1 is pretty much 3.9.0 + a bunch of minor-ish commits added that seemed to fix bugs aren't weren't very likely to add new problems.

So, 3.9.1 is kind of a stabilised build forked from nightlies code in August.

Does that help put things into a sensible time line?

**Comment by innermous** [comment] 2016-12-24 00:47
I already said I know what's wrong and need @MKleusberg help...

**Comment by MKleusberg** [comment] 2017-01-04 17:45
@prutz1311 This should be fixed with the latest commit from master. Can you grab that code and rebuild to check if it's working for you? :smiley:

**Comment by prutz1311** [comment] 2017-01-04 18:45
Yes, with a40fe0b it works as expected:

![image](https://cloud.githubusercontent.com/assets/6525383/21654555/03fefa6c-d2c7-11e6-9c2b-8845a98e8b4f.png)

Can we close the issue now?

**Comment by MKleusberg** [comment] 2017-01-04 18:51
Wow, that was a prompt reply from your side :smiley: Thanks for testing this!

Yep, I'm going to close this issue for now. If any further problems with this or anything else should occur feel free to open a new issue.

**Closed by MKleusberg** 2017-01-04 18:51 UTC
