### ISSUE TITLE
no utf-8 char support

### ISSUE THREAD

**Issue by abshuhuhuhu** [sqlitebrowser/sqlitebrowser#348] opened 2015-06-10 04:05 UTC
DB Browser for SQlite for SQLITE
version: 3.6.0
while execute sql, 
no uft-8 char is support
the sentence : 
select * from refer where namecn like '%术语%'
will be looks like this:
select * from refer where namecn like '%??%'

**Comment by justinclift** [comment] 2015-06-10 17:54
Yeah.  There was a bug in our Unicode handling with 3.6.0.  If you grab the latest nightly build though, it's fixed. :smile:

(download locations are shown on the front page of this repo, if that helps)

**Comment by justinclift** [comment] 2015-06-13 19:10
@abshuhuhuhu Have you had a chance to grab the latest nightly build, and use that instead?

**Comment by justinclift** [comment] 2015-06-16 03:02
Closing this, as we don't seem to be getting a response + the issue is already fixed in our codebase. :smile:

**Closed by justinclift** 2015-06-16 03:02 UTC
Labels: duplicate
