### ISSUE TITLE
Change axis limits

### ISSUE THREAD

**Issue by struck89** [sqlitebrowser/sqlitebrowser#838] opened 2016-10-18 21:29 UTC
### Details for the issue

Axis? Axes?

Well, my point is, it would be awesome to be able to change the limits of the axis window.
Right now it uses the current max/min for X and Ys, which is a little bit inconvenient. (Remember I can´t plot lines? So dots get cut in half)

Also, by adding that we would have a "zooming" tool. (I think this feature seems very easy to implement, whereas a true zooming thing seems much more complicated)

e.g. When I plot this:
![axis limits](https://cloud.githubusercontent.com/assets/18152095/19496875/9286c574-9557-11e6-91d5-f976cbbf0a4e.png)

I would rather be able to chose to have something like this:
![image](https://cloud.githubusercontent.com/assets/18152095/19496919/d4c1d4ce-9557-11e6-94f9-daa53691ca0a.png)

Or in this occasion:
![axis limits 2](https://cloud.githubusercontent.com/assets/18152095/19496994/198e81ec-9558-11e6-8f09-a8c88f223261.png)
Where do all the corners (upper left side) that follow a straight line go down to? If I was able to chose "show me X from 0 to 200", I wouldn't be forced to go to EXCEL

#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2016-10-18 22:01
Yep, sounds useful. :smile:

**Comment by mgrojo** [comment] 2017-12-02 17:03
@struck89 I've enabled some user interactions in the plot that might allow you to adjust the plot to your needs. Letting the user set explicitly the axis limits would also make sense, but this was actually easy to implement and, in my opinion, improves the situation a lot. If you are still using the application, could you try it in the next nightly build and give some feedback?

**Comment by justinclift** [comment] 2017-12-06 17:43
@struck89 ping? :smile:

**Comment by struck89** [comment] 2017-12-06 18:12
Hi!
I have been waiting to find a moment to test it (I am currently on vacation)
And as I said some months ago, I stopped being part of the project where I was using sqlitebrowser. Still I will give it a try. In a week!
(I had the message starred in my inbox btw)
Regards!

**Comment by justinclift** [comment] 2017-12-06 19:14
Thanks @struck89. :smile:

**Comment by struck89** [comment] 2017-12-11 10:40
Hey, the drag and drop, and the zooming are great. Is there any way to change the aspect ratio?

Sadly I have to say I managed to break the thing at my first attempt.

Problem? When executing an statement like:
"select foo from table1", plotting, and then "select foo,bar from table1" breaks the thing.

I uploaded a video. The link will expire soon:
s.amsu.ng/pgWoJxEEuPYN

Another observation, the number of elements plotted are limited to 50.000. If the number of results coming from the query is greater, and not everything is plotted (for performance reasons I assume), I think you should say it. "WARNING, too many rows, only plotting first 50K" or something. This is very important!! otherwise there is missing data in the plot!

Best regards,

**Comment by mgrojo** [comment] 2017-12-11 19:54
I think you're seeing the same crash as described in #1262.

The limit of 50K rows that you are seeing is the prefetch block size that you can set in the Preferences. There is also a button in the Plot Dock for loading all the data. I agree that some kind of feedback should be given, or assume that the prefecht works well for browsing, but not for plotting, and consequently try to plot everything... I don't know. Maybe @MKleusberg can help with that.

**Comment by struck89** [comment] 2017-12-12 13:08
>  There is also a button in the Plot Dock for loading all the data.


Great, thanks!
(then, a warning when plotting if not all data is there would be nice, because you might miss something important (instead of checking the number of returned rows in the query results table) (and even more if most of the times results are sorted..))

**Comment by mgrojo** [comment] 2017-12-12 21:57
What if we enable the "Load all data and redraw plot" button only when there is data not loaded yet due to the prefetch mechanism, or when the user has zoomed or dragged the plot? In the first case we could also set a red background to the button and set a warning in the button tooltip, so it is more visible and self-explanatory.

**Comment by justinclift** [comment] 2017-12-13 05:09
That sounds like a decent idea. :smile: What do you reckon @struck89?

**Comment by mgrojo** [comment] 2017-12-13 22:11
@struck89 I've implemented the visual warning so you can see it in action and give some feedback.

**Comment by struck89** [comment] 2017-12-14 08:55
Hi @mgrojo,
You make me feel important, like my opinion counts 😄 
Sadly I have to say it is not working for me. It just breaks when selecting the column. At the beginning I thought it might be because of the language, so I switched to English US (default).
s.amsu.ng/rl97voXwsorN
Most simple query ever.
Now I need a previous version to work 😆 

Thanks for your efforts!

**Comment by mgrojo** [comment] 2017-12-14 22:44
Hi @struck89,
Everyone is important :smiley:

Thanks for reporting the crash, I had tested only with a project with settings saved for the table. With
a query I reproduced it immediately. Thanks for reporting. It should be fixed now. 

That issue with the zoom is very strange. Does it happen also when one of the axis is selected? It is probably a precision calculation error in qcustomplot.

For getting the rowid of a selected dot, right-click first on the table header and click on "Show rowid column".

**Comment by struck89** [comment] 2017-12-15 10:55
Good morning to everybody and happy friday!
@mgrojo That red warning is great. There is a very very small error though, the tooltip square ends like this:
![image](https://user-images.githubusercontent.com/18152095/34038259-15030b3a-e18c-11e7-915c-28d5f09be7ab.png)

Once clicked it gets grayed out and back to normality. (but when we zoom: https://we.tl/ss2taw7Lqs) (maybe this is expected behaviour, to fix axis limits)

About the sparkling dots, it does still happen with one axis selected. (I just discovered, not only the zoom gets restricted to the axis but also the drag and drop. Love it!)

And about the rowid for a dot, I right-clicked everywhere (both table header in the plot or in the results, and everywhere else) and I can't see the "show rowid column". The only menu I get is "Copy" on the graph.

Thanks!

**Comment by mgrojo** [comment] 2017-12-15 17:44
Hi @struck89. The issue with the tool-tip should be fixed with the last commit. 

I've updated the plot library to version 2.0.0 from 2.0.0-beta. Let's see if this fixes the problem about disappearing points while zooming. Otherwise, I don't though how to solve it, sorry.

The "show rowid column" option is in the context menu of the table in Data Browser tab. If you are trying with query results, it will not work. In that case you should be able to add the rowid to your query. Does this helps?

**Comment by mgrojo** [comment] 2017-12-15 18:02
@struck89 I forgot to mention that the behaviour of the button after zooming is intended. It's the way to reset the plot to the initial zoom and axis ranges. Otherwise a different button would be needed. I don't think it is worthy of the space it would need.

**Comment by struck89** [comment] 2018-01-04 09:33
Hey @mgrojo!
I haven't tested yet enough to see again the disappearing points.

But regarding this:
> The "show rowid column" option is in the context menu of the table in Data Browser tab. If you are trying with query results, it will not work. In that case you should be able to add the rowid to your query. Does this helps?

I managed to find what you mentioned, and I found out it automatically selects (theoretically) the row of the dot.
Unfortunately there is a conceptual error, that I pointed out on this issue:
https://github.com/sqlitebrowser/sqlitebrowser/issues/821

To sum up again, plotting does not respect the order of the results, it rearranges the results, again, by the x value. So if the x value is not ordered, this results in a completely undesired effect, the selected row has nothing to do with the actual selected dot:
https://we.tl/neR2kMOQke

**Comment by mgrojo** [comment] 2018-01-04 22:43
Oh, that is very unfortunate. Ideally the problem of the reordering should be fixed with QCPCurve and then the selection problem would be easy to solved, but as you have already pointed, that is not straightforward. And we would lose the line style options and don't know if something more.

But the selection problem is more serious and I'd like to solve it without changing the plot implementation, which I don't dare to change. But the only solution that I come to is forcing the order in the table by x when a point is selected, and then selecting the correct row.

**Comment by mgrojo** [comment] 2018-05-01 12:00
I'll close this issue after the changes implemented in #1258 and #821. The only possible problem still to be addressed is the "disappearing dots". It seems a problem with QCustomPlot, although if it is still happening, you might open a new issue for tracking it.

**Closed by mgrojo** 2018-05-01 12:00 UTC
Labels: enhancement, response requested
