### ISSUE TITLE
Text file won't import

### ISSUE THREAD

**Issue by jwes44** [sqlitebrowser/sqlitebrowser#2330] opened 2020-07-15 21:00 UTC
Details for the issue
--------------------

#### What did you do?
Created a database and imported a CSV file

#### What did you expect to see?

Data
#### What did you see instead?
Error importing data from record number 3071110.
Inserting row failed: not an error

Useful extra information
-------------------------
File is tab separated with a header row.
I tried loading a few thousand records around the error record and that works.
I wrote a small Python script to load the file into sqlite and that works.
link to the file: https://drive.google.com/file/d/1B7W7Mw9fcjhdiagqFo6COKlZAZl-SAhq/view?usp=sharing
The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ x] Windows: ( _version:_ _7__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ no] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ yes] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2020-07-16 07:13
Can you post your database schema?  Right-click on a table and select 'Copy create statement'.

![image](https://user-images.githubusercontent.com/7872218/87638611-fa074600-c73b-11ea-8cb2-78cdf937e359.png)

**Comment by chrisjlocke** [comment] 2020-07-16 07:54
Importing a large CSV file is still 'problematic'.  Got stuck at 53% for a while .... 
![image](https://user-images.githubusercontent.com/7872218/87642755-d646fe80-c741-11ea-9b5e-91fa1d685f91.png)

and chewing up the CPU...

![image](https://user-images.githubusercontent.com/7872218/87642794-e9f26500-c741-11ea-927e-7fcd3bbe2de5.png)

**Comment by chrisjlocke** [comment] 2020-07-16 08:17
OK, can you split the file in half and try importing both halves?  I tried this, and it worked.  No, no idea either.

**Comment by justinclift** [comment] 2020-07-16 08:58
Oh, this sounds like something @MKleusberg would be interested in.

**Comment by chrisjlocke** [comment] 2020-07-16 09:13
I've a sneaky feeling this is malformed record related, but having trouble pinning it down at the moment.  
DB4S stalls regularly, which would indicate its trying to parse one huuuuuuuuuuuuuuuuge record rather than individual records.

![image](https://user-images.githubusercontent.com/7872218/87653024-de586b80-c74c-11ea-8da0-e1462067db6c.png)

I'll have more time later on to investigate further ... getting growled at here at the moment! 😄

**Comment by MKleusberg** [comment] 2020-07-16 09:43
@chrisjlocke is right. DB4S sees a huge record and cannot update the UI while looking for the end of it (hence the progress bar getting stuck at 53%). The solution seems to be to set the quote character to nothing in the Import CSV dialog. Can you try that?

This would mean it's not a problem in the CSV import per se. Except for the not very useful error message, that is of course :wink:

**Comment by chrisjlocke** [comment] 2020-07-16 10:48
Actually, it is a fault in the CSV.

![image](https://user-images.githubusercontent.com/7872218/87662423-1b772a80-c75a-11ea-9668-e63220da3993.png)

Record 469682 has only one quote (so an opening quote).

**Comment by chrisjlocke** [comment] 2020-07-16 16:18
My default options were to use quotes.

![image](https://user-images.githubusercontent.com/7872218/87695979-1af58880-c788-11ea-831c-a300bea45f08.png)

This is why its 'broken' my importing. 😄

**Comment by jwes44** [comment] 2020-07-16 17:53
Disabling quoting makes it work. I'll leave it to you whether this is a bug or not (though a more descriptive error message with the right record number would be nice).

**Comment by chrisjlocke** [comment] 2020-07-16 18:23
Its not a bug, as you've said to DB4S (if you used the same quoting options as me) 'use this as a quote character' which isn't correct - so more to do with user error than program error.  DB4S doesn't know the fault is at line X, as its read from one quote to the next (which could be anywhere) and then starts continuing the record from that point - that might (but more likely not) allow the import to continue until it falls over again.  This file contains a lot of single-quote-in-the-line lines, which may be correct CSV, but incorrect if you use " as a quoting character.

The 'answer' is to parse each line and determine if it contains an odd number of quote characters, but as your CSV was a billion lines (well, several million) that could take a while.  Better that than failing though...

I'll close this as the issue itself has been closed, but this may need tweaking in the future.

**Closed by chrisjlocke** 2020-07-16 18:23 UTC

**Comment by justinclift** [comment] 2020-07-17 00:17
> The 'answer' is to parse each line and determine if it contains an odd number of quote characters ...

Yeah, that's been raised as a potential idea before, but it's not really workable because CSV files aren't limited to just a single line per record.  Multi-line values are valid.  eg things like:

```
foo,bar,"ba
z",fred,joe,"what
the
heck
is
this?",nurk
```

That's a single "row" of data.  It's just two of the fields have multi-line content.

**Comment by chrisjlocke** [comment] 2020-07-17 06:03
Gah.  Peed on my great earth-shattering idea again.  😭 😭

**Comment by MKleusberg** [comment] 2020-07-17 20:49
In tomorrow's nightly build you should now get a better error message. Instead of showing "not an error" which admittedly isn't helpful at all, you'll now get an "unexpected end of file" message with an extra explanation that either the quote settings might be off or the file malformed.
