### ISSUE TITLE
[Suggestion] Display last commit hash used for nightly build

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#2441] opened 2020-10-14 11:22 UTC
Describe the new feature
--------------------------
Nightly builds start every day at midnight GMT timezone.
We are using the 'Major.Minor.99' build number for all nightly builds.

I think it would be better if you let me know what source used for nightly built.
For example, we can display the hash of the last commit of the repository used for the build to 'AboutDialog'.

Of course, the nightly build script and program source code need to be change a little for this,
but the advantage is that you can explicitly tell the developer or users what code the build was used.

It may seem that there is more harm than good, but please consider it. :thinking: 

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
No as far as I know

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![Screenshot from 2020-10-14 20-19-50](https://user-images.githubusercontent.com/64626662/95982082-a4395b80-0e5a-11eb-8df6-8d724cecc3bf.png)

**Comment by justinclift** [comment] 2020-10-14 13:35
The nightly builds for Windows are done by these two scripts (each run about an hour apart):

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/tree/master/installer/windows/nightly_build_scripts

The macOS ones are done by this script (run via cronjob):

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/installer/macos/build_sqlitebrowser_nightly.sh

The Ubuntu ones are done by... um... I'm not sure.  Let's ask @deepsidhu1313, as he set that up. :smile:

**Comment by chrisjlocke** [comment] 2020-10-14 13:44
> we can display the hash of the last commit of the repository used for the build to 'AboutDialog'

Do you need the whole hash?  It makes the dialog a bit 'busy'.  if you only used the last six characters from the hash, wouldn't that give enough entropy but also make it easier to read.  Just a thought.
Either that or a simple 'this is v3.12 with SQLite 3.30' at the top, with an 'advanced' area at the bottom showing more 'noise' ;)

**Comment by justinclift** [comment] 2020-10-14 13:46
> if you only used the last six characters from the hash

As a data point, git itself often uses the first 7 characters of a hash for that reason.  So, probably just follow that convention? :smile:

**Comment by lucydodo** [comment] 2020-10-14 13:50
@justinclift Oh, I've already seen it. If the build server works based on that script, I thought that each nightly build on the same day could be different if a commit pushed between the terms of the build process.
I think the words are a little weird, so let's explain more... :eyes: 

**Assume the final commit is 'A'**
- 00:00 GMT: Start building for macOS (based on 'A' commit)
- 00:10 GMT: A new commit called B is pushed to master branch.
    (but, macOS build is in progress with commit 'A')
- 01:00 GMT: Start build for Win64 (based on 'B', because this is latest commit at this time)

So the nightly build for this day looks like following:
- macOS : Built based on 'A' commit and released.
- Win64: Built based on 'B' commit and released.

So I thought if it would be better to display the commit hash on the DB4S. :thinking:

**Comment by lucydodo** [comment] 2020-10-14 13:54
@chrisjlocke There is no need to display the entire hash. That's just an example. :smile: 
It can be abbreviated, or if user click the version information text, a hash value can be displayed instead of that.

**Comment by justinclift** [comment] 2020-10-14 13:55
Yeah, none of the build scripts are tied together in any way.  So you're right, it can mean there are slightly different commits for each, if new ones are done between them starting.

In practise, it hasn't really been much of a problem. :smile:

For including the commit hash in the About dialog... I **think** we used to do that at the beginning of the project moving to git.  But we moved away from it, though I don't remember why.  (probably not relevant now anyway)

@MKleusberg Do you remember the details? :smile:

That being said, adding it back in seems like it would be useful for the nightlies.

**Comment by lucydodo** [comment] 2020-10-14 18:35
Now I'm ready to make PR. A new variable has been added to 'CMakeLists.txt',
so the build server's script needs some modification. Let me known when you're ready. 😄 

<img width="688" alt="Screen Shot 2020-10-15 at 3" src="https://user-images.githubusercontent.com/64626662/96030740-5db62200-0e97-11eb-9b79-d6620b2dd02f.png">

>When new variable is not defined, DB4S show as 'Unknown'

**Comment by chrisjlocke** [comment] 2020-10-15 06:36
Just a minor point .... 'built' is the past tense of 'build' ("I built something yesterday") so that should read, "Last commit hash when built: "
:)

**Comment by lucydodo** [comment] 2020-10-15 09:34
Thanks for review! I just updated in my local branch. 😄

**Comment by sky5walk** [comment] 2020-10-15 12:59
Can you print the hash for the [nightlies](https://nightlies.sqlitebrowser.org/latest/) builds.
Either appended to the filename or some text file containing the git status?
I asked for this in #1917 but it seems to have lost its way :(

**Comment by lucydodo** [comment] 2020-10-15 14:05
@sky5walk Technically it is possible, but there is a reason to need provide the commit hash in README.txt? (Just curious :wink: )

**Comment by justinclift** [comment] 2020-10-15 15:30
It's probably do-able with some ssh commands to the nightlies server.  Maybe a decent approach would be to have a blank template README file with placeholder tokens for the hashes, and we regenerate the README after each build?

Having the hash in the filename would be useful in one way, as that makes it easy to tell what a build was created from.  But we couldn't use it for the "/latest" directory, as those need to be stable filenames.  eg without a hash in them :smile:

**Comment by sky5walk** [comment] 2020-10-15 17:02
#1917 discusses the reasons why to add the hash or some other automated method to instruct users of the impetus for the nightly.
Nightlies are compiled with no explanation as to what changes were implemented.
The user must browse the git timeline?

**Comment by lucydodo** [comment] 2020-10-17 03:06
It seems reasonable. I will try implement it. But it needs @justinclift's consent to apply to the build server. 😄

**Comment by justinclift** [comment] 2020-10-17 10:31
@lucydodo The build scripts that run on our nightly build server VM's are just a copy of the build scripts here in this repo.  If you want to make changes, try in a local VM or something on your own PC and get them working, then apply them to the build scripts in this repo.  And let me know so I can copy them over to the build server. :smile:

**Comment by lucydodo** [comment] 2020-10-17 12:35
@justinclift Thanks. I will ready scripts until tomorrow. :smile: 
@sky5walk I just made a prototype what you want. See the below screenshot. Is it OK or need more changes?
![Screenshot from 2020-10-17 21-33-08](https://user-images.githubusercontent.com/64626662/96337248-a43a9500-10c0-11eb-96b8-4afe55b43697.png)

**Comment by chrisjlocke** [comment] 2020-10-17 12:45
Is this in date order?  (or would be in date order)  Would it be possible to include a yyyy-mm-dd date at all?   (abcdefab yyyy-mm-dd Commit details)

**Comment by lucydodo** [comment] 2020-10-17 12:46
Sure. I can include a yyyy-mm-dd date at all

**Comment by chrisjlocke** [comment] 2020-10-17 12:53
Just think it gives all the relevant info then.... more than enough for most users.

**Comment by lucydodo** [comment] 2020-10-17 13:01
How about like this format: `[date] commit title (commit short hash)`
e.g) `[2020-10-15] Fix to 'Window Layout' options work properly (9433601)`

**Comment by chrisjlocke** [comment] 2020-10-17 13:20
That looks neat and easy to follow.  Gets my vote! 👍

**Comment by sky5walk** [comment] 2020-10-17 13:51
This is great!
Just put the numbers in front. Thanks!
`[20201015] - [HASH] Fix to 'Window Layout' options work properly`

**Comment by chrisjlocke** [comment] 2020-10-17 14:17
No, put the commits first!
Make it a user option!
Extend the commit descriptions to 255 characters!
Include a link!
Add colours!

We could argue this all day, but I personally find 20201015 a nightmare to read.  yyyy-mm-dd is at least 'standard'.

**Comment by justinclift** [comment] 2020-10-17 14:23
> yyyy-mm-dd is at least 'standard'.

Yeah.  It's in the same sort order, just a little easier to read. :smile:

**Comment by lucydodo** [comment] 2020-10-17 14:37
Well.. I agree @chrisjlocke too. and also, I think it's a bit better for the hash value position go backwards.
In fact, users are not very interested in hash values. They interest in how the code actually changed. :smile:

**Comment by sky5walk** [comment] 2020-10-17 14:53
Arrrg, the point of this is to let users know which hash the nightly was built from. Not to reproduce the git timeline. I don't want to read tons of info, just quickly and left justified. If the hash is trailing after variable length commit comments, what an eyesore. :( 
I was also hoping the nightly filename would contain the short hash. This assures the user of the automated  build.

**Comment by lucydodo** [comment] 2020-10-17 17:23
I'm not sure what's the advantage of printing hash value first. Just to tell you what I think.. 🤔 
For most people, including me, a hash value is just a sequence of characters. I hope to achieve with this suggestion is:
- User can see what has changed since the previous nightly build.
- User can see what has changed since that last stable build.

We want to provide the best experience for all users, but time and resources are limited. 😞

**Comment by justinclift** [comment] 2020-10-17 17:39
Hmmm.  We can't change the filenames in any meaningful way, as those need to remain stable.

So, let's update the [README.txt](https://nightlies.sqlitebrowser.org/latest/%2A%20README.txt) file in the /latest directory for the nightlies server.

There are three sections currently in it:

* Windows
* macOS
* Linux

We don't need to change the Linux one, but it sounds like we need to add something to the "Windows" and "macOS" ones.

Probably an extra line in each, containing info for the commit hash the build was created from.

---

Instead of that, maybe we should just add extra files to the /latest directory containing the build information?

* `* BUILD_INFORMATION-Win32.txt`  <-- contains the commit hash this build was created from
* `* BUILD_INFORMATION-Win64.txt`  (etc)
* `* BUILD_INFORMATION-macOS.txt`

That should be easy enough to get working, without needing to muck around with the README.txt file.

---

Thoughts?

**Comment by lucydodo** [comment] 2020-10-17 17:46
> Instead of that, maybe we should just add extra files to the /latest directory containing the build information?

I'm on this one, Looking at the screenshot above, I put all the information in one file, but it would be a little wiser to divide it into three files like this. (Sometimes the builds hashes can be different for each platform: https://github.com/sqlitebrowser/sqlitebrowser/issues/2441#issuecomment-708417294)

**Comment by justinclift** [comment] 2020-10-17 17:49
Cool. :smile:

Yeah.  I was thinking three files is easier, because we can just have each script update it's own file when it runs.  That's going to be simpler than merging the output of three independent scripts into a single file.

**Comment by sky5walk** [comment] 2020-10-17 18:29
If you store the hash in the filenames, then we can have multiple versions in the nightly folder. This allows users to go back to previous working versions if one nightly broke something.

**Comment by justinclift** [comment] 2020-10-18 02:36
@sky5walk We already store historical nightly builds, they're just not in the`/latest` folder.  The `/latest` folder has binary names without any date or hash details on purpose, so the binaries can be linked to externally and (mostly) always work. :smile:

**Comment by lucydodo** [comment] 2020-10-18 08:55
@sky5walk Previous nightly builds can be download from the following link.
Including the hash value in the file name is one way to do it, but there is a problem that definitely makes the file name messy. 😞 

- macOS : https://nightlies.sqlitebrowser.org/osx/
- Win32 : https://nightlies.sqlitebrowser.org/win32/
- Win64 : https://nightlies.sqlitebrowser.org/win64/

**Comment by justinclift** [comment] 2020-10-18 09:14
We could probably include the hash in the filenames outside of the "latest" folder.

eg: `DB.Browser.for.SQLite-2020-10-15-win32.zip` → `DB.Browser.for.SQLite-2020-10-15-somehashvaluehere-win32.zip`

@sky5walk Does that sound useful to you?

**Comment by chrisjlocke** [comment] 2020-10-18 10:44
I downloaded VirtualBox yesterday, and they have a nice download page.
https://www.virtualbox.org/wiki/Download_Old_Builds_5_2

I'd keep the filename simple, and have an HTML page for every download.  Easy to knock something like this up containing every hash, commit and detail you could ever want in any order imaginable.  But keep the filename as basic and generic as possible.

**Comment by lucydodo** [comment] 2020-10-18 10:55
It's a bir complicated, but we can also do the following:

We can write a script that modifies a static HTML web page like VirtualBox website on every nightly build release, this method will be user-friendly. (Of course, constructing dynamic HTML web pages is best, but this method will make a fair amount of load on the server). What do you reckon? :smile:

**Comment by sky5walk** [comment] 2020-10-18 12:46
Ok, to date, I only used the /latest download page.
But if you start appending hash+datecode in the [historic/all](https://nightlies.sqlitebrowser.org/win64/) folders then we have nirvana.
What is the reason for the /latest folder if the majority of these users are testers?
New and novice users would choose /release downloads.

**Comment by justinclift** [comment] 2020-10-18 14:25
> I had write access to the server once ... lost it in the midst of time and computer changeovers!

@chrisjlocke It's probably just my forgetting to create account for people on the Digital Ocean nightlies VM when it was created.  Creating accounts is easy though.  Want one?  Same question for you too @lucydodo.  It might make things easier to test stuff out. :smile:

**Comment by lucydodo** [comment] 2020-10-18 14:35
@justinclift oh, that will be of great help to me. Thanks! :+1:

**Comment by chrisjlocke** [comment] 2020-10-18 14:40
I just used to tidy up the filenames and stuff to save you a job!  Happy to take on that role again... :)

**Comment by lucydodo** [comment] 2020-10-19 11:41
@sky5walk New / novice users generally use the stable version.
Those who use nightly builds want to quickly use the latest features or fixed bugs. and I think it is correct to use the latest version (in theory) for nightly builds. (because generally it develops further, does not regress :smile: )

Well, this is a private opinion, we decided to include the short hash value at the end of the filename.
eg: `DB Browser for SQLite_20201019-9433601.dmg`

Right now, it's delayed because there are other high-priority works out there. but I'll get the job done in the near future.
I will notify you again after the work is done. Also, if you have any other opinions, please let us know. Thanks. :smile:

**Comment by sky5walk** [comment] 2020-10-19 13:01
> DB Browser for SQLite_20201019-9433601.dmg
This filename is excellent and indicative of an automated and professional system. 👍 

Yes, in theory we only need the "latest" version, but that is challenged by the reality of human error. ☂️

**Closed** 2023-06-10 00:50 UTC
Labels: enhancement
