### ISSUE TITLE
'Continuous build' is marked as 'Latest Release' and not as 'Pre-release' in GitHub

### ISSUE THREAD

**Issue by core-code** [sqlitebrowser/sqlitebrowser#2566] opened 2021-01-31 19:01 UTC
'Continuous build' is marked as 'Latest Release' and not as 'Pre-release' in GitHub

**Comment by justinclift** [comment] 2021-02-01 07:26
Yeah, it's created automatically as part of a part of a script.  There doesn't seem to be a way to fix it, so it's marked as "Pre-release" either. :frowning:

**Comment by core-code** [comment] 2021-02-01 11:06
sorry don't know how to do it, but pretty sure there is some way as the automated builds of other projects are usually tagged right.

**Comment by chrisjlocke** [comment] 2021-02-01 13:49
Looks like it just needs a `prerelease: true` tag.

**Comment by mgrojo** [comment] 2021-02-02 07:05
This is fixed now. It was caused by a change in the upload.sh script that we use. It requires now an environment variable to declare the build as a pre-release.

**Closed by mgrojo** 2021-02-02 07:05 UTC
Labels: linux, packaging

**Comment by justinclift** [comment] 2021-02-02 09:13
Well done @mgrojo, that's awesome!

Thanks for reporting the problem @core-code.  It wouldn't have been fixed otherwise. :smile:

**Comment by core-code** [comment] 2021-02-02 10:51
thanks for solving this :)
