### ISSUE TITLE
Automatic Internet connection attempt at launch? 

### ISSUE THREAD

**Issue by digital-carver** [sqlitebrowser/sqlitebrowser#398] opened 2015-08-11 10:36 UTC
I installed SqliteBrowser recently, and to my surprise found that the program tries to make a https connection to an IP automatically at launch. With the amount of open-source involvement in this, I realize this probably something innocuous like Checking for updates or something, but even then, connecting to some IP without any form of notification to the user raises immediate red flags to me.

If it is indeed about automatic updates, please allow the user to choose it consciously, rather than doing it behind the curtains. With a simple dialogue at first launch, saying "Automatic updates are enabled and will ensure DB4S is at the latest version" - with a prominent OK button and a "Change setting" text link that takes you to the Preferences page - you can also ensure that only those who really wish to disable auto-updates do that. Currently, even if the user wishes not to allow external connections (for whatever reason), a connection is going to happen at the very first launch, before (s)he has a chance to change the Preferences.

And whenever update check is going on, you could also give a simple notification, putting to use the several unused pixels at the bottom of the window. I consider this necessary because, given that DB4S is a desktop program that one doesn't expect to connect to the Internet, making external connections is an unusual state for the program and something that deserves a user notification. Putting it at the bottom left also keeps it similar to browser status messages, which would make it easier for users to grok.

**Comment by justinclift** [comment] 2015-08-11 21:40
Hmmm, by default it's set to automatically check (by reading this file: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/currentrelease on GitHub) if you're running the latest version.  You can turn that off in the preferences though, if that's what you want.

Lots of apps do this checking... so I'm kind of thinking it's not a bad thing.

???

**Comment by justinclift** [comment] 2016-01-06 13:13
Thinking this over more, it's not a bad idea to update the status bar when doing the check if there's a later version.  It might happen pretty quickly though (depending on speed of user's network to the GitHub server), so we might need to ensure it sticks around for at least some period of seconds (eg 5 seconds?) so it's not too easily missed. :smile:

**Comment by MKleusberg** [comment] 2020-02-13 12:40
Closing this as the question seems to be answered and the issue is really old :smile:

**Closed by MKleusberg** 2020-02-13 12:40 UTC
Labels: enhancement
