### ISSUE TITLE
select appropriate file filter corresponding to "Mode"

### ISSUE THREAD

**Issue by n-arakawa** [sqlitebrowser/sqlitebrowser#1535] opened 2018-09-15 01:39 UTC
Describe the new feature
--------------------------
The file filter for "import" in "Edit Database Cell" is always start with "Text Files".
Hope to change it according to the "Mode" selection.

Version 3.10.99 (Sep 15 2018)

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment] 2018-09-15 10:15
Do you mean mode, not model, don't you? Yes, it makes sense to alter the order of the filters to get by default the filter appropriate for the currently selected mode.

**Comment by mgrojo** [comment] 2018-09-15 11:33
@n-arakawa, the change is already committed. Could you give it a try when you can?

**Comment by n-arakawa** [comment] 2018-09-15 13:55
Thank you,

I checkked Version 3.10.99 (Sep 15 2018).
It is almost OK. 

However XML mode is wrong.( filter as 'All files')

**Comment by mgrojo** [comment] 2018-09-15 15:09
I can't reproduce any problem with the XML mode. It's true it's different. The XML data is not currently being detected, but the other cases, yes. But depending on the currently selected mode, the XML filter is set first (which should be the default) and then is added the txt filter, just in case the mode is not coherent with the data. But it could be changed to use only XML and All files as filters.

Is your case different to this? The last option is truncated in the screenshot, but it's "All Files (*)".

![imagen](https://user-images.githubusercontent.com/13812910/45587633-9fff8480-b908-11e8-9b32-e1f7df65d271.png)

What operating system and Qt version are you using?

**Comment by n-arakawa** [comment] 2018-09-15 21:51
For me, the filter is fixed to 'All Files' with the XML mode.
For  other mode(txt, json..), default filter is correct and re-selecting filter is possible.

commit 9daf265
OS: Ubuntu 18.04
Version 3.10.99 (Sep 15 2018)
Qt Version 5.9.5
SQLCipher Version 3.4.1 (based on SQLite 3.15.2)

**Comment by mgrojo** [comment] 2018-09-16 15:15
@n-arakawa, my fault. I checked only the export case, while you always talked about the import. It should be fixed now.

**Comment by n-arakawa** [comment] 2018-09-16 21:32
Thank you!

OK with:
commit 18f0ef60ba129aca1f35f7811cf1769c96fb79cf
OS: Ubuntu 18.04
Version 3.10.99 (Sep 17 2018)
Qt Version 5.9.5
SQLCipher Version 3.4.1 (based on SQLite 3.15.2)

**Comment by mgrojo** [comment] 2018-09-16 21:54
Thanks for confirming! Closing this now.

**Closed by mgrojo** 2018-09-16 21:54 UTC
Labels: enhancement
