### ISSUE TITLE
Primary key not showing in Indices

### ISSUE THREAD

**Issue by dragonstar0828** [sqlitebrowser/sqlitebrowser#785] opened 2016-09-23 13:18 UTC
### Details for the issue

I created a field as a autoincrement primary key but it doesn't show in indicies - why
or why not?  
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [X] DB4S has another problem
#### I'm using DB4S on:
- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [X] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2016-09-23 14:02
Ouch, that doesn't seem good. :smile:

Would you have time to try the latest nightly build?  We have been fixing some of the problems with our handling of constraints (and similar), so there's a fairly good chance it's already been solved.

The download locations for nightly builds are on our front page, if that helps. :smile:

**Comment by dragonstar0828** [comment] 2016-09-23 14:12
Nightly builds for Windows link goes here...
 
http://sqlitebrowser.oldsch00l.com/
 
... which only contains a build log text file entry.

**Comment by justinclift** [comment] 2016-09-23 14:21
Aaarrgh.  That's right, we busted the build yesterday.  Sorry, I completely forgot.

The build was fixed earlier today though, so a new one should be automatically generated tonight.

Umm... would be ok to try it out tomorrow? (sorry for the hassle)

**Comment by dragonstar0828** [comment] 2016-09-23 14:23
Sure, or you can zip up the 64-bit Windows .exe and send it to me at darrel.christensen@tx.rr.com

**Comment by justinclift** [comment] 2016-09-23 14:28
Heh Heh Heh

Sorry, I'm focused on other stuff over the last few days, and probably until early next week.  Thus my leaving it to the automatic builds. :smile:

**Comment by dragonstar0828** [comment] 2016-09-24 13:29
I pulled down the nightly build and opened the db I created.
 
I have a table with a Primary Key and Indices still has (0) next to it.  :/

**Comment by justinclift** [comment] 2016-09-24 14:33
Arrrgh. 😦 

Thanks for checking. :smile:  This is definitely a bug we need to look into then.

Is there anything strange or unusual with your table structure?  Are you able to share the database, or it's structure with us, so we can try to replicate the problem?

**Comment by dragonstar0828** [comment] 2016-09-24 15:00
Right now it's a single table with 2 fields.  The first is the Primary Key and it's an Integer, the second is just a Text field.
 
Attached.
 
NOTE - as your product works with .db files it would be nice if your attachement technology supported that file type.
 
[miracap.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/491183/miracap.zip)

**Comment by justinclift** [comment] 2016-09-24 15:12
Thanks @dragonstar0828.  Yeah.  We're using GitHub, which has it's own ideas of what files are and aren't allowed in attachments. :smile:

**Comment by mafagafogigante** [comment] 2016-09-24 15:31
Fun fact: just changing the extension to any of the suggestions works too.

[miracap.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/491202/miracap.zip)
[miracap.pptx](https://github.com/sqlitebrowser/sqlitebrowser/files/491203/miracap.pptx)

But obviously actually zipping the files is a better practice.

**Comment by chrisjlocke** [comment] 2016-09-24 21:35
Replicated the issue here.  Simply created a new table with just one new field of an autonumber.  No index created.

http://screencast-o-matic.com/watch/cDQZr4jr3E

**Comment by justinclift** [comment] 2016-09-24 22:21
Sounds like people might hit this fairly commonly. 😦

**Comment by dragonstar0828** [comment] 2016-09-25 15:04
Looking forward to a build with this corrected, can't see moving ahead creating my db if indicies aren't being handled correctly.

**Comment by justinclift** [comment] 2016-09-25 16:07
It's unlikely to be fixed in the next few days, and probably not in the next week or so.

There are many other SQLite tools around.  At least one of them should work for you well enough for now. :smile:

**Comment by chrisjlocke** [comment] 2016-09-25 16:11
...or create the index manually.  Its not *that* difficult... 😉

**Comment by justinclift** [comment] 2016-09-25 16:20
Good point. :smile:

**Comment by dragonstar0828** [comment] 2016-09-25 16:24
True, I'll make 'em by hand for now.
 
Keep me posted, and let me know if there's any other features/fixes you need tested and I'll be happy to help...

**Comment by revolter** [comment] 2016-09-27 09:02
So should an index be created for every table with autoincrement column?

**Comment by chrisjlocke** [comment] 2016-09-27 10:03
Interesting.  Technically you don't need a primary key autoincrement field, as this is just an alias for the ROWID column anyway.
https://www.sqlite.org/autoinc.html

...and that doesn't have an index.  So I'd argue its not needed.  Haven't read the whole page yet though, as .... well, other things to do...! :wink:

**Comment by revolter** [comment] 2016-09-27 10:17
I knew that, but the code I'm working on never used the rowid, and I got used to the "primary key autoincrement `id` column" so I started using it in sqlite too, but I don't think it __has__ to have an index too. Aren't indexes optional?

**Comment by dragonstar0828** [comment] 2016-09-27 12:59
Yes they're optional, but when I tick a checkbox like "Primary Key" when creating a table where the operative word is KEY I usually get an index no matter the engine or front end I'm using - is hence my original posting.

**Comment by revolter** [comment] 2016-09-27 13:22
Ok, I know understood what you guys meant, and a colleague confirmed this behaviour too. Didn't know about this at all.

**Comment by chrisjlocke** [comment] 2016-09-28 07:19
Just a note that the following SQL **does** create an index.

`CREATE TABLE test (id TEXT PRIMARY KEY ASC)`

This was on v3.9

**Comment by chrisjlocke** [comment] 2016-09-28 07:41
Actuallly I lied.  It creates an index, but they're empty.

![image](https://cloud.githubusercontent.com/assets/7872218/18904545/75da2b02-8556-11e6-99b4-d333a2690dc5.png)

This was using the 'execute sql' tab.

**Comment by MKleusberg** [comment] 2016-10-12 21:46
I haven't read the entire conversation here to be honest but here are just some thoughts.

We get the indices list directly from SQLite. You can check it, too. Just run ```select * from sqlite_master where type='index'```. Now the point is that SQLite doesn't add primary keys to that list. They are sort of implicit indices that are there and are used as an index but aren't an index object like manually created indices.

So to avoid confusion in other places I would tend to leave it the way it is, i.e. rely on SQLite's behaviour here. Maybe we can highlight primary keys in some other way? Any suggestions would be welcome here. At the moment, if you expand the table tree and list all the columns, the PK will have a different icon. But that's it :smiley:

**Comment by chrisjlocke** [comment] 2022-08-25 18:13
Closing this as it's not a bug.

[sqlite.org/lang_createtable.html#rowid](https://www.sqlite.org/lang_createtable.html#rowid) The data for rowid tables is stored as a B-Tree structure containing one entry for each table row, using the rowid value as the key...Searching for a record with a specific rowid ...is around twice as fast as a similar search made by specifying any other PRIMARY KEY or indexed value.

So integer primary keys are not indexed in the same way.

This cab be proved by a simple database of 41000 rows.
Field1 is a primary key and a search takes less than 1ms.

![image](https://user-images.githubusercontent.com/7872218/186738735-aa1c3dec-6132-40ae-a60f-8f91b159d1ca.png)

But on field2 (not a key) takes 11ms.

![image](https://user-images.githubusercontent.com/7872218/186738939-0ae586a9-33fd-460e-93b2-d776add19807.png)

**Closed by chrisjlocke** 2022-08-25 18:13 UTC
Labels: question
