### ISSUE TITLE
[Feature]: Dark Mode

### ISSUE THREAD

**Issue by Arnauw** [sqlitebrowser/sqlitebrowser#3696] opened 2024-08-01 21:17 UTC
### Describe the new feature

My eyes burn.

### Does this feature exist in another product or project? Please provide a link

Duh

**Comment by lucydodo** [comment] 2024-08-01 21:27
Do you mean you want to enable dark mode?
If so, this is a duplicate of issue #3429.

**Closed** 2024-08-02 00:08 UTC
Labels: duplicate

**Comment by Arnauw** [comment] 2024-08-02 08:29
TY
