### ISSUE TITLE
Taskbar icon flashes on minimize

### ISSUE THREAD

**Issue by victor-david** [sqlitebrowser/sqlitebrowser#1100] opened 2017-08-24 21:12 UTC
### Details for the issue
When using the "Show Desktop" button (far right on task bar) to minimize all apps, DB4S minimizes to its task bar icon as expected, but then the task bar icon begins to flash. It continues to flash for about 10 seconds and then it settles into a a yellow-orange-highlighted state. Once you click on the icon to restore the app window again, the taskbar icon goes back to normal.

This only happens when DB4S is window maximized or in its window normal state at the time you click the "Show Desktop" button. If DB4s is already minimized when you click "Show Desktop", it doesn't flash. Or if you minimize DB4s with its minimize button, it doesn't flash.

Maybe this is as-designed. If so, please re-consider. A flashing icon is used to alert the user to something that needs attention. In this case, there's nothing pending, or in an error state. This flashing behavior happens even if there's no database open.

Installed from this GitHub. No funky external download. File is:  DB.Browser.for.SQLite-3.10.0-win64.exe

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: (7 64bit Ultimate )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-08-24 22:22
Thanks @victor-david, yeah that doesn't sound good.  It's not on purpose at all, and we'll need to look into it. :smile:

**Comment by chrisjlocke** [comment] 2017-08-25 08:52
Good ol' Windows 7 again.  Not sure about Win 8, but it doesn't happen on Win 10.

**Comment by justinclift** [comment] 2017-08-25 09:26
Hmmm, wonder if this is the Windows version of #934?

If so, then https://github.com/justinclift/sqlitebrowser/commit/e7933fac6dd9b881a0a7247c65c23ee0d66b75c1 might fix it.  Asked a few people in the #934 issue if they could try compiling and running that, but no takers.

@victor-david If I make a one off build for you with a potential fix, would you be ok to try it?

**Comment by chrisjlocke** [comment] 2017-08-25 09:41
I'll fire up my Win 7 VM.  Urgh, I feel so dirty just thinking about it.  ;)

**Comment by chrisjlocke** [comment] 2017-08-25 09:42
:cringe:

![image](https://user-images.githubusercontent.com/7872218/29708839-176658da-8982-11e7-8a41-052c873a6f69.png)

**Comment by chrisjlocke** [comment] 2017-08-25 09:50
Confirmed:

![image](https://user-images.githubusercontent.com/7872218/29709066-e56b8cbe-8982-11e7-8d18-16354e0948b4.png)

Interestingly, it doesn't occur if you click the 'Show Desktop' button while a modal form in DB4S is displayed, eg, 'Edit Table Definition'.

**Comment by chrisjlocke** [comment] 2017-08-25 09:52
Turning off the 'Edit Database Cell' pane also disabled this 'bug'.  (View | Edit Database Cell)

**Comment by justinclift** [comment] 2017-08-25 10:30
Thanks @chrisjlocke.  I'll kick off a build shortly. :smile:

**Comment by justinclift** [comment] 2017-08-25 11:20
Build online:  https://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-2017-08-25-win64.exe

Note that it's "About" calls itself 3.9.200, as the branch with that experimental commit in it was created during our recent beta period.

**Comment by chrisjlocke** [comment] 2017-08-25 11:48
No improvement, unfortunately.

Just to confirm the 'Edit Database Cell' pane is greyed out / disabled (and still occurs)

![image](https://user-images.githubusercontent.com/7872218/29712840-beeb0342-8993-11e7-8b2d-1755eb61ce00.png)

**Comment by justinclift** [comment] 2017-08-25 12:09
Damn.  Ahhh well.

It might be worth us looking through the Edit Database Cell event loop code, just to figure out what the difference is between that and the other panels.  It'll probably (hopefully) turn out to be something simple.

**Comment by victor-david** [comment] 2017-08-25 12:20
@justinclift Here also. I installed your nightly just now. Problem still exists.

**Comment by justinclift** [comment] 2017-08-25 13:10
Thanks @victor-david. :smile:

**Comment by chrisjlocke** [comment] 2017-08-25 16:52
I can't do much over the weekend, but next week I can try and add some debug code to see which events (or signals, in Qt speak?) are getting fired off, etc?  Using a process of elimination, it should be easy to track where its occurring.

**Comment by justinclift** [comment] 2017-08-25 18:38
Good thinking.  Yep, that'd help @chrisjlocke.

And we'd probably also be able to figure out if this is the same (or even related) to the Linux issue.

**Comment by chrisjlocke** [comment] 2017-08-25 19:14
\o/

**Comment by justinclift** [comment] 2017-10-12 14:32
This is problem fixed in our source code now, with #1168, thanks to @kehugter. :smile:

There seems to be a problem with our Windows nightly builds though, so it might be a few more days though until this can be confirmed. 😦

**Comment by chrisjlocke** [comment] 2017-10-12 15:40
Thanks @kehugter and @justinclift - confirmed this version no longer flashes in the taskbar.

**Closed by chrisjlocke** 2017-10-12 15:40 UTC
Labels: bug, windows

**Comment by justinclift** [comment] 2017-10-12 15:56
@victor-david Our Windows nightly builds were fixed faster than I'd guessed.  If you're wanting a build with the flashing task bar problem fixed, then any nightly build from tomorrow morning (2017-OCT-13) onwards should be good:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/
