### ISSUE TITLE
Crash when setting PRAGMA application_id then querying it

### ISSUE THREAD

**Issue by Max13** [sqlitebrowser/sqlitebrowser#2844] opened 2021-09-21 10:23 UTC
Details for the issue
--------------------

#### What did you do?

- Select "Execute SQL" tab
- Input `PRAGMA application_id = 0;` (the value isn't relevant, you can enter the current `application_id` or a different one), and RUN.
- Input `PRAGMA application_id;` and RUN.

#### What did you expect to see?

The value of the `PRAGMA application_id`

#### What did you see instead?

EXC_CRASH (SIGABRT)

Useful extra information
-------------------------

Also, changing and requesting the `PRAGMA application_id` in the same request works successfully:

```sql
PRAGMA application_id = 0;
PRAGMA application_id;
```

> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.15 (darwin/19.6.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by justinclift** [comment] 2021-09-21 15:41
Good find.  Thanks for letting us know @Max13. :smile:

**Comment by MKleusberg** [comment] 2021-09-26 08:50
Can you try again with the latest nightly build, @Max13? You can download it [here](https://nightlies.sqlitebrowser.org/latest/). In theory it should work with that version.

The crash here is actually caused by the QScintilla editor component. This also explains why it doesn't crash if you execute the two statements in the same request. Commit 367665e7f51073dbfa3c9c0c6700c0d761af3389 should have fixed this issue.

**Comment by Max13** [comment] 2021-09-26 21:39
Checked just now using the link you provided, it's fine now.

Thanks for your reactivity!

**Comment by MKleusberg** [comment] 2021-09-28 18:19
Awesome! I'll close this issue then.

@justinclift Another reason to prepare a new release I guess :smile:

**Closed by MKleusberg** 2021-09-28 18:19 UTC
Labels: crash, macOS

**Comment by justinclift** [comment] 2021-09-28 19:34
Yeah.  I need to renew my Apple Dev Certificate too now, as that's expired.  Probably get that done this weekend. :smile:
