### ISSUE TITLE
Crash in SqliteTableModel::getForeignKeyClause

### ISSUE THREAD

**Issue by schdub** [sqlitebrowser/sqlitebrowser#942] opened 2017-01-25 10:31 UTC
### Details for the issue

1) Open DB;
2) Open 'Execute SQL' tab;
3) Execute simply select query to retrive data;
4) Hover mouse over cell 1:1 in retrieved data.
5) Crash.

### Useful extra information

For some reason SqliteTableModel::m_sTable is empty:
![screenshot from 2017-01-25 13 13 37](https://cloud.githubusercontent.com/assets/1304776/22286599/c4304586-e300-11e6-84df-35df316d2c3f.png)

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [X] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-01-25 11:05
Awesome @schdub.  @MKleusberg has been working on Foreign Key stuff recently, so this will probably interest him. :smile:

**Comment by innermous** [comment] 2017-01-25 11:08
Can't reproduce it. 
```Execute simply select query to retrive data;```
It's not enough, something tells me it's specific for your table/database.
Please, provide more useful information.

**Comment by innermous** [comment] 2017-01-25 11:11
**UPD**: Sorry, I am able to reproduce it now. This happens if one hovers a cell for at least 3-4 seconds.
Working on it.

**Comment by innermous** [comment] 2017-01-25 12:24
Tooltips in execute SQL tab can't be shown right now, since foreign key functionality relies on fixed size tables as *static* database objects.
I can only apply little fix that prevents crash right now.

**Comment by justinclift** [comment] 2017-01-25 17:16
Cool, sounds like progress in the right direction. :smile:

**Comment by MKleusberg** [comment] 2017-01-27 11:18
Yeah, I don't there is much more that we can do right now. In order to support the foreign key tooltip + shortcut for queries in the Execute SQL tab we'd have to parse and understand SELECT statements and those can become quite complex. We'd need a mechanism to track which column in the results table comes from which column of which table in the database. It's the same effort that's needed to implement editing in the results view (see #393, and #141 as well).

**Comment by justinclift** [comment] 2017-01-27 19:52
@MKleusberg Should this be closed then?

**Comment by MKleusberg** [comment] 2017-01-27 20:13
Yeah, I guess we can close it. If you have the time you could open a meta issue for this instead to collect use cases for a full SELECT statement parser. This here is one of them, the two issues I've mentioned above are others, and maybe there are more.

**Closed by MKleusberg** 2017-01-27 20:13 UTC
Labels: constraints & foreign keys
