### ISSUE TITLE
Compound keys result in deletion of multiple rows

### ISSUE THREAD

**Issue by Bachsau** [sqlitebrowser/sqlitebrowser#1835] opened 2019-04-03 17:22 UTC
Details for the issue
--------------------
#### Table schema
`CREATE TABLE "contents" ("folder_id" INT NOT NULL, "message_id" CHAR NOT NULL, PRIMARY KEY ("folder_id", "message_id")) WITHOUT ROWID;`

#### What did you do?
Selected a row and clicked "delete row"

#### What did you expect to see?
The selected row beeing deleted.

#### What did you see instead?
All rows with the same first part of the compound primary key were deleted.

Useful extra information
-------------------------
> DB4S v3.11.1 [built for x86_64-little_endian-lp64] on Arch Linux (linux/4.19.32-1-lts) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.12.1

**Comment by justinclift** [comment] 2019-04-03 17:42
Thanks @Bachsau. :smile:

Wonder if this is related to #1834?  If so, some of the fixes for that are in our `master` branch source code.

Since you're using Linux... any interest in [compiling our latest development code](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd) and seeing if the problem still shows up?

**Comment by Bachsau** [comment] 2019-04-03 17:58
I didn't look at your code, but reading the description, it likely is. Same problem with the generated query, just another type of statement.

**Comment by MKleusberg** [comment] 2019-04-04 11:27
Just chiming in here to confirm that this should be fixed with the latest few commits. Since this required a lot of changes, some more testing would be very welcome.

@Bachsau as @justinclift said, you'll want to compile our latest code. If you need any help with that just let us know :smile: We're also interested if the newest code is working for you :smile:

**Comment by Bachsau** [comment] 2019-04-04 14:52
I will tell you as soon I had time to test it.

**Comment by Bachsau** [comment] 2019-04-08 11:08
I just compiled it and made a quick test. It now uses a command called `sqlb_make_single_value` with the expected result of just one row beeing deleted. Out of curiousity: Why not just `WHERE idxpart1 = X AND ixpart2 = Y`?

**Comment by MKleusberg** [comment] 2019-05-02 12:30
@Bachsau ```sqlb_make_single_value``` is indeed a custom function which I have introduced for this specific purpose. It takes multiple values and converts them into a single unique value (at the moment by converting them into a JSON array). There is no need and no "good" reason for this way of doing it instead of using ```WHERE idxpart1 = X AND ixpart2 = Y``` as you suggested. But it is a lot easier for us this way because a large part of our code base assumes the rowid value is in the first column and makes use of that. All the code for updating and deleting records uses the first column for that, the code for showing/hiding the rowid column does that, and lots of other code too. That's an unfortunate legacy thing and probably needs refactoring in the future. But until then I figured it would be easier to play along and use the single column approach here :wink:

**Comment by BrukerJWD** [comment] 2019-06-25 12:27
Today I have discovered this issue for UPDATE statements and could reproduce them from in 3.8.X, 3.10.X and 3.11.2.
If you could provide me a Windows binary with this fix I would be happy to verify it.

**Comment by mgrojo** [comment] 2019-06-25 12:44
@BrukerJWD You can install the [nightly build](https://nightlies.sqlitebrowser.org/latest/) which will include this fix.

**Comment by BrukerJWD** [comment] 2019-06-25 12:48
Thanks! This issue is indeed fixed in the nightly:

    UPDATE "main"."table" SET "IsolationWidth"=? WHERE sqlb_make_single_value("folder_id","message_id")='["2","150"]';

**Comment by mgrojo** [comment] 2019-06-25 14:07
Thanks for confirming! Let's close this and if there is some pending minor issues related to the feature, we should gather them in  #1834, which it is still open.

**Closed** 2019-06-25 14:08 UTC
Labels: bug
