### ISSUE TITLE
Column selection in Browse Data tab is slightly broken

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1717] opened 2019-01-23 08:02 UTC
Details for the issue
--------------------

With current master head (98c9b3ba98d7d0063e55c5fab31497bc88f19f32), there appears to be some problems with selecting columns in the Browse Data tab.

1. When clicking a column header (a normal click, not especially long), the column is sorted (as expected).  To select an individual column, it seems like doing a rectangle selection over the column header works, or even a long click + small mouse move...  but, when the mouse click (doing the selection) is released, our column sorting code catches it and the column is then sorted.

So, the selection area holds, but the rows are now in a different order.

2. Similar to above, but when doing a rectangle selection for multiple columns.  When the mouse click is released from the final column, which column it was over then catches the mouse release event, so that column then gets sorted.

What **should** happen, is our code should recognise a selection operation is in place + not generate a column sort from it. :smile:

Haven't checked if this happens in 3.11.0 series yet.

Useful extra information
-------------------------

#### What operating system are you using?

- [x] Linux: CentOS 7 x64 KDE

#### What is your DB4S version?

- [x] Other: current git master head (98c9b3ba98d7d0063e55c5fab31497bc88f19f32)

**Comment by chrisjlocke** [comment] 2019-01-23 09:31
On Windows, I can't select one column.  Long clicking doesn't work, nor does doing a rectangle selection on one column.  I can select two or more, and if I use the <kbd>Ctrl</kbd> or <kbd>Shift</kbd> keys can select multiple columns (only consecutive selections though, not individual columns) but not one.
If I select multiple columns, like you, the last column 'appears' to get sorted (it gets the arrow in the header to denote its sorted) but it doesn't *actually* get sorted.  See screenshot:
![image](https://user-images.githubusercontent.com/7872218/51596749-965ade80-1ef1-11e9-84b2-bce85da603e2.png)
Note the 3rd column appears to be sorted (it was the last one selected) but its not sorted...

**Comment by justinclift** [comment] 2019-01-23 10:07
Interesting.  Sounds like some basic UX bug have crept in. :wink:

**Comment by mgrojo** [comment] 2019-01-26 20:14
> If I select multiple columns, like you, the last column 'appears' to get sorted (it gets the arrow in the header to denote its sorted) but it doesn't actually get sorted. 

I've fixed that particular case, which is the ugliest. The sort indicator is no longer moved when the user selects more than one column. Ideally the sorting should not be done when the selection is extended to two and then back to one, but I don't know how to detect that. What I've done is binding the double click to the single column selection. The problem is that the sorting is triggered before, on the first mouse click, but at least there's a way.

All this behaviour isn't new, it is the same for 3.10 and 3.11.

**Comment by justinclift** [comment] 2019-01-26 20:39
Excellent stuff @mgrojo! :smile:

> Ideally the sorting should not be done when the selection is extended to two and then back to one, but I don't know how to detect that.

Yeah.  We might need to look at the code of how some other Qt 5.x applications do it, if they get it correct.

> All this behaviour isn't new, it is the same for 3.10 and 3.11.

Heh Heh Heh.  Didn't realise that.  In that case, kind of guess it's weird no-one's reported it yet.

Oh well, at least it's on the issue tracker now.

**Comment by iKlsR** [comment] 2019-01-28 06:55
From some quick poking around just now. <kbd>Shift</kbd> and <kbd>Ctrl</kbd> seem to be useless as I can simply drag to select both rows and or columns.

What about holding <kbd>Shift</kbd> on a column to select it in its entirety and also adding a right click option to the header as well. Holding <kbd>Shift</kbd> can add or remove (if a selected column is pressed) from the current column selections. Additionally, holding <kbd>Shift</kbd> **and** <kbd>Ctrl</kbd> should do perform the same operation but for rows without having to use the table margin.

I don't think there's any use for gap selecting (picking arbitrary cells akin to a file browser) with <kbd>Ctrl</kbd> and as mentioned earlier <kbd>Shift</kbd> isn't needed to grab adjoined cells. Having sorting as a byproduct of sorts of intending to select a column is pretty bad UX.

**Comment by mgrojo** [comment] 2019-10-28 20:38
In the latest nightly, there are shortcuts for selection of entire columns ("Ctrl+Space") or rows
("Shift+Space") from the current cell selection. They are based on traditional spreadsheet shortcuts for those actions.

There is also a menu entry in the column header for selecting that column. It does not interfere with sorting. Do these changes address correctly this issue or are there still some pending detail?

**Comment by gnbl** [comment] 2019-12-17 17:53
> Version 3.11.99 (Dec 16 2019)
> Built for x86_64-little_endian-llp64, running on x86_64
> Qt Version 5.12.6
> SQLite Version 3.30.1

Double-clicking on a sorted column to select all column cells changes sort order.

It appears sorting via click on table header selects the entire row by default (column highlighted, row index shown in bold, data info in status bar), sorts, deselects current cell, and restores selected cell (not by data, but by underlying col/row index, i.e. e.g. "1" in topmost cell after sorting may be other data e.g. "100"). This consequently affects "Edit Database Cell" (losing selection, editing different cell without actively selecting another cell).

**Comment by mgrojo** [comment] 2019-12-23 16:26
@gnbl the current nightly build does no longer select the row when the column is single clicked. Single click is only used for sorting and Control+Click for adding column to sorted columns.

Unfortunately, double click for selection still makes a sorting (after the first click) and a selection (after the second click). Note that you can use cleaner methods for selection now, like using the contextual menu in the column header or selecting some cells and pressing Ctrl+Space to select the entire columns.

**Comment by MKleusberg** [comment] 2020-02-12 22:21
Closing this because it seems like all problems described here are solved. Feel free to re-open this issue if I missed something :smile:

**Closed by MKleusberg** 2020-02-12 22:21 UTC
Labels: bug, gui
