### ISSUE TITLE
[Bug]: copy results in html data

### ISSUE THREAD

**Issue by eevleevs** [sqlitebrowser/sqlitebrowser#3125] opened 2022-08-07 18:21 UTC
### What did you do?

I browsed a table or view, selected a cell and copied the data. 

### What did you expect to see?

I expected the clipboard to contain the text-only version of the data.

### What did you see instead?

The clipboard contains html like:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><title></title><meta name="generator" content="DB Browser for SQLite"><meta name="date" content="YYYY-08-DDT20:15:22.721"><style type="text/css">br{mso-data-placement:same-cell;}</style></head><body>

E Books
--


</body></html>
```

and in some application, pasting results in ```br{mso-data-placement:same-cell;}E Books```.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Debian Bullseye

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment] 2022-08-07 18:44
In Windows, copying something copies it in several formats, and its up to the application when you click 'paste' which 'flavour' of whats on the clipboard is the most suitable format - in Notepad it'll be plain text, but in Excel it could be one or two cells.
I've not seen this myself - copying data and the clipboard contains HTML.  The date format doesn't even appear valid - "content="YYYY-08-DDT20:15:22.721">" - what data did you actually highlight and copy?  Could you have a background process monitoring and tweaking the clipboard?  I know in Windows, MS Office can play havok with the clipboard, grabbing it and Outlook grabbing it to try and identify meeting data, etc.

**Comment by eevleevs** [comment] 2022-08-07 19:56
I am not on Windows, but on Chrome Os. The application is running in a Debian container. No background process that I am aware of. I am copying a text cell with the context menu, or ctrl-c.

**Comment by eevleevs** [comment] 2022-08-11 17:10
You might be right, thanks for the ideas. It really depends where I paste. The example I gave above is copied from a simple text field. When pasting in the address bar of the browser it looks normal. Pasting in this textarea gives the HTML. Pasting inside an Android application (I have also those on this machine) gives ```br{mso-data-placement:same-cell;}E Books```. No clue if you can do anything, close the issue if not.

**Comment by mgrojo** [comment] 2022-10-01 22:06
I confirm we are including the data in several formats in the clipboard, and it should be up to the application where the data is pasted the most relevant to them, for example, a plain text editor will choose text/plain and a word processor will take and interpret the text/html data pasting rich text format. Some applications will let the user choose or have different keyboard shortcuts. This works on Linux and Windows, so I suppose the issue is with Qt on ChromeOS or ChromeOS itself.

I'll close the issue, as suggested, since there's nothing we can do to fix it, without loosing functionality on other platforms.

**Closed by mgrojo** 2022-10-01 22:06 UTC
