### ISSUE TITLE
Cannot delete some indexes it was able to create

### ISSUE THREAD

**Issue by mafagafogigante** [sqlitebrowser/sqlitebrowser#773] opened 2016-09-11 03:08 UTC
### Details for the issue

As of https://github.com/sqlitebrowser/sqlitebrowser/commit/7deeb02889e170752bba2aa9ed367fcdb9912cdf, DB4S fails to delete some indexes it creates.

### Useful extra information

If one was to create an index starting or ending with trimmable characters (such as an ASCII whitespace ` `), one would create an index which the browser cannot delete by itself.

This is the type of bug you find when you make typos (such as trailing whitespaces), but I don't think such behavior is acceptable anyway.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [X] Linux: (distro: Fedora 23 4.6.6-200.fc23.x86_64)
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

https://github.com/sqlitebrowser/sqlitebrowser/commit/7deeb02889e170752bba2aa9ed367fcdb9912cdf

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

#### How to reproduce

In the interface, create an index called "Index " on any table. Then try to delete it using the interface. It will issue

    DROP INDEX `Index`; -- No whitespace

and fail.

Executing 

    DROP INDEX `Index `; -- With the trailing whitespace

works as expected.

**Comment by justinclift** [comment] 2016-09-11 09:59
Good catch. :smile:

**Comment by innermous** [comment] 2016-09-20 20:36
I wonder how people find these bugs... I thought I am the special one.

**Comment by mafagafogigante** [comment] 2016-09-20 22:41
The right mindset to find failures. Similar attempts reveal problems in several non-mature terminal utilities. These problems, however, never happen to an end user until they happen, which may take a few years, or may never happen.

**Comment by justinclift** [comment] 2016-09-20 22:50
Yeah.  On a similar note, if you want to see weird things happen (and you use Libvirt for anything), make some VM's with unusual unicode characters in (eg) their pathname, paths to their storage, etc.

Note - Don't do that with anything running important data.  Just saying. :wink:

**Comment by chrisjlocke** [comment] 2016-09-21 06:35
Just chippin' in, but I don't think or regard this as a bug per se.  If I type this:
`create table     jack      (id text);`
`create index    jack2    on jack (id);`

Then the table 'jack' and index 'jack2' are created as expected (well, as semi-expected - without whitespace).
If I enclose that in quotes, then yes, the whitespace is created.  However, as its explicitly set, DB4S is doing what I'm asking.  There may be a specific reason I want a table called "jack " (with spaces) and it would annoy me (and I'd consider it more of a bug) if I asked for one using "jack " and DB4S changed that to "jack".  I haven't tested the official sqlite3 commandline program, but I'm sure that would have this 'feature'.

**Comment by justinclift** [comment] 2016-09-21 10:14
Creating tables/indexes/(etc) with spaces isn't really the problem.  The problem is DB4S failing to work with those tables/indexes/(etc) afterwards.

eg select the "jack " index, choose to delete it... and the delete will fail.  In the code for the deletion, there seems to be the equivalent of a trim() function happening on the object name before it's getting deleted.

I took a quick look at this just after @mafagafogigante reported it, but the reason isn't obvious.  The code which pulls out the object name itself just prior to the delete function already has the trimmed name.  I didn't have time/energy to dig further then.

**Comment by mafagafogigante** [comment] 2016-09-21 10:15
I was typing and your comment popped up. Damn. Will present a demo soon.

**Comment by mafagafogigante** [comment] 2016-09-21 10:24
[How to reproduce the issue](https://www.youtube.com/watch?v=fp_pzS7FD3c).

**Comment by justinclift** [comment] 2016-09-21 10:27
Yep, that's clear. :smile:

**Comment by chrisjlocke** [comment] 2016-09-21 11:52
Aah, through the GUI.  Apologies - so used to using the 'Execute SQL' tab, I do all the work through that.

**Comment by mafagafogigante** [comment] 2016-09-21 12:25
I like that Gnome makes these captures so easy (and working on multiple 1080p screens out of the box). Many examples are show, don't tell and these settle most issues.

**Comment by justinclift** [comment] 2016-09-29 18:28
@mafagafogigante Martin has just added a fix for this to the master branch in git.

Would you have a few minutes to compile the latest code to verify from your point of view? :smile:

**Comment by mafagafogigante** [comment] 2016-09-29 18:55
@justinclift on it right now.

**Comment by mafagafogigante** [comment] 2016-09-29 19:00
@justinclift it now works as expected.

**Comment by justinclift** [comment] 2016-09-29 19:57
Awesome @mafagafogigante!

Thanks for both reporting, and verifying this. :smile:

**Closed by justinclift** 2016-09-29 19:57 UTC
Labels: bug
