### ISSUE TITLE
Error right after installing

### ISSUE THREAD

**Issue by samokosik** [sqlitebrowser/sqlitebrowser#2628] opened 2021-03-13 17:42 UTC
What is your question
-----------------------
Hi,
I downloaded the SQLite browser yesterday and right after the installation an error regarding to the font occurs every time I start it, however, I have not found any "broken things" just the error message regarding to the font.
My system: Windows 10 Enterprise LTSC
![image](https://user-images.githubusercontent.com/73645764/111038971-e7a8ed80-842b-11eb-87e9-a7cee4bed101.png)

**Comment by chrisjlocke** [comment] 2021-03-13 20:33
Yes, this is a weird one, and I've no idea what's going on.
This has been reported before, and the resolution seems to be to create a custom font.  See here:
https://github.com/sqlitebrowser/sqlitebrowser/issues/2556

I can't reproduce this, so don't know why it's happening, or if there is a better solution.

**Comment by samokosik** [comment] 2021-03-14 16:38
It actually does not happen anymore!
I created a file using eudcedit and created a random file, then save it - this resulted in the message not appearing anymore...

**Comment by chrisjlocke** [comment] 2021-03-14 18:30
Excellent, thanks for letting us know.  It's only happened to a couple of people (considering the number of downloads we've had) so it would be interesting to know whats going on.
I'll close this but of course yell if it pops up again. 👍

**Closed by chrisjlocke** 2021-03-14 18:30 UTC
Labels: core application

**Comment by yanoolo** [comment] 2021-05-24 20:13
I had the same issue with the error: Unable to open default EUDC font: "C:\\Windows\\FONTS\\EUDC.TTE"
Using WINDOWS 10 21H1
The solution in #2556 works.
