### ISSUE TITLE
[Bug]: Unable to open the browser on macOS Monterey

### ISSUE THREAD

**Issue by rjbhullar** [sqlitebrowser/sqlitebrowser#2944] opened 2022-01-13 03:54 UTC
### What did you do?

I downloaded the latest version(3.12.2) on my Apple M1 machine that has Monterey macOS.

### What did you expect to see?

I expected that the app will open.

### What did you see instead?

When I try to open the app, an error is shown saying *DB Browser for SQLite quit unexpectedly.* I have tried reopening it multiple times but encountering the same error every time.

<img width="283" alt="Screen Shot 2022-01-12 at 7 05 08 PM" src="https://user-images.githubusercontent.com/54448409/149262920-0301422e-4f46-47aa-a405-763c2ec437c3.png">
*

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

Monterey

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment] 2022-01-13 07:50
We've not had other reports of this, so (not being rude) it's hopefully something specific to your machine.  Some weird setting or something.
Could you try the nightly?  It has different versions of sqlite, so is a different build.
https://nightlies.sqlitebrowser.org/latest/

You might have to click on 'report' or dig out the debug thingy so someone with more knowledge than me in macOs can identify what the issue is.

**Comment by rjbhullar** [comment] 2022-01-13 14:46
I tried the nightly and it worked. Thanks for your help. :)

**Comment by MKleusberg** [comment] 2022-01-21 09:05
Awesome :smile: I'll close this issue then. In case you notice any crashing with this nightly build or a more recent nightly build in the future, just let us know so we can pin down this issue.

**Closed by MKleusberg** 2022-01-21 09:05 UTC
Labels: crash, macOS
