### ISSUE TITLE
move field up

### ISSUE THREAD

**Issue by kaldown** [sqlitebrowser/sqlitebrowser#306] opened 2015-05-11 04:37 UTC
move field up sometimes make a crush, and most of the time I have sth like this:
![screenshot_2015-05-11_09-34-13](https://cloud.githubusercontent.com/assets/3754017/7558600/5389386e-f7c1-11e4-90e9-9010a082c44b.png)

FreeBSD 10.1
SQLBrowser 3.5.1

**Comment by justinclift** [comment] 2015-05-11 08:59
Interesting, that definitely looks like a bug of some sort.  Do you have time to check if it happens on our 3.6.0 release as well?

**Comment by MKleusberg** [comment] 2015-12-21 13:32
@kaldown This looks like a Qt bug to me... Do you have time to test with our latest release? We're using a newer Qt version in there which might fix this issue for you without any extra work :smile:

**Comment by kaldown** [comment] 2015-12-21 19:09
@MKleusberg sure, soon I'll check it out.

**Comment by kaldown** [comment] 2015-12-25 18:42
Version 3.6.0
Qt Version 4.8.7
SQLite Version 3.8.11.1

Still the same

**Comment by justinclift** [comment] 2015-12-25 20:12
Hmmm, in theory it should be possible to compile with Qt5 on FreeBSD, rather than Qt4.  @kaldown If you have an idea how to get that happening (I don't :wink:), it would be worth trying out.

**Comment by kaldown** [comment] 2015-12-25 20:28
Actually I think that I make some mistake.
https://freshports.org/databases/sqlitebrowser/ According this, it should be 3.7.0 version, rather than my 3.6.0. Seems interesting, why `pkg upgrade` didn't catch this scenario.
Doesn't use FreeBSD for a while, so...
Will check and repeat in further. 
Sorry for worrying.
If problem still take place, I'll write to port maintainer.

**Comment by justinclift** [comment] 2015-12-25 21:32
No worries at all.  If it turns out the problem is fixed, please remember to close this issue. :grin:

**Comment by kaldown** [comment] 2015-12-30 01:20
Yes, it continuous even with 3.7.0 compiled from ports.
I invited the maintainer coder@tuxfamily.org, so It's nothing I can do more.

**Comment by justinclift** [comment] 2015-12-30 08:24
No worries. :smile:

We released version 3.8.0 a few days ago.  I do the packaging for MacOS X, and for this release I used Qt5 instead of Qt4.  It was very simple to change - I just needed to make sure I had the Qt5 development pieces installed instead of Qt4.

I kind of wonder if it might be that simple for FreeBSD as well.  I'm not sure... the maintainer might have better idea if it's easy to try that. :wink:

**Comment by MKleusberg** [comment] 2017-05-08 11:57
Any update on this, @kaldown? We're Qt5-only by now and chances are that the issue is fixed simply by using the new Qt version :smiley: Do you have the time and the interest to do a quick test?

**Comment by kaldown** [comment] 2017-05-09 17:48
2 years past since.
I'm no more FBSD everyday user ;D

**Comment by justinclift** [comment] 2017-05-09 18:21
Interesting, our servers for dbhub.io are running on FreeBSD.

I might as well try spinning up a desktop sometime next week, and take a look into the state of the DB4S port there.

**Comment by MKleusberg** [comment] 2017-05-12 08:33
No worries, @kaldown :smiley:

@justinclift We could just close this issue then. I'd guess it's solved by now and if anybody else should encounter the same issue they can just open a new one or reopen this one.

**Comment by justinclift** [comment] 2017-05-12 09:01
No worries.  I'll get to the FreeBSD port of DB4S at some point anyway.

**Closed by justinclift** 2017-05-12 09:01 UTC
Labels: bug

**Comment by justinclift** [comment] 2017-08-22 20:11
Closing this now as DB4S has been updated on FreeBSD to v3.10.0 by @lbartoletti, and there have been no other reports of this weirdness.  If someone else does have it happen, feel free to re-open this. :smile:
