### ISSUE TITLE
Crash with EXC_BAD_INSTRUCTION  on OS X

### ISSUE THREAD

**Issue by lphooge** [sqlitebrowser/sqlitebrowser#465] opened 2015-12-28 15:16 UTC
When creating a new database or opening an existing one the application crashes with the error 
Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Complete crash log is attached

[sqlitebowser crashdump.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/73302/sqlitebowser.crashdump.txt)

**Comment by justinclift** [comment] 2015-12-28 18:23
Interesting.  As a thought, do you have Homebrew installed?

If you do, would you be ok to compile DB4S and see if it still crashes for you?  That would help figure out if it's something wrong with our code, or instead if it's a packaging problem.

Compiling DB4S is very, very, very simple if you have Homebrew installed.  You can literally cut-n-paste the instructions here, and it takes ~5 minutes in total (including reading the instructions). :)

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

**Comment by Z4us** [comment] 2015-12-29 12:40
What version of OS X you're on, lphooge?

**Comment by lphooge** [comment] 2015-12-29 13:02
Yosemite, 10.10.5

**Comment by lphooge** [comment] 2015-12-29 13:17
@justinclift yes i do have homebrew installed.
I do not know what you are referring to with "compiling DB4S", but when I build the app bundle like the instructions say, the resulting app does not NOT crash when creating a database. The official build still crashes.

One thing I noticed: I got the warning "Warning: sqlite-3.8.11.1 already installed" when trying to install sqlite via brew.
Also, a sqlite3-binary already existed in /usr/bin (3.8.5 2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace).

**Comment by justinclift** [comment] 2015-12-29 16:10
Ok, that sounds like the packaging I did might not like OSX 10.10 then. :frowning:

I should be able to get it running in a VM and test it sometime in the next few days.  In the meantime, it sounds like you're ok for now (with the self-compiled .app version).  That warning is new to me too... guessing it won't be important, but I won't really know for sure until I've had a chance to muck around with things on 10.10 to find out too. :wink:

**Comment by pbtura** [comment] 2015-12-30 16:47
I think I'm seeing the same issue. Here is a crash log if it will help:

Process:               sqlitebrowser [36634]
Path:                  /Applications/sqlitebrowser.app/Contents/MacOS/sqlitebrowser
Identifier:            net.sourceforge.sqlitebrowser
Version:               3.8.0 (3.8.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           sqlitebrowser [36634]
User ID:               503

Date/Time:             2015-12-30 11:42:05.974 -0500
OS Version:            Mac OS X 10.10.5 (14F1509)
Report Version:        11


Time Awake Since Boot: 88000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsqlite3.0.dylib            	0x000000010158f41d sqlite3_mutex_alloc + 98
1   libsqlite3.0.dylib            	0x000000010158ed23 sqlite3_initialize + 38
2   libsqlite3.0.dylib            	0x000000010159d716 sqlite3_open + 79
3   net.sourceforge.sqlitebrowser 	0x0000000101186424 DBBrowserDB::tryEncryptionSettings(QString const&, bool*, CipherDialog*&) + 52
4   net.sourceforge.sqlitebrowser 	0x00000001011856f6 DBBrowserDB::open(QString const&) + 70
5   net.sourceforge.sqlitebrowser 	0x000000010119cc37 MainWindow::fileOpen(QString const&, bool) + 439
6   net.sourceforge.sqlitebrowser 	0x000000010127f39a Application::event(QEvent*) + 58
7   org.qt-project.QtWidgets      	0x00000001016c44bb QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
8   org.qt-project.QtWidgets      	0x00000001016c789e QApplication::notify(QObject*, QEvent*) + 8318
9   org.qt-project.QtCore         	0x000000010243a983 QCoreApplication::notifyInternal(QObject*, QEvent*) + 115
10  org.qt-project.QtGui          	0x0000000101d05137 QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 951
11  org.qt-project.QtGui          	0x0000000101cf1af3 QWindowSystemInterface::handleFileOpenEvent(QString const&) + 67
12  libqcocoa.dylib               	0x0000000104428d36 0x104405000 + 146742
13  com.apple.AppKit              	0x00007fff84998788 -[NSApplication(NSAppleEventHandling) _openDocumentURLs:withCompletionHandler:] + 875
14  com.apple.AppKit              	0x00007fff84997639 __69-[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:]_block_invoke + 917
15  com.apple.AppKit              	0x00007fff84b190f0 __95-[NSPersistentUIManager restoreAllPersistentStateRegisteringAsReadyWhenDone:completionHandler:]_block_invoke557 + 37
16  com.apple.AppKit              	0x00007fff8486f949 __97-[NSDocumentController(NSInternal) _autoreopenDocumentsIgnoringExpendable:withCompletionHandler:]_block_invoke_3 + 140
17  com.apple.AppKit              	0x00007fff8486f491 -[NSDocumentController(NSInternal) _autoreopenDocumentsIgnoringExpendable:withCompletionHandler:] + 798
18  com.apple.AppKit              	0x00007fff84b19034 -[NSPersistentUIRestorer finishedRestoringWindowsWithZOrder:completionHandler:] + 1745
19  com.apple.AppKit              	0x00007fff851438f2 run_cocoa_block + 41
20  com.apple.AppKit              	0x00007fff84b67e4b __82-[NSPersistentUIRestorer restoreStateFromRecords:usingDelegate:completionHandler:]_block_invoke_2379 + 210
21  com.apple.AppKit              	0x00007fff84b67d42 __99-[NSApplication(NSPersistentUIRestorationSupport) _restoreWindowWithRestoration:completionHandler:]_block_invoke + 368
22  com.apple.AppKit              	0x00007fff84b5dac3 -[NSApplication(NSPersistentUIRestorationSupport) _restoreWindowWithRestoration:completionHandler:] + 773
23  com.apple.AppKit              	0x00007fff84b17cec -[NSPersistentUIRestorer restoreStateFromRecords:usingDelegate:completionHandler:] + 1990
24  com.apple.AppKit              	0x00007fff84b174a1 -[NSPersistentUIManager restoreAllPersistentStateRegisteringAsReadyWhenDone:completionHandler:] + 406
25  com.apple.AppKit              	0x00007fff8486dc07 -[NSApplication _reopenWindowsAsNecessaryIncludingRestorableState:registeringAsReady:completionHandler:] + 412
26  com.apple.AppKit              	0x00007fff84995795 -[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:] + 306
27  com.apple.AppKit              	0x00007fff8486d586 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 757
28  com.apple.Foundation          	0x00007fff886ce818 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 290
29  com.apple.Foundation          	0x00007fff886ce689 _NSAppleEventManagerGenericHandler + 102
30  com.apple.AE                  	0x00007fff8767843c aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 531
31  com.apple.AE                  	0x00007fff876781b9 dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 31
32  com.apple.AE                  	0x00007fff876780c3 aeProcessAppleEvent + 295
33  com.apple.HIToolbox           	0x00007fff8636fc6e AEProcessAppleEvent + 56
34  com.apple.AppKit              	0x00007fff84866da2 _DPSNextEvent + 2249
35  com.apple.AppKit              	0x00007fff84865e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
36  com.apple.AppKit              	0x00007fff8485baf3 -[NSApplication run] + 594
37  libqcocoa.dylib               	0x000000010442608d 0x104405000 + 135309
38  org.qt-project.QtCore         	0x000000010243807d QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
39  org.qt-project.QtCore         	0x000000010243af5a QCoreApplication::exec() + 346
40  net.sourceforge.sqlitebrowser 	0x000000010118535c main + 44
41  net.sourceforge.sqlitebrowser 	0x0000000101185324 start + 52

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff8dccf232 kevent64 + 10
1   libdispatch.dylib             	0x00007fff91b7926e _dispatch_mgr_thread + 52

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff8dcce94a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff906563dd start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff8dcce94a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff906563dd start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff8dcce94a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff906563dd start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff8dcce94a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff906563dd start_wqthread + 13

Thread 6:

Thread 7:: Qt bearer thread
0   libsystem_kernel.dylib        	0x00007fff8dcce3fa __select + 10
1   org.qt-project.QtCore         	0x0000000102489398 qt_safe_select(int, fd_set*, fd_set*, fd_set*, timespec const*) + 104
2   org.qt-project.QtCore         	0x000000010248a450 QEventDispatcherUNIXPrivate::doSelect(QFlags<QEventLoop::ProcessEventsFlag>, timespec*) + 672
3   org.qt-project.QtCore         	0x000000010248b51a QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 234
4   org.qt-project.QtCore         	0x000000010243807d QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
5   org.qt-project.QtCore         	0x000000010228c245 QThread::exec() + 117
6   org.qt-project.QtCore         	0x000000010228fd93 0x102258000 + 228755
7   libsystem_pthread.dylib       	0x00007fff9065905a _pthread_body + 131
8   libsystem_pthread.dylib       	0x00007fff90658fd7 _pthread_start + 176
9   libsystem_pthread.dylib       	0x00007fff906563ed thread_start + 13

Thread 8:: QScanThread
0   libsystem_kernel.dylib        	0x00007fff8dcc951a semaphore_wait_trap + 10
1   libdispatch.dylib             	0x00007fff91b7d7f6 _dispatch_semaphore_wait_slow + 213
2   com.apple.framework.CoreWLAN  	0x00007fff88be3755 -[CWInterface(Private) scanForNetworksWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergedScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:waitForWiFi:waitForBluetooth:priority:error:] + 638
3   com.apple.framework.CoreWLAN  	0x00007fff88bddfdc -[CWInterface scanForNetworksWithName:error:] + 109
4   libqcorewlanbearer.dylib      	0x0000000108c838ba 0x108c7e000 + 22714
5   org.qt-project.QtCore         	0x000000010228fd93 0x102258000 + 228755
6   libsystem_pthread.dylib       	0x00007fff9065905a _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff90658fd7 _pthread_start + 176
8   libsystem_pthread.dylib       	0x00007fff906563ed thread_start + 13

Thread 9:: Qt HTTP thread
0   libsystem_kernel.dylib        	0x00007fff8dcce3fa __select + 10
1   org.qt-project.QtCore         	0x000000010248a450 QEventDispatcherUNIXPrivate::doSelect(QFlags<QEventLoop::ProcessEventsFlag>, timespec*) + 672
2   org.qt-project.QtCore         	0x000000010248b51a QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 234
3   org.qt-project.QtCore         	0x000000010243807d QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
4   org.qt-project.QtCore         	0x000000010228c245 QThread::exec() + 117
5   org.qt-project.QtCore         	0x000000010228fd93 0x102258000 + 228755
6   libsystem_pthread.dylib       	0x00007fff9065905a _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff90658fd7 _pthread_start + 176
8   libsystem_pthread.dylib       	0x00007fff906563ed thread_start + 13

Thread 10:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff8dccf21a kevent + 10
1   libsystem_info.dylib          	0x00007fff91c26875 mdns_addrinfo + 692
2   libsystem_info.dylib          	0x00007fff91c26581 search_addrinfo + 179
3   libsystem_info.dylib          	0x00007fff91c1ef2e si_addrinfo + 1395
4   libsystem_info.dylib          	0x00007fff91c1e917 getaddrinfo + 179
5   org.qt-project.QtNetwork      	0x0000000102891254 0x10280b000 + 549460
6   org.qt-project.QtNetwork      	0x0000000102884c5a 0x10280b000 + 498778
7   org.qt-project.QtCore         	0x000000010228c8f7 0x102258000 + 215287
8   org.qt-project.QtCore         	0x000000010228fd93 0x102258000 + 228755
9   libsystem_pthread.dylib       	0x00007fff9065905a _pthread_body + 131
10  libsystem_pthread.dylib       	0x00007fff90658fd7 _pthread_start + 176
11  libsystem_pthread.dylib       	0x00007fff906563ed thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010162e220  rbx: 0x00007ff67a428b08  rcx: 0x000000010162e268  rdx: 0x0000000000000002
  rdi: 0x00007ff67a46fab8  rsi: 0x00007fff5ea7d458  rbp: 0x00007fff5ea7d350  rsp: 0x00007fff5ea7d350
   r8: 0x0000000000000016   r9: 0x00000000000006fa  r10: 0x0000000000000f00  r11: 0x000000010159e12a
  r12: 0x00007fff5ea7d458  r13: 0x0000000000000000  r14: 0x00007ff67a46fab8  r15: 0x0000000000000002
  rip: 0x000000010158f41d  rfl: 0x0000000000010202  cr2: 0x000000010158f3f6
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     6

**Comment by justinclift** [comment] 2015-12-30 20:32
Yeah, that's OSX 10.10 as well.  Looks like that's really not happy. :frowning:

**Comment by justinclift** [comment] 2016-01-03 15:07
@lphooge @pbtura Out of curiosity, does the nighty build work for either of you?

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/nightly/

That was built on a different system, and uses Qt4 instead of Qt5.  If that one works instead, it helps narrow down the cause of the problem. :wink:

**Comment by justinclift** [comment] 2016-01-05 10:37
Ping?

If either of you have a chance to try this, that would be useful:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx/sqlitebrowser-sqlcipher_20160105.dmg

**Comment by pbtura** [comment] 2016-01-05 13:31
Sorry for the delay. Yes, that nightly build seems to work for me.

**Comment by justinclift** [comment] 2016-01-05 14:10
Interesting.  Do you have time to try the one from the day before it?

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx/sqlitebrowser-sqlcipher_20160104.dmg

That was built with Qt5.  If that one crashes, then the problem is likely something to do with Qt5.

**Comment by pbtura** [comment] 2016-01-05 18:22
Are you sure that version was built with Qt5? I downloaded and ran it successsfully and in the 'about' menu it said it was built with 4.8.7 just like the newer nightly (and the 3.7 release).

**Comment by justinclift** [comment] 2016-01-05 19:48
Ugh, nope.  The About dialog always reports the correct version, so I'm wrong somewhere. :frowning: 

Hmmm, I'll check the versions here and see what's up. :wink:

**Comment by justinclift** [comment] 2016-01-05 19:52
Ahhh, found the problem.  The nightly build script wasn't removing Qt4 when it ran, so had both Qt4 + Qt5 installed when building.  The build seems to default to Qt4... so Qt5 was being left out.

I'll manually build a Qt5 one now for testing with.

**Comment by justinclift** [comment] 2016-01-05 20:41
Well, that's a bust.  The nightly build server literally cannot build anything with Qt5 installed + linked into the system.  Gives this bogus error (Xcode is fine):

    Project ERROR: Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.

Looks like the nightlies will only use Qt4 from here on.

k, tomorrow I'll rebuild new binaries for 3.8.0 using Qt4.  That might fix the crashing problems on OSX. :smile:

**Comment by justinclift** [comment] 2016-01-06 12:24
@pbtura @lphooge Do either of you have time to test the new 3.8.0 OSX release build, prior to it being officially published?

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-prerelease/

It "should be good", but it wouldn't hurt to have some more people test it (instead of just me), prior to updating the official release with it. :grin:

**Comment by lphooge** [comment] 2016-01-06 12:49
I don't have much time to test, but it seems fine, no crash when creating a new database.

**Comment by justinclift** [comment] 2016-01-06 12:55
Thanks @lphooge, that's a good start. :smile:

**Comment by pbtura** [comment] 2016-01-06 13:38
Looks good for me as well. One bit of feedback though. The default font for the data browser is really cramped and hard to read, especially when you are looking at some 20 character uid. I eventually found the setting to change it but it is something that may be worth looking at.

**Comment by justinclift** [comment] 2016-01-06 14:13
Thanks @pbtura.  Do you remember what the default font was for you?  I can look into it here and see if I can figure something out. :grin:

**Comment by justinclift** [comment] 2016-01-06 14:18
k, new 3.8.0 downloads are available for OSX now:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases

**Comment by pbtura** [comment] 2016-01-06 14:19
I'm not sure. When I went into the settings there was no font selected so I assume it was using whatever the default system font is for OSX.

**Closed by justinclift** 2016-01-06 14:18 UTC
Labels: crash, osx, packaging

**Comment by justinclift** [comment] 2016-01-06 14:20
k.  Are you using a HiDPI monitor?  Kind of wondering if we might need to try detecting for that, and choose different defaults in that situation or something. :smile:

**Comment by pbtura** [comment] 2016-01-06 14:29
Not that I know of. Defaulting to a font like arial that is easier to read at small sizes or simply defaulting to a larger font size would probably solve the issue. Not sure what font the previous versions used but that one seemed pretty good.

**Comment by justinclift** [comment] 2016-01-06 14:42
Thanks for putting up with my questions @pbtura. :grin:

**Comment by pbtura** [comment] 2016-01-06 14:52
Not a problem. This little app makes my job easier on a daily basis, so a few questions are a small price to pay ;)
