### ISSUE TITLE
New compilation warnings on OSX

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1042] opened 2017-06-16 18:36 UTC
When compiling DB4S now on OSX (first time I've tried in a few weeks), a bunch of warnings show up.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -g -fPIC -std=gnu++11 -Wall -W -DQT_QML_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../../Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtNetwork.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -Idebug -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/jc/Qt/5.8/clang_64/lib -o debug/qcustomplot.o qcustomplot.cpp
In file included from qcustomplot.cpp:26:
./qcustomplot.h:3301:18: warning: 'selectTest' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const = 0;
                 ^
./qcustomplot.h:717:18: note: overridden virtual function is here
  virtual double selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const;
                 ^
./qcustomplot.h:3441:19: warning: 'pixelPosition' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QPointF pixelPosition() const;
                  ^
./qcustomplot.h:3375:19: note: overridden virtual function is here
  virtual QPointF pixelPosition() const;
                  ^
./qcustomplot.h:5998:15: warning: 'dataCount' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int dataCount() const;
              ^
./qcustomplot.h:3821:15: note: overridden virtual function is here
  virtual int dataCount() const = 0;
              ^
./qcustomplot.h:5999:18: warning: 'dataMainKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataMainKey(int index) const;
                 ^
./qcustomplot.h:3822:18: note: overridden virtual function is here
  virtual double dataMainKey(int index) const = 0;
                 ^
./qcustomplot.h:6000:18: warning: 'dataSortKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataSortKey(int index) const;
                 ^
./qcustomplot.h:3823:18: note: overridden virtual function is here
  virtual double dataSortKey(int index) const = 0;
                 ^
./qcustomplot.h:6001:18: warning: 'dataMainValue' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataMainValue(int index) const;
                 ^
./qcustomplot.h:3824:18: note: overridden virtual function is here
  virtual double dataMainValue(int index) const = 0;
                 ^
./qcustomplot.h:6002:20: warning: 'dataValueRange' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QCPRange dataValueRange(int index) const;
                   ^
./qcustomplot.h:3825:20: note: overridden virtual function is here
  virtual QCPRange dataValueRange(int index) const = 0;
                   ^
./qcustomplot.h:6003:19: warning: 'dataPixelPosition' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QPointF dataPixelPosition(int index) const;
                  ^
./qcustomplot.h:3826:19: note: overridden virtual function is here
  virtual QPointF dataPixelPosition(int index) const = 0;
                  ^
./qcustomplot.h:6004:16: warning: 'sortKeyIsMainKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual bool sortKeyIsMainKey() const;
               ^
./qcustomplot.h:3827:16: note: overridden virtual function is here
  virtual bool sortKeyIsMainKey() const = 0;
               ^
./qcustomplot.h:6005:28: warning: 'selectTestRect' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QCPDataSelection selectTestRect(const QRectF &rect, bool onlySelectable) const;
                           ^
./qcustomplot.h:3828:28: note: overridden virtual function is here
  virtual QCPDataSelection selectTestRect(const QRectF &rect, bool onlySelectable) const = 0;
                           ^
./qcustomplot.h:6006:15: warning: 'findBegin' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int findBegin(double sortKey, bool expandedRange=true) const;
              ^
./qcustomplot.h:3829:15: note: overridden virtual function is here
  virtual int findBegin(double sortKey, bool expandedRange=true) const = 0;
              ^
./qcustomplot.h:6007:15: warning: 'findEnd' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int findEnd(double sortKey, bool expandedRange=true) const;
              ^
./qcustomplot.h:3830:15: note: overridden virtual function is here
  virtual int findEnd(double sortKey, bool expandedRange=true) const = 0;
              ^
12 warnings generated.
```

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -g -fPIC -std=gnu++11 -Wall -W -DQT_QML_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../../Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtNetwork.framework/Headers -I../../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -Idebug -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/jc/Qt/5.8/clang_64/lib -o debug/moc_qcustomplot.o debug/moc_qcustomplot.cpp
In file included from debug/moc_qcustomplot.cpp:9:
debug/../qcustomplot.h:3301:18: warning: 'selectTest' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const = 0;
                 ^
debug/../qcustomplot.h:717:18: note: overridden virtual function is here
  virtual double selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const;
                 ^
debug/../qcustomplot.h:3441:19: warning: 'pixelPosition' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QPointF pixelPosition() const;
                  ^
debug/../qcustomplot.h:3375:19: note: overridden virtual function is here
  virtual QPointF pixelPosition() const;
                  ^
debug/../qcustomplot.h:5998:15: warning: 'dataCount' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int dataCount() const;
              ^
debug/../qcustomplot.h:3821:15: note: overridden virtual function is here
  virtual int dataCount() const = 0;
              ^
debug/../qcustomplot.h:5999:18: warning: 'dataMainKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataMainKey(int index) const;
                 ^
debug/../qcustomplot.h:3822:18: note: overridden virtual function is here
  virtual double dataMainKey(int index) const = 0;
                 ^
debug/../qcustomplot.h:6000:18: warning: 'dataSortKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataSortKey(int index) const;
                 ^
debug/../qcustomplot.h:3823:18: note: overridden virtual function is here
  virtual double dataSortKey(int index) const = 0;
                 ^
debug/../qcustomplot.h:6001:18: warning: 'dataMainValue' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataMainValue(int index) const;
                 ^
debug/../qcustomplot.h:3824:18: note: overridden virtual function is here
  virtual double dataMainValue(int index) const = 0;
                 ^
debug/../qcustomplot.h:6002:20: warning: 'dataValueRange' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QCPRange dataValueRange(int index) const;
                   ^
debug/../qcustomplot.h:3825:20: note: overridden virtual function is here
  virtual QCPRange dataValueRange(int index) const = 0;
                   ^
debug/../qcustomplot.h:6003:19: warning: 'dataPixelPosition' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QPointF dataPixelPosition(int index) const;
                  ^
debug/../qcustomplot.h:3826:19: note: overridden virtual function is here
  virtual QPointF dataPixelPosition(int index) const = 0;
                  ^
debug/../qcustomplot.h:6004:16: warning: 'sortKeyIsMainKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual bool sortKeyIsMainKey() const;
               ^
debug/../qcustomplot.h:3827:16: note: overridden virtual function is here
  virtual bool sortKeyIsMainKey() const = 0;
               ^
debug/../qcustomplot.h:6005:28: warning: 'selectTestRect' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QCPDataSelection selectTestRect(const QRectF &rect, bool onlySelectable) const;
                           ^
debug/../qcustomplot.h:3828:28: note: overridden virtual function is here
  virtual QCPDataSelection selectTestRect(const QRectF &rect, bool onlySelectable) const = 0;
                           ^
debug/../qcustomplot.h:6006:15: warning: 'findBegin' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int findBegin(double sortKey, bool expandedRange=true) const;
              ^
debug/../qcustomplot.h:3829:15: note: overridden virtual function is here
  virtual int findBegin(double sortKey, bool expandedRange=true) const = 0;
              ^
debug/../qcustomplot.h:6007:15: warning: 'findEnd' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int findEnd(double sortKey, bool expandedRange=true) const;
              ^
debug/../qcustomplot.h:3830:15: note: overridden virtual function is here
  virtual int findEnd(double sortKey, bool expandedRange=true) const = 0;
              ^
12 warnings generated.
```

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -std=c++11 -DENABLE_SQLCIPHER -DCHECKNEWVERSION -g -std=gnu++11 -Wall -W -fPIC -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MACEXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_QML_DEBUG -I. -I/usr/local/opt/sqlcipher/include -I/usr/local/include -I../libs/antlr-2.7.7 -I../libs/qhexedit -I../libs/qcustomplot-source -I../libs/qscintilla/Qt4Qt5 -I../../sqlitebrowser -I../../../Qt/5.8/clang_64/lib/QtPrintSupport.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtMacExtras.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -Idebug -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I.ui -I../../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/jc/Qt/5.8/clang_64/lib -o debug/PlotDock.o PlotDock.cpp
In file included from PlotDock.cpp:2:
In file included from .ui/ui_PlotDock.h:28:
../libs/qcustomplot-source/qcustomplot.h:3301:18: warning: 'selectTest' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const = 0;
                 ^
../libs/qcustomplot-source/qcustomplot.h:717:18: note: overridden virtual function is here
  virtual double selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const;
                 ^
../libs/qcustomplot-source/qcustomplot.h:3441:19: warning: 'pixelPosition' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QPointF pixelPosition() const;
                  ^
../libs/qcustomplot-source/qcustomplot.h:3375:19: note: overridden virtual function is here
  virtual QPointF pixelPosition() const;
                  ^
../libs/qcustomplot-source/qcustomplot.h:5998:15: warning: 'dataCount' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int dataCount() const;
              ^
../libs/qcustomplot-source/qcustomplot.h:3821:15: note: overridden virtual function is here
  virtual int dataCount() const = 0;
              ^
../libs/qcustomplot-source/qcustomplot.h:5999:18: warning: 'dataMainKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataMainKey(int index) const;
                 ^
../libs/qcustomplot-source/qcustomplot.h:3822:18: note: overridden virtual function is here
  virtual double dataMainKey(int index) const = 0;
                 ^
../libs/qcustomplot-source/qcustomplot.h:6000:18: warning: 'dataSortKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataSortKey(int index) const;
                 ^
../libs/qcustomplot-source/qcustomplot.h:3823:18: note: overridden virtual function is here
  virtual double dataSortKey(int index) const = 0;
                 ^
../libs/qcustomplot-source/qcustomplot.h:6001:18: warning: 'dataMainValue' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual double dataMainValue(int index) const;
                 ^
../libs/qcustomplot-source/qcustomplot.h:3824:18: note: overridden virtual function is here
  virtual double dataMainValue(int index) const = 0;
                 ^
../libs/qcustomplot-source/qcustomplot.h:6002:20: warning: 'dataValueRange' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QCPRange dataValueRange(int index) const;
                   ^
../libs/qcustomplot-source/qcustomplot.h:3825:20: note: overridden virtual function is here
  virtual QCPRange dataValueRange(int index) const = 0;
                   ^
../libs/qcustomplot-source/qcustomplot.h:6003:19: warning: 'dataPixelPosition' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QPointF dataPixelPosition(int index) const;
                  ^
../libs/qcustomplot-source/qcustomplot.h:3826:19: note: overridden virtual function is here
  virtual QPointF dataPixelPosition(int index) const = 0;
                  ^
../libs/qcustomplot-source/qcustomplot.h:6004:16: warning: 'sortKeyIsMainKey' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual bool sortKeyIsMainKey() const;
               ^
../libs/qcustomplot-source/qcustomplot.h:3827:16: note: overridden virtual function is here
  virtual bool sortKeyIsMainKey() const = 0;
               ^
../libs/qcustomplot-source/qcustomplot.h:6005:28: warning: 'selectTestRect' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual QCPDataSelection selectTestRect(const QRectF &rect, bool onlySelectable) const;
                           ^
../libs/qcustomplot-source/qcustomplot.h:3828:28: note: overridden virtual function is here
  virtual QCPDataSelection selectTestRect(const QRectF &rect, bool onlySelectable) const = 0;
                           ^
../libs/qcustomplot-source/qcustomplot.h:6006:15: warning: 'findBegin' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int findBegin(double sortKey, bool expandedRange=true) const;
              ^
../libs/qcustomplot-source/qcustomplot.h:3829:15: note: overridden virtual function is here
  virtual int findBegin(double sortKey, bool expandedRange=true) const = 0;
              ^
../libs/qcustomplot-source/qcustomplot.h:6007:15: warning: 'findEnd' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int findEnd(double sortKey, bool expandedRange=true) const;
              ^
../libs/qcustomplot-source/qcustomplot.h:3830:15: note: overridden virtual function is here
  virtual int findEnd(double sortKey, bool expandedRange=true) const = 0;
              ^
12 warnings generated.
```

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9  -Wl,-rpath,/Users/jc/Qt/5.8/clang_64/lib -o DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite debug/main.o debug/sqlitedb.o debug/MainWindow.o debug/EditIndexDialog.o debug/EditTableDialog.o debug/Settings.o debug/PreferencesDialog.o debug/AboutDialog.o debug/EditDialog.o debug/ExportDataDialog.o debug/ImportCsvDialog.o debug/sqltextedit.o debug/sqlitetypes.o debug/csvparser.o debug/ExtendedTableWidget.o debug/Sqlite3Lexer.o debug/Sqlite3Parser.o debug/sqlitetablemodel.o debug/FilterTableHeader.o debug/SqlExecutionArea.o debug/VacuumDialog.o debug/DbStructureModel.o debug/Application.o debug/CipherDialog.o debug/ExportSqlDialog.o debug/SqlUiLexer.o debug/FileDialog.o debug/ColumnDisplayFormatDialog.o debug/FilterLineEdit.o debug/RemoteDatabase.o debug/ForeignKeyEditorDelegate.o debug/PlotDock.o debug/RemoteDock.o debug/RemoteModel.o debug/qrc_icons.o debug/qrc_flags.o debug/qrc_translations.o debug/qrc_CaCerts.o debug/moc_sqlitedb.o debug/moc_MainWindow.o debug/moc_EditIndexDialog.o debug/moc_AboutDialog.o debug/moc_EditTableDialog.o debug/moc_PreferencesDialog.o debug/moc_EditDialog.o debug/moc_ExportDataDialog.o debug/moc_ImportCsvDialog.o debug/moc_sqltextedit.o debug/moc_ExtendedTableWidget.o debug/moc_sqlitetablemodel.o debug/moc_FilterTableHeader.o debug/moc_SqlExecutionArea.o debug/moc_VacuumDialog.o debug/moc_DbStructureModel.o debug/moc_Application.o debug/moc_CipherDialog.o debug/moc_ExportSqlDialog.o debug/moc_SqlUiLexer.o debug/moc_FileDialog.o debug/moc_ColumnDisplayFormatDialog.o debug/moc_FilterLineEdit.o debug/moc_RemoteDatabase.o debug/moc_ForeignKeyEditorDelegate.o debug/moc_PlotDock.o debug/moc_RemoteDock.o debug/moc_RemoteModel.o   -F/Users/jc/Qt/5.8/clang_64/lib -lsqlcipher -L/usr/local/opt/sqlcipher/lib -ldl -L/usr/local/lib -framework Carbon -L/Users/jc/git_repos/sqlitebrowser/src/../libs/qhexedit -L/Users/jc/git_repos/sqlitebrowser/src/../libs/antlr-2.7.7 -L/Users/jc/git_repos/sqlitebrowser/src/../libs/qcustomplot-source -L/Users/jc/git_repos/sqlitebrowser/src/../libs/qscintilla/Qt4Qt5 -lantlr -lqhexedit -lqcustomplot -lqscintilla2 -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtMacExtras -framework QtNetwork -framework OpenGL -framework AGL 
ld: warning: direct access in function 'ExpandAllInPlace(PropSetSimple const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, int, VarChain const&)' from file '/Users/jc/git_repos/sqlitebrowser/libs/qscintilla/Qt4Qt5/libqscintilla2.a(PropSetSimple.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file 'debug/ExportDataDialog.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'ExpandAllInPlace(PropSetSimple const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, int, VarChain const&)' from file '/Users/jc/git_repos/sqlitebrowser/libs/qscintilla/Qt4Qt5/libqscintilla2.a(PropSetSimple.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file 'debug/ExportDataDialog.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'ExpandAllInPlace(PropSetSimple const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, int, VarChain const&)' from file '/Users/jc/git_repos/sqlitebrowser/libs/qscintilla/Qt4Qt5/libqscintilla2.a(PropSetSimple.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file 'debug/ExportDataDialog.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'ExpandAllInPlace(PropSetSimple const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, int, VarChain const&)' from file '/Users/jc/git_repos/sqlitebrowser/libs/qscintilla/Qt4Qt5/libqscintilla2.a(PropSetSimple.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file 'debug/ExportDataDialog.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'ExpandAllInPlace(PropSetSimple const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, int, VarChain const&)' from file '/Users/jc/git_repos/sqlitebrowser/libs/qscintilla/Qt4Qt5/libqscintilla2.a(PropSetSimple.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file 'debug/ExportDataDialog.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

None of these are build breaking, but we should get these resolved at some point. :smile:

**Comment by MKleusberg** [comment] 2017-06-28 13:19
These are all caused by the third-party libraries. So I don't think it really makes sense to fix them in our repository when they should really be fixed upstream. Not sure though how active the QCustomPlot project is at the moment...

**Comment by justinclift** [comment] 2017-06-28 14:11
No worries.  I'll file issues on the upstream project(s) then, and we can figure out what to do based upon their response.  Or lack thereof. :smile:

**Comment by MKleusberg** [comment] 2020-02-14 09:56
Closing this since it's an old problem in the upstream libraries.

**Closed by MKleusberg** 2020-02-14 09:56 UTC
Labels: osx
