### ISSUE TITLE
No version number displayed in app's About Box nor in Finder's GetInfo dialog.

### ISSUE THREAD

**Issue by Vidbuf** [sqlitebrowser/sqlitebrowser#551] opened 2016-04-03 17:36 UTC
The app's version number should be displayed in app's About Box and in Finder's GetInfo dialog.

**Comment by justinclift** [comment] 2016-04-03 18:32
Hmmm, it's supposed to show up there.  Would you be ok to add a screenshot here, displaying what you're seeing? :smile:

**Comment by Vidbuf** [comment] 2016-04-03 18:51
OK I uploaded two screen shots to my initial report above. In doing so I discovered that I had been using the your version from Jan 2015 which doesn't show the version info in either the AboutBox nor Finder GetInfo, as reported.
However I then downloaded the latest version which does now show the version in the About Box, however the version info is still NOT displayed in the Version field of Finder GetInfo. Cheers, Joe

**Comment by justinclift** [comment] 2016-04-04 01:02
Oops, not seeing any screenshots here.  How did you upload them? :wink:

**Comment by justinclift** [comment] 2016-04-04 01:04
With the version info not displaying in Finder GetInfo, that sounds like a problem with the way I built/created the .app bundle on OSX.  Sounds like it might be time to investigate how macdeployqt does stuff, in case that's the cause.

**Comment by Vidbuf** [comment] 2016-04-04 16:37
I uploaded the screen shots again here....

![screen shot 2016-04-03 at 11 45 35 am](https://cloud.githubusercontent.com/assets/16469286/14255421/bb8e6c10-fa48-11e5-8a34-01b93dccdf6b.png)
![screen shot 2016-04-03 at 11 41 10 am](https://cloud.githubusercontent.com/assets/16469286/14255420/bb8d7076-fa48-11e5-8fde-22ede59e3744.png)

**Comment by justinclift** [comment] 2016-04-04 20:31
Ahhh interesting.  Checking there here on my desktop shows the same thing.  Now I grok what you're meaning.

I'll have to look into that for the next release.  Thanks for pointing this out. :smile:

**Comment by revolter** [comment] 2016-07-15 19:00
@justinclift Where is the OS X building defined?

**Comment by justinclift** [comment] 2016-07-15 21:24
Do you mean the DB4S release version number?

For OSX, we've been manually (at release time) making the change to src/app.plist.  It used to also be in CMakeLists.txt, and src/gen_version.h (according to our slightly outdated [https://github.com/sqlitebrowser/sqlitebrowser/wiki/Release-process] doc), but looks like those last two don't have it any more.  That doc should be updated to the current approach... when we're sure what that is these days. :wink:

**Comment by revolter** [comment] 2016-07-15 21:38
@justinclift, Great, thanks! Added a PR for this.

**Comment by justinclift** [comment] 2016-07-15 21:46
@Vidbuf In theory :smile:, this should be fixed now.  Do you have time to test the nightly build (tomorrow) to verify it from your point of view and let us know?

**Comment by justinclift** [comment] 2016-08-01 17:09
Just double checked this here, and it's definitely fixed. :smile:

Thanks heaps @revolter. 😁

**Closed by justinclift** 2016-08-01 17:09 UTC
Labels: osx, packaging
