### ISSUE TITLE
 btreeInitPage() returns error code 11

### ISSUE THREAD

**Issue by ReneMorgner-0000** [sqlitebrowser/sqlitebrowser#3085] opened 2022-07-04 14:27 UTC
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment] 2022-07-04 14:49
This error is more from SQLite than DB4S, and generally means the data is corrupt.  While you can export the data from the database which is at least readable, it may not be reliable data ... you'd be better reverting to a backup copy of the database.

**Comment by ReneMorgner-0000** [comment] 2022-07-04 15:24
Can we copy from one to a second database?

Outlook for Android
________________________________

**Comment by chrisjlocke** [comment] 2022-07-04 17:09
You can export the data and import it into another database, but you can't rely on the data.
If you have order ID 1 which belongs to user ID 2, and user ID 2 cannot be read, your data is going to be invalid.  Depending on how much data you have, will you know about a missing record?  Is it important?
If the data was important, you'd have a backup, so guess that answers that question...

**Comment by MKleusberg** [comment] 2023-02-10 19:25
Closing this as unfortunately there's not much we can do here. The issue here seems to be caused by a malformed database file that SQLite itself cannot read correctly.

**Closed by MKleusberg** 2023-02-10 19:25 UTC
