### ISSUE TITLE
Editing a field is updating multiple fields

### ISSUE THREAD

**Issue by alexhart23** [sqlitebrowser/sqlitebrowser#516] opened 2016-02-11 04:07 UTC
I'm running into an issue where when I try and update a single field. It shows the single field as being updated, but when I refresh the table, it updates the column for other rows that have the same id. I'm using a composite primary key, so not sure if that has anything to do with it, but I should be able to update the individual field.

Here is my structure for the table:
`CREATE TABLE "soap_scent" (
`scent_id`text,
`soap_id`text,
`scent_percentage`float,
    PRIMARY KEY(scent_id,soap_id),
    FOREIGN KEY(`scent_id`) REFERENCES scent ( scent_id ),
    FOREIGN KEY(`soap_id`) REFERENCES soap ( soap_id )
) WITHOUT ROWID`

and here are some screenshots of what's happening:

scent_percentage for row 1 and 2 are both 0.7
![ss1](https://cloud.githubusercontent.com/assets/12749891/12969127/eb461ecc-d049-11e5-964c-07c817694773.png)

update scent_percentage in row 2 to 0.5, and write changes. I'd expect row 1 to stay at 0.7

![ss2](https://cloud.githubusercontent.com/assets/12749891/12969141/20a32eac-d04a-11e5-87e0-13ff4071b3d5.png)

click refresh (or filter or move around the program), and row 1 and row 2 are now both 0.5
![ss3](https://cloud.githubusercontent.com/assets/12749891/12969145/310844e4-d04a-11e5-8ea3-852b4ea2467f.png)

I tried updated a single field through the sqlite3 python library and that doesn't seem to mess with the other field.

Thanks!

**Comment by alexhart23** [comment] 2016-02-11 04:17
I tried recreating the table without the "WITHOUT ROWID" option, and that seems to have cleared up the problem. I'm not sure if there's a bug related to that, or if I'm misunderstanding how that option is supposed to work.

**Comment by MKleusberg** [comment] 2019-08-10 10:48
Sorry, I entirely missed this issue for over three years! :scream: Good news is that it should be finally resolved since April this year. So if you are still around, @alexhart23, you can download one of the latest nightly builds [here](https://nightlies.sqlitebrowser.org/latest/). With this new version, updating will work fine even with the ```WITHOUT ROWID``` flag. Since this issue is really old and I'm pretty confident the issue is fixed, I'm going to close this. If you're testing the new build and experience any issues with it, you're absolutely welcome to reopen this issue though :smile:

**Closed by MKleusberg** 2019-08-10 10:48 UTC
Labels: bug, help wanted
