### ISSUE TITLE
Wrong UPDATE for WITHOUT ROWID table

### ISSUE THREAD

**Issue by raddinet** [sqlitebrowser/sqlitebrowser#1834] opened 2019-04-01 14:46 UTC
Sorry if this is a duplicate. Changing single value in WITHOUT ROWID table generates UPDATE without all required constrains.

#### What did you do?

Change single value in table created by following statement:

    CREATE TABLE `properties`(`window` INT, `id` ID, `value` INT, PRIMARY KEY (`window`,`id`)) WITHOUT ROWID

#### What did you expect to see?

    UPDATE "main"."properties" SET "value"=? WHERE "window"='4' AND "id"='1'

#### What did you see instead?

    UPDATE "main"."properties" SET "value"=? WHERE "window"='4';

Useful extra information
-------------------------
> DB4S v3.11.1 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.14393) [x86_64]
> using SQLite Version 3.27.1
> and Qt 5.11.3

**Comment by justinclift** [comment] 2019-04-01 15:47
Ouch, that sounds like a bug that could go badly wrong!

**Comment by raddinet** [comment] 2019-04-01 17:05
Yup, took me quite some time to discover it wasn't bug in my app. Also fixing the ``id` ID` typo in the CREATE TABLE statement makes no difference.

**Comment by MKleusberg** [comment] 2019-04-01 17:15
Thanks, @raddinet! I found two issues regarding this #516 and #1075. I'll see what we can do about this :smile:

**Comment by justinclift** [comment] 2019-04-01 18:34
Release blocker for 3.11.x?

**Comment by MKleusberg** [comment] 2019-04-01 18:37
In my opinion: Definitely not :smile: This is going to require so many changes throughout the entire code base that it is quite likely to add more issues rather than solving issues for the first couple of weeks or so :wink:

**Comment by MKleusberg** [comment] 2019-04-01 19:46
I have committed a first version of support for multi-column primary keys. As said, this is very likely to break things somewhere, so be cautious everybody when testing the new nightly build.

@raddinet Can you check with tomorrow's nightly build if this is working for you? Any unexpected results are worth reporting here.

@justinclift We do include the JSON extension in all our builds, do we?

**Comment by justinclift** [comment] 2019-04-02 04:04
> We do include the JSON extension in all our builds, do we?

The win and macOS ones we create do have the JSON extension, but the ones created by the various Linux distributions, and the *BSD ones probably don't.

**Comment by chrisjlocke** [comment] 2019-04-02 08:26
It dies on Windows.

(Can't post screenshot, but its the usual 'DB4S has stopped responding')
Created the above table, then went to browse data.  Empty table showed fine.  Went to click 'add record' and it died.

**Comment by chrisjlocke** [comment] 2019-04-02 08:28
Sorry, actually, it was a simplier table than the above.
    
    create table test2 (field1 integer,primary key(field1)) WITHOUT ROWID

**Comment by chrisjlocke** [comment] 2019-04-02 08:29
Adding a record to a 'normal' table works fine.

**Comment by chrisjlocke** [comment] 2019-04-02 08:36
The same crash occurs on a table with two primary keys (as per first post).

**Comment by MKleusberg** [comment] 2019-04-02 14:26
Thanks, Chris! I was so focused on getting the updating and the deleting bits to work (which are way more complicated than inserting in this case) that I totally forgot to test the inserting :roll_eyes: Should be fixed in the next build :smile: 

If you want to test this some more it's also worth checking if unlocking views for editing (and actually editing them) still works and if there are any new problems in the Edit Table dialog.

**Comment by chrisjlocke** [comment] 2019-04-02 15:28
Unlocking a view for editing isn't possible, as the dialog only accepts a singular field.

**Comment by chrisjlocke** [comment] 2019-04-02 15:36
Renaming a field which is also a primary key fails.  This doesn't occur on a normal table.

**Comment by MKleusberg** [comment] 2019-04-02 15:37
You're right (and we might want to change that at same time, but I guess it's super low priority). But the the multi-column PK feature as I implemented it reuses large parts of the view editing code. So we have the same bits of code for view editing and for multi-column PKs now and in theory I could have broken the view editing by changing those bits of code in order to get the multi-column PKs working :wink:

**Comment by chrisjlocke** [comment] 2019-04-02 15:40
Sorry - forgot to put the error.  "Renaming the column failed.  DB says, expressions prohibited in PRIMARY KEY and UNIQUE constraints (ALTER TABLE "main"."test3" RENAME COLUMN "field1" to "field11";)

Field1 is ticked as a primary key.  This also fails if there is just one primary key.  As above, it doesn't fail if the table does not have the 'WITHOUT ROWID' setting (ie, a normal table).

**Comment by MKleusberg** [comment] 2019-04-02 16:01
Can you paste the table schema for that one in here? Definitely sounds like a likely bug - but I can't seem to reproduce it with just any WITHOUT ROWID table.

**Comment by MKleusberg** [comment] 2019-04-02 16:03
@justinclift You're probably right. We're using a custom extension function now which does the same thing but offers us more flexibility in the future and doesn't add a dependency on the JSON extension.

**Comment by chrisjlocke** [comment] 2019-04-02 16:26
It fails if I rename field1

CREATE TABLE "test2" (
	"Field2"	INTEGER,
	"field1"	integer,
	PRIMARY KEY("field1")
) WITHOUT ROWID

but renaming any field in this one works fine. 

CREATE TABLE "test3" (
	"Field3"	INTEGER,
	"Field1"	INTEGER,
	"Field4"	INTEGER,
	PRIMARY KEY("Field1")
) WITHOUT ROWID

I have no views, indexes or triggers.

**Comment by MKleusberg** [comment] 2019-04-02 18:46
I have no idea how I couldn't reproduce this, it's quite obvious now :laughing: Because all you modify is a column name, we don't go through the entire process of creating a new table, copying all the data from the old table to the new one, deleting the old one, and renaming the new one. Instead we use SQLite's handy new ```ALTER TABLE .. RENAME COLUMN``` syntax - which is actually the only command we execute here:
```
ALTER TABLE "main"."test2" RENAME COLUMN "field1" TO "field1x";
```

Therefore I would argue that this is a bug in SQLite itself and should be fixed there. Weren't you subscribed to their mailing list, Chris? Can you maybe ask there if they consider it a bug in SQLite as well? If not, well, we can always use the old process of creating a new table and copying all the data for all modifications of WITHOUT ROWID tables as a workaround, but that's certainly not ideal.

Here's a minimal example of the issue using the command line tool instead of DB4S:

```
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> CREATE TABLE test1(Field1 INTEGER, Field2 INTEGER, PRIMARY KEY(Field1));
sqlite> CREATE TABLE test2(Field1 INTEGER, Field2 INTEGER, PRIMARY KEY(Field1)) WITHOUT ROWID;
sqlite> ALTER TABLE test1 RENAME Field1 To Field1x;
sqlite> ALTER TABLE test2 RENAME Field1 To Field1x;
Error: no such column: Field1
```

**Comment by chrisjlocke** [comment] 2019-04-02 19:05
👍 Will post as requested, and let you know.

**Comment by raddinet** [comment] 2019-04-17 06:00
The basic usage scenario described above now (nightly build) works reliably, thank you.

It seems that there is another issue though: When I change value of a field that's part of the compound primary key, the subsequent changes to non-PK fields still reference the row using previous compound primary key values.

**Comment by justinclift** [comment] 2019-05-02 11:42
Oh, that definitely still sounds bug like. :frowning: 

@MKleusberg ?

**Comment by MKleusberg** [comment] 2019-05-02 12:23
Thanks for the reminder. I completely missed @raddinet's comment. Sorry about that! :smile: But it should be fixed now. Can you check with tomorrow's nightly build (or any later one) and see if it's completely working for you now, @raddinet?

**Comment by MKleusberg** [comment] 2019-05-07 20:20
@chrisjlocke Good news! [This](https://www.sqlite.org/src/info/91f701d39852ef1d) looks like it might be a fix for the problem you discovered. The commit is only from yesterday but with any luck the next version of SQLite should fix that issue.

**Comment by MKleusberg** [comment] 2019-08-10 13:11
Did you have a chance to test the last changes, @raddinet :smile:

**Comment by raddinet** [comment] 2019-08-10 14:45
Hi, yes, both issues are fixed for me.
For a while already I'm using some nightly build and didn't encounter any of them again.
Thanks for fixing this! The issue can be closed if you deem so too.

**Comment by MKleusberg** [comment] 2019-08-10 16:17
Awesome :smile: Thank you again for reporting this issue and confirming it is fixed now!

**Closed by MKleusberg** 2019-08-10 16:17 UTC
Labels: bug, response requested
