### ISSUE TITLE
add column constraint

### ISSUE THREAD

**Issue by grahamlabdon** [sqlitebrowser/sqlitebrowser#221] opened 2015-03-09 13:57 UTC
Hi
I am trying to add a column constraint in order to restrict a column to a certain set of values
Field1 IN ("one","two")
However, when I enter this in the 'Check' column in the table editor I see it in the SQL but pressing OK makes it disappear

If I open an existing database with such a constraint I am unable to add a row

What is happening?

**Comment by MKleusberg** [comment] 2015-03-09 21:44
Strange, I can't reproduce this... Are you sure you're using the latest version? You can check this by clicking on the Help->About menu item; it should be 3.5.1.

**Comment by justinclift** [comment] 2015-03-11 22:30
@grahamlabdon ping?

**Comment by MKleusberg** [comment] 2015-12-21 13:43
Closing this issue as we haven't had any updates on this for some time now. If the problem still pesists please feel free to reopen this issue, @grahamlabdon :smile:

**Closed by MKleusberg** 2015-12-21 13:43 UTC
