### ISSUE TITLE
[Suggestion] Default data type for new fields

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#650] opened 2016-07-14 13:14 UTC
I'm creating a database with about 16 tables, and when new fields are created with the default 'Integer' type, 98% of the time I will have to change this to the 'Text' data type.  While its easy to change from Integer to Text via simple scroll of the mousewheel, it would be preferable to have an option ("Another one?!  Argh!!!!!") so that new fields could be default to whatever I wanted.
Alternatively, if it created the same field as last time would be helpful - so if you're creating a block of Integers, then a block of text fields...

Edit: Suggestion 'tidied up' as I made it quite confusing.

**Comment by revolter** [comment] 2016-07-14 13:25
Hmm, for me, new fields are of type `Integer` by default.

**Comment by chrisjlocke** [comment] 2016-07-14 13:31
Thats why it would be an option! ;)

**Comment by justinclift** [comment] 2016-07-14 13:34
Yeah, can't see why it would hurt. :smile:

**Comment by revolter** [comment] 2016-07-14 13:44
@chrisjlocke, I know it would be an option, but you said that for you, new rows are defaulting to `Text`, and I was wondering if it's not a bug (or feature) that I didn't know about. Moreso because you said that it's happening in `98% of the time` 😟

**Comment by chrisjlocke** [comment] 2016-07-14 14:37
Aah, I apologise - my bad English.  What I meant was, each field is indeed created as an Integer as default, but 98% of the time, I have to change this to 'Text'.  Ids, names, addresses, batch numbers (which aren't numbers.... argh!), status codes, etc, etc.  I don't use a lot of Integers.  Even if it created the same field as last time would be helpful - so if you're creating a block of Integers, then a block of text fields...

**Comment by chrisjlocke** [comment] 2016-07-14 14:38
Changing the original post, as its confusing...

**Comment by revolter** [comment] 2016-07-14 15:01
Ok, got it, I'll try to implement this in the following days.

**Comment by revolter** [comment] 2016-07-14 15:01
@justinclift, What do you think? Default type option in Preferences or automatically save last used type?

**Comment by justinclift** [comment] 2016-07-14 15:09
Cool. :smile:

In Preferences somewhere sounds better to me.

**Comment by justinclift** [comment] 2016-07-14 22:27
@chrisjlocke The code for this by @revolter has just been merged.  Would you be ok to try the nightly build tomorrow, and let us know if it works well from your point of view? :smile:

**Comment by chrisjlocke** [comment] 2016-07-15 05:44
Wow, thanks @revolter.  Much appreciated.  This will save so much time!  It
was my birthday the other day so this is the best present I received! ;)

**Comment by revolter** [comment] 2016-07-15 06:07
I'm glad I could help you :) And happy birthday! 🎉

**Comment by chrisjlocke** [comment] 2016-07-15 07:15
Just tested the nightly build, and this works perfectly!  Thanks again!

**Comment by revolter** [comment] 2016-07-15 07:19
Awesome!

**Closed by revolter** 2016-07-15 07:19 UTC
Labels: enhancement, fix applied
