### ISSUE TITLE
Ubuntu packaging errors

### ISSUE THREAD

**Issue by deepsidhu1313** [sqlitebrowser/sqlitebrowser#994] opened 2017-04-10 07:33 UTC
### Details for the issue
@justinclift 

Getting error while Building package for Ubuntu (Debian)

```
/<<PKGBUILDDIR>>/src/EditTableDialog.cpp: In member function ‘void EditTableDialog::itemChanged(QTreeWidgetItem*, int)’:
/<<PKGBUILDDIR>>/src/EditTableDialog.cpp:324:24: error: ‘sqlb::FieldVector’ has no member named ‘removeAll’
                     pk.removeAll(field);
                        ^
make[3]: *** [CMakeFiles/sqlitebrowser.dir/src/EditTableDialog.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/<<PKGBUILDDIR>>/obj-powerpc64le-linux-gnu'
make[2]: *** [CMakeFiles/sqlitebrowser.dir/all] Error 2
make[2]: Leaving directory `/<<PKGBUILDDIR>>/obj-powerpc64le-linux-gnu'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/<<PKGBUILDDIR>>/obj-powerpc64le-linux-gnu'
dh_auto_build: make -j4 returned exit code 2
make: *** [build-arch] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
```

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Ubuntu 14.04, 15.04, 15.10 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: nightly
#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-04-10 09:30
Thanks @deepsidhu1313, I'll setup a *buntu VM again later today and investigate. :smile:

**Comment by MKleusberg** [comment] 2017-04-10 12:27
This is probably because of the Qt version. The QVector::removeAll() method was introduced in Qt 5.4 (see https://doc.qt.io/qt-5/qvector.html#removeAll), so when trying to compile with any version <5.4 this error will occur. In theory we could work around that but I vaguely remember there being more features from newer Qt version that we're using...

**Comment by deepsidhu1313** [comment] 2017-04-10 12:41
Please let me know of the main iasue so that i can stop nightly builds for
unsupported ubuntu versions.

**Comment by justinclift** [comment] 2017-04-10 13:43
Ahhh, from memory we require Qt 5.6 and above now.

@deepsidhu1313 which versions of Ubuntu don't have that available?

**Comment by deepsidhu1313** [comment] 2017-04-11 09:34
@justinclift Ubuntu 16.04 and prior version are effected. 

Ubuntu 16.04 and 14.04 are LTS version. 16.04 End of Life Cycle is in April 2021 and 14.04 is in April 2019. Which is a concern if we are unable to pack our software for these distros.

Meanwhile i will try to find a work around or fix.

**Comment by justinclift** [comment] 2017-05-07 22:00
As a data point the CMake approach in our BUILDING.md instructions is working fine "as-is" with Kubuntu 17.04.  Tried it today since I was already looking into compiling stuff for other Linux distributions anyway.

**Comment by justinclift** [comment] 2017-05-14 15:24
@deepsidhu1313 This was fixed by @MKleusberg a few days ago, with https://github.com/sqlitebrowser/sqlitebrowser/commit/6e6f7cdc18e127a0004296c53e13054c5da7c24d.

Closing this now as people using Ubuntu 16.04 have confirmed the nightlies are building correctly again. :smile:

**Closed by justinclift** 2017-05-14 15:24 UTC
Labels: linux
