### ISSUE TITLE
Output pane text could be made more visible

### ISSUE THREAD

**Issue by dannguyen** [sqlitebrowser/sqlitebrowser#523] opened 2016-02-18 16:47 UTC
Ported over from this issue: https://github.com/sqlitebrowser/sqlitebrowser/issues/428#issuecomment-147124785

Not sure if this is a bug or not, but the output panel font remains unchanged despite changing the **SQL Log Font Size**:

![image](https://cloud.githubusercontent.com/assets/121520/13150645/74d88c0c-d61b-11e5-814d-d98956c1b73f.png)

Is the output pane _the_ considered the "log"? if not, then obviously it's not a bug. But would love to have the option to configure it.

The other perhaps orthogonal suggestion is that the output pane have some kind of visual cue to show that something has happened when a query executes. Even as a moderate "power" user of SQL and of DB Browser, I sometimes forget I have to look down there to see if my query had an error or if I just wrote a query that returned a nonsensical empty set (it varies depending on which monitor I'm using and how large the editor is currently stretched out to...). 

A cue that an **error** happened would be especially useful. Not for people like me, but perhaps for the Excel-to-SQLite users who are used to have Alert Boxes thrown in their faces when an error happens. But don't make it an alert box...a little red highlight around the output pane (or error text) is good enough :)

**Comment by justinclift** [comment] 2016-02-18 19:14
Thanks. :smile:

**Comment by mgrojo** [comment] 2017-11-19 00:13
@dannguyen, I cannot reproduce the issue with the font setting. In  87e1b9b I have implemented a cue in the results pane of the error occurrence. Now the background turns to a reddish color when the last query returned an error. Could you give it a try with the next nightly build? I have also changed the preference label for "SQL log font size" to "SQL results font size" for avoiding confusion.

**Comment by mgrojo** [comment] 2017-12-15 17:55
Let's close this since all the commented issues seem fixed. If @dannguyen or anyone wants to provide some feedback, commenting or a reopening are still possible.

**Closed by mgrojo** 2017-12-15 17:55 UTC
Labels: response requested
