### ISSUE TITLE
TEXT values show as BLOB

### ISSUE THREAD

**Issue by ap-Codkelden** [sqlitebrowser/sqlitebrowser#1731] opened 2019-02-07 19:04 UTC
Details for the issue
--------------------

#### What did you do?

Just had compiled 3.11 from sources, opened my database and execute an query.

#### What did you expect to see?

![image](https://user-images.githubusercontent.com/1292133/52432623-9115aa80-2b13-11e9-97fa-4e7b6dc448d3.png)

Values in the `res_text` field  actually is text and have a TEXT type accordingly. With  previous version 3.10 looks as shown above.

#### What did you see instead?

But with 3.11 I see `BLOB` in the  for some values, both in the Browse Data tab and in the Execute SQL tab result pane. SQLite returns `typeof()` as `'text'`. 

![image](https://user-images.githubusercontent.com/1292133/52432060-2f087580-2b12-11e9-8ce1-5c64dabf3cc3.png)

Useful extra information
-------------------------

A lot of `res_text` values in my database starts with a newline symbol `\n`. First screenshot in **What did you expect to see?** section was made in 3.11 too, but after **manually**  removing leading newline `\n` symbol from `res_text` for values with `doc_id` `59867564` and `67412037`. Trim with query `...set res_text=trim(res_text)` has no effect.

Also I made a sample of my data as SQL dump, which I upload [to Pastebin](https://pastebin.com/7CyVY338).

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro:_ Arch Linux )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

It seems looks like #16: Long TEXT values show as (BLOB) since version 3.1.0, 
but `BLOB` mark appears not depends on the length of text. 

Regardless of all above, new version is much faster, thank you :)

**Comment by chrisjlocke** [comment] 2019-02-07 19:13
I believe the first chunk of the field is looked at to determine whether its text or a blob - the actual fieldtype itself is not looked at.  I assume its that which is mis-identifying your textfields.
In the 'Edit Cell' pane, can you change from 'Blob' to 'text' ?

**Comment by ap-Codkelden** [comment] 2019-02-07 19:36
@chrisjlocke 
 > In the 'Edit Cell' pane, can you change from 'Blob' to 'text' ?

Yes, I tried, but it has no effect («Текст» is for "Text").

![image](https://user-images.githubusercontent.com/1292133/52437179-ec00cf00-2b1e-11e9-9a6f-127b6d422c9e.png)

Also as I mentioned above, bulk removing of `\n` with `trim()` has no effect too.

**Comment by mgrojo** [comment] 2019-02-07 23:54
Out text detection test is failing for these cases. One case is the leading line-feed that you've discovered. Another row seems to have problems with these characters: № and » (row with Id 43046774). But copying only those two characters to a new cell does not raise the issue. Only copying the whole cell to another cell does, but as soon as you delete those two, the text in the cell is shown.

The test consists of converting the first 512 characters to Unicode and then back to utf-8. If the conversion is losless, we regard the data as text. Either the Qt encoding has some bug, or that conversion cannot be done in Unicode for all cases.

The responsible function is: https://github.com/sqlitebrowser/sqlitebrowser/blob/0ad00afcbea78c2996f5fecba00618dde41c40d3/src/Data.cpp#L13

**Comment by mgrojo** [comment] 2019-02-08 00:02
The automatic switching of the Cell editor to text means that the non-quick version of the test is working well. The problem is related to truncating the first 512 bytes. That is problably messing up the UTF-8 encoding for multibyte characters.

**Comment by mgrojo** [comment] 2019-02-09 12:40
@ap-Codkelden I have a solution but I'd like to test it for performance and for some encodings before commiting it. Since you have compiled from source, if you'd like to try, you could apply the attached patch and report whether it works for your whole database (the sample you upladed is working).

[issue_1731.patch.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/2847800/issue_1731.patch.txt)

Another problem that can be seen in your screenshots is #1658. Could you report which Qt version have you used? It can be found in the About dialog.

**Comment by mgrojo** [comment] 2019-02-09 18:08
@ap-Codkelden The fix is already in the master branch, so you can simply pull it. According to callgrind, it is also quicker than the previous approach.

**Comment by ap-Codkelden** [comment] 2019-02-09 18:22
@mgrojo Thank you!

I have apply your patch, it works perfectly for me. On my database with only 36.5K records I haven't seen any slowdowns.

Regarding to #1658  I report that Qt my version is 5.12.1.

**Comment by mgrojo** [comment] 2019-02-09 19:09
Thanks. We can close this issue, then.

> Regarding to #1658 I report that my Qt version is 5.12.1.

That matches my expectation. Qt 5.12.0 and 5.12.1 have [this problem](https://bugreports.qt.io/browse/QTBUG-73721).

**Closed by mgrojo** 2019-02-09 19:09 UTC
Labels: bug, response requested

**Comment by justinclift** [comment] 2019-02-09 23:21
@mgrojo Want to apply the commit to the `v3.11.x` branch too? :smile:

**Comment by mgrojo** [comment] 2019-02-09 23:49
If nobody reports a problem with this, yes, it would be a good candidate. :smile:

**Comment by mgrojo** [comment] 2019-02-13 20:47
Given the lack of bug reports in the nightlies about this (I hope someone is still using them), I've cherry-picked this in the v3.11.x branch.

**Comment by justinclift** [comment] 2019-02-14 01:05
Sounds good to me. :smile:

**Comment by singminhong** [comment] 2019-02-28 15:20
Hi, I have similar issue with @ap-Codkelden. I am a newbie to how to use GitHub so please bear with me. I want to report that my text column have English texts and texts that have symbols above the letters (It seems like a European language but not sure which one). But the texts that have symbols above the letters are seen as BLOB in the cells. I can see the actual wording at the right small window of my DB Browser for SQLite. Here I attach the screenshot what I meant.
![bug_symboltextappearasblob](https://user-images.githubusercontent.com/15607744/53576540-e2fb9e80-3bae-11e9-954d-480bbe4e1efb.jpg)

This is my email address singmin_92@hotmail.com. Don't hesitate to ask me more in details about the issues as I am not sure how to do proper issue reporting and solution. I would appreciate if you guys can guide me how to convert these BLOB texts to the actual words that have symbols in it. Thank you. :)
@chrisjlocke @mgrojo @justinclift @Shouqun

**Comment by mgrojo** [comment] 2019-02-28 20:44
> Hi, I have similar issue with @ap-Codkelden. I am a newbie to how to use GitHub so please bear with me. I want to report that my text column have English texts and texts that have symbols above the letters (It seems like a European language but not sure which one). 

That language is German and the product name is "Gummy bear, little gummy bear" :bear: :smile:

> But the texts that have symbols above the letters are seen as BLOB in the cells. I can see the actual wording at the right small window of my DB Browser for SQLite. Here I attach the screenshot what I meant.

This is working as expected, because the character encoding is not the one expected by the application (UTF-8), but ISO-8859-1. The hex editor shows text in this encoding (because, contrary to UTF-8, all characters are one byte wide, so it's better for showing the text representation of the hex-dump, which also uses byte boundaries).

The way to tell DB4S which encoding to use is clicking with the right mouse button over the column header and choosing 'Set encoding'. In your case, select ISO-8859-1. You can find more details about how DB4S behaves regarding encoding in https://github.com/sqlitebrowser/sqlitebrowser/issues/1461#issuecomment-403320868

> This is my email address [singmin_92@hotmail.com](mailto:singmin_92@hotmail.com). Don't hesitate to ask me more in details about the issues as I am not sure how to do proper issue reporting and solution. I would appreciate if you guys can guide me how to convert these BLOB texts to the actual words that have symbols in it. Thank you. :) By the way, I am rushing for this assignment completion and your help would mean a lot to me. @chrisjlocke @mgrojo @justinclift @Shouqun

You'll receive a notification about the updates in this issue, since you've commented on it. Luck with your assignment.

**Comment by justinclift** [comment] 2019-02-28 23:39
Ahhh, the Bertelsmann Data Science Program.  Looked through the course contents for that a while back... looks like mostly basic stats stuff.  Is that how it's been so far? :smile:

**Comment by singminhong** [comment] 2019-03-01 06:34
Thank you @mgrojo. I am able to change the encoding to ISO-8859-1 for a selected column header in **Browse Data**. But the results produced still give BLOB. Here I attach what I meant. 
![bug_symboltextappearasblob_2](https://user-images.githubusercontent.com/15607744/53620430-e5e9a400-3c2d-11e9-9c7b-3b8de08c6b89.jpg)
Any idea how to change the output to show the exact text according to their own language?
Please ignore the query as I am halfway coding and encountering some errors. 

Another question about the errors, do you guys know where is the proper platform to ask for answers and helps to check up my query code in SQLite? Is it StackOverflow or any other platform? I have an error to solve here: I could not get the max value of the last column **DateG** using MAX(ROW_NUMBER() ...). It says **misuse of window function ROW_NUMBER()**.
@chrisjlocke @mgrojo @justinclift @Shouqun
@justinclift It is not easy for me when I am stuck at one place for a long time, especially SQL query. I did not have a strong foundation in that prior to the Program.

**Comment by justinclift** [comment] 2019-03-01 07:30
> Another question about the errors, do you guys know where is the proper platform to ask for answers and helps to check up my query code in SQLite? 

Definitely the official SQLite Users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

There are lots of people on there, including the SQLite developers themselves.  They're pretty helpful. :smile:

**Comment by justinclift** [comment] 2019-03-01 07:35
> It is not easy for me ...

Oops, that's not what I was meaning.  Keep at it. :smile:

**Comment by skerit** [comment] 2019-07-02 20:25
I'm using 3.11.2 on Linux Manjaro, but I still have this issue.

![image](https://user-images.githubusercontent.com/755212/60544063-3aa24600-9d18-11e9-9584-ac22df292b32.png)

**Comment by chrisjlocke** [comment] 2019-07-02 20:42
Can you supply the database at all?  With all fields recognised as blobs, looks 'suspicious'.  Are you using any funky language and/or any encoding?

**Comment by skerit** [comment] 2019-07-02 21:10
Sure I can.
It's a database made by Ultrastar Deluxe, it just contains a lot of scores for karaoke sessions :)
It was made back in 2009, I believe.

[Ultrastar.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/3352341/Ultrastar.zip)

**Comment by mgrojo** [comment] 2019-07-02 21:46
The data is null terminated. I'd say that is not a correctly encoded UTF-8 string. The workaround is to define a custom display format and use the quote function on the Artist and Title columns. This is precisely what the views scores_* are doing, so I guess someone has faced the same problem as us and created those views to display the data.

**Comment by skerit** [comment] 2019-07-02 22:00
Yeah, I created those views a long time ago

**Comment by chrisjlocke** [comment] 2022-01-13 07:46
> update content set data = replace(data,'Open Sans Semibold', 'DejaVu Sans');

Obviously without looking at the data or the result, that /looks/ OK, and I can't see why it would be turning it into BLOBs.
Can you delete all the data in the table apart from a couple of rows that have the BLOBs and post that database?  Any chance of a 'before' for those couple of rows too, so we could replicate it here on the same database?  Rather than post it publicly, you could just email it to me - issue1731@chrisjlocke [dot] co.uk

**Comment by paul1149** [comment] 2022-01-18 02:00
Thank you for this. I will create a small database, and then edit it until the problem manifests. I'm not sure when this will happen, but I won't forget.

**Comment by chrisjlocke** [comment] 2022-01-18 07:48
Thanks for the email.
The data has clearly been mangled.

![image](https://user-images.githubusercontent.com/7872218/149892438-aeb7e7ca-9549-4cbf-9259-1e6af6d92c3e.png)

The top line is on multiple lines and contains black diamonds, which is never a good sign.  There are also no { characters like the lower line.  This data has been corrupted and I don't see how the REPLACE command would have done this.  This has occurred before this step.
You mentioned in the email about a corrupted database, which you don't mention in your post above.  I would suspect the database has been corrupted prior to your actions.
Without looking at other parts of the database, I would suspect other fields would also be corrupted, so this database should be discarded.  The data cannot be recovered or used with certainty for being valid.

**Comment by paul1149** [comment] 2022-01-20 00:17
Thanks again, Chris. Just to follow up for the next guy, I realized that I could use the same csv sheet to rescue the lost data. It's a lot of work, though libreoffice macros help, but I'm saving over 99% of it.
