### ISSUE TITLE
Tables containing blob cannot be export to json properly.

### ISSUE THREAD

**Issue by cresouls** [sqlitebrowser/sqlitebrowser#1408] opened 2018-06-03 15:31 UTC
I have exported a table containing blob to JSON. When I tried to read that assuming it as base64 string, it doesn't work. Is it converting to some other format on your end or am I missing something? Please enlighten me.

**Comment by justinclift** [comment] 2018-06-03 15:46
Hmmm, these seem to be the lines which do the exporting of BLOB for JSON files:

https://github.com/sqlitebrowser/sqlitebrowser/blob/abf70ea7bd4a1683f2ff0d1df84cd7e5e8d429b7/src/ExportDataDialog.cpp#L242-L245

Not seeing a mention of base64 in there, so I'm not 100% sure how to answer this.

I think one of our proper C++ developers will need to answer this. :smile:

**Comment by iKlsR** [comment] 2018-06-04 17:13
Would appear that we're using Qt's own binary representation which is what you get by default from a `QByteArray` which isn't useable outside of Qt. I believe we should be using `QByteArray`'s `toBase64()` function since we currently aren't allowed to import back from JSON and would also serve to make the export more universal.

**Comment by justinclift** [comment] 2018-06-04 17:26
Thanks @iKlsR, that makes sense to me.

Would you have time to make a PR with that change?  Without knowing better, it **sounds** like it would be fairly simple to do. :smile:

**Comment by iKlsR** [comment] 2018-06-05 04:00
Actually wrong, only had a very quick glance at this earlier today. For JSON we are writing the raw bytes for the blob. Missed the actual snippet above... heh.

**Comment by iKlsR** [comment] 2018-06-05 04:32
This should fix the issue, I was concerned earlier that this would have to be enabled this everywhere but the functions are nice separate units.

Files get significantly longer but are actually still smaller than their counterparts. Can someone test or sanity check this? Very late here ;). @MKleusberg ?

https://github.com/iKlsR/sqlitebrowser/commit/dcacd44751eb1d9c674a1de740bc6fd2b1d29dda

```diff --git a/src/ExportDataDialog.cpp b/src/ExportDataDialog.cpp
index d252453..8580da0 100644
--- a/src/ExportDataDialog.cpp
+++ b/src/ExportDataDialog.cpp
@@ -11,6 +11,7 @@
 #include <QJsonDocument>
 #include <QJsonArray>
 #include <QJsonObject>
+#include <QTextCodec>
 
 ExportDataDialog::ExportDataDialog(DBBrowserDB& db, ExportFormats format, QWidget* parent, const QString& query, const sqlb::ObjectIdentifier& selection)
     : QDialog(parent),
@@ -237,14 +238,21 @@ bool ExportDataDialog::exportQueryJson(const QString& sQuery, const QString& sFi
                         json_row.insert(column_names[i], QJsonValue());
                         break;
                     }
-                    case SQLITE_TEXT:
-                    case SQLITE_BLOB: {
+                    case SQLITE_TEXT: {
                         QString content = QString::fromUtf8(
-                            (const char*)sqlite3_column_blob(stmt, i),
+                            (const char*)sqlite3_column_text(stmt, i),
                             sqlite3_column_bytes(stmt, i));
                         json_row.insert(column_names[i], content);
                         break;
                     }
+                    case SQLITE_BLOB: {
+                        QByteArray content((const char*)sqlite3_column_blob(stmt, i),
+                                           sqlite3_column_bytes(stmt, i));
+                        QTextCodec *codec = QTextCodec::codecForName("UTF-8");
+                        QString string = codec->toUnicode(content.toBase64(QByteArray::Base64Encoding));
+                        json_row.insert(column_names[i], string);
+                        break;
+                    }
                     }
                 }
                 json_table.push_back(json_row);

**Comment by justinclift** [comment] 2018-06-05 11:06
Thanks @iKlsR.  I'll chuck that in a PR for review shortly. :smile:

**Comment by justinclift** [comment] 2018-06-05 11:12
#1413 created.  Looks good to me personally, but I barely remember C++ at all. :smile:

**Comment by iKlsR** [comment] 2018-06-05 14:04
I wonder if this will break anyone's workflow, maybe we should have a checkbox `encode blobs` as well as retaining the original behavior. I think defaulting to base64 is a better default however since JSON is one way at the moment.

**Comment by justinclift** [comment] 2018-06-05 14:05
Yeah, I'm not sure.  At the very least we should mention it somewhere pretty clearly in the Release Notes for 3.11.0. :smile:

**Comment by cresouls** [comment] 2018-06-06 04:38
Thank you guys for the help. Is 3.11.0 going to release anytime sooner? :D

**Comment by iKlsR** [comment] 2018-06-06 08:30
@cresouls As soon as someone can approve/review the pull request you can grab a nightly build to use until final release.

**Comment by justinclift** [comment] 2018-06-06 18:53
@cresouls As a thought, if you're on Windows or OSX then I can made a once-off build with this patch included for you to test, and confirm back to us if the patch works ok or not.

Would that be of use? :smile:

**Comment by MKleusberg** [comment] 2018-06-07 11:42
@cresouls Tomorrow's nightly build will include @iKlsR's patch. Can you download and check that? That should also bridge the time till the 3.11.0 release :wink:

**Comment by cresouls** [comment] 2018-06-09 04:34
@justinclift That will be good. I am working on OSX. Please provide me a once-off build. I will test it.

**Comment by cresouls** [comment] 2018-06-09 04:35
@MKleusberg sure. 👍

**Comment by justinclift** [comment] 2018-06-09 08:52
Good news @cresouls.  The code for doing this has already been merged, so it's in our nightly builds:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Just grab one of the .dmg's there, try it out, and please let us know if the new base64 encoding works well for you.  :smile:

**Comment by cresouls** [comment] 2018-06-11 16:03
@justinclift @iKlsR Hi, I have checked the nightly build. Base64 is working fine.

Though when I export tables which contains blob, Int is not converted to String. But the table which doesn't have blob is converting to string.

for ex:

without blob

```
{
       "id" : "1",
       "name": "John Doe"
}
```

with blob  (dp is a blob)

```
{
       "id": 1,
       "name": "John doe",
       "dp": "/9j/4Rd........../KX1b86FqLc//Z"
}
```

**Comment by iKlsR** [comment] 2018-06-11 16:24
Ok that is peculiar, I'll take a look at it when I get a little free time today. Thanks for the feedback.

**Comment by mgrojo** [comment] 2018-06-11 20:41
@cresouls I guess the first export is from a version before #1323 and the second from the latest nightly, that includes this enhancement. So it is not a bug, but a feature :smile: Is that behaviour a problem for you or was it only unexpectation?

**Comment by mgrojo** [comment] 2018-06-11 20:46
Another possibility, in case both exports are from the nightly: have you checked the column type in both tables. In theory, if the column is of type INTEGER it is exported as integer in JSON and if it is TEXT, as string.

**Comment by justinclift** [comment] 2018-06-11 20:48
Just as a data point, the nightly build machine wasn't online last night so I've manually started the build jobs again a few minutes ago.

**Comment by iKlsR** [comment] 2018-06-12 00:49
Had a look with some test cases and it appears to be correct on my end as per https://cswr.github.io/JsonSchema/spec/introduction/ with and without the patch. Could be as @mgrojo says above. If not can you show us your schema or share a copy of a small database with the problem record?

**Comment by cresouls** [comment] 2018-06-12 05:17
@mgrojo @justinclift @iKlsR  My bad. As you said first one was exported from older build and the one with blob is exported from nightly build.

**Comment by justinclift** [comment] 2018-06-12 05:35
Thanks @cresouls. :smile:

Just to confirm, the base64 bit is working ok now for the json export, and the Int fields are exported as Int's too?

If that's the case, it sounds like this is now definitely fixed and this issue can be closed.

**Comment by cresouls** [comment] 2018-06-12 07:08
Yes, the base64 is working for JSON and Int fields are exported to Int as well.

You can close the issue.

Thank you @justinclift. 😄

**Comment by justinclift** [comment] 2018-06-12 08:03
Excellent!

Well done @iKlsR. :smile:

**Closed by justinclift** 2018-06-12 08:03 UTC
Labels: export, response requested
