### ISSUE TITLE
Open Database action doesn't remeber last opened folder

### ISSUE THREAD

**Issue by AlbertIslamov** [sqlitebrowser/sqlitebrowser#281] opened 2015-04-30 13:50 UTC
Click Open Database, then choose database file. Next click on Open Database - you'll see the User sesttings folder again, not previously selected folder. Actual for version 3.6.0

**Comment by justinclift** [comment] 2015-04-30 14:31
This sounds like a duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/281 to me.

@AlbertIslamov Do they sound the same to you?

**Comment by justinclift** [comment] 2015-05-03 13:34
@AlbertIslamov Would you be ok to test the latest nightly build (tomorrow)?  We've changed the behaviour a bit for this, so feedback would be useful. :smile:

**Comment by justinclift** [comment] 2015-06-13 19:26
Going to close this, as we only really need one issue for this to be open (until we figure out a full solution and get it done). :smile:

**Closed by justinclift** 2015-06-13 19:26 UTC
Labels: duplicate, enhancement

**Comment by MKleusberg** [comment] 2015-06-21 20:56
This should be fixed in the 3.7.0 release where we've introduced a new option to the Preferences dialog to change this behaviour. This way everybody should be happy :smiley:
![lastlocation](https://cloud.githubusercontent.com/assets/3153504/8273318/9c697f04-1868-11e5-9791-7dce9ff25cfe.png)
