### ISSUE TITLE
Windows File Association Doesn't Like 3.9.1 Executable

### ISSUE THREAD

**Issue by dmscheck** [sqlitebrowser/sqlitebrowser#861] opened 2016-11-03 19:06 UTC
### Details for the issue

I had Windows configured to associate the .db extension with DB4S in version 3.9.0.  When I upgraded to 3.9.1, I removed 3.9.0 and had to reassociate the extension.  To do this I:
1. Double click the .db file
2. In the "Open With" dialog, browse to C:\Program Files\DB Browser for SQLite and double click the exe

At this point the dialog doesn't recognize that an application was selected.

If I replace the spaces in the executable name with with underscores (i.e. DB_Browser_for_SQLite), the association works correctly.

I reinstalled 3.9.0 and found that it has the same executable naming convention as 3.9.1, so I have a feeling that the underscore solution may be a red herring.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_Win7 SP1 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by jungle-boogie** [comment] 2016-11-03 19:21
I don't have this problem on my windows 8.1 machine. After associating .db with `DB Browser for SQLite.exe`, I'm able to double-click the database and it will launch the application.

**Comment by justinclift** [comment] 2016-11-03 20:13
@dmscheck Hmm, that's definitely weird.

Do you have the time/inclination to try some stuff out to hopefully figure out what's wrong?

Specifically, the process monitor tool pointed at by @chrisjlocke here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/issues/847#issuecomment-256763348

A few comments down from that Chris has an overview screencast, showing how it operates.

That might help track down what's wrong when the spaces are in the path. :smile:

**Comment by dmscheck** [comment] 2016-11-03 22:05
That tool sure spits out a lot of noise,
 
Here's my procedure:
1. Open process monitor, disabled capturing and cleared the output
2. Got to the Open With dialog, browsed to the path (C:\Program Files\DB Browser for SQLite), and selected the exe (didn't click open yet).  
3. Started capturing in the process monitor, quickly switched over and clicked Open in the dialog, then back to turn off capturing.

I've attached the PML log.  If you want it as CSV or XML let me know.  Here's what I see that's interesting with the Registry and File System Activity enabled.

1. 4:55:13.9534235 - Looks like the first time DB4S is accessed. 
2. There are then a lot of registry hits, some of which look like they may be looking for EXEs
3. 4:55:13.9751138 - It looks like there are a series of registry accesses for DB4S
4. 4:55:13.9767010 - I see an access for the 3.9.0 path that I used to have

I imagine that something is still pointing to the 3.9.0 path in registry, Windows gets confused and just punts.
[Logfile.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/570186/Logfile.zip)

On a hunch, I jumped into regedit and looked at HKCU\Software\Classes\Applications\DB Browser for SQLite.exe\shell\open\command, and that looks like the culprit.  It has a value of "C:\Program Files\DB Browser for SQLite\3.9.0\bin\DB Browser for SQLite.exe" "%1" 

So it looks to me that either the 3.9.0 uninstall didn't clean this up or the 3.9.1 install didn't overwrite it.  Also, the reason that adding the underscores worked is that it pointed it to a new registry key.

Let me know if you need anything else from me.

**Comment by justinclift** [comment] 2016-11-03 23:31
Ahhh, that's interesting.  Looks like you've found the cause. :smile:

With our installer and uninstaller, they don't yet set up any Windows file associations.  It's on our ToDo list for the next release, but until then... yeah, manual approach. :wink:

**Comment by chrisjlocke** [comment] 2016-11-04 10:39
> HKCU\Software\Classes\Applications\DB Browser for SQLite.exe\shell\open\command, and that looks like the culprit. It has a value of "C:\Program Files\DB Browser for SQLite\3.9.0\bin\DB Browser for SQLite.exe" "%1"

Thats half of it.  In another post somewhere, I suggested a Microsoft tool of ASSOC and FTYPE.  It depends on what .db files are registered as.  If they're registeered as 'big green panties' then it won't be looking at the 'HKCU\Software\Classes\Applications\DB Browser for SQLite.exe' part.  I think the underscores are a new thing, thus the new registry.  You can check this in the registry by looking in HKCR\.db (or HKCU\Software\Classes\.db, if you've overwridden the default) and check the 'default' value.

![image](https://cloud.githubusercontent.com/assets/7872218/20002829/e5937232-a27a-11e6-9fed-636555362c48.png)

**Comment by HarelM** [comment] 2017-03-18 13:37
In windows 10 is't super simple, but .sqlite and .db association would be a great addition to the installer.

**Comment by MKleusberg** [comment] 2020-02-13 13:10
Pretty sure they were added to the installer in the meantime, so I'm closing this issue. If it turns out that it's not working with the last release after all, please just re-open this issue :smile:

**Closed by MKleusberg** 2020-02-13 13:10 UTC
Labels: windows
