### ISSUE TITLE
Plot only allows Axis Type = Numeric

### ISSUE THREAD

**Issue by ecanfi** [sqlitebrowser/sqlitebrowser#2286] opened 2020-06-17 21:07 UTC
Details for the issue
--------------------

#### What did you do?
Attempted to plot results from a SQL statement. 

#### What did you expect to see?
In the previous release, I was able to display my record results with text labels as a bar chart

#### What did you see instead?
The Axis Type for all columns is set to Numeric and cannot be changed.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0-(alpha or betas)
- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: 3.12.0 released version

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2020-06-18 05:34
Out of curiosity, was the database loaded using a project file (eg it should have restored existing settings), or was it loaded directly (eg from File -> Open)? :smile:

**Comment by ecanfi** [comment] 2020-06-18 13:20
Update: The plot feature works correctly when viewing tables, but when executing a sql statement in the "Execute SQL" tab, all the Axis Type fields are numeric only. Same results if loading database from "Open Database" or loading from "Open Project"

**Comment by justinclift** [comment] 2020-06-19 01:27
Interesting.  Sounds like something we should fix for the upcoming 3.12.1 update.  No firm plans for an ETA yet though. :wink:

**Comment by mgrojo** [comment] 2020-06-20 15:10
I couldn't reproduce the problem, but I've found a bug which wasn't present in 3.11. If there are NULL values in a column used as labels for a bar chart, the plot is done, but the labels are not displayed and the zoom is not reset. This should be fixed in [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/).

Regarding your issue, I can only guess that the type detection is not working. We check the first 10 values for valid data type. If the first 10 values are numbers or NULL (even if the column affinity is string) the type for the axis is guessed as numeric. But that behaviour hasn't changed since 3.11. Does it make any sense for you? Otherwise, could you publish the table structure and data for reproducing the problem?

**Comment by grumble1965** [comment] 2020-06-24 21:59
I think I'm seeing something similar since upgrading.  Before upgrading this query showed time series plot, with version 3.12.0 I see a vertical line of data.  I assume that X axis is being interpreted differently than before.

Thanks!

FYI - data is [NYTimes US Covid-19 data](https://github.com/nytimes/covid-19-data)

Schema: 
`
CREATE TABLE ss(
  "date" TEXT,
  "state" TEXT,
  "fips" TEXT,
  "cases" TEXT,
  "deaths" TEXT
)
`

Select:
>select 
	a.date, 
	a.cases, 
	a.deaths, 
	(a.cases-b.cases)/7 as 'Avg new Cases', 
	(a.deaths-b.deaths)/7 as 'Avg new Deaths'
from ss a, ss b
where a.state = 'California' AND
	a.state=b.state AND
	date(a.date, '-7 days')=b.date ;
>

Sample Data:
>2020-06-23	191039	5637	4558	62
2020-06-22	184620	5561	4136	63
2020-06-21	178807	5517	3693	61
2020-06-20	174854	5495	3488	62
2020-06-19	170843	5425	3365	62
2020-06-18	167135	5359	3346	59
2020-06-17	163381	5283	3320	59
2020-06-16	159131	5202	3126	61
2020-06-15	155662	5120	3053	63
2020-06-14	152953	5089	2993	62
>

**Comment by mgrojo** [comment] 2020-06-27 14:23
@grumble1965 I wasn't able to reproduce the problem. I couldn't get any data out of the query and the database, but the sample data is working for me:

![image](https://user-images.githubusercontent.com/13812910/85924279-92bf4a00-b891-11ea-9734-7b13edf87d0c.png)

Could you provide more data to analyse the problem, like a screenshot, more detailed steps or anything that could be useful?

**Comment by justinclift** [comment] 2020-06-27 15:04
@grumble1965 The database you created when importing the data... do you still have it around? :smile:

**Comment by grumble1965** [comment] 2020-06-28 22:44
Thanks for trying to repro this.  This is not an obvious thing, but I think I can reproduce this.

The data is from https://github.com/nytimes/covid-19-data

>sqlite> .schema
CREATE TABLE cc(
  "date" TEXT,
  "county" TEXT,
  "state" TEXT,
  "fips" TEXT,
  "cases" TEXT,
  "deaths" TEXT
);
CREATE TABLE ss(
  "date" TEXT,
  "state" TEXT,
  "fips" TEXT,
  "cases" TEXT,
  "deaths" TEXT
);
CREATE INDEX idx_state on ss (state);
CREATE INDEX idx_state_county on cc (state, county);
CREATE TABLE us(
  "date" TEXT,
  "cases" TEXT,
  "deaths" TEXT
);

sqlite> .import /mnt/g/Code/covid-19-data/us.csv us
sqlite> .import /mnt/g/Code/covid-19-data/us-counties.csv cc
sqlite> .import /mnt/g/Code/covid-19-data/us-states.csv ss
sqlite> delete from ss where date='date'; delete from cc where date='date'; delete from us where date='date' ;

I open DB Browser, open that database, and try a simple query - no problems and things look good (date column is flagged as type 'date').  See screen caps named 'before'.
![Before-plot](https://user-images.githubusercontent.com/1594290/85960131-0a56ad00-b956-11ea-86cf-05b9a5767b36.png)
![Before-query](https://user-images.githubusercontent.com/1594290/85960133-0aef4380-b956-11ea-80ba-889aaf6b51c0.png)

I try increasingly complex queries, and after maybe 5 or 6 tries, the date column is now recognized as type 'numeric' and the plot is broken.  See screen caps named 'after'.
![After-query](https://user-images.githubusercontent.com/1594290/85960134-0aef4380-b956-11ea-9e56-326550a3567a.png)
![After-plot](https://user-images.githubusercontent.com/1594290/85960135-0b87da00-b956-11ea-8282-5270f68f4dfe.png)

Trying simpler queries doesn't change the type back to 'date', neither does closing and reopening the database.  The only fix is to close and reload DB Browser.

Hope this helps!

**Comment by mgrojo** [comment] 2020-06-29 21:46
Ok, thank you. I'm reproducing it now, although in my case, a simple reexecution of the query, or pressing the button to load all data, solves the problem.

This seems a race condition, because each time the query is executed, the plot loads more or less data. When I reproduce it, only three dots are present from two different columns, and the date value seems to be 0. I guess the plot is drawn before the model has enough data.

![image](https://user-images.githubusercontent.com/13812910/86058612-7a058e80-ba61-11ea-821b-5f9a67681d30.png)

@MKleusberg I suppose you can help with the concurrent code.

**Comment by mgrojo** [comment] 2020-08-09 16:01
@MKleusberg could you take a quick look to this? What I've seen so far is that when the SqliteTableModel::finishedFetch signal is emitted, which is connected to the plot update, the cache isn't still loaded. That means the plot dock reads data which is still in the "loading..." state (null data when read in the edit role). Then the plot has only a few elements or even in some cases, there isn't any value to make the guess of type, causing it to default to Numeric. Is it expected that finishedFetch is emitted and the cache is not yet complete?

**Comment by justinclift** [comment] 2020-08-09 16:21
@mgrojo Is there any change in the behaviour after my two changes to signal and slots related code today?

**Comment by mgrojo** [comment] 2020-08-09 16:39
@justinclift No, I've just pulled them and the behaviour is the same :smile: This is related to the model between the table widgets (and the plot in this case) and the SQLite database.

**Comment by mgrojo** [comment] 2020-08-16 13:13
@ecanfi, we think we have fixed this issue in our development version. The fix is included in our nightly build. Would you mind installing it to confirm that we can close this issue?

**Comment by grumble1965** [comment] 2020-10-01 04:55
I cannot reproduce this issue in 1.12.1-RC1.

Thank you very much!

**Comment by mgrojo** [comment] 2020-10-01 18:33
Thanks for confirming!

**Closed by mgrojo** 2020-10-01 18:33 UTC
Labels: bug, plot, response requested
