### ISSUE TITLE
[Bug]: Fails to alter tables with generated columns containing data.

### ISSUE THREAD

**Issue by pchemguy** [sqlitebrowser/sqlitebrowser#3209] opened 2022-10-30 06:25 UTC
### What did you do?

I attempted to set the UNIQUE constraint on a column.

### What did you expect to see?

When altering table structure via DROP TABLE/CREATE TABLE/INSERT VALUES, it is essential that generated columns are not present in the INSERT VALUES statement. Otherwise, INSERT will fail.

### What did you see instead?

Error reporting an attempt to insert values into generated column.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10.

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment] 2022-11-04 04:31
Interesting.  Do you have an example of the columns and a failing insert, to make it a bit clearer? :smile:

**Comment by pchemguy** [comment] 2022-11-06 06:53
OK, to reproduce, for example:

  1. Create a new database
  2. Execute the following SQL

~~~sql
DROP TABLE IF EXISTS paths;
CREATE TABLE paths (
    prefix  TEXT,
    name    TEXT,
    paths   TEXT GENERATED ALWAYS AS (prefix || name)
);
INSERT INTO paths(prefix, name) VALUES ('/user/bin/', 'bash');
~~~

  3. Try to alter the table, for example by applying the non-null constraint on the prefix *column*.

I get an error message shown on the screenshot:
![DBBS](https://user-images.githubusercontent.com/39730837/200158234-e7fa5e3f-7f3b-4100-a36a-fec8eae4c220.jpg)

**Comment by scottfurry** [comment] 2022-11-06 07:24
This looks like an error with the table definition. When I attempted the above with single quotes (\') as shown I got an error that insert failed. Changing to double quotes (\"), everything went fine.

In both cases, I did not see the error dialog shown.
DB4S on system is 3.12.2 and SQLite 3.85.5

From a safety standpoint, I would advise against naming a table and a field in the table with the same name, but that's my pedagogic nature.

**Comment by chrisjlocke** [comment] 2022-11-06 09:26
...thats step 1 and 2 ... what about step 3.... ;)

**Comment by pchemguy** [comment] 2022-11-06 09:28
1. This is a dummy table, and the same applies to names.
  2. The current SQLite version is 3.39.4. Did you mean SQLite **3.35.5**?
  3. The SQL code shown above works for me. While double quotes also work because SQLite is tolerant with respect to certain violations, double-quoted string literals should never be used. Double quotes should only be used for escaping names of database object identifiers. String literals should always use SINGLE quotes. In fact, you should verify SQL against the official SQLite fiddle: https://sqlite.org/fiddle/. If you try to execute my snippet there, it works. Your code generates an error:
~~~
Parse error near line 7: no such column: /user/bin/
  INSERT INTO paths(prefix, name) VALUES ("/user/bin/", "bash");
                            error here ---^
~~~
If it is opposite for you, you have a problem with either your copy of SQLite or the app.
  4. And yes, the step 3.

**Comment by scottfurry** [comment] 2022-11-06 09:36
> ...thats step 1 and 2 ... what about step 3.... ;)
> 
> > Try to alter the table, for example by applying the non-null constraint on the prefix column.
You're right. I was missing that salient detail. And yup. Blows up on my end.

**Comment by scottfurry** [comment] 2022-11-06 09:40
>     2. The current SQLite version is 3.39.4. Did you mean SQLite **3.35.5**?

Actually, 3.38.5 - finger dyslexia. See a doctor for treatment options. :smile_cat: 

> Your code generates an expected error:
> 
> ```
> Parse error near line 7: no such column: /user/bin/
>   INSERT INTO paths(prefix, name) VALUES ("/user/bin/", "bash");
>                             error here ---^
> ```

No clue why you got an error while I didn't. But again, a step was missed in recreating/testing circumstances.

**Comment by pchemguy** [comment] 2022-11-06 09:45
You did not get this error in DB Browser, which uses a copy of SQLite compiled without the option to prohibit double-quoted literals. When I execute your version in the app, it also works. This error occurs if you run your code in the SQLite fiddle.

**Comment by scottfurry** [comment] 2022-11-06 09:48
So, I'm not running the same 3rd Party app unrelated to DB4S that you are?
Okay...

**Comment by pchemguy** [comment] 2022-11-06 09:51
I am running DB4S and check the code in the **OFFICIAL SQLite fiddle**. This fiddle is provide by SQLite. It is not a third party! It is the **reference** SQLite fiddle!

**Comment by justinclift** [comment] 2022-11-06 11:07
Cool.  Didn't know there's an official SQLite fiddle now.  That sounds useful for people.

That being said, if we should change the options we use with our compiled versions of SQLite, we very much can. :smile:

**Comment by justinclift** [comment] 2022-11-06 11:11
Reading back over this thread more:

> You did not get this error in DB Browser, which uses a copy of SQLite compiled without the option to prohibit double-quoted literals.

Yeah.  We tend to be *permissive* with things, as it makes stuff easier for a wider variety of people.

That being said, it's kind of the exact opposite choice that some people need for their use cases. :frowning_face:

**Comment by pchemguy** [comment] 2022-11-06 11:51
I am not advocating for being more restrictive. The very first reply indicated an error with proper (single-quoted) string literals. That was a problem. The fact the DB4S uses a more permissive copy is fine with me. But it should not generally generate errors where the reference fiddle does not.

That being said, whether to be more strict or more permissive is indeed a dilemma. A stricter approach may fail to execute sloppier code, where the code is otherwise ok. On the other hand, early detection of standard violation might save a lot of headache/wasted efforts down the road.

Regarding customization of the SQLite library. The SQLite dll that comes with DB4S can be swapped with the official release copy obtained from sqlite.org or a custom compiled copy. I have been using this option for quite a while, where I compiled SQLite with ICU support and several other extensions enabled. I only did it on Windows, but, I guess, it should be possible on other supported systems, as well. It is difficult to make everyone happy with a single version, but perhaps you could also advertise the fact that it is fairly straightforward to swap the library (while any issues should still be reported using a non-altered installation).

**Comment by MKleusberg** [comment] 2023-02-10 19:42
Thanks for reporting this, @pchemguy! The issue with altering these tables should be fixed in the next nightly build. It'll be available [here](https://nightlies.sqlitebrowser.org/latest/) by tomorrow. Can you give that a try and confirm the problem is fixed?

**Comment by pchemguy** [comment] 2023-02-10 19:59
Please comment again once the build is available, @MKleusberg.

**Comment by justinclift** [comment] 2023-02-10 23:47
@pchemguy The windows nightly builds have just been generated, so you should be good to go. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by pchemguy** [comment] 2023-02-11 07:44
It looks good (checked winXX.zip).

**Comment by MKleusberg** [comment] 2023-02-11 11:15
Awesome! Closing this issue then.

**Closed by MKleusberg** 2023-02-11 11:15 UTC
