### ISSUE TITLE
Creating a table with computed columns

### ISSUE THREAD

**Issue by houghtonap** [sqlitebrowser/sqlitebrowser#2426] opened 2020-10-09 13:06 UTC
Describe the new feature
--------------------------
SQLite allows you to create computed columns, unfortunately there is no way in the UI to create a table with computed columns without writing the SQL by hand. There should be some mechanism in place where clicking on Create Table on the Database Structure tab allows you to add the necessary information.

I though I could just hack the SQL in Edit Table Definition dialog, but unfortunately it's readonly. There may be a good reason why it's readonly and that is fine, just pointing out something I tried which didn't work. I was however able to copy the SQL table definition without the computed column information and put it into an Execute SQL tab, then hack it and successfully create the table.

The SQLite [Generated Columns](https://www.sqlite.org/gencol.html) web page says that computed columns are column constraints. So my thoughts would be to allow them to be added on the Constraints tab of the Edit Table Definition dialog. Perhaps simply adding both the VIRTUAL and STORED keywords to the Add Constraint drop down would provide the necessary UI functionality and the correct specification would be added to the table definition at the bottom of the Fields tab.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
The underlying feature resides in SQLite, it just needs to be brought through in the UI.
See SQLite [Generated Columns](https://www.sqlite.org/gencol.html) web page.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No.

**Comment by rayures** [comment] 2022-01-12 09:27
+1 missing this atm

**Comment by burkasaurusrex** [comment] 2022-07-02 22:34
This is a duplicate of #2107 

Currently, you can add generated columns by crafting an `ALTER TABLE` query, but this breaks a lot of the edit table functionality

**Comment by chrisjlocke** [comment] 2022-07-03 07:28
Closed as #2107 provides more information.

**Closed by chrisjlocke** 2022-07-03 07:28 UTC
Labels: enhancement, database structure
