### ISSUE TITLE
The field "type" occupy the "NN" (NOT NULL) when I want to create table

### ISSUE THREAD

**Issue by peterchin98** [sqlitebrowser/sqlitebrowser#3054] opened 2022-06-02 07:22 UTC
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
![Screenshot 2022-06-02 152200](https://user-images.githubusercontent.com/106666139/171575737-b52678d7-de77-45f7-bd89-2937e5492027.png)

> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8
![image](https://user-images.githubusercontent.com/106666139/171575526-1bd3cbed-45a8-4914-bf8b-c79e086d85c7.png)

**Comment by mgrojo** [comment] 2022-06-18 14:52
Duplicate of #3035

**Closed by mgrojo** 2022-06-18 14:52 UTC
