### ISSUE TITLE
database file corruption

### ISSUE THREAD

**Issue by cederom** [sqlitebrowser/sqlitebrowser#489] opened 2016-01-10 12:46 UTC
I am editing my sqlite database for Android application on OSX 10.11.2. I have both AndroidStudio and SQLiteBrowser (3.8.0) opened. My database is broken after hours of editing and saving on each change. There must be something in the backround chaning the database file, maybe AndroidStudio, or the AndroidVirtualMachine. Changes are partial - lots of fields are blanked. Please introduce backround file change detection. I have lost my hours of work two times already. SQLiteBrowser does not verify the written file, so I am writing into pure space and the results are lost. Please add database file verification.

OSX 10.11.2
Version 3.8.0
Qt Version 4.8.7
SQLCipher Version 3.8.10.2
<img width="1066" alt="screen shot 2016-01-10 at 13 14 05" src="https://cloud.githubusercontent.com/assets/3051832/12221571/4d500afa-b7a0-11e5-9f4a-78d2be3bc6ae.png">
<img width="1022" alt="screen shot 2016-01-10 at 13 14 16" src="https://cloud.githubusercontent.com/assets/3051832/12221572/4d53ad68-b7a0-11e5-85a8-68fa01b45e64.png">

**Comment by cederom** [comment] 2016-01-10 12:57
There is no concurrency problem. No other application have access to a database file. SQLiteBrowser 3.8.0 corrupts sqlite database files - it does not save what it show, it does corrupt database file!!!!! :-1:

**Comment by justinclift** [comment] 2016-01-10 15:05
This is a bit confusing... you mention there is no concurrency problem, but also mention using AndroidStudio and DB4S at the same time.  I'm not sure if AndroidStudio changes things or not. :frowning: 

Out of curiosity, is your database file located on your tablet while you're editing it (eg connected through USB cable), or are you copying it to your computer first before editing?  Android has some reasonably well known problems with copying files around in some modes.  Some of the links in here might help, if this is what the problem is: https://github.com/sqlitebrowser/sqlitebrowser/issues/476

**Comment by cederom** [comment] 2016-01-10 16:21
I have local file. Simple case. At first I though that would be concurrent access problems. But then I rebooted with nothing else accessing the sqlite file. I was only editing it with SQLiteBrowser. For some reason it does not save data into database, and even worse it randomly blanks some fields..

What I did was to put some data into table cells, then save, then refresh view of that table by re-selecting it from the list, and some data was gone... sometimes data was on refresh but it was gone when I closed and reopened the file. I had to repeat until success, but finally I have switched to dbeaver.. :-(

**Comment by justinclift** [comment] 2016-01-10 21:35
Yeah, that's really, really not good. :frowning:

**Comment by Joshua-Kirk** [comment] 2016-01-30 18:59
I have reviewed the source files and found no issues in concurrence with your problem too which I also  have been using this application for creating pre generated databases for mobile development and I have not had these same issues. From the sounds of your problem you may have a coding logic error. As justinclift has stated Android does have some issues that are related to using a pre generated database and thus it is at times best to programmatically generate it.

**Comment by cederom** [comment] 2016-01-30 21:20
Nope, I access only sqlite, modify database, store database, close database, open database that is already corrupted. Maybe that is dependency/libraries problem for a binary download. I am also using MacPorts tree for the rest of the OpenSource.. no clue :-)

**Comment by justinclift** [comment] 2016-01-31 11:42
@cederom Hmmm, one thing that **might** fix the problem for you, is if you compile DB4S yourself (pretty easy), so that it uses the MacPorts dependencies instead of the bundles ones.

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

Do you have the time/interest to try that? (it should only take a few minutes)

**Comment by jasonclarkjc** [comment] 2016-04-06 13:11
Here you can find the root cause of this problem [http://sqliteviewer.com/blog/know-corrupt-sqlite-database-file.html](http://sqliteviewer.com/blog/know-corrupt-sqlite-database-file.html)

**Comment by justinclift** [comment] 2017-04-23 09:24
This may be the problem:

https://stackoverflow.com/questions/9058169/sqlite-database-disk-image-is-malformed-on-windows-but-fine-on-android

As pointed out by @MKleusberg [earlier on in the year](https://github.com/sqlitebrowser/sqlitebrowser/issues/476#issuecomment-168403277).

**Comment by cederom** [comment] 2017-04-23 09:37
hello @justinclift, that database crop is not the case in my case, i am working on a file that is source for apk that is then copied to app data directory, so its one way operation.. but your notice is valuable thanks!! :-)

**Comment by justinclift** [comment] 2017-04-23 10:19
Doh.  Damn, hoped we'd found the problem. :smile:

**Comment by cederom** [comment] 2017-04-23 14:12
yea hope so! =)

maybe concurrent access from AndroidStudio and SQLiteBrowser? is sqlite file modified anyhow on open? although its only read once a while to copy, maybe some race condition occurs.. it would be nice to make a md5 sum of the opened file and verify against external file change..?

**Comment by justinclift** [comment] 2017-04-23 14:33
Yeah, concurrent access **may** have something to do with it.  But, that's just (a reasonable) guess. :smile:

**Comment by mgrojo** [comment] 2018-01-02 15:47
Something similar happened to me some days ago. At least in my case, I think, it was a concurrency problem between two sqlitebrowser instances. I was testing some development (not DB related) and I closed two instances that I had for the same testing database. Both asked whether I want to save changes. I click yes for both almost without thinking (it was testing data, after all). The next time I opened the database file, it showed several blank (not NULL) rows. When I open this file with sqlite3 and make a query over the table, it prints some rows and then it says: "Error: database disk image is malformed". 

Now, I cannot reproduce it. In the second instance, when you try to change anything, it says that database is locked. Although it does ask for saving when closing the application, nothing is written nor corrupted.

It suppose it's a problem with SQLite and not with DB4S, who doesn't write directly to the database file.

These are my versions, just in case it's useful:
Version 3.10.99 (some days ago, sorry I did not take note)
Qt Version 5.5.1
SQLite Version 3.11.0
Ubuntu 16.04

**Comment by MKleusberg** [comment] 2018-01-02 17:37
Yeah, that sounds more like an SQLite problem than a DB4S problem. Maybe we could work around it somehow if we knew more but I guess it's not going to be easy.

Here are some way to corrupt your database: https://www.sqlite.org/howtocorrupt.html
Does that help you reproduce the problem, @mgrojo?

**Comment by chrisjlocke** [comment] 2021-04-06 14:24
I'll close this as not only has there been updates to DB4S and SQLite, but getting to the crux of the issue is quite difficult - seems a weird edge case which hasn't been reported frequently - DB4S itself doesn't corrupt databases otherwise we'd have been inundated with disgruntled users.

@cederom - if you have further details or reproducible steps, then of course comment further where this can be reopened.

**Closed by chrisjlocke** 2021-04-06 14:24 UTC
Labels: SQLCipher, android
