### ISSUE TITLE
slow selects compared to python

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#2165] opened 2020-03-20 22:45 UTC
I have query with several subqueries that returns 11 rows, 12 columns and has 485 instructions according to "EXPLAIN". I see two issues
a) sqlitebrowser performs really slow compared to python script (90 seconds compared to about 30-40 seconds with python). I would expect better or same performance.
b) in sqlite browser the query finishes in 90 seconds but the result view still displays "loading" for all data and it takes another 10-20 seconds to load the data.
Tested with several different databases and datasets, I believe the problem is not related to particular query/data.
Query does not contain any regex, just SELECT,WHERE,AND,ROUND,COUNT,SUM,DISTINCT,ORDER BY
sorry I but I can't provide the data I use.

Details for the issue
--------------------

#### What did you do?
run query

#### What did you expect to see?
better performance, data after the query finishes insted of "loading..."

#### What did you see instead?
slow performance, "loading..." for several more seconds after the query finished.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [X] Other: 3.11.99 (Mar 4 2020)

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment] 2020-03-21 18:36
There have been improvements regarding this since the last release. Would you mind testing the same query with a [nighlty build](https://nightlies.sqlitebrowser.org/latest/)? But in any case, take into account that we have to load the data in a graphical table view, and that would also add some penalty.

**Comment by mglatz** [comment] 2020-03-21 19:16
I downloaded the latest nightly build (09-Mar-2020) but I don't see any improvement, it might actually be even worse (avg 100 seconds out of 3 tries; about 120 seconds including loading data) 
python (jupyter notebook in vs code using pandas.read_sql ) on the other hand has the data in 40 seconds or less (incuding displaying them) .

So I see the execution time measures query execution time but not reading the data itself. I believe this has been changed recently, as far as I know all previous versions I used measured query execution and data fetch. Furthermore the "status" listbox says 

> Result: 11 rows returned in 93013ms

which is not true, 93013ms took the query execution, 11 rows were returned some time later.
I believe displaying the data itself in GUI takes few miliseconds.

**Comment by mglatz** [comment] 2020-12-22 12:50
Hi I would really appreciate fixing this :) as Db Browser seems rally awfully slow. 
A query that python pandas fetches in 33s (158 rows) takes 93s to Db Browser. That is a BIG difference. Currently on 3.12.99

**Comment by chrisjlocke** [comment] 2020-12-22 12:56
Both Python and DB4S just use SQLite to perform the query.  Is it a mega-complex query?  Indexes?  Cache?  DB4S just throws the requests to SQLite - it's not like we've written our own interface library or convoluted wrapper.

**Comment by mgrojo** [comment] 2020-12-22 21:15
In a query that returns only 11 rows I've never seen the "loading..." label. I suppose that query or the database is very particular, and maybe we are doing something that harms performance in SQLite, or maybe SQLite is doing something very particular for this case, that makes us behave unexpectedly. However, without having the data and the query is difficult to know. Could you provide them or reproduce the problem with publicly available data?

Maybe our slowness when compared to python pandas is our additional query:
```sql
SELECT COUNT(*) FROM (_your query_);
```
That additional query is known to cause problems when the query contains some randomness that make it return a different number of rows each time it is executed (#1442). While looking for that issue, I find an interesting one (#409) where a Recursive CTE severely impacted performance. Do you have a similar case?


It would be also interesting to know, how we compare to the same query and database executed with the sqlite3 command-line tool.

**Comment by mglatz** [comment] 2020-12-24 10:40
>  it's not like we've written our own interface library or convoluted wrapper

I know :) So there must be something else holding it up. 

Select COUNT(\*) is probably to blame, maybe also the restorepoints, that I think are unnecessary for select queries. 
Is the COUNT(\*) really necessary? If I'm not mistaking you could skip it and count returned rows, If the number mateches LIMIT, then you could do COUNT(\*) afterwards to get the total number of rows.

But I think that is not all to it. Adding COUNT(\*) can't possibly make the total time 3x slower. The query has some timestamp -> datetime conversion and filterig by dateTimeString but no recursion or anything too complicated.

I'l see if I can get you some extract of that data, but I don't think this problem is related to particular database or query. I use sqlite quite a lot and I see much lower performance compared to python on any database and query.

**Comment by mgrojo** [comment] 2020-12-24 14:22
> > it's not like we've written our own interface library or convoluted wrapper
> 
> I know :) So there must be something else holding it up.
> 
> Select COUNT(*) is probably to blame, maybe also the restorepoints, that I think are unnecessary for select queries.

If the `restorepoints` are to blame, you would see a difference in performance when you open the database in read-only mode, where the `restorepoints` are not produced. I don't appreciate any difference.

> Is the COUNT(*) really necessary? If I'm not mistaking you could skip it and count returned rows, If the number mateches LIMIT, then you could do COUNT(*) afterwards to get the total number of rows.

Yes, in theory it is not really necessary, but I personally don't dare yet to change that part of the code, since supporting multithreading and big databases has made it a "bit" complex.

> 
> But I think that is not all to it. Adding COUNT(*) can't possibly make the total time 3x slower. The query has some timestamp -> datetime conversion and filterig by dateTimeString but no recursion or anything too complicated.
> 
> I'l see if I can get you some extract of that data, but I don't think this problem is related to particular database or query. I use sqlite quite a lot and I see much lower performance compared to python on any database and query.

After debugging the application I've seen that there is an additional call to `sqlite3_prepare_v2` with only a subsequent call to `sqlite3_step` in order to get the columns. This call is not logged, and I don't know if it's really so costly, but it should be removed as well.

**Comment by mglatz** [comment] 2020-12-27 15:53
opening in read only does  not seem to have any significant performance benefit.
the count however makes the query run about 2x the time. I would really appreciate removing the count(*) unless its really necessary.

**Comment by MKleusberg** [comment] 2020-12-28 14:25
The query is executed at least four times:
- in ```RunSql::executeNextStatement()``` for determining whether it returns rows or alters the database.
- in ```SqliteTableModel::getColumns()``` to retrieve the columns it returns
- in ```RowLoader:::countRows()``` to retrieve the number of rows it returns
- in ```RowLoader::process()``` to get the actual data

So 93s is still pretty fast compared to 33s :wink: But seriously, this should be improved! I'll see if I manage you find the time over the next week or so.

**Comment by mglatz** [comment] 2020-12-28 16:10
Thanks! Had similar issue when I implemented sqlite in excel vba. Back then I compared speed with sqlite browser which was for some reason much faster :)
Just out of curiosity, would you know what version was this introduced in?

**Comment by MKleusberg** [comment] 2020-12-29 21:29
Can you give tomorrow's nightly build a try? In my tests the runtime is reduced by about 30%, so in your case it should take around 60s instead of 90s. But since I don't even understand in the first place why it takes 90s and not 120s, I can't make any promises :wink: The only downside I noticed is that instead of showing "loading..." for an extra couple of seconds the view now stays blank for the same amount of time. But I think that's definitely worth the saved time.

So yeah, it would be interesting to hear your results. But either way I'll try to optimise this further.

**Comment by mgrojo** [comment] 2020-12-30 13:17
@MKleusberg, I've got a crash with a big table. I suppose it's related to this change, although after merging it with my local changes. GDB backtrace:

```gdb
 #0  0x00007ffff4c87fb7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4c89921 in __GI_abort () at abort.c:79
#2  0x00007ffff567c957 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5682ae6 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5682b21 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5682d54 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff567e85d in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000555555a2c866 in std::vector<QByteArray, std::allocator<QByteArray> >::_M_range_check(unsigned long) const (this=0x7fffb4e43010, __n=37) at /usr/include/c++/7/bits/stl_vector.h:825
#8  0x0000555555a2a18b in std::vector<QByteArray, std::allocator<QByteArray> >::at(unsigned long) (this=0x7fffb4e43010, __n=37) at /usr/include/c++/7/bits/stl_vector.h:846
#9  0x0000555555b3e085 in SqliteTableModel::data(QModelIndex const&, int) const (this=0x5555569df8f0, index=..., role=2) at /home/mgr/src/sqlitebrowser/src/sqlitetablemodel.cpp:317
#10 0x0000555555bae825 in PlotDock::guessDataType(SqliteTableModel*, int) const (this=0x55555683bf40, model=0x5555569df8f0, column=37) at /home/mgr/src/sqlitebrowser/src/PlotDock.cpp:806
#11 0x0000555555ba9937 in PlotDock::updatePlot(SqliteTableModel*, BrowseDataTableSettings*, bool, bool) (this=0x55555683bf40, model=0x5555569df8f0, settings=0x555556f5aa60, update=true, keepOrResetSelection=false) at /home/mgr/src/sqlitebrowser/src/PlotDock.cpp:185
#12 0x0000555555aa327b in MainWindow::<lambda()>::operator()(void) const (__closure=0x555556bbaed0) at /home/mgr/src/sqlitebrowser/src/MainWindow.cpp:3750
#13 0x0000555555aaaaaf in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, MainWindow::newTableBrowserTab(const sqlb::ObjectIdentifier&)::<lambda()> >::call(MainWindow::<lambda()> &, void **) (f=..., arg=0x7fffffffd4b0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:130
#14 0x0000555555aaa085 in QtPrivate::Functor<MainWindow::newTableBrowserTab(const sqlb::ObjectIdentifier&)::<lambda()>, 0>::call<QtPrivate::List<>, void>(MainWindow::<lambda()> &, void *, void **) (f=..., arg=0x7fffffffd4b0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:240
#15 0x0000555555aa96d1 in QtPrivate::QFunctorSlotObject<MainWindow::newTableBrowserTab(const sqlb::ObjectIdentifier&)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x555556bbaec0, r=0x5555569df8f0, a=0x7fffffffd4b0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:168
#16 0x00007ffff5c3266f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x0000555555c73254 in SqliteTableModel::finishedFetch(int, int) (this=0x5555569df8f0, _t1=49999, _t2=55714) at /home/mgr/src/sqlitebrowser/sqlitebrowser_autogen/UVLADIE3JM/moc_sqlitetablemodel.cpp:172
#18 0x0000555555b3ccbc in SqliteTableModel::handleFinishedFetch(int, unsigned int, unsigned int) (this=0x5555569df8f0, life_id=5, fetched_row_begin=49999, fetched_row_end=55714)
    at /home/mgr/src/sqlitebrowser/src/sqlitetablemodel.cpp:102
#19 0x0000555555b50ef6 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2>, QtPrivate::List<int, unsigned long, unsigned long>, void, void (SqliteTableModel::*)(int, unsigned int, unsigned int)>::call(void (SqliteTableModel::*)(int, unsigned int, unsigned int), SqliteTableModel*, void**) (f=
    (void (SqliteTableModel::*)(SqliteTableModel * const, int, unsigned int, unsigned int)) 0x555555b3c9d2 <SqliteTableModel::handleFinishedFetch(int, unsigned int, unsigned int)>, o=0x5555569df8f0, arg=0x7fffc000b410) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:136
#20 0x0000555555b4f362 in QtPrivate::FunctionPointer<void (SqliteTableModel::*)(int, unsigned int, unsigned int)>::call<QtPrivate::List<int, unsigned long, unsigned long>, void>(void (SqliteTableModel::*)(int, unsigned int, unsigned int), SqliteTableModel*, void**) (f=
    (void (SqliteTableModel::*)(SqliteTableModel * const, int, unsigned int, unsigned int)) 0x555555b3c9d2 <SqliteTableModel::handleFinishedFetch(int, unsigned int, unsigned int)>, o=0x5555569df8f0, arg=0x7fffc000b410) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:169
#21 0x0000555555b4cf75 in QtPrivate::QSlotObject<void (SqliteTableModel::*)(int, unsigned int, unsigned int), QtPrivate::List<int, unsigned long, unsigned long>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555556766620, r=0x5555569df8f0, a=0x7fffc000b410, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:120
#22 0x00007ffff5c330c2 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff698183c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff6989104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff5c038d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff5c0604d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff5c5d263 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff3397417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff3397650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff33976dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff5c5c88f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff5c0190a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff5c0a9b4 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000555555b7afef in main(int, char**) (argc=1, argv=0x7fffffffdd58) at /home/mgr/src/sqlitebrowser/src/main.cpp:65

```

**Comment by mgrojo** [comment] 2020-12-30 13:18
Console message for the crash:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 37) >= this->size() (which is 37)
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by MKleusberg** [comment] 2021-01-09 10:52
Thanks, Manuel! This should be fixed now. So tomorrow's nightly build should still be ~30% faster but now without crashing :smile:

**Comment by MKleusberg** [comment] 2021-01-09 13:36
> Is the COUNT(*) really necessary? If I'm not mistaking you could skip it and count returned rows, If the number mateches LIMIT, then you could do COUNT(*) afterwards to get the total number of rows.

I have just implemented this. It didn't reduce the execution time any further in my test case but with this we got rid of the extra time to show the data ("it takes another 10-20 seconds to load the data.") entirely. This also makes the Browse Data tab feel much more responsive for large tables. Thanks a lot for the suggestion, @mglatz! :+1: 

Do you want to give tomorrow's nightly build another try?

**Comment by MKleusberg** [comment] 2021-01-09 13:55
Well... I could reduce the runtime even further. It should be now be close to your Python script. It would be interesting to hear how it performs on your system and with your database :smile:

**Comment by mglatz** [comment] 2021-01-09 19:41
sorry guys, I've been busy over past week. will test it soon and let you know!

**Comment by mgrojo** [comment] 2021-01-10 13:50
It works nicely! Great performance and no bug so far.

**Comment by mglatz** [comment] 2021-01-11 08:31
yep that is much better :) Now the queries are slightly faster than python, which is expected behaviour.

I have the latest nightly build, however there is an issue: I can't run query more than once in execute sql tab. Second and subsequent runs will show no results. The results view contains only rowids but no data. Opening new tab works.

**Comment by MKleusberg** [comment] 2021-01-11 17:26
Thanks for the feedback! Good to hear that it's even slightly faster than the Python code :smile: 

The bug with the empty result view you mentioned should be fixed in tomorrow's nightly build too. Can you give that another try?

**Comment by mglatz** [comment] 2021-01-12 15:57
yes! Can we close this?

**Comment by MKleusberg** [comment] 2021-01-13 18:11
Sure, let's close this then. Thank you very much for your time with this, @mglatz! :smile:

**Closed by MKleusberg** 2021-01-13 18:11 UTC
Labels: performance
