### ISSUE TITLE
Dark Mode isn't applying on Title Bar [macOS Big Sur]

### ISSUE THREAD

**Issue by irvanjitsingh** [sqlitebrowser/sqlitebrowser#2308] opened 2020-06-27 04:13 UTC
Details for the issue
--------------------

#### What did you do?
Enabled Dark Style.

#### What did you expect to see?
Expected it to be applied to the entire app window.

#### What did you see instead?
The style was applied to all parts of the window except for the Title Bar (and until a database is opened, the text preview/edit window doesn't get the change either.

<img width="994" alt="Screen Shot 2020-06-27 at 12 00 58 AM" src="https://user-images.githubusercontent.com/1472548/85914336-cb681080-b80a-11ea-9319-5dd239f58785.png">

<img width="994" alt="Screen Shot 2020-06-27 at 12 12 42 AM" src="https://user-images.githubusercontent.com/1472548/85914355-f5213780-b80a-11ea-82d1-9902c5bed8cd.png">

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version: 11.0 )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2020-06-27 04:41
Interesting.  Maybe a case of [QDarkStyleSheet](https://github.com/ColinDuquesnoy/QDarkStyleSheet) needs updating, or our version of it does.

**Comment by mgrojo** [comment] 2020-06-27 11:44
I'm afraid that [changing the style of the title bar using a Qt stylesheet](https://stackoverflow.com/questions/4507864/how-to-customize-the-title-bar-of-a-qt-app-through-qt-stylesheet) isn't possible. I guess some applications disable the desktop title bar and add their own. I think it's too much for an application like ours.

The Alternative is configuring the dark mode for all the desktop applications and setting the "follow desktop style" preference. There were problems with this option in the past (#1751), but how is the situation now?

**Comment by lucydodo** [comment] 2023-10-18 06:25
I can't reproduce this problem, at least not in the current nightly release, so I'm closing it.

**Closed by lucydodo** 2023-10-18 06:25 UTC
Labels: osx
