### ISSUE TITLE
COLLATE NOCASE unsupported

### ISSUE THREAD

**Issue by slidertom** [sqlitebrowser/sqlitebrowser#411] opened 2015-08-31 11:41 UTC
I do create COLUMN with the COLLATE NOCASE. Sqlite browser does not parse COLLATE NOCASE
statement correctly.
e.g:
CREATE TABLE `MyTable` (`ID` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,`Filter` TEXT COLLATE NOCASE)

**Comment by justinclift** [comment] 2015-09-09 10:17
Oh, that's not good.  Which version of DB4S are you using, and which OS are you on?

**Comment by slidertom** [comment] 2015-09-09 15:11
DB4S: Version: 3.7.0
OS: Windows 7 64 bit

**Comment by MKleusberg** [comment] 2015-09-11 11:45
Can you maybe try the latest nightly build (see here: https://github.com/sqlitebrowser/sqlitebrowser#windows) because we've made some changes in the meantime and at least for me your table statement gets parsed correctly :smiley:

**Comment by glawrence** [comment] 2015-12-07 07:42
@slidertom did you get a chance to test this please?

**Comment by chrisjlocke** [comment] 2016-06-14 14:10
Was just going to raise a ticket when I saw this was already here.  

Using the latest nightly build (13 Jun) and this works 40% successfully (using Windows 10 64bit)

Maybe I broke it, but I 'cheated' by editing a table and changing the field from 'text' to 'text collate nocase'.  DB4S kindof accepted it...
![image](https://cloud.githubusercontent.com/assets/7872218/16045736/b02c725a-3241-11e6-965b-65ee0ab5cb0b.png)

But its not in the dropdown
![image](https://cloud.githubusercontent.com/assets/7872218/16045764/cfd73aae-3241-11e6-8916-48e250c3cb75.png)

...and the 'Modify Tab;e' GUI doesn't see it.
![image](https://cloud.githubusercontent.com/assets/7872218/16045783/e5b2b11e-3241-11e6-96eb-a071e3111ed6.png)

It does physically work though - the field is now nocasing, so 'fred' is found with a field containing 'FRED'.  Adding a field doesn't break this, but MOVING a field does.
![image](https://cloud.githubusercontent.com/assets/7872218/16045824/1bab18ba-3242-11e6-8960-06f189491e84.png)

So it works, but only just...

**Comment by mtissington** [comment] 2017-02-14 22:42
I am still getting this error on the latest nightly build.
Do I need to be concerned about this?
Can you fix it?

**Comment by MKleusberg** [comment] 2017-02-17 12:04
As long as you're just inserting, updating, or deleting records there is no need to be concerned at all. This works just fine. You only get in trouble when editing the table using our Edit Table dialog. In this case the collation gets dropped. That issue is related to #741. I'll try to fix that, too, so there's no need to worry about collations here anymore :smiley:

**Comment by MKleusberg** [comment] 2017-02-17 13:07
This should be working in the next nightly build. Do you have the time to check if it's fixing your problems, @mtissington, @slidertom and @chrisjlocke? You still can't edit collations in the Edit Table dialog but at least they shouldn't get lost when editing the table.

**Comment by wezzix** [comment] 2017-07-11 18:11
I can confirm that moving columns "COLLATE NOCASE" appears to work, no schema info is lost. Table browser still looks scary with dialog warning though... What's the worst that can happen?

**Comment by chrisjlocke** [comment] 2017-07-11 19:38
![bang](https://media.giphy.com/media/rhYsUMhhd6yA0/giphy.gif)

**Comment by MKleusberg** [comment] 2017-10-19 13:16
With tomorrow's nightly build the warning should be gone for COLLATE NOCASE as well as BINARY and RTRIM. It's still going to be shown for other collations (and actually makes some sense for these, even though the wording could be tweaked a little).

@wezzix Want to download tomorrow's nightly build and check if the warning is gone for your database? I think we can finally close this issue then 😄

**Comment by justinclift** [comment] 2017-12-04 17:44
Closing this as it was fixed a while ago, and multiple people have confirmed `COLLATE NOCASE` now works properly. :smile:

**Closed by justinclift** 2017-12-04 17:44 UTC
Labels: bug
