### ISSUE TITLE
Unsaved Query closes without prompt

### ISSUE THREAD

**Issue by russlamb** [sqlitebrowser/sqlitebrowser#938] opened 2017-01-20 19:01 UTC
### Details for the issue
Query tabs can be closed without any prompt to save or warning about lost data. 

I had several queries open for a coding test.  Each query corresponded to an answer to a test question.  I had saved the queries to SQL files, but i needed to close the database.  I closed out of all the open query tabs, not realizing i had made changes to each of them after I had last saved.  To my dismay, when I opened the files again all my changes were lost.  It cost me a couple hours of lost work.  

In other database management GUI, when the user clicks to close out a query they are presented with a prompt like "You have unsaved changes.  Do you want to save before closing?" to prevent lost work.  DB Browser should add this for unsaved query tabs.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( _version: 3.91 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-01-20 20:25
Yep, this does make sense to implement.  Shouldn't be to hard to do either. :smile:

**Comment by palmiche** [comment] 2017-06-13 16:25
👍 for this to be in the next release.
👍 👍 👍 👍 👍 if implemented like SSMS:  a single dialog with all unsaved files.
![20170613-122330-000542 microsoft sql server management studio](https://user-images.githubusercontent.com/12277525/27092998-331f70b2-5033-11e7-878f-0edf9a81441e.png)

**Comment by justinclift** [comment] 2017-06-13 16:51
Ahhh, good thinking.  Yep, that makes sense. :smile:

**Comment by beRto-** [comment] 2019-11-17 01:43
I got burned by this a couple of times recently! I wish DB4S would have saved me from myself! :)

**Comment by iKlsR** [comment] 2019-11-17 03:10
Yikes, hmm. I still don't have the time to get to this 😥. I will peek again month end if somebody doesn't take it as it.

**Comment by mgrojo** [comment] 2020-02-17 19:40
@russlamb, are you still using DB4S. We finally managed to implement this prompt. If you'd like to try it, you can install a nightly build or wait to the imminent 3.12 release. I'll close this issue now, since other users have already confirmed that it is working for them, but feel free to reopen it if I've missed something.

**Closed by mgrojo** 2020-02-17 19:40 UTC
Labels: enhancement
