### ISSUE TITLE
No way to insert values in table Unknown function:get_user() error

### ISSUE THREAD

**Issue by haplox** [sqlitebrowser/sqlitebrowser#2497] opened 2020-12-02 10:38 UTC
Details for the issue
Hello,

I am tryin to insert values in a sqlite database (attached) in the table "main", and always get the error: "Unknown function:get_user()". In fact I do not know if this is a software issue or the problem is in the sqlite file.

Does not matter the way I try it: neither importing CSV, nor executing SQL code nor introducing values in the table view

#### What did you do?
Import CSV file with new values in table "main"
Execute SQL code to insert new values
Try to add new values in the table view

#### What did you expect to see?
Values inserted in database in table "main"

#### What did you see instead?
No way to insert values, always "Unknown function:get_user()" error 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:10 64 bits )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X
[kalibro.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/5628631/kalibro.zip)

] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2020-12-02 11:30
The problem is in the database.... sort of.  
The main table seems OK - the issue is with mainAddFieldLog.
Each field can have a default value (for new records) and this table has fields with a default value that state that the user value derives from a function called 'getUser'

![image](https://user-images.githubusercontent.com/7872218/100867050-8323dd00-3491-11eb-80a2-4815a69c9428.png)

This isn't part of normal SQLite, so I assume whatever uses the database also uses an SQLite extension.  
You'll have to remove this default setting, amend the database as required, then if needed, put those default settings back.

Again, this isn't a fault of DB4S nor the database specifically - just that a required component to make the database fully functional isn't available.

**Comment by chrisjlocke** [comment] 2020-12-02 11:31
I'll close this as this isn't an issue in DB4S that we can handle, but feel free to comment further if needed. :)

**Closed by chrisjlocke** 2020-12-02 11:31 UTC

**Comment by haplox** [comment] 2020-12-02 12:17
Many thanks chrisjlocke. I said it in my post, that I did not know if the problem was in the soft or in the database.. I will try to bypass this

**Comment by chrisjlocke** [comment] 2020-12-02 12:22
No problem - you were right to raise the issue.  :)
Once the default value has been removed, it should work OK.  You can then put it back once the record has been added.
You should only need to amend that default value if you're adding new records.
