### ISSUE TITLE
Cannot add record to table with foreign keys

### ISSUE THREAD

**Issue by peku33** [sqlitebrowser/sqlitebrowser#463] opened 2015-12-27 22:16 UTC
I have a table 'A' with Primary Key on 'ID' column. I have some data inside, however there is no record with ID = 1.

I have a table 'B' with AID marked as Foreign Key from table 'A'.

If I try to add new record in B i get:
DB Browser for SQLite
Error adding record:
CHECK constraint failed: B (INSERT INTO `B` (AID) VALUES (1, ...);)

**Comment by justinclift** [comment] 2015-12-27 22:54
Hmmm, that doesn't sound good.  Which version of DB4S is this for, and which OS are you on? :smile:

**Comment by peku33** [comment] 2015-12-27 22:57
I found out that the problem is not caused by foreign keys but constraints added to columns.

It seems that when adding new row, it is added with 'default' values and then edited with values given by user.

This is for version I downloaded today, so 3.8.0. The same applies for 3.7.0. I'm running windows, downloaded x64 version.

**Comment by justinclift** [comment] 2015-12-27 23:51
No worries, thanks for the bug report.  Hopefully someone (maybe @MKleusberg ?) has time to look at it in the near-ish future. :smile:

**Comment by iursevla** [comment] 2016-11-25 17:54
I had this problem today. I try to add a new record but it says:

**"Error adding record: FOREIGN KEY constraint failed (INSERT INTO `FriendShit('id', 'user1', 'user2') VALUES(4,0,0);)"**

**Comment by MKleusberg** [comment] 2016-12-28 12:51
@iursevla and @peku33 Do you have the time to check if this solution (https://github.com/sqlitebrowser/sqlitebrowser/issues/901#issuecomment-268693029) from issue #901 helps you? :)

**Comment by justinclift** [comment] 2017-05-16 21:45
@peku33 @iursevla Ping?

**Comment by iursevla** [comment] 2017-05-17 09:10
@justinclift I tried today and it seems to work. Windows 10, Version 3.9.1

**Comment by justinclift** [comment] 2017-05-17 09:26
@iursevla Awesome, thanks for checking. :smile:

**Comment by sharpdot** [comment] 2017-08-25 22:03
I have this issue on the mac osx sierra after updating to 3.10.0. The previous version I had (3.9.1) did not have the issue.

**Comment by justinclift** [comment] 2017-08-25 22:31
Ouch.  We did a lot of changes to our foreign key handling for 3.10.0.  It sounds like you're hitting a bug that the new code isn't handling correctly. 😦 

Our main developer, @MKleusberg, who wrote the new foreign key code is on vacation until the end of this month.  So... you'll probably need to use version 3.9.1 until he's back and can investigate.

Sorry for the hassle. 😕

**Comment by sharpdot** [comment] 2017-08-28 13:51
Thanks for the swift repy @justinclift  - I can wait and stay on 3.9.1. @MKleusberg let me know if I can provide more detail when you're back.

**Comment by MKleusberg** [comment] 2017-09-01 17:39
@sharpdot Just tried to reproduce the original issue and didn't have any luck. Can you upload or send me an example database (with all the records deleted for privacy reasons) and some sort of instructions for triggering the issue? 😄

**Comment by ge-org** [comment] 2017-09-05 14:59
Hi @MKleusberg,

I have the same issue. Whenever I try to add a record I get the following error message:

> Error adding record:
> FOREIGN KEY constraint failed (INSERT INTO `schedules`(`id`,`photoId`) VALUES (386845,'');)

My DB looks like this:
`CREATE TABLE photos ( id TEXT NOT NULL UNIQUE, title TEXT NOT NULL, PRIMARY KEY(id) )

CREATE TABLE schedules ( id TEXT NOT NULL UNIQUE, photoId TEXT NOT NULL, PRIMARY KEY(id), FOREIGN KEY(photoId) REFERENCES photos(id) )`

**Comment by UrugHodu** [comment] 2017-11-02 12:17
HI @MKleusberg,
Just updated to 10.3.1. I created row ok on parent but going to child and hitting New Record on empty table throws Foreign Key... failed trying to insert null primary key and null FK as it attempts to create the New Record template.

**Comment by justinclift** [comment] 2017-11-02 16:53
@UrugHodu Would you have time to try the latest nightly build?  We've been changing things around again, and there's a decent chance this has been fixed. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by UrugHodu** [comment] 2017-11-09 11:53
Justin,
Sorry I did not get back to you earlier. Your email had been flagged as spam and  I stumbled on it by accident. I just download and tried the installation and I got:
[cid:image001.png@01D35959.4AE15880]

It is probably okay but I’m just too busy right now to deal with my machine having issues. If it installs okay, then I would have no issues.

I am available to test updates that can pass the anti-virus and install okay.

Thanks for immediate response.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by chrisjlocke** [comment] 2017-11-09 13:27
Hi @UrugHodu 
Unfortunatrly images pasted into emails don't come through to GitHub properly.  Could you visit the thread here:
https://github.com/sqlitebrowser/sqlitebrowser/issues/463

and edit your comment, pasting in the image?  Sorry.

**Comment by buza971** [comment] 2017-11-12 16:52
Remove NOT NULL from FOREIGN KEYs and PRIMARY KEYs. It worked in DB browser for sqlite.

**Comment by UrugHodu** [comment] 2017-11-12 17:42
Okay, I’ll give it short and let you know mid this week.
Thank you very much.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by justinclift** [comment] 2017-11-17 17:09
@UrugHodu Reminder ping. :smile:

**Comment by stefan-schindler** [comment] 2017-12-28 15:51
![image](https://user-images.githubusercontent.com/26493472/34415388-bed8590a-ebee-11e7-907b-ee2f1c3faafd.png)

Hello, I still have the same problem with the 64 bit windows build you provided here: https://nightlies.sqlitebrowser.org/latest/

The table shown in the first image has two columns which are both PKs, can't be NULL and both are foreign keys reffering to other tables. 

If the columns can be NULL, it works. So the solution would be probably to ask the user to enter the values in the columns immediately after hitting the New Record button I suppose :)

**Comment by pamtbaau** [comment] 2017-12-30 18:12
Created the following table:
`CREATE TABLE temp ( value TEXT NOT NULL CHECK (value <> '') );`

No tupples can be added in Data Browser due to the following error:
![error](https://user-images.githubusercontent.com/5120011/34456265-aa45f4d4-ed92-11e7-9219-15aa1a5ddf7f.png)
> Note the value '' in insert statement.

Created the following table:
`CREATE TABLE temp2 ( userId INTEGER NOT NULL REFERENCES user(id) )`

No tupples can be added in Data Browser due to the following error:
![error2](https://user-images.githubusercontent.com/5120011/34456312-a759cc72-ed93-11e7-9f73-429046273085.png)
>Note the value 0 in insert statement.

Is `New Record` first inserting a record into the database with default values '' or 0 in the case of NOT NULL? And later updating the record with data entered by user? In that case both cases are deemed to fail...

Is it possible to first add a new row to QT's table and insert it later when row looses focus?

**Comment by Bigparadox** [comment] 2018-01-10 12:09
I encountered the same problem today. I should be fixed of course, but the solution in my case (for data entry) was to connect to the database with MS Access through ODBC. Worked nicely, and it has a more convenient UI for data entry.

**Comment by pamtbaau** [comment] 2018-01-10 12:29
@Bigparadox,  Manual insert statements will suffice for now, but interesting workaround though...

**Comment by chrisjlocke** [comment] 2018-01-10 12:41
> and it has a more convenient UI for data entry

Interestingly, we were looking at this (see #1278) - is this sort of UI the thing you had in mind?  I've used Access a lot in the past, and it allows user defined input screens (or forms).

**Comment by Bigparadox** [comment] 2018-01-10 12:56
Well, I did not switch to MS Access to get a better UI really. But sure, if you need to enter a lot of data and not just some tests, then a better UI would be good. But perhaps the primary purpose for the sqlite browser is more the creation of tables and relationships and so, When the database is ready, you most probably will us it in a different way, in an application or so.

**Comment by Bigparadox** [comment] 2018-01-10 12:57
I can add that I used this one
http://www.ch-werner.de/sqliteodbc/
If someone wants to try

**Comment by pamtbaau** [comment] 2018-01-10 13:22
Playing with LibreOffice Base using that same ODBC driver. Has some troubles configuring the driver, but all works fine now :-)

Tupple validation/insert occurs on row blur/lost focus which allows for entering data which is not valid during editing.

**Comment by MKleusberg** [comment] 2018-08-27 20:16
Sorry for taking so long with this but we have finally merged a change by @mgrojo which should fix this problem :smile: If you're still around, can you give [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/) a try and see if it's working now, @ge-org, @UrugHodu, @stefan-schindler, @Bigparadox and @JeongJun-Lee?

**Comment by stefan-schindler** [comment] 2018-08-30 18:11
It is working for me. Thanks :)

**Comment by mgrojo** [comment] 2018-09-28 18:00
Thanks, @stefan-schindler. I'll close this then. It will be one of the additions to our hopefully imminent 3.11.0 release :+1:

**Closed by mgrojo** 2018-09-28 18:00 UTC
Labels: bug, constraints & foreign keys, response requested
