### ISSUE TITLE
Option to find&replace in selection

### ISSUE THREAD

**Issue by mdro** [sqlitebrowser/sqlitebrowser#1618] opened 2018-11-18 08:36 UTC
Describe the new feature
--------------------------
I previously mentioned in #1612 that Visual Studio has a usefull feature for find&replace:
If you have more than one line highlighted when you open the replace menu, "replace all" will be limited to that part.

This is usefull for example when you want to add a `CREATE TABLE` statement (with separate `PRIMARY KEY` or `FOREIGN KEY` clauses) that is very similar to a different one in the same file: Ctrl+C, Ctrl+V, Highlight, Ctrl+H, change field names:

<img width="650" alt="vsreplace" src="https://user-images.githubusercontent.com/4457627/48670231-6f101b80-eb14-11e8-89b2-b3d5ed8cc312.png">

Visual Studio also prepopulates the search box (for search and find&replace) with selections smaller than a line or the word under the cursor. This feature would be less important to me.

Both features can be turned off in the settings menu of Visual Studio.

**Comment by SilvioGrosso** [comment] 2018-11-18 11:11
I second that.
This feature would be extremely useful while working in the Execute SQL tab and you want to replace some SQL parts. With very long SQL scripts it might allow you to replace only the selected part of code you are interested in.

Pretty much every text editor allows you to do so. Usually, there is check-box to tick to enable it :-)

**Comment by chrisjlocke** [comment] 2018-11-18 18:19
The feature I thought I'd use a lot in Visual Studio is the multiple carats, so you can edit multiple places at once.  So in your example, rather than search/replace 'foo_id' with 'bar_id', you simply multiple-click on each 'foo' (to create multiple carats) then delete 'foo' and type 'bar' - all are edited.  However, in practice, I've not used it at all yet! 🤣

**Comment by SilvioGrosso** [comment] 2018-11-24 07:10
Hello @mgrojo

Thanks a lot for your last awesome effort!
I have also noticed that this option (find > replace) is case-insensitive, which is an extra-bonus for me.
Keeps rocking :-)

I have tested this new option on Windows 10 - 64 bit, with DB.Browser.for.SQLite-win64.

Here is my screenshot where I have selected my text and  then replaced the word mary with LUCY (just for testing purposes):

![selection_only](https://user-images.githubusercontent.com/33007383/48965537-b0467680-efbf-11e8-801e-0152d976e9f4.jpg)

**Comment by SilvioGrosso** [comment] 2018-11-24 07:39
Hello @justinclift 

I have dowloaded this build (3.11.99) this morning, an hour ago.
Judging by your latest github commits, I suppose it is after you  Added Win64 nightly build script.

Here is my screenshot on Windows 10 (64 bit) though:

![db_today](https://user-images.githubusercontent.com/33007383/48965778-e259d780-efc3-11e8-975f-438205952632.jpg)

**Comment by justinclift** [comment] 2018-11-24 07:56
Excellent, thanks heaps @SilvioGrosso. :smile:

**Comment by SilvioGrosso** [comment] 2018-11-24 08:32
Hello @chrisjlocke @mgrojo 

In appreciation of your hard work on Db Browser for SQLite I have just increased my monthly payment on Patreon.
By doing so, it is for instance now possible to purchase the basic certificate for signing the builds on Windows (since the total sponsorship is now > 75$).

**Comment by justinclift** [comment] 2018-11-24 09:43
Fantastic @SilvioGrosso.  That's good timing, as the next release shouldn't be too far off now. :smile:

**Comment by SilvioGrosso** [comment] 2018-11-24 09:47
Yep. I know: I did it on purporse: to make Windows users happy  :-) 

    Il Sabato 24 Novembre 2018 10:44, Justin Clift <notifications@github.com> ha scritto:
 

 Fantastic @SilvioGrosso. That's good timing, as the next release shouldn't be too far off now. 😄 —

**Comment by mgrojo** [comment] 2018-11-24 15:29
Thanks a lot, @SilvioGrosso!

By the way, curious location of the Help button in Windows. In Linux is at the left aligned relatively to the window, and Close right aligned. If at least the buttons were in different positions, with Close at the right end, it would look better. That's funny because the Help button under Windows wouldn't be necessary, since I see there is a [?] window button. The Help button enters also in What's This mode and I added it because in Linux there is no such thing as a [?] window button.

**Comment by SilvioGrosso** [comment] 2018-11-24 16:40
Hello @mgrojo 

This ? window button is indeed quite interesting :-)
Its own tooltip is another ?

When you press this button no action is triggered but, alongside the mouse's cursor, another ? appears.
Later on, whenever you click somewhere on the GUIs new tooltips show up to illustrate the part where your mouse in positioned.

For example, I have just clicked on this part of the GUI:

![tooltip png](https://user-images.githubusercontent.com/33007383/48970691-b6644380-f00f-11e8-971b-2d79eda2152a.jpg)

**Comment by mdro** [comment] 2018-11-24 17:30
Works perfectly.
Thanks for the great work @mgrojo !

**Comment by mgrojo** [comment] 2018-11-24 18:46
@SilvioGrosso
> When you press this button no action is triggered but, alongside the mouse's cursor, another ? appears.
Later on, whenever you click somewhere on the GUIs new tooltips show up to illustrate the part where your mouse in positioned.

Yes, that's exactly it's use. It's the so called What's This? feature. You can also access it from the Help menu in the main window or almost everywhere pressing Shift+F1. We have included some helpful messages in some of them. Other are plain boring. If we don't use it more it's because we think they are usually overlooked by users :smile:

I have code for adding all the editor shortcuts to the "Execute SQL" message, because it currently lacks one and QScintilla provides a list of them with short descriptions. The problem is that the text is then too large and these floating tips are not thought for so much content (the text is truncated at least on my computer). I've finally added the generated list to the wiki page: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Keyboard-shortcuts#sql-json-and-xml-editors but I'm still thinking on how to add them to the application. Most are widely known, but there are also less known/standard shortcuts that are also useful.

**Comment by mgrojo** [comment] 2019-08-10 12:50
Closing this as it was already confirmed.

**Closed by mgrojo** 2019-08-10 12:50 UTC
Labels: enhancement, response requested
