### ISSUE TITLE
Feature request: profiler

### ISSUE THREAD

**Issue by denisz1** [sqlitebrowser/sqlitebrowser#903] opened 2016-12-15 19:34 UTC
Would be really cool to have profiler feature.

There is no SQLite profiler out there, so would be a first.

**Comment by justinclift** [comment] 2016-12-15 20:38
Sounds interesting.  To me, that kind of sounds like some sort of special support for the EXPLAIN command (which can be run in the Execute SQL tab now).

Are you meaning that, or something different? :smile:

**Comment by denisz1** [comment] 2016-12-16 10:25
I think SQLite has profiling built-in, like you said, but it's text-based and not easy to use. No SQLite tool right now has proper GUI profiling.

I don't know if SQLite would support that though, because a profiler, when listening, will automatically list queries sent to the db. You don't need to interact with it, just keep the window open and see what is happening.

Can SQLite do such a thing, that is listen for events?

**Comment by MKleusberg** [comment] 2016-12-28 12:39
SQLite doesn't offer much profiling information. The explain command tells you something about what SQLite is doing when a statement is executed but doesn't include any timings. Then there is the sqlite3_trace_v2 function (https://www.sqlite.org/c3ref/trace_v2.html) which allows profiling but all it does is measuring the total time that each statement took. So we can't really use it because a) it doesn't allow us to distinguish between Application and User SQL like we're currently doing it in the SQL log and b) it doesn't give us much more information than out timer in the Execute SQL tab right now.

But then again, I have to admit I'm a little confused right now. Is that what you need anyway? :)

**Comment by denisz1** [comment] 2016-12-28 15:47
@MKleusberg I see what you mean. I guess it's not possible. Pity.

Not being able to see what commands are sent to the database, makes development and debugging a real pain.

**Comment by justinclift** [comment] 2016-12-28 17:24
Hmmm, the SQL Log tab should show that already shouldn't it?

Maybe we're filtering something out from that which might actually be useful?

**Comment by denisz1** [comment] 2016-12-28 17:58
@justinclift Unless I'm using it wrongly, I don't think that the log tab does it. What I do: 

  - load sqlitebrowser, open my SQLite database file
  - run my app, perform some operation which hits that database
  - observe the log tab

...and nothing is logged there. Not under "Application" or "User".

**Comment by justinclift** [comment] 2016-12-28 17:59
Hmmm, yeah we might be able to do something about that.  @MKleusberg thoughts?

**Comment by MKleusberg** [comment] 2017-01-04 19:42
Unfortunately that's most likely not possible. The problem is that SQLite is serverless. Each application opens the database on its own and doesn't share the connection. So even though multiple applications can open the same file at the same time it's basically two separate connections that can't really interact with each other (except for some basic locking functionality). But this means one application can't see what the other is doing and vice versa. So DB4S has no chance to log the SQL statements executed by another application :frowning: What you will need to do is add some hook to your application that does this job. The ```sqlite3_trace_v2``` I've linked to above is an easy way to implement this into an existing application.

**Comment by justinclift** [comment] 2017-01-04 19:51
Ahhh, so an ideal solution would be some kind of SQLite proxy.  eg load that and point it at a database, then load DB4S and point it at the proxy

It's not something we can do ourselves (in the short term anyway), though as a separate idea it does sound kind of nifty

Doing some quick Google searching turned up a few hits for "SQLite proxy", but nothing seeming to be the right kind of thing. @denisz1 You might have more luck than me if you look look further, I just did cursory searching.

Hmmm... guessing we might as well close this Issue too, as it seems like something we can't really do much about.

**Closed by justinclift** 2017-01-04 19:51 UTC

**Comment by MKleusberg** [comment] 2017-01-04 20:07
Even a 'proxy' would be difficult to do because SQLite only opens database files. So the proxy would just open the database file, but what would the application open? It can't open the same file because then it's no proxy. But it can't open some connection to the proxy either because that's no file. So I'm afraid you'll definitely need to update your application or the SQLite library...
