### ISSUE TITLE
Unable to open default EUDC font: "EUDC.TTE"

### ISSUE THREAD

**Issue by stephenhsiao** [sqlitebrowser/sqlitebrowser#3435] opened 2023-08-08 03:06 UTC
Details for the issue
--------------------

#### What did you do?
Launch the app.

#### What did you expect to see?
Just the app.

#### What did you see instead?
A pop up windows saying: Unable to open default EUDC font: "EUDC.TTE"

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.22621) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by justinclift** [comment] 2023-08-08 03:54
This seems like a duplicate of #2556.  Probably try the suggested fix there, as it's reported to work.

I'll close this issue for now, but if the fix(es) suggested in the other issue don't work then feel free to re-open it. :smile:

**Closed by justinclift** 2023-08-08 03:54 UTC

**Comment by chrisjlocke** [comment] 2023-08-08 08:21
The last comment (deleting the leg HKEY_CURRENT_USER\EUDC in the registry) is the quick fix. :)

**Comment by justinclift** [comment] 2023-08-08 12:12
"leg"?

**Comment by justinclift** [comment] 2023-08-08 14:10
Awesome. :smile:

**Comment by chrisjlocke** [comment] 2023-08-09 06:35
> "leg"?

Sorry - ye olde Win95 speak when the registry was first introduced.  Proper terminology would be 'branch'.  Deleting that key which would delete all corresponding keys and values under it.
