### ISSUE TITLE
Copy column name with right click

### ISSUE THREAD

**Issue by kanter** [sqlitebrowser/sqlitebrowser#3059] opened 2022-06-06 12:24 UTC
A nice to have : copy the column name with a right click mouse. What do you think ?

**Comment by mgrojo** [comment] 2022-06-23 19:45
Currently, you can use drag & drop from the DB Schema dock for that. Be sure to adjust your preferences using the contextual menu.

**Comment by sky5walk** [comment] 2022-06-23 20:19
Can you elaborate? I rarely open the DB Schema window.

I am mostly within Browse Data and Execute SQL results.
Accordingly, it would be simpler to grab the column names from either of these windows.

**Comment by chrisjlocke** [comment] 2022-06-23 21:52
If you have the 'DB Schema' window open, you can drag elements to the Execute SQL window.

![image](https://user-images.githubusercontent.com/7872218/175406791-8863b413-b85a-4bf5-a400-2e6650bf85fa.png)

So drag the 'tableA' to add to the end of 'from', or drag an individual field.

![image](https://user-images.githubusercontent.com/7872218/175406953-3aea596f-abd5-4117-a5f6-3169a5448920.png)

If you right-click, you have some toggleable options.  'Qualified names' means it'll append the table name to field names, so tableA.field1 for example, rather than just field1

![image](https://user-images.githubusercontent.com/7872218/175407156-e767ae9c-af68-40dc-8165-27d74c34ae22.png)

(Yes, I know the SQL is now not valid.... shhhhhhhh ;) )

'Enquoted names' means it'll put quotes around the item you select - "tableA"."field1"

![image](https://user-images.githubusercontent.com/7872218/175412917-7f5fe198-5142-46aa-b83c-616ace65931a.png)


Hope this makes sense.  Yell back and I can fire up the other PC to do a screencast instead of screenshots.

**Comment by mgrojo** [comment] 2022-06-23 21:58
Thanks, @chrisjlocke. With the latest commit from master, there is also an option for dropping the fields or table as a `SELECT` query: 8bb16d1dd0ed9989ff7d22bcdb31eff51b86228b

**Comment by sky5walk** [comment] 2022-07-04 18:28
v220629 nightly does NOT place column name(s) into the clipboard.
I can get the Create Statement, but that is in the Database Structure tab.

Am I doing something wrong?
Browse Data tab -> RM Clk and Copy column name -> clipboard contents unchanged.

**Comment by chrisjlocke** [comment] 2022-07-04 22:53
> Implemented thanks to PR https://github.com/sqlitebrowser/sqlitebrowser/pull/3051

Did you copy it verbatim, or correct it?  It appears to be a bug/description issue in the video posted, and (at least in Windows) nothing gets put into the clipboard.  Wondering if it's because the caption on the button is now different? (copy column name, and not copy table name)

**Comment by mgrojo** [comment] 2022-07-08 20:25
> Edit #2: Does copyColumnName actually get called?

No, it wasn't associated to the menu entry. Sorry, it seemed so simple that I didn't test it before merging.

**Comment by chrisjlocke** [comment] 2022-07-09 08:31
I never test any of the code I write either! 😁

**Comment by chrisjlocke** [comment] 2022-12-22 18:58
Closing this as the issue is now resolved.

**Closed by chrisjlocke** 2022-12-22 18:58 UTC
Labels: enhancement, browse data
