### ISSUE TITLE
Math extension

### ISSUE THREAD

**Issue by Bilge** [sqlitebrowser/sqlitebrowser#1224] opened 2017-11-12 19:38 UTC
Is it possible to either incorporate the [mathematical extension](https://www.sqlite.org/contrib) (extension-functions.c) into the core application or provide it as a compiled extension?

**Comment by justinclift** [comment] 2017-11-12 20:01
Interesting thought.  If you compile it yourself, you should be able to load it in the extensions part of Preferences.

Which OS are you using?

**Comment by Bilge** [comment] 2017-11-12 22:08
Windows 7.

**Comment by justinclift** [comment] 2017-11-12 23:46
k, you can probably get the extension compiled by setting up MSVC 2013 using the steps here:

* https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S

I've not personally tried to compile external SQLite extensions though, so you'd likely need to experiment a bit.

**Comment by Bilge** [comment] 2017-11-12 23:58
Since I'm not very familiar with C compiling I may have to insist on my original proposal. Notwithstanding my own capabilities, it seems others would benefit from official support, too.

**Comment by struck89** [comment] 2017-12-14 11:11
Hi @Bilge,
I also think it would be a great addition to the queries to be able to add these math functions.
I tried the thing, compiled it, but when loading it, it says "error loading extension: No se puede encontrar el módulo especificado"
I don't know why the text is half in spanish (like my computer), since the app is in english. Does this mean that it is a OS Error? I am on Windows. The error means translates to "the specified module could not be found".

I also tried the command SELECT load_extension(".....libsqlitefunctions.so");
No luck, same error:
No se puede encontrar el módulo especificado.
I tried to change the path spec in many different ways (single quotes, double quotes, /, \, \\, ... No luck.
I tried to compile .so (as the documentation of the extension says) or to .dll (since it is an accepted extension in the app extension loader) (even though I am 99% sure this makes no difference)
Any ideas?

**Comment by justinclift** [comment] 2017-12-14 22:19
@struck89 Wow, that's really, really awesome!

Any interest in writing up the steps onto our Wiki so others can figure out similar for other extensions?  Also, I might be able to follow along them and get it added into the official process. :smile:

**Comment by justinclift** [comment] 2017-12-14 22:20
@Bilge Do you have a few moments to test out the extension compiled by @struck89?

**Comment by mgrojo** [comment] 2017-12-14 22:56
I can confirm that the extension-functions can be compiled and works also for Ubuntu 16.04. Here is a sin plot directly copied from the plot dock and pasted here (you can now do that :smile:)

![imagen](https://user-images.githubusercontent.com/13812910/34018405-fc63948a-e129-11e7-8871-af2f5c688d27.png)

**Comment by justinclift** [comment] 2017-12-14 23:23
Muaaa Haaa Haaa.  This is really good stuff.

Looking at the .c source file now, it has basic instructions for compiling on Linux and OSX at the top.  Sounds like it'll be fairly easy on those platforms.  Windows though... I'm having trouble figuring out the steps it'd need. 😕

**Comment by justinclift** [comment] 2017-12-15 00:01
Looking into the history of this extension code, it **seems** to be public domain:

&nbsp; &nbsp; https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg16048.html

That being the case, adding them into our builds wouldn't introduce any licensing problems (important). :smile:

**Comment by justinclift** [comment] 2017-12-15 00:32
This might also be useful reference info too.  Not sure yet.

* http://sqlite.1065341.n5.nabble.com/Example-Showing-ACTUAL-Use-of-sqlite3-auto-extension-td27657.html

**Comment by justinclift** [comment] 2017-12-15 00:52
@liamh Are there any gotchas we should keep an eye out for?

Note - Hoping you're the correct Liam Healy there. :wink:

**Comment by justinclift** [comment] 2017-12-15 01:59
As a data point, just received a response from Liam Healy, pointing at his canonical source repo for the functions.  He accepts PR's (etc), in case anyone wants to expand things out and so on. :smile:

&nbsp; &nbsp; https://gitlab.com/liamh/extension-functions

**Comment by liamh** [comment] 2017-12-15 02:16
You do have the right person.

One of the emails referenced in this thread said " Also note that the typing on sqlite3_auto_extension() pointer is wrong. " If anyone has a patch to fix the problem, I'll take it if it's been tested. I'm a bit embarrassed that I said to post problems to the mailing list - I think I must have dropped off that mailing list years ago, so I haven't seen anything that's posted.

**Comment by struck89** [comment] 2017-12-15 10:18
So where are we now?
I could write the steps to compile the shared library, but I just followed what was included in the heacer of the source file:

> * Windows:
>  1. Install MinGW (http://www.mingw.org/) and you will get the gcc
>  (gnu compiler collection)
>  2. add the path to your path variable (isn't done during the
>   installation!)
>  3. compile:
>   gcc -shared -I "path" -o libsqlitefunctions.so extension-functions.c
>   (path = path of sqlite3ext.h; i.e. C:\programs\sqlite)

I would change it for:
> * Windows, 32 bit sqlitebrowser:
>  1. download the "C source code as an amalgamation," from https://www.sqlite.org/download.html
>  2. copy the file sqlite3ext.h next to extension-functions.c
>  3. Install MinGW (http://www.mingw.org/) and you will get the gcc (gnu compiler collection)
>  4. add the path to your path variable (isn't done during the installation!)
>  5. compile:
>   gcc -shared -o libsqlitefunctions.so extension-functions.c
>
> For Windows, 64 bit sqlitebrowser, download Mingw-w64 instead (can be downloaded from http://win-builds.org/doku.php and it also installs a shit-ton of things, I couldn't see how to install "nothing but..") and follow the same steps (add to path and compile)

@mgrojo That's a beautiful Moiré pattern!

**Comment by justinclift** [comment] 2017-12-16 01:16
Ahhh.  I didn't realise that extensions compiled by MinGW's gcc would work for our releases, as they've been compiled with MSVC.  I should be able to try that out in a VM and see if there are any gotchas.

**Comment by justinclift** [comment] 2017-12-16 01:19
Note - setting the "response requested" tag on this so I remember to come back to it in a few days and follow up, just in case I don't get to this before. (yeah, not a great way of tracking things, but it works ok)

**Comment by chrisjlocke** [comment] 2018-11-28 10:49
>  setting the "response requested" tag on this so I remember to come back to it in a few days 

347 days and counting.  😆

**Comment by Bilge** [comment] 2018-11-28 10:56
>it works ok

:thinking:

**Comment by karim** [comment] 2018-11-29 01:34
@justinclift Want to test compiling the math extension with Visual Studio now? :smile: 

I managed to build and load it successfully. It is only 37kb so I guess we can include it with the installer.

**Comment by justinclift** [comment] 2018-11-29 01:40
Sure.  If it can be compiled as part of the nightly build batch file(s), we might as well add it in for testing sooner rather than later. :smile:

**Comment by karim** [comment] 2018-11-29 01:54
Yes, it is is simple.

1. Create a file and call it anything with .def extension, and paste these in it.

```
EXPORTS
    RegisterExtensionFunctions
    double_cmp
    int_cmp
    map_destroy
    map_insert
    map_iterate
    map_make
    node_destroy
    node_insert
    node_iterate
    print_elem
    sqlite3_api
    sqlite3_extension_init
    xcalloc
    xfree
```
2. Move this file along with `extension-functions.c` inside extracted SQLite amalgamation folder.

3. Add this to the build script `cl /MD extension-functions.c -link -dll -def:extension-functions.def -out:math.dll`

**Comment by justinclift** [comment] 2018-11-29 01:57
Sounds pretty simple.  Are you ok up update the `*-new.bat` files?  We'll probably need to add the extension source code to our repo too, so it's version controlled and can be grabbed from a known filesystem spot. :smile:

**Comment by karim** [comment] 2018-11-29 02:01
Sure. We will add `extension-functions.c` to to this repo? In its own folder?

**Comment by karim** [comment] 2018-11-29 02:04
We continue on gitter, slack or IRC/freenode?

**Comment by justinclift** [comment] 2018-11-29 02:08
Continue here, so the entire conversation is in plain view for future reference. :smile:

Add `extension-functions.c` to our main repo.  Probably in a new `extensions` folder under the `src` folder.  I'll also have a go at adding it to the macOS installer at some point too. :smile:

**Comment by karim** [comment] 2018-11-29 02:17
Okay, done. I will now edit the build scripts and test.

**Comment by karim** [comment] 2018-11-29 03:11
All done now. Can you make another build to test it also?

**Comment by justinclift** [comment] 2018-11-29 03:42
Yep.  Just killed the macOS nightly build (it takes hours), and started the updated Win64build (new) batch file.  I'll do the Win32 one too when that finishes. :smile:

**Comment by justinclift** [comment] 2018-11-29 04:42
Win64 build succeeded and is online here:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi

Tested both the SQLite and SQLCipher variants quickly on the build VM.  Both loaded the bundled `math.dll` extension fine.  Didn't try to do anything with it though.  I'll leave that to others.

The Win32 builder is running now.  In theory that should work ok too, but lets see how it goes.

Looks like a win all around @karim, good stuff. :smile:

**Comment by justinclift** [comment] 2018-11-29 04:47
@Bilge @SilvioGrosso Would you have time to try the new Win64 (msi) nightly build?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi

That one installs the math extension file (`math.dll`) to an `extension` folder inside the standard DB4S installation.  It still needs manually adding into DB4S via the GUI, but some people verifying it works as expected - or letting us know it doesn't - will be useful. :smile:

**Comment by justinclift** [comment] 2018-11-29 04:56
@struck89 Same as above comment if you're still into this stuff. :smile:

**Comment by justinclift** [comment] 2018-11-29 05:51
Sure, as long as they compile ok we might as well add them. :smile:

With the Win32 build, the build + zipping seems to have worked ok, but the uploading went weird.  Not sure why, but investigating now.

**Comment by justinclift** [comment] 2018-11-29 06:03
The build system weirdness was just a one-off, due to some left over stuff on the VM hanging around from previous testing earlier in the day.  Now cleaned up and fixed.

Win32 msi with the math extension included is here:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.msi

**Comment by SilvioGrosso** [comment] 2018-11-29 07:05
Hello everyone,

Just tested the 2 new installers with the math extension (.ddl) included, on Windows 10 (64 bit).
In essence, I have tried both versions (32 bit and 64 bit).
They both work fine.
More precisely:
- After installing them, I have tested the function stdev (standard deviation) on my column containing numbers and an error pops up (which was to be expected);
- To get this new function (stdev) working, as suggested, I have loaded the .ddl (math) through the GUIs and thanks to the new extenstion the stdev started to work.

Here is a video with all my steps (Windows 10 - 64 installer):
https://www.dropbox.com/s/o8etqwyywtm3rvf/MATH_EXTENSION.mp4?dl=0

BTW, I have also tested the remove option from the new installer and this option works fine as well (it removes correctly the previous installation) :-)

**Comment by justinclift** [comment] 2018-11-29 10:21
> It would definitely be preferably to have the extension loaded automatically rather than load it manually each time.

In theory (haven't tested it myself yet), there's a tab in our Preferences dialog for telling DB4S about extensions to be loaded automatically when DB4S loads.  If `math.dll` gets added there, it should be loaded automatically.

That being said, now that it's being provided on Windows anyway it would make sense to somehow pre-fill that in.  Not real sure on the right way of doing that though.  @MKleusberg @mgrojo ideas? :smile:

**Comment by chrisjlocke** [comment] 2018-11-29 10:21
Quick question.  This is linked more to the installer than the math extension, but as a bit of the above conversation was about the installer, I thought I'd ask here.  

We're now bundling DB4S and DB4S+SqlCipher together.  However, the 'shortcuts' page on the installer is a bit misleading?

![image](https://user-images.githubusercontent.com/7872218/49214991-af4a8600-f3bf-11e8-92c7-1b29ce071760.png)

A shortcut to 'SQLite' isn't created, but the 'normal' DB4S.  The explanation of SQLite would imply we're creating a shortcut to SQLite itself - it doesn't mention DB4S.  

![image](https://user-images.githubusercontent.com/7872218/49215249-47486f80-f3c0-11e8-8f44-38e467cfb580.png)

Being nitpicky here, but we're not installing an extension - its a full blown application - it just happens to have the extension baked into it.  If I was a noob user, I'd be a bit confused and wonder if I'd have to install the extension, etc....

**Comment by chrisjlocke** [comment] 2018-11-29 10:57
Suggestion:

Shortcuts should give two options.
"DB Browser for SQLite"
"DB Browser for SQLite (DB4S) is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite."  (stolen from the website, but the 'compatible with' line niggles me ... makes it sound like DB4S doesn't create 100% SQLite databases - just ones that happen to be compatible with SQLite... its own format of files)

"DB Browser for SQLite with SQLCipher"
"SQLCipher is an open source extension to SQLite that provides transparent 256-bit AES encryption of database files.  DB4S with SQLCipher has the SQLCipher extension integrated into it, available from the Tools menu option."

Unsure if "DB Browser for SQLite with SQLCipher" will fit in the tree - don't know if scrollbars appear?

**Comment by justinclift** [comment] 2018-11-29 11:41
> "DB Browser for SQLite" - "DB Browser for SQLite (DB4S) is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite." (stolen from the website, but the 'compatible with' line niggles me ... makes it sound like DB4S doesn't create 100% SQLite databases - just ones that happen to be compatible with SQLite... its own format of files)

Maybe:

    "DB Browser for SQLite (DB4S) is a high quality, visual, open source tool to create, design,
    and edit SQLite database files."

> "DB Browser for SQLite with SQLCipher" - "SQLCipher is an open source extension to SQLite that provides transparent 256-bit AES encryption of database files. DB4S with SQLCipher has the SQLCipher extension integrated into it, available from the Tools menu option."

Maybe:

    "DB4S with SQLCipher has the SQLCipher extension integrated into it, providing 256-bit AES
    encryption (strong!) of SQLite database files."

> "DB Browser for SQLite with SQLCipher"

Ewww.  Just no. :stuck_out_tongue_winking_eye:

**Comment by justinclift** [comment] 2018-12-04 00:08
Hmmm, I wonder...

@karim is updating the installer on Windows at the moment.  It would be kind of nifty to have some part of that be a dialog with a list of extensions to install/enable (with everything selected?).

### Extensions to install
- [ ] math
- [ ] SpatiaLite
- [ ] (etc)

I wonder if we could automatically enable whichever ones the user chooses?  The settings DB4S uses for that Preferences tab (listing extensions to automatically load) are probably stored in the registry.

It makes sense (to me) that msi installers would have some ability to manipulate registry entries.  If we can have the msi installer make the changes directly, mimic-ing the exact same way DB4S does it, then it should be transparent to the user and "it just works" (from the user point of view).

Thoughts? :smile:

**Comment by karim** [comment] 2018-12-04 11:29
> It would work on Windows, but was about other OSes?

Chris is right. What works for Windows will not work for other OSes.

> It makes sense (to me) that msi installers would have some ability to manipulate registry entries.

Yes, it is possible, but what we can do with the msi installer will not work on anything other than Windows. Even if you are on Windows but using the .zip file and not the installer, then you will be left out as well.

I suggest moving the logic to load the extensions to the application itself.

Extensions now are dropped in `extensions` folder next to the application. On startup, DB4S should look in that folder and load the .dlls from there.

The msi installer will not put any extension/.dll there if the user deselect it during installation anyway. And if you are using the .zip version you can simply load extensions by moving them to extensions folder.

If you no longer wishes to use an extension, simply move it out of this folder or delete it.

This will work with every OS and with the portable/.zip version too.

**Comment by chrisjlocke** [comment] 2018-12-04 11:32
> Extensions now are dropped in extensions folder next to the application. On startup, DB4S should look in that folder and load the .dlls from there.

That would work well.

**Comment by justinclift** [comment] 2018-12-04 13:48
> > It would work on Windows, but was about other OSes?
>
> Chris is right. What works for Windows will not work for other OSes.

The other OS's already have completely different installation methods.  Let's not get distracted by "other OS's" for the Windows installer? :wink:

> I suggest moving the logic to load the extensions to the application itself.
> 
> Extensions now are dropped in extensions folder next to the application. On startup, DB4S should look in that folder and load the .dlls from there.

Sounds like a decent initial idea to me.  If the user decides they **don't** want the extension automatically loaded every time, they'll need to move the extension .dll to a different folder.  That shouldn't be too hard and (hoping here) it would be an edge case anyway.

We might want to do some basic sanity checking of the .dll too, now I come to think about it.  eg make sure having it autoload doesn't significantly slow things down / take more memory / etc.

I'm thinking "it shouldn't", but lets take a quick look at some Task Manager memory use figures to make sure.  @chrisjlocke That sounds like your kind of thing, if you're up for it? (shouldn't take long anyway?)

**Comment by justinclift** [comment] 2018-12-04 13:49
> Someone somewhere is going to report, "DB4S crashes when I start it up..." and we'll be hunting high and low, ripping bits out of the code, until we realise its a wacky extension running at startup....

Good point.  It'd probably also simplify how people install extensions too. :smile:

**Comment by karim** [comment] 2018-12-04 14:47
> The other OS's already have completely different installation methods. Let's not get distracted by "other OS's" for the Windows installer? :wink:

My point is to be consistent. DB4S should have a place to *auto load* extensions from. In Windows this will be `extensions` folder right next to the .exe. In other OSes this could be something different.

If someone wanted to use an extension, on whatever OS, we can simply tell the user to put it *there* and it will be loaded on the next run.

If the user want to load an extension randomly from somewhere else on the file system (network drive, shared folder, etc), then `Edit > Preferences > Extensions` is the right place.

In both methods above, if loading the extension failed or crashed the application (wrong arch, 32-bit dll in a 64-bit installation), the user will get an instant feedback that this is caused by the extension.

**Comment by chrisjlocke** [comment] 2018-12-04 14:47
> Would need some sort of log though. Someone somewhere is going to report, "DB4S crashes when I start it up..." 

Maybe on the 'About' screen it could list the extensions currently loaded?  We're still going to have to ask when troubleshooting an 'crash at startup' issue, but at least for newbies, it'll stop the "how do I know if its loading an extension?" etc, or "how do I know its loaded it successfully?", etc.

**Comment by chrisjlocke** [comment] 2018-12-04 15:01
> I'm thinking "it shouldn't", but lets take a quick look at some Task Manager memory use figures to make sure. 

😆 
Windows isn't the best OS for this.  Start up DB4S.  21.2 MB.  Open a database.  Jumps to 27.2 MB just opening the 'browse for database' dialog.  Increases to 33 MB when I cancel that dialog.  After a bit (flipped back to Edge to look up something) and its dropped back down to 10.9 MB.  Windows is doing wacky things with the memory!  In typing the above, its increased to 14.7 MB and I haven't done anything.  Now 21 MB.  Loaded the extension and it hasn't moved.

Short answer (without fiddling some more) it'll have very little impact on performance.  Certainly takes microseconds to load, etc.

**Comment by justinclift** [comment] 2018-12-04 15:11
Cool, that's probably all we needed to check, just to be on the safe side. :smile:

**Comment by justinclift** [comment] 2018-12-13 21:15
Excellent.  Just updated the [3.11.0-beta3 release info](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-beta3) with a pointer to it.

> BTW, feel free to ask for other video tutorials in case you need them...

Cool.  That would be really welcome.  Any interest in maybe setting up some kind of official DB4S channel for them on YouTube and getting stuff created there? :smile:

> ... my British pronunciation sucks (I am an Italian guy).

Yeah, I'm an Aussie.  My (spoken) English tends to have swear words in it. :angel:

**Comment by SilvioGrosso** [comment] 2018-12-14 16:12
Hello @justinclift 

> Any interest in maybe setting up some kind of official DB4S channel for them on YouTube and getting stuff created there?

Sure. No problem at all.

At present, I am waiting for the stable version to be released in order to ascertain what features I can show in my video tutorials.
For instance, many latest addition as "the uncomment code button",  in the Execute SQL tab, are not available in the 3° beta. They are present in the nightly builds for future releases :-)

**Comment by justinclift** [comment] 2019-01-19 02:54
Noticed something with our Windows build batch files today.  The maths extension for them is only being included with the SQLite builds, not the SQLCipher ones.

We should probably get it added to the SQLCipher ones too.

**Comment by karim** [comment] 2019-01-19 11:54
>  The maths extension for them is only being included with the SQLite builds, not the SQLCipher ones.

Since both SQLite and SQLCipher are included together, did you mean built against SQLite and not SQLCipher?

I don't think that's necessary. The same .dll works for both SQLite and SQLCipher. Just tested it to confirm.

It is just being built *after* SQLite in the build batch files, but it doesn't have to be. The reason is that it needs `sqlite3ext.h` header file to get the names of some of the required function, like `sqlite3_load_extension`. These functions exist in SQLite and SQLCipher.

We build SQLite first, then move the extension .c/.def to the same folder (where `sqlite3ext.h` exist) and build there. We can also build it first, before SQLite and SQLCipher, by copying `sqlite3ext.h` file, from either, to its folder.

**Comment by justinclift** [comment] 2019-01-19 13:41
Thanks @karim.  Yep, that was me forgetting we only need it built once, as both .exe's get installed in the same place.

I'd probably just been faked out by looking through the macOS stuff before it, as that still needs to build both SQLite and SQLCipher completely separately. :smile:

So yeah, the math extension on Win is fine as-is.  My bad. :innocent:

**Comment by karim** [comment] 2019-01-19 16:21
No worries. :smile: 

Should we close this issue or wait till the 3.11 release?

**Comment by justinclift** [comment] 2019-01-19 23:22
Ahh yeah.  Closing it. :smile:

**Closed by justinclift** 2019-01-19 23:22 UTC
Labels: enhancement, sqlite-extension
