### ISSUE TITLE
Export with delimiter "

### ISSUE THREAD

**Issue by jhillmannco** [sqlitebrowser/sqlitebrowser#1544] opened 2018-09-28 08:40 UTC
When using Export Table as CSV-File und using Field - Seperator '|' and the delimiter " then Export will not have the delimiter in its Export file !

**Comment by justinclift** [comment] 2018-09-28 09:08
Oh, that's not supposed to happen.

Hmmm, which version is that with, and would you be ok to screenshot the export settings used so we can double check things look ok?

**Comment by jhillmannco** [comment] 2018-09-28 09:41
![sqlite](https://user-images.githubusercontent.com/20331756/46201030-6fa9e400-c313-11e8-9ba0-86ce5fa70d1e.png)

**Comment by jhillmannco** [comment] 2018-09-28 09:42
Version 3.8.0

Qt Version 5.5.1

SQLite Version 3.9.2

**Comment by justinclift** [comment] 2018-09-28 09:58
Thanks @jhillmannco.  Yep, it looks like you're doing the right things, and it's just a straightforward bug instead of something weird.

A couple of thoughts spring to mind.  Version 3.8.0 is pretty ancient, and even our most recent full release (3.10.1) is getting pretty long in the tooth now.

Would you be ok to grab the latest nightly build and try with that?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

In theory, that should work fine as we've done a lot of stuff for CSV import/export over the last few years. :smile:

**Comment by jhillmannco** [comment] 2018-09-28 11:16
Problem still not solved !

Version 3.10.99 (Sep 28 2018)
Qt-Version 5.7.1
SQLite-Version 3.25.1

**Comment by justinclift** [comment] 2018-09-28 12:45
Oh wow.  That's definitely not good.

Hmmm.  I've just tried it here with [this database](https://dbhub.io/nicva/Assembly%20Election%202017.sqlite).

If I export the `Candidate_Information` table to CSV, with the quote character set to `"`... in the resulting .csv file the fields aren't enclosed in quotes.

@MKleusberg @mgrojo @chrisjlocke Am I forgetting something obvious here?

**Comment by chrisjlocke** [comment] 2018-09-28 13:48
Nope.  I've even used 'other' and set it to pound signs, dollars, and the letter R.  Nothing.  
Tried a couple of other variations (in case it was something like new line option causing a problem) but can't seem to get field quotes out at all.

**Comment by MKleusberg** [comment] 2018-09-28 13:52
We only add quote chars if they are needed, that is if the field contains a line break, a separator character or a quote. That's how CSV usually works and how e.g. LibreOffice is doing it as well (but they added an option to always quote everything), same for Excel if I remember correctly.

**Comment by chrisjlocke** [comment] 2018-09-28 13:54
Well, if I set the line option to R, some fields are quoted

![image](https://user-images.githubusercontent.com/7872218/46212596-49de0880-c32e-11e8-87e6-31a0e311f50c.png)

Can't see a pattern - 'Jim Bowen' has a space in it, but no quotes, 'Sally Sparrow' has spaces and quotes, but 'Chris' has no spaces but quotes! 😕

**Comment by chrisjlocke** [comment] 2018-09-28 13:58
Aah, was getting confused and thinking quotes were put around with fields with spaces in them - ignore me!

**Comment by justinclift** [comment] 2018-09-28 14:12
Ahhh yeah, I was probably thinking the same too.

Um... @jhillmannco, it looks like we're only adding quotes where they needed (as per the CSV spec), and I'd just forgotten.

With the quotes not being on every field, what kind of problems is it causing?

**Comment by jhillmannco** [comment] 2018-10-01 07:10
The problem is when having lines without quotes systems like Excel making wrong entries !
![sqliteexcel](https://user-images.githubusercontent.com/20331756/46274475-e506f600-c559-11e8-8ef0-ea5e00a79ae8.png)

**Comment by chrisjlocke** [comment] 2018-10-01 08:56
Field2 has an ; after it.  Was this created by DB4S?  In my table exports, field names don't have an extra terminator?
If you remove this erroneous terminator, it should be OK?

**Comment by jhillmannco** [comment] 2018-10-01 09:14
no sorry this was an sample remove last ; in line 1 and result is the same (not OK !)

**Comment by justinclift** [comment] 2018-10-01 09:40
Yeah, the problem still isn't sinking into my head either. :smile:

With that screenshot, it looks like there should be a header row (with two fields), and then two rows following, also with two fields:

Field1 | Field2
-- | --
1 | 2
001 002 | 001 002

It kind of looks like what's in the CSV file?

Hmmm, that middle row (of the CSV file) has entries being converted from "001" to "1".

Is that the problem?

**Comment by chrisjlocke** [comment] 2018-10-01 09:51
Excel is a bitch though.  Even if you stick quotes around fields, it'll interpret them as numbers.

![image](https://user-images.githubusercontent.com/7872218/46281854-ce679b80-c567-11e8-9a5c-4f934dc9e542.png)

Numbers have to prefixed with an apostrophe (') to be forced as text.  Oh goodness - another export option.... 😆

**Comment by jhillmannco** [comment] 2018-10-01 11:27
Ok , this discussion is getting hot, but when i say in the Dialog delimited with " " then it should do that !
even MS ACCESS is able to do so, i will take a workaroud use Notepad++ und do a replace ' ;'  with ";" like i always do !

**Comment by chrisjlocke** [comment] 2018-10-01 13:00
Users having issues isn't good - especially if there is a fault with the software.  As Martin has pointed out though, its not 100% clear if there is an issue with the export though.  If you can post some data, the exported CSV (the outcome) and the CSV you envisaged it should be (the expected outcome).

**Comment by mgrojo** [comment] 2018-10-01 19:06
> Ok , this discussion is getting hot, but when i say in the Dialog delimited with " " then it should do that !
even MS ACCESS is able to do so, i will take a workaroud use Notepad++ und do a replace ' ;' with ";" like i always do !

We only use the quotes when it's needed: multi-line values, fields with quotes inside... We could quote everything but then, as demonstrated by @chrisjlocke, that wouldn't make any difference when the problem is importing 001 as a string into Excel. Is that actually your problem? Please, be specific so we can help you.

**Comment by jhillmannco** [comment] 2018-10-02 08:56
Suggestion and Solution:
only Fields that are based on Type Text should have the delimiters !

**Comment by chrisjlocke** [comment] 2018-10-02 09:19
I'm not sure that would actually be a solution.  Having said that, now I understand why some fields are quoted, I'm not sure there is actually even a problem.  
In Excel, there is a difference in opening a CSV file (which doesn't respect field types) or you can import a CSV file, which Excel then gives you a wizard, to set what data type is in each field.

![image](https://user-images.githubusercontent.com/7872218/46340183-a68e3b80-c62c-11e8-9f84-f5f444337df3.png)

**Comment by chrisjlocke** [comment] 2018-10-12 15:00
I'll close this, as this seems to be 'resolved' in a way .... 
@jhillmannco - feel free to comment further if you feel this issue should be reopened, but the export seems to be as expected.

**Closed by chrisjlocke** 2018-10-12 15:00 UTC
Labels: export, response requested
