### ISSUE TITLE
Says there is no unique data but there was only one duplicate

### ISSUE THREAD

**Issue by SimpleSamples** [sqlitebrowser/sqlitebrowser#1657] opened 2018-12-13 04:42 UTC
Details for the issue
--------------------

#### What did you do?
I had a table with data in it that I forgot to set a field to unique, so I tried to modify the table to add unique for the field.

#### What did you expect to see?
I expected it to just do it. But actually, there was one duplicate.

#### What did you see instead?
It said there were **no** unique data and that was not true. When I looked I found one duplicate and deleted one row and then I was able to modify the table.

The message saying there was no unique data was totally wrong. Most of the data was unique.

Useful extra information
-------------------------
> DB4S v3.10.100 (Oct 10 2018) on Windows 10 (10.0) (winnt/10.0.17134) [x86_64]
> using SQLCipher Version 3.4.1 (based on SQLite 3.15.2)
> and Qt 5.8.0

**Comment by justinclift** [comment] 2018-12-13 05:03
> The message saying there was no unique data was totally wrong. Most of the data was unique.

Ouch, that's not good.  We'll probably need to check if that happens in the general case, or if it was something unexpected to do with your database structure or data.

Do you happen to have a copy of the database still around, with the duplicate row that causes the error?  Checking just in case we can't duplicate the problem (haven't tried yet), it'll be useful to have some ability to trigger the problem + figure out the cause/solution. :smile:

**Comment by SimpleSamples** [comment] 2018-12-13 05:17
I have the data but not before I modified it. The data is not for public consumption. It is a very simple table with the three columns User, Priority and Comments, all text.

I can re-create the problem easily. My test DB is:

CREATE TABLE "SomeUniques" (
	"User"	TEXT,
	"Priority"	TEXT,
	"Comments"	TEXT
)

And with some data with one duplicate it complains when I try to add "Unique".

**Comment by justinclift** [comment] 2018-12-13 07:12
Interesting.  Does the same thing happen with the nightly build from a few hours ago?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by SimpleSamples** [comment] 2018-12-13 08:19
I installed DB.Browser.for.SQLite-win64.msi from that page. The About box for my DB Browser for SQLite says:

Version 3.11.99 (Dec 13 2018)
Qt Version 5.12.0
SQLite Version 3.26.

I hope that is the version you are hoping for. I get the same message with that.

**Comment by SimpleSamples** [comment] 2018-12-13 08:32
[DB Browser for SQLite - Album on Imgur](https://imgur.com/a/yQl1iU1)

**Comment by chrisjlocke** [comment] 2018-12-13 08:39
> I get this message when I click the "U" column for the "User" field.

But the data in that column isn't unique - you have two 'User2' records.  When you click 'Unique', it means ALL the data in that field for every record has to be unique, ie, no duplicates.
The usual recommended method is to add an 'id' field of an integer field, and set the 'primary key' checkbox.  This gives each row a sequential number, which will be unique.

**Comment by justinclift** [comment] 2018-12-13 09:35
Looking at that message, the wording could be improved:

> Column 'User' has no unique data.
> This makes it impossible to set this flag. Please change the table data first.

Something like this would probably be clearer:

> Column 'User' has duplicate data.
> This makes it impossible to enable the 'Unique' flag.  Please remove the duplicate data, which will allow this flag to be enabled.

Thoughts? :smile:

**Comment by SimpleSamples** [comment] 2018-12-13 17:39
Sorry, I thought I made it clear in my initial post. I said there was only one duplicate. So yes, it is just a matter of wording.

As for my table, the user id is unique. I don't want to support duplicates. I wanted to make the field unique so it would tell me if the user id exists in the table already.

**Comment by justinclift** [comment] 2018-12-13 19:52
No worries @SimpleSamples, it's probably just us reading this while being a bit rushed. :smile:

My suspicion here is the phrase "has no unique data" is probably a typo from "has non unique data".

Looking through our source code, this seems like it'll be easy to update:

https://github.com/sqlitebrowser/sqlitebrowser/blob/1af7b031ead6f60153f2b4e00b95dc55b4057479/src/EditTableDialog.cpp#L472-L473

@SimpleSamples @chrisjlocke Does my suggested wording sound reasonable to you?  If so, we can change it right away.

Translations of the updated strings won't happen immediately.  We do those in a batch just prior to our releases, but the English version would be fixed in our automatic nightly builds from here on. :smile:

**Comment by SimpleSamples** [comment] 2018-12-13 21:56
It seems very likely it was a typographical error.  I agree that changing it to "has non unique data" would work but to be more precise it should be "has non-unique data".

**Comment by chrisjlocke** [comment] 2018-12-13 22:59
"Column 'User' has duplicate data" makes more sense than "non unique data".

> Sorry, I thought I made it clear in my initial post. I said there was only one duplicate.

If you have any duplicate data, then you do not have unique data.  That is where the error dialog is coming from.  Are you suggesting that if your table has one duplicate record, it should still have allowed you to create the unique flag?  I get the fact the error could be better worded, but I'm not sure why this issue was raised.

**Comment by SimpleSamples** [comment] 2018-12-14 01:03
You are misquoting what was said then using that as proof. It says _**no** unique data_ and that is wrong.

No, I am not saying the unique option should have been allowed. You are making this into something hundreds of times bigger than it needs to be.

I am sorry for the trouble but this think exploded into something bigger than it needed to be.

**Comment by fomoruto** [comment] 2018-12-14 07:09
I vote for "has duplicate data..."
Regards 👍

**Comment by justinclift** [comment] 2018-12-14 07:17
Thanks @fomoruto. :smile:

**Comment by chrisjlocke** [comment] 2018-12-14 08:03
> It says no unique data and that is wrong.
> You are making this into something hundreds of times bigger than it needs to be.

Sorry.  I don't do programming on DB4S, so usually just troubleshoot users' problems and narrow down the cause, to help the proper people who do the proper work.
'No unique data' isn't wrong - your rows do not have unique data.  That is what I was trying to explain.  I won't comment further as the issue is resolved and will get corrected anyway, but if your rows have duplicate data (even one duplicate), its not unique.  It does not have unique data.  Thats what I was quoting, and is therefore correct.

This issue will remain open until the wording is amended, then @justinclift will ask you to confirm you're happy with the dialog, which will be available in a nightly build of DB4S.  

I know you think I'm going on, but again (as pointed out in another issue) I thank you for raising this issue which helps make DB4S better.  Thank you for your patience!

**Comment by justinclift** [comment] 2018-12-14 08:57
@SimpleSamples Ahhhh, now I get it.  Brain wise, I was just skipping over the hypen as not-being-relevant.  However, that's the bit you were trying to point out needs to be there.  `non-unique` (correct) vs `non unique` (incorrect).  Got it. :smile:

I'll tweak the wording in a minute.  Just finishing up some other stuff atm.

**Comment by justinclift** [comment] 2018-12-14 09:03
Just fixed the typo in 66c2ad10c0919f17d772aa6fb60bf36d993537d9.

Also applied the same fix to our `v3.11.x` branch, so the change will make it into our upcoming release.

Thanks heaps for reporting this @SimpleSamples, and sorry for us misunderstanding the hyphen problem. :smile:

**Closed by justinclift** 2018-12-14 09:03 UTC
