### ISSUE TITLE
Paging arrows issue

### ISSUE THREAD

**Issue by harrisrap** [sqlitebrowser/sqlitebrowser#232] opened 2015-03-19 12:27 UTC
There are some issues with the paging arrows in the bottom left.  One thing is just a little confusing at first.  You are doing something that is not typical UI.  I've never seen software that lets you scroll, and also tells you which lines are being displayed in just the viewable window, and also lets you page through the scrollable view.  Once I figured out what was going on, it is actually pretty cool.  But then I found that if I change the window size, then use those paging arrows, they don't give me correct results.  They seem to skip large amounts of records.  I would suggest first, of course, to fix that errant behaviour.  And then maybe add the word 'Viewing' before the range of rows displayed, or something to make it clear the user can either scroll to see more records, or use the arrows to jump scroll.

**Comment by justinclift** [comment] 2015-03-19 16:17
Interesting.  I'll try this out after work to get a better idea what you mean, although I kind of think I know already. :smile:

Which version of DB4S and OS are you using btw?

**Comment by harrisrap** [comment] 2015-03-19 16:20
V3.5.1
OSX Yosemite 10.10.2

**Comment by justinclift** [comment] 2015-03-19 16:21
Cool. :smile:

**Comment by samir-aguiar** [comment] 2015-03-19 16:31
I think it might be a OS X thing, because I couldn't reproduce on Fedora. Will try on OS X when I get home as well. :)

**Comment by justinclift** [comment] 2015-03-19 23:38
On OSX 10.9 here, and I'm trying it out now.  It seems to be **trying** to page through results by 100 at a time, but getting it wrong for the first page worth.  Here's an example... I've resized the window to just show the first 10 results:
![screen shot 2015-03-19 at 23 31 43](https://cloud.githubusercontent.com/assets/406299/6743317/258c7d72-ce90-11e4-97b0-b17ab6efab07.png)
Now I click the single > right arrow:
![screen shot 2015-03-19 at 23 32 37](https://cloud.githubusercontent.com/assets/406299/6743326/45b9dedc-ce90-11e4-80e6-fdf4959d9e42.png)
Then I click it again:
![screen shot 2015-03-19 at 23 33 22](https://cloud.githubusercontent.com/assets/406299/6743335/5b8c9bc8-ce90-11e4-987f-3fe791331e57.png)
And again:
![screen shot 2015-03-19 at 23 34 16](https://cloud.githubusercontent.com/assets/406299/6743345/7bbd6940-ce90-11e4-832c-a6fe02097e4f.png)
Next I make the window a bit bigger, and click the single > again:
![screen shot 2015-03-19 at 23 34 58](https://cloud.githubusercontent.com/assets/406299/6743360/a02162fa-ce90-11e4-8f87-7e7de583706a.png)
Interestingly, the cursor is (I guess correctly) placed on row 1, then 101, then 201, then 301, then 401.  I think it's just the window positioning (eg not 101-110, 201-210), which is making it look really inconsistent.

Thoughts?

**Comment by samir-aguiar** [comment] 2015-03-22 20:53
Yeah, the buttons are supposed to scroll 100 records up/downwards, no matter the size of the window. So if the window is very small, it will appear to skip a lot of records, but it's just moving the selection by 100 records.

**Comment by justinclift** [comment] 2015-03-22 21:02
Are we able to control the positioning of the cursor in the window, so the cursor keeps it's current position in the window?  eg if it's on the first row when the arrow is pressed, the new window still has it on the first row

Kinda thinking it might be tricky, but then again I don't know Qt. :wink:

**Comment by justinclift** [comment] 2017-05-07 12:57
Ahhh, so the correct approach here is probably to determine how many rows are visible in the Browse Data tab, then have the next/previous pagination buttons move by that value.

Changing the size of the window would change that too of course.

**Comment by MKleusberg** [comment] 2017-05-08 10:09
Just tried to implement the pagewise scrolling. But I think it needs some more testing.

Also, the code for calculating the number of currently visible rows if off by one for me, and thus is the page-wise scrolling. Does anybody else have this issue, too? You can check by looking at the row numbers at the bottom of the window and comparing them to the row numbers in the table view.

**Comment by justinclift** [comment] 2017-05-17 08:46
Trying this out here on OSX, and it's a lot better now than the previous step-by-100 behaviour. :smile:

The "off-by-one" thing could be kind of annoying though. 😕 
![screen shot 2017-05-17 at 09 39 03](https://cloud.githubusercontent.com/assets/406299/26145610/f3f949e8-3ae4-11e7-9e33-74df62a71d95.png)
![screen shot 2017-05-17 at 09 38 52](https://cloud.githubusercontent.com/assets/406299/26145616/f7ba09a0-3ae4-11e7-9dd4-084ea4d44323.png)
![screen shot 2017-05-17 at 09 42 31](https://cloud.githubusercontent.com/assets/406299/26145751/8560e90e-3ae5-11e7-80f3-8d961978dee8.png)

Wonder if this is a Qt bug more than a DB4S bug?

**Comment by MKleusberg** [comment] 2017-05-17 09:58
Actually, it looks a lot better on your system than on mine. In your case it's (as far as I can see) just that we're counting the last "visible" row even if it's just one pixel high. That doesn't make a lot of sense but there's not that much we can do about it because only counting fully visible rows is no alternative either. And only counting rows that are more than x % visible will always be messy because all possible values for x are arbitrary. On the other hand we can play around with this and test it. But...
On my system when I resize the window, the row number at the bottom changes when about half of the row is visible. I have no idea why it does this because it's not in our code and it didn't use to be like this. Might be a Qt thing or a Qt platform specific thing. Also, I get an extra +1 on the number of the last visible row. So e.g. in your last screenshot I'd see 44793. So no matter how I resize the window it's always wrong :frowning:

**Comment by justinclift** [comment] 2017-05-17 10:11
Wow, that's weird.  Sounds like we need to intercept the event handler on Linux that changes the row counter, and stop the +1 behaviour.

**Comment by MKleusberg** [comment] 2017-05-17 10:21
But we'd need to know when exactly it's happening. The problem seems to be that our ```ExtendedTableWidget::numVisibleRows()``` method returns the wrong value which probably means that Qt's ```rowAt()``` returns a wrong value. But as this only happens on some platforms and with some Qt versions it's going to be hard to fix it...

**Comment by justinclift** [comment] 2017-05-17 10:42
Gah. ☹️

**Comment by MKleusberg** [comment] 2020-02-13 12:30
Closing this because the original issue has been solved years ago. The inaccuracy pointed out by @justinclift has been dealt with just now. I'd suggest opening a new issue for this if it turns out it's not working as expected :smile:

**Closed by MKleusberg** 2020-02-13 12:30 UTC
Labels: bug
