### ISSUE TITLE
SQL Logic Error when attempting to change SQLCipher password

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#1690] opened 2018-12-26 21:22 UTC
Opened an encrypted database and then clicked on Set Encryption to change the password

![set encryption](https://user-images.githubusercontent.com/6769116/50457560-3c97e080-0954-11e9-8e5b-47d1f880bd30.jpg)

When I clicked OK I got the following error

![logic error](https://user-images.githubusercontent.com/6769116/50457571-4f121a00-0954-11e9-989f-e21f598a4eeb.jpg)

Windows 10 latest
DB4S - 3.11.99 (SQLCipher)

**Comment by mtissington** [comment] 2018-12-27 08:31
Why is sqlcipher_export being used to change the password?

According to [sqlcipher api](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_default_page_size)
`PRAGMA rekey` is all that is required.

**Comment by chrisjlocke** [comment] 2018-12-27 09:59
Related to this (but I guess should ideally be a separate issue) if 'Tools' and 'Set Encryption' is successfully run (using an older nightly) there is nothing logged in the application 'log' window.
```
PRAGMA foreign_keys = '1';
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA encoding
```
After opening a database then encrypting it, that was all that was in the sql log.

**Comment by chrisjlocke** [comment] 2018-12-27 10:10
> Why is sqlcipher_export being used to change the password?

Very much like the 'Modify Structure' dialog, the 'Set Encryption' (and change password, which uses the same code) creates a new database using the new settings, then copies all the data, renames the databases, then deletes the old database.

The error in question is happening [here](https://github.com/sqlitebrowser/sqlitebrowser/blob/6425fb177eba293ae000415392d088af96e27c91/src/MainWindow.cpp#L3044) but I don't know enough to know why its suddenly doing it.  Looking back to a working version, that code hasn't changed.

**Comment by MKleusberg** [comment] 2018-12-27 10:18
That's weird - it's working fine for me. But I'm still using SQLCipher 3.4 instead of 4.0. Can somebody check with 3.4 and with 4.0?

The reason we use ```sqlcipher_export``` is mainly for simplicity because we need to support the current approach either way while the ```rekey``` approach is an optional optimisation. That said, we should probably add that some time :wink: Can you open a separate issue for that? :smile:

**Comment by mtissington** [comment] 2018-12-27 11:04
I get the same error when I start with a NON encrypted database and then try to encrypt it (either with 3.4 or 4)

**Comment by chrisjlocke** [comment] 2018-12-27 12:59
That's the process I tried initially.  Theoretically its doing the same thing - creating an encrypted database, moving the data, then deleting the original.

**Comment by justinclift** [comment] 2018-12-28 21:53
@MKleusberg Looking at the code that error message comes from:

https://github.com/sqlitebrowser/sqlitebrowser/blob/1925ccfd37bea327683a6704de625e47dc260cf4/src/MainWindow.cpp#L3059-L3080

The specific string shown in the dialog isn't inside a `QString()` call, unlike the sibling SQL statement around it.  Is there any way that could be leading things astray? :smile:

The other possibility that comes to mind, is that since it's a `SELECT` it'll be returning a value.  The other statements around it are ones which don't always return a value, so maybe it's a case of `executeSQL()` not being the right function call for running it?

**Comment by mtissington** [comment] 2018-12-29 14:56
I just replaced sqlcipher.dll with a version I had build against OpenSSL 1.1.1a (also need libcrypto-1_1)
and I get exactly the same issue. But everything else seems to still work.

**Comment by mtissington** [comment] 2018-12-31 09:20
I don't know if this is related but when I try the following in DB4S the ATTACH fails saying it can't find the database instead of creating a new one. When I do the same in sqlcipher.exe it works correctly.

First I create a new empty database then in a SQL window

`ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'testkey';
SELECT sqlcipher_export('encrypted');
DETACH DATABASE encrypted;`

**Comment by justinclift** [comment] 2018-12-31 09:49
This one sounds like it'll need some special effort to debug.  Probably need to replicate the problem, and attach a debugger to it in order to step through the code as the bug occurs.

* Setup a working dev environment (Qt Creator) on Windows, with Qt 5.11.3, SQLCipher 4.0.1.
* Build DB4S in debug mode
* Step through the problem code

Technically I could do it, however I'm presently knocking myself out (not literally) getting new online infrastructure + monitoring set up for it.  That's probably more important than this, at least for the moment.

**Comment by chrisjlocke** [comment] 2018-12-31 10:32
@mtissington - what version of DB4S?  I'm using the nightly from 28 Dec, and that works fine.

![image](https://user-images.githubusercontent.com/7872218/50558569-63a13a00-0ce7-11e9-9948-2370de9a9d38.png)

**Comment by chrisjlocke** [comment] 2018-12-31 10:37
Quick thought.  You're not setting a path for the database, so its trying to store it where the .exe lives.  Is yours in c:\program files? 
Mind you, just tried that myself and that seems to work OK too.

**Comment by mtissington** [comment] 2018-12-31 12:45
@chrisjlocke your test is not quite the same, I have `Key 'testKey'` on the end ..

**Comment by chrisjlocke** [comment] 2018-12-31 12:48
Isn't that what the second screenshot shows? 😕

**Comment by mtissington** [comment] 2018-12-31 12:51
oops, my bad 😕

**Comment by chrisjlocke** [comment] 2018-12-31 12:56
Well, how weird.  NOW it fails.

![image](https://user-images.githubusercontent.com/7872218/50560692-45453980-0cfb-11e9-8bde-a4dc7b4ffeac.png)

Can you try 'fresh' from starting DB4S? I started DB4S and it worked.  Now I've flipped from tab to tab and played with it for a bit, its broken.  Just got to work out what it is...

**Comment by mtissington** [comment] 2018-12-31 12:58
Glad that's it's not just me ... so far I can't get it to work.
I do start with a new database.

**Comment by chrisjlocke** [comment] 2018-12-31 13:03
Sorry, I meant closing DB4S and restarting it - I'm guessing some internal flag is stuck somewhere, or its got its widgets in a mess.

**Comment by chrisjlocke** [comment] 2018-12-31 13:06
> First I create a new empty database 

Where is your new database stored?  On your desktop, or somewhere else?  Seems if the database is on a network (at least from initial testing) I get this error.

**Comment by mtissington** [comment] 2018-12-31 13:10
The database is stored on my Desktop.
I've tried it when creating a new database or when opening a plaintext database.
It never works for me.

**Comment by mtissington** [comment] 2018-12-31 13:19
OK, I have managed to get a database attached ... but then I immediately try to detach the database using `DETACH DATABASE name` and I get an error that it's locked .....

**Comment by mtissington** [comment] 2018-12-31 13:33
@justinclift  just tried build 3.11.99 (31 Dec) and I still get a lock error.

**Comment by justinclift** [comment] 2018-12-31 15:07
Gah.  :frowning:

**Comment by user20190106** [comment] 2019-01-08 14:44
I also get the same SQL logic error if I compile DB Browser for SQLite with a SQLCipher 4.0.1 build I did myself. But if I encrypt the database using the SQLCipher command line interface, I can then use it with DB Browser without problems.

But if I compile DB Browser with the standard Debian Stretch SQLCipher packages (v.3.2.0), encrypting with DB Browser works.

**Comment by chrisjlocke** [comment] 2019-01-08 17:55
> and I get an error that it's locked .....

Its not still copying the data in the background is it?  DB4S is using a lot of background threads now...
(Just clutching at straws....!!)

**Comment by justinclift** [comment] 2019-02-12 04:18
@mtissington Initial builds with a fix (that worked for me) are online as of about an hour ago:

Win32 builds:

* https://nightlies.sqlitebrowser.org/win32-onceoffs/DB.Browser.for.SQLite-issue1732v1-win32.msi
* https://nightlies.sqlitebrowser.org/win32-onceoffs/DB.Browser.for.SQLite-issue1732v1-win32.zip

Win64 builds:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v1-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v1-win64.zip

Tracking this problem in #1732 although it's really a duplicate of this one. :wink:

**Comment by mtissington** [comment] 2019-02-12 04:24
thanks - I'll let you know ...

**Comment by justinclift** [comment] 2019-02-12 12:19
Updated Win64 builds:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v2-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v2-win64.zip

**Comment by mtissington** [comment] 2019-02-12 18:46
Hmm, so I installed 1732v1 and now when I attempt to install v2 it says a later version is already installed.

**Comment by justinclift** [comment] 2019-02-12 23:25
@mtissington Yeah, I dumbly made the v1 builds based off of our `master` branch (effectively 3.12.x development code).  For the v2, realised it would be better built from the same code as the 3.11.1 release, so did that.  Thus the complaining from it that v1 (3.12.x) is newer. :wink:

@chrisjlocke Good idea. :smile:

**Comment by mtissington** [comment] 2019-02-12 23:37
how do this differ to the nightly?

**Comment by justinclift** [comment] 2019-02-12 23:50
The nightly is also built from the `master` branch.  The v1 was (quite literally) nightly + likely fix applied.

The v2 was an updated (slightly tweaked for future compatibility) fix, but applied to the v3.11.x code base instead.

**Comment by MKleusberg** [comment] 2019-08-10 13:25
I think we fixed this issue some time ago. Can you give the last nightly build a try, @mtissington? :smile:

**Comment by mtissington** [comment] 2019-08-10 18:41
fixed a while back and confirmed still fixed 😄

**Comment by MKleusberg** [comment] 2019-08-11 10:24
Awesome! Thank you for confirming :smile:

**Closed by MKleusberg** 2019-08-11 10:24 UTC
Labels: SQLCipher, bug, response requested
