### ISSUE TITLE
not minimizing

### ISSUE THREAD

**Issue by sandip3dec** [sqlitebrowser/sqlitebrowser#1318] opened 2018-02-14 11:08 UTC
### Details for the issue

it is not minimizing the app.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2018-02-14 14:45
As a complete guess from the title :wink:, this could be a duplicate of #934.

@sandip3dec If that'st he case, the fix is to use a nightly build (as @chrisjlocke mentioned) or build DB4S from our latest source code. :smile:

**Comment by justinclift** [comment] 2018-02-16 14:07
@sandip3dec Did you solve this problem? :smile:

**Comment by sandip3dec** [comment] 2018-02-21 11:32
yes thanx.

**Comment by chrisjlocke** [comment] 2018-02-21 11:43
Excellent!

**Closed by chrisjlocke** 2018-02-21 11:43 UTC
