### ISSUE TITLE
[Bug]: Tiny icons for UI elements in 3.13.0-rc1 on Windows

### ISSUE THREAD

**Issue by amine-aboufirass** [sqlitebrowser/sqlitebrowser#3684] opened 2024-07-14 16:49 UTC
### What did you do?

I just installed the latest release from [here](https://sqlitebrowser.org/dl/) using the standard 64 bit installer for windows

### What did you expect to see?

Regularly sized icons for the various UI elements in the app

### What did you see instead?

Tiny icons for the various UI elements in the app

![image](https://github.com/user-attachments/assets/230555d7-07c2-4825-b3eb-efc85f7a4559)

### DB4S Version

3.13.0-rc1

### What OS are you seeing the problem on?

Windows

### OS version

Microsoft Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment] 2024-07-14 18:27
Oh wow, that looks kind of strange.

I'm kind of wondering if it might be some kind of incorrect handling in our code for your monitor's dpi setting.  I don't suppose your monitor is a HiDPI model of some sort?

**Comment by justinclift** [comment] 2024-07-14 23:15
No worries.  That does sound like it might be a HiDPI issue of some sort.

**Comment by justinclift** [comment] 2024-07-16 12:09
Oops, sorry I got distracted.  I'd give the solution here a go and see if that fixes things:

https://github.com/sqlitebrowser/sqlitebrowser/issues/2305#issuecomment-652221799

It's *probably* something to do with the HiDPI handing in the graphical toolkit we use (Qt5).

That toolkit has a few environment variables which can be set to adjust it's way of operating.

So, some experimentation can be needed because what works for one person might not work for the next person (etc).  It's kind of a pain. :frowning:

**Comment by lucydodo** [comment] 2024-07-17 00:07
By any chance, can you tell us the UI scale set in Windows? I'm in the same environment* and can't reproduce the issue.
Please see the following link for instructions on how to check the UI scale value:
https://community.microcenter.com/kb/articles/746-how-to-adjust-display-scaling-in-windows-11

> *: 3840*2160 and 200% UI Scale

**Comment by vlakoff** [comment] 2024-07-23 09:51
I am also using a 3840x2160 monitor, I have tried DB4S 3.13.0 on Windows 10 22H2 with various font scaling values, and I did not encounter this issue.

**Comment by lucydodo** [comment] 2024-08-27 16:47
Hi @amine-aboufirass, This issue will be resolved by the 2c50024435b510e70f89e7ff38c46c543b8533b5 commit.
Could you please check it out and let us know? You can download a binary with this change [here](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous). :)

**Comment by vlakoff** [comment] 2024-08-28 21:29
> I am also using a 3840x2160 monitor, I have tried DB4S 3.13.0 on Windows 10 22H2 with various font scaling values, and I did not encounter this issue.

I have compared the latest release (3.13.0) with the very latest binary:

* Previously, my icons had correct sizes (contrarily to what [amine-aboufirass](https://github.com/amine-aboufirass) was encountering), but upon further inspection, they were quite pixelated, as if they were upscaled using some low-quality [nearest-neighbor interpolation](https://en.wikipedia.org/wiki/Image_scaling#Nearest-neighbor_interpolation).
* Now, the icons are slightly larger, but more importantly, they are now very sharp and clear. Which is a great thing.

<br>Using a 4K monitor with 150% font scaling, screenshots for comparison (click to expand):

version 3.13.0:
![1 - version 3 13 0](https://github.com/user-attachments/assets/87e38c7b-3c14-4557-8520-8d68f2158cef)

latest binary:
![2 - latest binary](https://github.com/user-attachments/assets/0297c8b3-6f66-48c8-ad9a-1efd53a2c78d)

**Comment by justinclift** [comment] 2024-08-29 02:02
Awesome, sounds like the change makes a good difference. :smile:

**Comment by lucydodo** [comment] 2024-08-29 09:00
As an aside, the font size looks (to me) too large after this patch was applied.
I changed the default value of 13 to 8 and it was just right. What do others think? 🤔

**Closed** 2024-10-19 04:35 UTC
