### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ghost** [sqlitebrowser/sqlitebrowser#615] opened 2016-05-30 08:48 UTC
Hi, I'm using your tool for many years, and it's always been my best choice in dealing with sqlite, but this last version crashes very often, especially if you run this app, change to another with ALT+TAB and then return  by the same keys with the SQLite Browser, app crashes...
Please fix that.

Thank you for your work!

**Comment by justinclift** [comment] 2016-05-30 12:10
Ahhh, that's not good.

Would you be ok to try the latest nightly build? (download locations are listed on our front page)

There have been a bunch of fixes in it since the last release, many of which deal with crash type things. :smile:

**Comment by chrisjlocke** [comment] 2016-06-07 07:59
Just a nod (either helpful or not...) that I've been using 3.8.99 (why don't nightlies have a specific version number?  Even 3.8.99.20160707? Just noticed x.99 is a generic version number) with no application crashes. The version I use every day is dated 26 Dec 2015 (so just after the main release... without the data cell popup) but just downloaded the latest nightly and couldn't replicate it in that either.  I'm using Win 10 64bit.

**Comment by jungle-boogie** [comment] 2016-06-07 15:05
I'm not able to reproduce the issue originally reported on windows 8.1. I'm using a nightly build from last week. I don't get a new nightly build unless there's any updates to the github source.

**Comment by justinclift** [comment] 2016-06-08 14:29
@ghost Have you had a chance to try the nightly build? :smile:

**Comment by justinclift** [comment] 2016-07-08 13:05
Closing this, as it's been a month since asking and no update from the original poster.

@ghost, if this still happens for you even with the latest nightly build, you're welcome to re-open this issue again.

**Closed by justinclift** 2016-07-08 13:05 UTC
