### ISSUE TITLE
COLLATE NOCASE not working

### ISSUE THREAD

**Issue by psmendyka** [sqlitebrowser/sqlitebrowser#2915] opened 2021-11-29 20:07 UTC
When using queries such as the example below COLLATE NOCASE is not being honored.  Entries such as f:\\FolDer1\\FOlder2\\ will not be updated.
`UPDATE Rule SET Statements = replace( Statements, 'F:\\Folder1\\Folder2\\' , '\\\\Folder3\\folder4\\Folder5\\') WHERE Statements like '%F:\\Folder1\\Folder2\%' COLLATE NOCASE;`

Thank you.

**Comment by chrisjlocke** [comment] 2021-11-29 20:56
Can you upload your database to dbhub.io (or email it to db4s-issue2915 [at] chrisjlocke [dot] co [dot] uk. 
This appears to work for me.
 
https://user-images.githubusercontent.com/7872218/143941607-997c96b5-8626-4535-95b3-89f123b9f869.mp4

**Comment by psmendyka** [comment] 2021-11-29 21:33
Unfortunately I can not provide the DB.

**Comment by chrisjlocke** [comment] 2021-11-30 11:46
No problem.  Can you replicate the above database?  Just one table, one field.  
I don't know what version of DB4S you're using and don't know what operating system you're using.
If you can provide these details, and ensure you're using the latest version (currently 3.12.2) that would be helpful.

Edit: 
Any reason why you're using REPLACE statements in the UPDATE statement rather than just plain SET ?  The REPLACE function is case sensitive, which may be why you're getting issues.  So it's not the COLLATE NOCASE that's not working, but the REPLACE.  
If you want to keep using REPLACE, then you'll have to change both the string and find_string parameters to lowercase (or uppercase...) to make it a case insensitive search.

**Comment by chrisjlocke** [comment] 2021-12-15 07:27
@psmendyka - Is this still an issue?  Have you managed to replicate the database as per my screencast to at least confirm if your version of DB4S is behaving OK?

**Comment by pete7628** [comment] 2023-12-30 08:20
I too have a COLLATE NOCASE problem.

The field "val" is 

**val       TEXT COLLATE NOCASE**

and the query is 

```
SELECT
    (SELECT val FROM table1 WHERE dn="kv" ORDER BY checkDate DESC LIMIT 1 OFFSET 0) =
    (SELECT val FROM table1 WHERE dn="kv" ORDER BY checkDate DESC LIMIT 1 OFFSET 1) AS AreLastTwoNsSame;

```
which compares the "val" of the last 2 records.

It fails for instance for "google" and "Google"

**Comment by chrisjlocke** [comment] 2023-12-30 09:20
What version of DB4S are you using?

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/0ef122c3-529c-412e-b1df-975f3af5738f)

I tried replicating this and worked OK.

If you want to email me your database at issue2915 [at] chrisjlocke.co.uk I'll have a look, just in case there is something obvious.

If you did a normal ```select * from table1 where dn = 'GOOGLE'``` does it display the 'google' and 'Google' records?
Note that you've put ```where dn = "kv"``` but thats the wrong quotation.  For strings, use single quotes, ie, ```where dn = 'kv'```
Double-quotes are used for field names that contain spaces, etc, so ```where "field 2" = 'wibble'```

I don't think thats the cause of your issue, but it helps to at least be correct.

**Comment by pete7628** [comment] 2023-12-30 09:34
Thanks Chris,

in your example you have used field2 twice, could it be that it makes it work ?

**Comment by chrisjlocke** [comment] 2023-12-30 11:14
No, thats just because my table only has one field.  
Oh, hang on though .. the field ```val``` has nocase (but it doesn't need to) but your comparing against ```dn``` - thats the field that should have nocase applied to it, as thats the field you're looking at.
The nocase means 'make a comparison case insensitive'.

**Comment by pete7628** [comment] 2023-12-30 11:48
Both fields are COLLATE NOCASE...

I also think that there are two string comparisons, one on dn and the other on val.

When I changed Google to google, it worked. This means that the trouble is with the val field.

**Comment by chrisjlocke** [comment] 2023-12-30 12:01
Aah, finally the penny dropped.  Sorry, took a while...

So yes, the first query might return 'google' and the second 'Google', but strictly they're not going to match.  Putting a 'nocase' constraint on the field isn't going to help here, as thats outside the point of where thats used.

You have two options.  One is to force both comparisons to lower case, so you're looking at like-for-like (pun intended) or use the actual LIKE keyword, which is already case insensitive, ie,

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/1c674b36-0df4-4028-b842-3d7fedce2b2f)


So using your original query

**Method 1**
```SELECT
    (SELECT lower(val) FROM table1 WHERE dn = 'kv' ORDER BY checkDate DESC LIMIT 1 OFFSET 0) =
    (SELECT lower(val) FROM table1 WHERE dn = 'kv' ORDER BY checkDate DESC LIMIT 1 OFFSET 1) AS AreLastTwoNsSame;```

**Method 2**
```SELECT
    (SELECT val FROM table1 WHERE dn = 'kv' ORDER BY checkDate DESC LIMIT 1 OFFSET 0) like
    (SELECT val FROM table1 WHERE dn = 'kv' ORDER BY checkDate DESC LIMIT 1 OFFSET 1) AS AreLastTwoNsSame;```

So you'd still need the nocase constraint on the dn field, because if you searched for 'KV', it wouldn't find records matching 'kv'.

The nocase constraints only work in explicit SQL statements and not within comparisons between subqueries.

**Comment by chrisjlocke** [comment] 2023-12-30 12:06
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/7b3089b8-271b-4a81-aef5-b187120f607b)

Just another fly in the ointment, but by default SQLite has a case insensitive LIKE, although this can be changed, so just check the pragmas tab.

**Comment by pete7628** [comment] 2023-12-30 12:06
Oh fantastic ! Thank you.

I would have never guessed it, but now it makes sense.

**Comment by chrisjlocke** [comment] 2023-12-30 12:09
You can of course use LOWER instead of nocase in the database.  

```
SELECT
    (SELECT lower(val) FROM table1 WHERE lower(dn) = 'kv' ORDER BY checkDate DESC LIMIT 1 OFFSET 0) =
    (SELECT lower(val) FROM table1 WHERE lower(dn) = 'kv' ORDER BY checkDate DESC LIMIT 1 OFFSET 1) AS AreLastTwoNsSame;
```

Of course, if 'kv' is derived from user input (eg, you were programming this) you'd also ensure this was lowercase, otherwise it could fail... (lower('hello') wouldn't match 'HELLO'....) but that may not be something important to you at this stage.

**Comment by chrisjlocke** [comment] 2023-12-30 12:12
Closing this issue as the original issue and now the related issue is resolved.

**Closed by chrisjlocke** 2023-12-30 12:12 UTC
Labels: SQLite fundamentals
