### ISSUE TITLE
Assertion when executing SQL queries - FreeBSD

### ISSUE THREAD

**Issue by clibc** [sqlitebrowser/sqlitebrowser#2655] opened 2021-04-06 00:27 UTC
Details for the issue
--------------------

#### What did you do?
Executed SQL query (SELECT * FROM table WHERE ('Id')=2) 

#### What did you expect to see?
Execution finished without errors.
Result: 1 rows returned in 4ms

#### What did you see instead?
Assertion [cpMax <= pdoc->Length()] failed at /wrkdirs/usr/ports/databases/sqlitebrowser/work/sqlitebrowser-3.12.1/libs/qscintilla/src/Editor.cpp 6096

Actually, I don't exactly know if ('Id')=2 syntax is correct, but anyway I guess this is not important in this context.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [x] Other: FreeBSD 12.2-RELEASE

#### What is your DB4S version?

- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2021-04-06 06:35
Thanks for reporting this.
Was this the exact SQL you entered?  I tried running this, and it reported it wasn't valid.

![image](https://user-images.githubusercontent.com/7872218/113667544-deb4e000-96a8-11eb-88e1-ec5b3469d30d.png)

I even tried 3.12.1 as I normally use the nightly versions - same result.

It's technically wrong, as **table** is a keyword, so it has to be wrapped around brackets (or double-quotes).  Without it, it still reports an error.  However, correcting that still runs OK.

![image](https://user-images.githubusercontent.com/7872218/113668132-b8437480-96a9-11eb-8acf-e1cb444423dd.png)

> Actually, I don't exactly know if ('Id')=2 syntax is correct

Not for what you want to achieve.  In SQL, wrapping text in single quotes (or apostrophes) is making it literal text, so you're saying, "for every record, does the text **Id** equal the number **2**?" which will be false for every record - you won't get anything displayed.  Just remove the apostrophes to check the actual field *Id*.  

`SELECT * FROM "table" WHERE (Id)=2`

And then we don't need the brackets, as it doesn't achieve anything.

`SELECT * FROM "table" WHERE Id=2`

Can you right-click on the table and select 'Copy create statement' and paste it here.

![image](https://user-images.githubusercontent.com/7872218/113668764-a1515200-96aa-11eb-9287-b17ed37379c2.png)

This only copies the structure of the table, not the data itself.  Would be useful to ensure the error isn't being caused by how the table is built - could be possible.

**Comment by clibc** [comment] 2021-04-06 08:45
Thank you for helping me. 
I am sorry for not being transparent here because the table name is not really `table`.
The actual table that I'm trying to fetch data from:
```
CREATE TABLE "train" (
	"Id"	INTEGER NOT NULL,
	"Departure Location"	TEXT,
	"Departure Date"	TEXT,
	"Arrival location"	INTEGER,
	"Seats left"	INTEGER,
	PRIMARY KEY("Id")
)
```
And at the time I open this issue query that caused the program crash was:
` SELECT * FROM train WHERE ('Id')=2 `
But now it does not crash at all (rebooted my pc, no data changed in DB).
![](https://i.ibb.co/hD2nzVC/Screenshot-2021-04-06-10-32-49.png)

So I tried another query and it crashed again (with the same error):
`SELECT * FROM train WHERE ('Id')=2`
And another one:
`SELECT * FROM train WHERE Id=2`

**Comment by chrisjlocke** [comment] 2021-04-06 10:44
This might be slightly related to an issue we had where DB4S got upset if the result of a query was more or equal to a previous one.  On Windows, it just spun, and didn't get out of the loop - on freeBSD, it might be erroring more 'angrily' and causing the exception you describe.

I'm not familiar with freeBSD - can you build DB4S from the nightly source at all?  I see from our downloads page there is just one link to the 3.12.1 release you're using.  

As an example, can you create a new database (File - Create in-memory database), cancel the 'new table' dialog, go to the 'execute sql' tab, and just type `select 1`

![image](https://user-images.githubusercontent.com/7872218/113698951-e4bcb800-96cc-11eb-882d-81388302fbb1.png)

If you run that a couple of times, does that crash too?

There is nothing wrong with the table structure, so the errors you're getting might just be the problem I describe.  I don't know if you can go back a version to either 3.12.0 or worse, 3.11.x ?

As an aside, I would **strongly** advise against having spaces in field names.  I would instead use camelCase, so:

`CREATE TABLE "train" (
	"Id"	INTEGER NOT NULL,
	"DepartureLocation"	TEXT,
	"DepartureDate"	TEXT,
	"ArrivalLocation"	INTEGER,
	"SeatsLeft"	INTEGER,
	PRIMARY KEY("Id")
)`

this makes creating queries easier, and easier to read.

Also, did you know you have departure location as a text, but arrival location as an integer?

**Comment by clibc** [comment] 2021-04-07 02:10
> Can you build DB4S from the nightly source at all?
I guess no.

> (File - Create in-memory database), cancel the 'new table' dialog, go to the 'execute sql' tab, and just type `select 1`
It works fine a couple of times but at some point, it goes into a state that it just keeps running until I hit the stop button.
![](https://imgur.com/bNzwHqJ.png)


> I don't know if you can go back a version to either 3.12.0 or worse, 3.11.x ?

So I managed to build an older version of DB4S from outdated ports of my FreeBSD system.
```
$ sqlitebrowser --version
$ This is DB Browser for SQLite version 3.12.0.
```
And all of these queries just worked fine!
```
 SELECT * FROM train WHERE ('Id')=2
 SELECT * FROM train WHERE 'Id'=2
 SELECT * FROM train WHERE Id=2
```

> Also, did you know you have departure location as a text, but arrival location as an integer?

Oh, thank you for spotting this bug I did't really notice that. (This is a university project btw.)

**Comment by chrisjlocke** [comment] 2021-04-07 07:10
I'm glad you got 3.12.0 working.  3.12.2 should be 'soon' (couple of months?) so hopefully you can try again.
Theoretically you should be able to build from the current source - the nightlies - the current master.  

> And all of these queries just work fine!

Do you mean they don't crash, or they display the records you were expecting?

In your first example, ('id')=2, this shouldn't bring up any records.

If I have ten records

![image](https://user-images.githubusercontent.com/7872218/113824932-4423d200-9778-11eb-8230-c1e5a21f6066.png)

You'll notice that query does not pull out anything.

![image](https://user-images.githubusercontent.com/7872218/113824990-5a319280-9778-11eb-8798-32919313b184.png)

Nor the second example.

![image](https://user-images.githubusercontent.com/7872218/113825055-6c133580-9778-11eb-89a1-112350e9bc8b.png)

This is not a bug, but the query is asking SQLite, 'get me records where the text 'Id' is equal to 2'.  This will never work.

Your third example is correct and returns one record.

![image](https://user-images.githubusercontent.com/7872218/113825224-99f87a00-9778-11eb-9bc8-939ca42ffa8d.png)

Note that DB4S spots this, and the 'id' in the first two examples is coloured red, indicating text, while in the third example, it's purple.

**Comment by chrisjlocke** [comment] 2021-04-07 07:12
I'll close this as you got it working, but thanks for reporting it and trying other versions.
If you've SQL questions, feel free to ask - always happy to explain and hope the university project goes well! 👍

**Closed by chrisjlocke** 2021-04-07 07:12 UTC
Labels: Execute SQL, crash, freeBSD

**Comment by clibc** [comment] 2021-04-07 08:41
Yes, I get the results exactly in the way you described. Thank you so much again. (I will try to build nightly build)

`SELECT * FROM train WHERE ('Id')=2`
```
Execution finished without errors.
Result: 0 rows returned in 4ms
At line 1:
SELECT * FROM train WHERE ('Id')=2
```

`SELECT * FROM train WHERE 'Id'=2`
```
Execution finished without errors.
Result: 0 rows returned in 4ms
At line 1:
SELECT * FROM train WHERE 'Id'=2
```

`SELECT * FROM train WHERE 'Id'=2`
```
Execution finished without errors.
Result: 1 rows returned in 3ms
At line 1:
SELECT * FROM train WHERE Id=2
```
