### ISSUE TITLE
Installer tries to restart computer without prompt

### ISSUE THREAD

**Issue by erakli** [sqlitebrowser/sqlitebrowser#1099] opened 2017-08-24 16:27 UTC
### Details for the issue

After installer finished it's work it tried to restart computer without prompt

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 7 SP1 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.9.1
- [ ] 3.10.0-beta*
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-08-24 16:35
Oh, that's not good.  There's nothing in our package installers to restart the computer, so that really shouldn't be happening. 😦 

Just to check, where did you download it from?  Only asking in case someone has made a dodgy version of it or something. (eg CNET)

**Comment by chrisjlocke** [comment] 2017-08-24 16:48
Depending on the OS, it might be the redist wanted a reboot.  With a /q swictch, it may not prompt the user?  I can try a vanilla Win 8.  Most of my work machines already have .net and runtimes installed, so would have to try a virtual machine 'out the packet' so to speak.

**Comment by erakli** [comment] 2017-08-24 17:11
@justinclift I've downloaded it from GitHub's Release page. Filename: DB.Browser.for.SQLite-3.10.0-win64.exe

**Comment by justinclift** [comment] 2017-08-24 17:43
@erakli Thanks, that's good info.  Yep, just making sure it's not some dodgy external thing. :smile:

@chrisjlocke Good thinking.  That's the only thing I can think of which might be the cause.  Not sure how we'd workaround that though. 😖

**Comment by chrisjlocke** [comment] 2017-08-25 10:09
I've a 'clean' Win 7 x64 (Ultimate, but not SP1) and the above reboot doesn't occur.  :(

**Comment by erakli** [comment] 2017-08-25 14:47
@chrisjlocke ok, tried to reinstall app today and reboot doesn't occur too. But I installed bunch of MS Visual C++ redists. I think reboot happened when terminal poped up

**Comment by justinclift** [comment] 2017-08-25 15:33
Interesting.  It could be related, but I have no idea how.  Btw, this is the command run by the terminal:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/distri/winlaunch.bat

At least you've found a solution that worked for you.  If this happens to other people too, we'll probably need to look into it more. :smile:

**Comment by bmshmatok** [comment] 2017-08-26 06:02
same problem windws 10 x64, file from GitHub's Release page

**Comment by justinclift** [comment] 2017-08-26 09:22
@bmshmatok Interesting, thanks for mentioning it.

We made a change to our installers [about 3 weeks ago](https://github.com/sqlitebrowser/sqlitebrowser/issues/1068#issuecomment-320944506), updating the MSVC redistributables included with them.

Would you be ok to try one of our nightly builds from before that, so we can figure out if that change is the likely cause? :smile:

If so, this one should be suitable for testing with:

* https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-sqlcipher-2017-08-01-win64.exe

**Comment by Mischanix** [comment] 2017-08-31 17:56
http://asawicki.info/news_1597_installing_visual_c_redistributable_package_from_command_line.html -- note the `/norestart` command line :)

**Comment by justinclift** [comment] 2017-08-31 18:14
Thanks @Mischanix, just merged that.

Is anyone who is experiencing this problem up for testing the nightly build tomorrow?

Assuming nothing goes wrong, it will be here:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by Mischanix** [comment] 2017-09-01 06:55
To confirm, it's no longer trying to restart with the latest nightly build.

**Comment by justinclift** [comment] 2017-09-01 07:07
Fantastic!  Well done @Mischanix. :smile:

**Closed by justinclift** 2017-09-01 07:07 UTC
Labels: bug, packaging, windows

**Comment by justinclift** [comment] 2017-09-21 14:23
@erakli @bmshmatok Version 3.10.1 was released yesterday, with @Mischanix's fix for this included. :smile:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1
