### ISSUE TITLE
Column filter under OSX incorrect

### ISSUE THREAD

**Issue by raananb** [sqlitebrowser/sqlitebrowser#3270] opened 2023-02-03 13:31 UTC
Details for the issue
--------------------

#### What did you see instead? Rows with index 7, 17, 27, 37, 47

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.15 (darwin/19.6.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by raananb** [comment] 2023-02-03 13:35
All the rows related to index 7 and only these rows

**Comment by justinclift** [comment] 2023-02-03 15:52
Hmmm  To me it sounds like it's working as intended, with the *filter* removing any rows without a '7' in them from the displayed results.

Unless I'm misunderstanding? :smile:

**Comment by chrisjlocke** [comment] 2023-02-03 17:24
![image](https://user-images.githubusercontent.com/7872218/216667194-0eb70d3f-2ebb-44d6-9a9d-5ce908133df2.png)

The filter displays any row _containing_ the entered text.


![image](https://user-images.githubusercontent.com/7872218/216667430-1e61bc2d-aa92-4dc8-b36d-72789d1736d0.png)

You can prefix the filter with **=** to mean, 'no you idiot - just give me _exactly_ what I'm after'.

So in your filter, type **=7**

**Comment by MKleusberg** [comment] 2023-02-10 14:26
Closing this as it's been answered by @chrisjlocke. But feel free to reopen this issue any time when you have further questions.

**Closed by MKleusberg** 2023-02-10 14:26 UTC
