### ISSUE TITLE
Browse Data tab empty when loading a subsequent database

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1748] opened 2019-02-18 02:51 UTC
Details for the issue
--------------------

Noticed a bug with last night's nightly builds (tested on Win32, Win64, and macOS).  Haven't checked to see when it was introduced. :wink:

It doesn't happen with 3.11.x.

#### What did you do?

Closed an [open database](https://dbhub.io/nolanbconaway/pitchfork.db) while on the Browse Data tab.  As expected, the database closed.

The bug shows up when opening the database again without changing away from the Browse Data tab (same database in this instance, not sure if that's important).

The database loads, the "Table" drop down widget switches to say "artists" - indicating some part of the load worked.  However, the row count at the bottom still says "0 - 0 of 0" and no rows are displayed in the table view.

This seems to have been mentioned in comment on a different issue too: https://github.com/sqlitebrowser/sqlitebrowser/issues/1654#issuecomment-446847883

#### What did you expect to see?

Row data, and probably a non-0 row count at the bottom.

#### What did you see?

![db4s-issue_1748-screenshot1](https://user-images.githubusercontent.com/406299/52925857-4acc1100-3387-11e9-99a8-178b514ca402.png)

Useful extra information
-------------------------

#### What operating system are you using?

- [x] Windows: 7 x64

#### What is your DB4S version?

- [x] Other: Win32 nightly build for Feb 18 2019
- [x] Other: Win64 nightly build for Feb 18 2019
- [x] Other: macOS nightly build for Feb 18 2019

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment] 2019-02-18 05:55
I can reproduce this one. Tested on 3.11.0 and https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1595v10-Qt5.11.3-MSVC2017-win64.zip.

Tested on smaller databases though, and with opening the same database or different ones.

**Comment by justinclift** [comment] 2019-02-18 06:15
Yep, just tested it with a new `3.11.x` branch build a minute ago, and it doesn't happen there.

It does seem to happen with the recently nightlies though.

**Comment by karim** [comment] 2019-02-18 06:56
- Working: https://nightlies.sqlitebrowser.org/win64/2018-12/DB.Browser.for.SQLite-2018-12-04-win64.zip
- Not working: https://nightlies.sqlitebrowser.org/win64/2018-12/DB.Browser.for.SQLite-2018-12-05-win64.zip

**Comment by justinclift** [comment] 2019-02-18 07:11
Good stuff @karim.  That narrows it down to (most likely) one of these three commits:

* 1f9101ae2a564121ba2843b68c1d7d3f8cff93ad - Move SQL execution in Execute SQL tab into a separate thread
* 7e0ff3061bb13b149db5b5e3287f8906ad6d9249 - Move code for running SQL statements into a separate class
* 10b6c34be6d51bc3949cc1a7840905e264b34791 - Fix view editing

**Comment by justinclift** [comment] 2019-02-18 21:14
Noticed a few other issues which may also be this:

* #1649
* #1701

**Comment by MKleusberg** [comment] 2019-08-18 12:15
@justinclift I believe this is fixed now. Do you have the time to confirm this? :smile:

**Comment by sky5walk** [comment] 2019-08-18 13:54
Yes, it happened to me with the X64 nightlies on Windows 10 Pro latest.
This sounds like a familiar bug that was fixed?

**Comment by MKleusberg** [comment] 2019-08-18 14:09
I think this is the same bug as yours from #1701. With the next nightly build it should no longer be necessary to select a new table - it should just work :smile:

**Comment by MKleusberg** [comment] 2020-02-12 23:04
I'll close this issue because it seems like it's fixed now and there's another open issue for it :smile:

**Closed by MKleusberg** 2020-02-12 23:04 UTC
Labels: bug, response requested
