### ISSUE TITLE
[Bug]: row does not updated when changing primary key

### ISSUE THREAD

**Issue by hubaishan** [sqlitebrowser/sqlitebrowser#3240] opened 2022-12-08 08:30 UTC
### What did you do?

I have table with tow columns column1 is primary key.  In (Browse Data) when I insert new record then I change column1 value then change column2 value.

### What did you expect to see?

I expect to change the value of both column1 and column2 as I see it changed on screen.

### What did you see instead?

when refreshing data. Only column1 will be saved and column2 value remain NULL.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment] 2022-12-08 16:45
This is sort of logical if you think about it.
As you click around the grid, each update is sent to the database independently.
If you change the primary key, (eg, from 1 to 2) record 1 no longer exists.  However, you haven't yet committed the changes.  So when you next amend a cell, DB4S tries to edit record 1, but it no longer exists - its now record 2.
The workaround is to change every other cell, then change the primary key last.

**Comment by chrisjlocke** [comment] 2022-12-22 18:43
Closing as there has been no response.

**Closed by chrisjlocke** 2022-12-22 18:43 UTC
Labels: browse data

**Comment by c-boeckler** [comment] 2024-09-25 16:39
I encountered this problem with the latest version 3.13.0 on Windows 11 recently and it annoyed me a lot. I think DB4S should try to minimize moments of surprise, especially if the surprise is a pretty negative one.

To be more precise: 
1. If I insert a new row then I get a default primary key value, that has to be changed, which is OK. 
2. The rest of the row is more or less emtpy (NULL) at this moment. I assume that the table has more colums than two, since in this case this bug hurts the most.
3. Then I change the primary key value and press tab key to enter the next field. In my understanding (and your comment seems to say this as well) the primary key of this row has now a changed value in the GUI and SQLite has received an UPDATE command to change the primary key value of this row as well.
4. So if I go on and enter values in all colums following, then I see the row as desired.
5. To be sure I press ctrl + S to write changes into the database file.
6. If i return into the table to check wheter my changes are still there (clicking on Refresh has the same effect), then only the changed primary key value is still there, the other column(s) are NULL again.

Step 6 is definitely an unpleasant surprise, especially if you check back after having entered lots of rows manually.
My guess is that the "link" between the row in the GUI and the row in the database gets lost in between.

To be honest, your advise
> The workaround is to change every other cell, then change the primary key last.

is exactly what you call it: a (non intuitive) workaround. And 

> you'll have to refresh the grid after adding a record and pressing 'Write Changes'.

brings productivity down a lot if you have to enter many rows.

**Comment by chrisjlocke** [comment] 2024-09-25 22:35
> is exactly what you call it: a (non intuitive) workaround

Its just a two-step process.  Again, you can see what DB4S is doing, so its just working around the issue.
Yes, its a bug, but its how DB4S was designed all those years ago.
There is an argument that the primary key of an auto-increment field shouldn't be changed, but hey - I'm not going down that route.  If you do need a user-editable field, you can add another field and use that to link to other tables.  Somewhere there is an argument that you shouldn't use primary keys as foreign keys, otherwise if the table has to be rebuilt, there is no guarantee that the records will go in in the same order, or if a record is deleted that number is lost, etc, etc, etc.  

> My guess is that the "link" between the row in the GUI and the row in the database gets lost in between

I've already explained this.  Although you update the primary key, the value is 'locked' in the row as the changes haven't been written to the database yet, so DB4S uses the value it knows, not the value now in the cell.  This is why I suggest making the primary key change last.

**Comment by c-boeckler** [comment] 2024-09-26 18:50
In my opinion it would be sufficient to update the newly created row (in the database) each time after a single value has beend edited interactively (in the GUI) instead of one UPDATE command after editing the whole row. Would that be so hard to implement? Performace is certainly no issue, since each edit is made manually at a low frequency.

**Comment by chrisjlocke** [comment] 2024-09-27 08:23
> it would be sufficient to update the newly created row (in the database) each time after a single value has beend edited interactively 

Well, it does that already, that's kind of the issue.  but the row / changes have to be committed.  DB4S could do that automatically, but then that negates the whole point of a 'write changes' button.
The problem with updating on each change is that if you change the primary key from 1 to 2, on the next change, its trying to change field name 'foo' for record 1, forgetting that you changed the 1 to a 2.  Again, this is why the primary key change should be the last change .. because then it doesn't matter.
