### ISSUE TITLE
minimising issue

### ISSUE THREAD

**Issue by sanjeethboddi** [sqlitebrowser/sqlitebrowser#1063] opened 2017-07-26 09:47 UTC
### Details for the issue

The application is not minimising ...
if i click the minimise button its popping back

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-07-26 09:52
Heya.  That's a bit light on detail.  What's going wrong? :smile:

**Comment by sanjeethboddi** [comment] 2017-07-26 09:57
db browser doesn't minimise .. 
on clicking minimising button it minimises and pops back...
(i don't know whats wrong with the source code)
i hope that you will understand

**Comment by justinclift** [comment] 2017-07-26 10:02
Thanks, yes.  That's easy to understand. :smile:

Which distribution and version of Linux are you using?

**Comment by sanjeethboddi** [comment] 2017-07-26 10:03
UBUNTU 17.04

**Comment by justinclift** [comment] 2017-07-26 10:06
Cool. :smile:

I'm not personally sure what the cause might be, but hopefully someone else on here does.  :smile:

**Comment by chrisjlocke** [comment] 2017-07-26 10:38
See also #934.  A suggestion in there was that it only occurs if View | Edit Database Cell is enabled.  I have no idea if it will help or not.... just thought I'd mention it...

**Comment by sanjeethboddi** [comment] 2017-07-26 13:19
thanks @chrisjlocke 
it has solved my problem 
but may i know why the bug appears when the view--> edit database cell is enabled.

**Comment by chrisjlocke** [comment] 2017-07-26 14:08
Magnets.  Its always magnets.  (Obscure Stargate reference there....)

**Comment by justinclift** [comment] 2017-08-17 21:48
@sanjeethboddi If you have a few minutes to try something out, would you be ok to try compiling and testing the version mentioned here? https://github.com/sqlitebrowser/sqlitebrowser/issues/934#issuecomment-323203577 :smile:

**Comment by chrisjlocke** [comment] 2017-11-09 17:24
I'll close this now as we 'know' its now resolved.  @sanjeethboddi - please comment back or reopen this issue if this is still occurring for you on the latest version.

**Closed by chrisjlocke** 2017-11-09 17:24 UTC
Labels: linux
