### ISSUE TITLE
Plot column checkboxes become checked again on refresh

### ISSUE THREAD

**Issue by Orimay** [sqlitebrowser/sqlitebrowser#1245] opened 2017-11-30 16:58 UTC
### Details for the issue

If I check a plot column, it gets a color. If I uncheck it, and then refresh data for the plot, the mark gets checked back. This is very annoying - I am forced to uncheck all the checkboxes, I ever checked, every time I refresh the data. Please make it so checkboxes don't get checked back on refresh.

### Useful extra information

Weekly build does even worse - after refresh columns disappear at all.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( version: Windows Server 2012 R2 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment] 2017-11-30 22:55
What you see in the nightly is probably caused by the same inner problem as #1222. This is how I reproduce it:
1) Draw a plot
2) Filter by one of the columns
3) Press refresh
4) The plot may disappear. The probability seems to be inverse to the number of rows.

This seems a race condition in the data loading.

**Comment by MKleusberg** [comment] 2017-12-01 12:06
@Orimay Can you download tomorrow's nightly build and check if it's working as expected in there? I think I could fix this bug but you never know :wink:

@mgrojo That sounds like a different issue to me. I'll have a look into that now :smile:

**Comment by chrisjlocke** [comment] 2017-12-07 15:12
If I refresh data while the plot is open, DB4S crumples on the floor in a heap, sobbing.

https://screencast-o-matic.com/watch/cblioX2Cw7

This was on the nightly from 7 Dec.  The nightl;y from 6 Dec also did this.

**Comment by MKleusberg** [comment] 2018-08-16 16:40
Sorry for the delay, @Orimay! But can you check out tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest/) and see if it's working for you? :smile: 

@mgrojo I believe the problem you saw was caused by the old and buggy multithreading code we had. Ironically the new multithreading code had the same issue but in a more reliable manner :wink: Anyway, I believe it is finally fixed now. Can you double check? I'm not 100% about the fix so it's worth a try before closing this.

**Comment by mgrojo** [comment] 2018-09-08 12:53
All the reported problems were solved, but we forgot to report back and close this issue. I'll close it now.

**Closed by mgrojo** 2018-09-08 12:53 UTC
Labels: bug, response requested
