### ISSUE TITLE
Type of imported BLOB data

### ISSUE THREAD

**Issue by gimKondo** [sqlitebrowser/sqlitebrowser#239] opened 2015-03-28 08:54 UTC
BLOB data imported from file is not typed BLOB but TEXT.
We can replicate by following way.

1. create table
```sql
    CREATE TABLE 'Sample' ('ID' INTEGER, 'Image' BLOB, PRIMARY KEY(ID))
```
2. add new record on "Browse Data" tab
3. update 'Image' data by importing image file(e.g. jpg file) on 'Edit database cell'
4. query type of 'Image' data, and get TEXT type
```sql
    SELECT typeof(Image) FROM Sample
```

Maybe, the reason of this issue is DBBrowserDB::updateRecord(sqlitedb.cpp) method.
Imported data for update bind by sqlite3_bind_text without reference to actual (or estimated) data type.

**Comment by justinclift** [comment] 2015-03-28 12:10
Definitely sounds like a bug. :smile:

**Comment by gimKondo** [comment] 2015-03-28 16:24
Thanks for response.
Yes, I guess #229 is caused by same problem, too.

**Comment by schdub** [comment] 2015-04-12 18:54
@justinclift, on my local repo I've fix to this bug.

long story short: in SqliteTableModel when setTable() is called need to fetch and store data types of each field of DB.

next, in  DBbrowserDB::updateRecord() append argument - bool isBlob.

and then in code this function: 
    //...
    
    if (isBlob) {
        sqlite3_bind_blob(...)
    } else {
        sqlite3_bind_text(...)
    }
    
    //...

and we can rewrite "Cheap BLOB test here..." function to:

    bool SqliteTableModel::isBinary(const QModelIndex& index) const
    {
        return m_vDataTypes.at(index.column()) == SQLITE_BLOB;
    }

PS: this solution will be work incorrect if need DB with values of multiple data types in one field.
PPS: waiting to resolve situation with my last pull-request.

**Comment by justinclift** [comment] 2015-04-15 10:26
@gimKondo Would you be ok to try our latest nightly build, and let us know if the problem is completely fixed for you?

In theory it should be now, due to the fix by @schdub.  But, it's always good to verify. :smile:

**Comment by gimKondo** [comment] 2015-04-18 16:34
Thanks. That solves my problem, completely.

But, I worry about column that has multiple data type.
Now, we cannot insert TEXT data to BLOB column.
yes, this is the issue @schdub points on PS.

I think that use of such column is not good practice.
But, SQLite accepts such column by right.

For example, if we execute following SQL to last DB,
```sql
INSERT INTO 'Sample' (ID, Image) Values(2, 'some text');
```
We get text value on Image column.

I think best solution is data type is switched according to 'Edit database cells' dialog.
Maybe, data type should not be decided by column type, but user's decision.

PS : I'm trying such a solution on my local code.

**Comment by justinclift** [comment] 2015-04-18 19:49
Interesting. :smile:

@gimKondo If the solution you're trying works, would you be ok to make a Pull Request out of it? :wink:

**Comment by justinclift** [comment] 2016-08-25 13:28
@gimKondo Would you have time to check if this is fixed in [our new 3.9.0 release](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0)?

I **think** it is, because the new release checks the data type for each cell, instead of only checking the column.  So, this new release should be more accurate. :smile:

**Comment by justinclift** [comment] 2016-09-05 19:12
Closing this due to lack of response. 😦

**Closed by justinclift** 2016-09-05 19:12 UTC
Labels: bug, response requested

**Comment by gimKondo** [comment] 2016-09-11 15:14
@justinclift Sorry, I missed your request.

Now, I confirm that this has been fixed.
Thanks for your nice release.

**Comment by justinclift** [comment] 2016-09-11 16:07
You're welcome @gimKondo. :smile:
