### ISSUE TITLE
Refresh no longer appears to work...

### ISSUE THREAD

**Issue by MYeager1967** [sqlitebrowser/sqlitebrowser#661] opened 2016-07-20 15:09 UTC
I used to be able to refresh the view of the database in the browse data window and see changes. This appears to no longer be the case. If it's by design, so be it. Just thought it was a very handy feature. Now I have to reload the database.

**Comment by justinclift** [comment] 2016-07-20 15:25
Refresh is definitely supposed to work. :smile:

Which OS are you on, and which version of DB4S are you using? :smile:

**Comment by MYeager1967** [comment] 2016-07-20 16:01
Was on Windows 7, didn't work there either. On 10 now. Newest release version, just reinstalled it...

**Comment by justinclift** [comment] 2016-07-20 16:11
k.  Would you have a minute to try the latest nightly build and see if things are better there?

If so, download locations are listed on our front page. :smile:

**Comment by MYeager1967** [comment] 2016-07-20 16:25
Funny enough, if I have BOTH versions open at the same time, it works. With just one or the other, it doesn't appear to want to update... I'm clueless on that one....

**Comment by justinclift** [comment] 2016-07-20 16:28
Wow.  Yeah, that's a new one on me to.

Something doesn't seem right. 😦

**Comment by justinclift** [comment] 2016-07-20 16:28
For added info, how are you (trying to do) the refresh?

**Comment by MYeager1967** [comment] 2016-07-20 16:31
I'm using the refresh button in the program window. 

Just did a test. If I open a second instance of the program and open the database, I can refresh just fine. I opened the newer version twice. Going to try now with the older version. I have no idea why it makes a difference, but it does...

**Comment by MYeager1967** [comment] 2016-07-20 16:33
Ok. Exactly same behavior with the release version... Wish I could offer a hint but there's a reason I love your program, I know NOTHING about SQL....

**Comment by justinclift** [comment] 2016-07-20 16:36
No worries at all.  We'll definitely look into this.  It might be a few days away though. 😦

**Comment by MYeager1967** [comment] 2016-07-20 16:43
If needed, you're welcome to Skype in and see it on this end. It's no big rush, I just happened to think of reporting it when I reinstalled and it still didn't work.  :-)

**Comment by justinclift** [comment] 2016-07-20 16:44
Cool. Focused on some other issues at the moment, but may ping you for exactly that if it turns out to be needed. 😁

**Comment by chrisjlocke** [comment] 2016-07-21 09:25
Out of curiousity (as works fine here) @MYeager1967- if you bring up the SQL log (Ctrl L) when you click the refresh button, does the log window populate?  (lines numbers on the left should increase)
If you create a new database, does the same thing occur?  Is it a local database (C drive) or on a network?

**Comment by jtara** [comment] 2016-07-22 05:56
I am seeing something similar, on OSX. But it just started happening today, and worked fine earlier today!

I just updated to OSX 10.11.6, but only BECAUSE of this problem. (I took a chance it might fix it...)

I don't typically use the refresh button, though, I always forget it is there. I usually switch to a different table, then go back to the table that's been updated.

Other strange symptom is that if I do a query using ExecuteSQL, it will say, e.g. 4 records found, but they aren't shown.

Perhaps a complication is that I am using it to look at databases in an iOS simulator. (I use simPholders to conveniently find the directory, and it mounts the directory using OSXFuse...)

**Comment by revolter** [comment] 2016-07-22 06:03
@jtara, I didn't understand your last part. I am using DB4S for SQLite databases insidr iOS apps running in simulator too. But I don't need to mount anything. The app's Documents folder is just a regular folder at a weird path.

**Comment by jtara** [comment] 2016-07-22 06:07
@revolter, I think I just solved it. I disabled simPholder's use of simPhuse, and now it seems to be working fine.

simPholders finds your simulator images and exposes them in a menu bar window. simPhuse provides yet another convenient way to access them, via a mounted filesystem.

I rarely actually use the simPhuse mounted filesystem, though.

It's strange it worked until today.

**Comment by revolter** [comment] 2016-07-22 07:31
@jtara, I know, I'm using simPholders too, but not simPhuse though. And, indeed is strange that it didn't work.

**Comment by justinclift** [comment] 2016-07-22 07:44
This definitely sounds like one of the stranger bugs. :wink:

**Comment by justinclift** [comment] 2016-07-22 08:02
@jtara Would you have a minute to try out this version?

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-201607220858.dmg

It's our very latest code, plus some UI cleanup I was doing yesterday.  The refresh functionality in it is working ok (tested here on my desktop) according to the SQL log.

If you can get the problem to occur again (eg try trying on simPhuse with it), it'll be helpful for tracking down the cause then figuring out a more proper fix. :smile:

**Comment by jtara** [comment] 2016-07-22 10:09
I can confirm same issue with the nightly. And once I turned off simPhuse, then no problem with refresh.

So, I have my workaround. But you still have your odd behavior, when using it with an odd filesystem. ;)

Perhaps, though, this will give you a clue as to related issues.

**Comment by justinclift** [comment] 2016-07-22 10:11
Thanks @jtara, that really does help. :smile:

**Comment by justinclift** [comment] 2016-07-22 10:12
Just moved the target for this to 3.10.0, instead of our next release (3.9.0), as it's doubtful we'd get it done in time.

**Comment by rwelti** [comment] 2017-08-29 22:49
MacOS Sierra, still having this issue after update to 3.10.0
As mentioned above, running a second copy of the program makes it work properly.
Maybe that's a clue, it doesn't understand the db has been modified, unless another program also has it open... Thanks for all the hard work you guys do.

**Comment by chrisjlocke** [comment] 2017-08-30 06:57
@rwelti - is this via simPholders and/or simPhuse?

**Comment by rwelti** [comment] 2017-08-30 20:54
No but it is a remotely-mounted file (sftp mounted via ExpandDrive).
I blamed that fact, before. 
But when I tried the two open DB Browser instances, both opening that same database, and it fixed the refresh issue, I thought that would be valuable information.  Seems I can't blame ExpandDrive per se.

Sent from Russ (rwelti at Yahoo dot com)


From: Chris Locke <notifications@github.com>To: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>Cc: R. Welti <rwelti@yahoo.com>; Mention <mention@noreply.github.com>Sent: Tuesday, August 29, 2017, 11:58:05 PM PDTSubject: Re: [sqlitebrowser/sqlitebrowser] Refresh no longer appears to work... (#661)

@rwelti - is this via simPholders and/or simPhuse?

**Comment by justinclift** [comment] 2017-08-31 09:18
> But when I tried the two open DB Browser instances, both opening that same database, and it fixed the refresh issue, I thought that would be valuable information.

Yep, it likely is.  The problem is getting sometime to put focus time on it, as it seems pretty edge case and we're time limited at the moment. 🤕

**Comment by MKleusberg** [comment] 2017-09-01 10:53
A quick search indicates that this is a common problem with ExpanDrive... They seem to cache a lot locally and only update that very sporadically: https://expandrive.uservoice.com/forums/205560-expandrive-feature-requests/suggestions/6150107-show-changes-in-real-time. Not sure what to do about that, though [this](https://expandrive.uservoice.com/forums/205560-expandrive-feature-requests/suggestions/6574398-purge-local-cache-of-connected-drives) at least sounds like the situation might be improving. Either way, I'm afraid there isn't much we can do about that in DB4S ☹️

**Comment by chrisjlocke** [comment] 2017-09-01 11:09
> Cache is limited to 1Gb as of mid-2106

Its not going to improve for the next 90 odd years...

**Comment by rwelti** [comment] 2017-09-01 21:35
I know about said cache issues, as a 10 year user -- but that is not the issue here.  And my database is not large. 

Anyway I just quit ED and launched a similar program, Mountain Duck,  and got the same behavior.

It's possible **any** sftp-mounted "drive" in Finder, even just using a shell cmd, would have this issue.  (for example with SSHFS).

It's OK, the DB product is excellent, and free; if it doesn't handle refresh of remote-mounted databases it isn't a huge deal.

**Comment by MKleusberg** [comment] 2020-02-13 13:01
Closing this as it seems to be some external problem which unfortunately we can't do much about.

**Closed by MKleusberg** 2020-02-13 13:01 UTC
Labels: bug, osx, windows
