### ISSUE TITLE
Error when opening DB Browser

### ISSUE THREAD

**Issue by Lord-Henry** [sqlitebrowser/sqlitebrowser#1744] opened 2019-02-14 03:10 UTC
Details for the issue
--------------------

#### What did you do?
Open a SQLite Database.db 

#### What did you expect to see?
The DB Browser main window.

#### What did you see instead?
An error message that says:
Error: Network is not acessible.
(But I have normal connection to internet)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2019-02-14 04:32
Thanks @Lord-Henry, this seems to be a duplicate of #1595, which we're investigating at the moment.

An initial working build, if it helps, is here:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1595v2-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1595v2-win64.zip

Both the .msi and .zip are the same thing, it's just the .msi one has an installer vs the .zip which can just be unzipped and run directly.

If that build doesn't work though, please let us know. :smile:

**Comment by chrisjlocke** [comment] 2019-02-14 09:21
> What did you see instead?
> An error message that says:
> Error: Network is not acessible.

Just a quick note that its a weird issue with DB Browser, that its can't 'find' the Internet to find the current release version, so technically, it can be safely ignored - once you click 'OK', the program will work as normal.

**Comment by chrisjlocke** [comment] 2019-02-14 13:29
I'll close this, as its a duplicate and 'work in progress'.  @Lord-Henry - feel free to comment or re-open the issue if you have further problems regarding this.

**Closed by chrisjlocke** 2019-02-14 13:29 UTC

**Comment by Lord-Henry** [comment] 2019-02-16 17:59
> If that build doesn't work though, please let us know. 😄

Yes, this build worked. Thanks a lot.

> technically, it can be safely ignored - once you click 'OK', the program will work as normal.

I know that, but this error message annoys me.
-----------
Thank you everyone by the help.

**Comment by justinclift** [comment] 2019-02-16 18:05
No worries at all @Lord-Henry.  It looks like we've found a proper solution to this, so we'll probably have a 3.11.1 release out in the next few days with this + some other fixes in it. :smile:
