### ISSUE TITLE
Right to left text option 'breaks' language dropdown

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#667] opened 2016-07-21 13:42 UTC
While dabbling with the translation files, I noticed that when Arabic is selected, the language dropdown is mangled with text prefixed by an opening bracket instead of suffixed by a closing bracket.

![image](https://cloud.githubusercontent.com/assets/7872218/17024863/5d14f52e-4f51-11e6-9476-54f96cbd5e72.png)

**Comment by innermous** [comment] 2016-07-21 13:43
@0xbsec your commit is broken :anguished:

**Comment by justinclift** [comment] 2016-07-21 13:55
Hmmm, yeah that doesn't seem happy.

It's not a deal breaker, but if someone has an idea what could be causing that it would be great. :smile:

**Comment by SafaAlfulaij** [comment] 2016-07-29 06:13
Qt expects a RTL text, so it sets the text direction to RTL.
An easy fix is to add a "LRM" character to the end of the string, it acts as an English letter and would move the bracket to the right :)
Or forcing the combobox direction not to mirror by using `setLayoutDirection`.

**Comment by revolter** [comment] 2016-07-29 07:26
I think that the texts should remain left aligned, as they are in English.

**Comment by justinclift** [comment] 2016-07-29 11:37
@revolter This shouldn't be hard to fix.  Looking here:

* https://doc.qt.io/qt-4.8/qwidget.html#layoutDirection-prop
* https://doc.qt.io/qt-4.8/qt.html#LayoutDirection-enum

The LayoutDirection enum has an "Auto" setting. `Qt::LayoutDirectionAuto`

If that doesn't work for us in practise, instead we could add a small bit of code in the constructor for each dialog to detect an RTL language, then switch the layout direction for the appropriate widgets.

Sounds kind of simple in theory... 😉

**Comment by justinclift** [comment] 2016-07-29 11:57
Just tried out the 3 setLayoutDirection options on the Language selector drop down box.

It didn't seem to have any effect at all. 😕 

### LayoutDirectionAuto
![layoutdirectionauto-english](https://cloud.githubusercontent.com/assets/406299/17247473/723520d8-558b-11e6-98a3-04c1d383bd80.png)

![layoutdirectionauto-arabic](https://cloud.githubusercontent.com/assets/406299/17247494/89cea73c-558b-11e6-834b-f18e803e3df6.png)

### LeftToRight
![lefttoright-english](https://cloud.githubusercontent.com/assets/406299/17247515/a6bb8414-558b-11e6-9f94-97a2761daa47.png)

![lefttoright-arabic](https://cloud.githubusercontent.com/assets/406299/17247517/ac5dea06-558b-11e6-87fd-f2a884a82ae6.png)

### RightToLeft
![righttoleft-english](https://cloud.githubusercontent.com/assets/406299/17247521/b503b3e8-558b-11e6-90ee-74d3bb148dea.png)

![righttoleft-arabic](https://cloud.githubusercontent.com/assets/406299/17247527/b9db3850-558b-11e6-842c-9a51f3603227.png)

`setLayoutDirection` was set using the Design window in Qt Creator.

I'll try setting it manually in the PreferencesDialog constructor next.

**Comment by justinclift** [comment] 2016-07-29 12:06
Ahhh, this might be what we need:

&nbsp; &nbsp; https://doc.qt.io/qt-4.8/qapplication.html#layoutDirection-prop

**Comment by justinclift** [comment] 2016-07-29 12:19
Hmmm, adding this to Application.cpp definitely works to force most of the application to RTL:

```
QApplication::setLayoutDirection(Qt::RightToLeft);
```

... except that specific comboBox.

### English
![setlayoutdirection-rtl-english](https://cloud.githubusercontent.com/assets/406299/17247963/f6d31658-558e-11e6-89a9-1c3d424c2ff0.png)

### Arabic
![setlayoutdirection-rtl-arabic](https://cloud.githubusercontent.com/assets/406299/17247969/ff632182-558e-11e6-8313-c4ee8e7de581.png)

**Comment by SafaAlfulaij** [comment] 2016-07-29 13:06
That's not what I'm seeing here. While the selection direction is not right (I'll report that upstream), the items direction is correct:
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17248915/1a144fda-55a6-11e6-87aa-0aa39be1f15f.png)

_I'm building the app right now and would update this when done._

**Comment by justinclift** [comment] 2016-07-29 13:09
Cool.  Out of curiosity which OS are you using, and which version of Qt are you compiling against?

I might be able to spin up a VM to match, so verify on my end. :smile:

**Comment by SafaAlfulaij** [comment] 2016-07-29 13:13
ArchLinux 64bit, Qt 5.7.
I think you would take some time to finish installing Arch :sweat_smile:

_Done!_

![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17249149/38b2fd46-55a7-11e6-9a8e-2845e876ebc8.png)

So it's exactly as in the designer. I think another bug report should be filed ASAP!

**Comment by justinclift** [comment] 2016-07-29 13:15
Heh Heh Heh

I'm building against Qt 4.8.7 at the moment, but I have Qt 5.6.0 installed too.  I'll give that a go after getting some food, and see if it affects things on my existing (OSX) desktop. :smile:

**Comment by SafaAlfulaij** [comment] 2016-07-29 13:32
> getting some food

Have a nice meal :)

> For "I think another bug report should be filed ASAP!" are you meaning for us, or for Qt? If for Qt... um... are you ok to do it? I probably wouldn't even describe the issue clearly enough for them to fix it.

[This](https://github.com/sqlitebrowser/sqlitebrowser/issues/667#issuecomment-236175247):

> While the selection direction is not right (I'll report that upstream)

It is already reported, and I just updated it ;)
Here: https://bugreports.qt.io/browse/QTBUG-55012

**Comment by justinclift** [comment] 2016-07-29 13:44
Looking at:

&nbsp; &nbsp; https://bugreports.qt.io/browse/QTBUG-55012?focusedCommentId=327173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-327173

That's just a comment on an existing issue. :wink:

If you want it fixed 😜 , shouldn't it be a new issue so they can track/address it properly?

**Comment by mgrojo** [comment] 2018-09-01 16:15
What is the state of this?

I don't reproduce the initial problem.

![imagen](https://user-images.githubusercontent.com/13812910/44947792-f651cb00-ae12-11e8-8b75-d8fcf24a82ee.png)

**Comment by SafaAlfulaij** [comment] 2018-09-01 18:48
With Qt5.11, this issue is now resolved internally as Qt uses the latest Unicode standards stating that the closing bracket’s direction should match the first one (I’m simplifying this). Check [here](https://bugreports.qt.io/browse/QTBUG-57743).

**Comment by mgrojo** [comment] 2018-09-02 09:48
> Your screenshot is showing a lot of untranslated controls though, isn't it... :( (separate issue from the original issue....)

Yes, all the translations need a big update for the next release. 

> With Qt5.11, this issue is now resolved internally as Qt uses the latest Unicode standards stating that the closing bracket’s direction should match the first one (I’m simplifying this). 

Should we then close this issue?

**Comment by justinclift** [comment] 2018-09-02 10:05
The Qt 5.11 thing will probably present us a small challenge, as there seems to be things that don't work very well in DB4S with newer Qt versions that what we're currently building with.

I don't remember the exact details off hand, it's just I remember we do hit problems (all solveable) every time I'm upgraded the nightlies build server to more modern Qt's.  And each time I've then rolled back to the same older ones.

Just mentioning it for awareness. :smile:

**Comment by mgrojo** [comment] 2018-09-02 11:08
Oh, I didn't paid attention to the mentioned Qt version. If the bug was fixed in Qt 5.11 why is working fine for me with Qt 5.5.1?

**Comment by SafaAlfulaij** [comment] 2018-09-02 17:13
> Oh, I didn't paid attention to the mentioned Qt version. If the bug was fixed in Qt 5.11 why is working fine for me with Qt 5.5.1?

This is because the layout is not mirrored. Check the screenshots [here](https://github.com/sqlitebrowser/sqlitebrowser/issues/667#issuecomment-236166112) and notice how the layout is mirrored correctly. I’m not entirely about the Qt version, but I think you need to install qt-translations package for the layout to be mirrored. You may need also to use it under a RTL-locale environment (LANG=ar_BH for example).

**Comment by mgrojo** [comment] 2018-09-02 20:54
I see now. Thanks for clarifiying, @SafaAlfulaij.

**Comment by mgrojo** [comment] 2024-08-05 10:40
![imagen](https://github.com/user-attachments/assets/23aeb3d6-3e75-4466-b721-15933f86d9ad)

> DB Browser for SQLite Version 3.13.99 (Aug  4 2024)
Last commit hash when built: 73ebe93e
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.15.3
SQLite Version 3.37.2.

Can this be closed with our latest release?

**Comment by justinclift** [comment] 2024-08-11 09:03
Hmmm, I'm just going to close it.  If it should have remained open, then it can be done at that point. :smile:

**Closed by justinclift** 2024-08-11 09:03 UTC
Labels: bug, translation, response requested
