### ISSUE TITLE
Crash in TableBrowser when using *.sqbpro file from current release (3.11.2-1) 

### ISSUE THREAD

**Issue by hertzhaft** [sqlitebrowser/sqlitebrowser#2232] opened 2020-05-04 11:56 UTC
Details for the issue
--------------------

I am working with a fresh build (May 3, 2020).
I open a `*.sqbpro` project file created with the actual version `3.11.2-1`.
It loads without error messages or warnings.
I open the TableBrowser to view table contents. The program crashes on some of the tables. 

#### What did you expect to see?
The table content.

#### What did you see instead?
The program crashes with a segmentation fault.

Useful extra information
-------------------------
The error message on the command line is:

> QFont::fromString: Invalid description '(empty)'

I rebuilt in Qt Creator.
When debugging, the crash happens in `TableBrowser.cpp`, line 786.

Relevant parts of the call stack:
`1 TableBrowser::applySettings TableBrowser.cpp 786 0x5555557b6946`
`2 TableBrowser::unlockViewEditing TableBrowser.cpp 938 0x5555557b7803`
`3 TableBrowser::applySettings TableBrowser.cpp 777 0x5555557b684c`
`4 TableBrowser::updateTable TableBrowser.cpp 544 0x5555557b3ba4`
`5 TableBrowser::qt_static_metacall moc_TableBrowser.cpp 317 0x555555807bd2`

It seems that, after parsing the older `*.sqbpro` XML file, some checks for unset values are missing when the results are applied to the UI.

The error message is not pointing to the real reason for the crash.
I think there should be a quiet and error-free migration from the v.3.11 project file format to 3.12.

#### What operating system are you using?
ArchLinux 5.6.10

#### What is your DB4S version?
Current build from source, `3.12.0-(alpha or betas)`

#### Did you also
- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2020-05-04 15:05
Thanks, that sounds like something we'll need to fix for the upcoming release too. :smile:

**Comment by MKleusberg** [comment] 2020-05-06 12:18
Can you send us the project file? No need for the database itself and you can replace any names or other sensitive information.

**Comment by hertzhaft** [comment] 2020-05-06 12:50
Here it is, unchanged. Just checked that it crashes. It has a number of open tabs with SQL commands. The tables that cause the crash are views that have some fields with deeply nested JSON content.  Not all views crash.

```xml
<?xml version="1.0" encoding="UTF-8"?><sqlb_project><db path="/home/martin/test/maps/db/maps.sqlite" foreign_keys="1" case_sensitive_like="0" temp_store="0" wal_autocheckpoint="1000" synchronous="2"/><attached/><window><current_tab id="3"/></window><tab_structure><column_width id="0" width="300"/><column_width id="1" width="0"/><column_width id="2" width="100"/><column_width id="3" width="3271"/><column_width id="4" width="0"/><expanded_item id="0" parent="1"/><expanded_item id="1" parent="1"/><expanded_item id="2" parent="1"/><expanded_item id="3" parent="1"/></tab_structure><tab_browse><current_table name="top_bib"/><default_encoding codec=""/><browse_table_settings><table schema="main" name="bib" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="4" value="146"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="cit" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="ft_top_idx" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="groups" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="guide" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="2" value="214"/><column index="3" value="202"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="item" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="map" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="4" value="238"/><column index="5" value="137"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="origin" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="src" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="12" value="216"/><column index="13" value="181"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_all" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="2" value="143"/></column_widths><filter_values><column index="3" value="chiara"/></filter_values><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_bib" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_cit" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_citation" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="2" value="1031"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_guide" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="2" value="516"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_guides" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_mapitem" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="1" value="216"/><column index="2" value="1191"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_mapitems" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort><column index="2" mode="1"/></sort><column_widths><column index="2" value="1496"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_origin" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="2" value="1084"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_top" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths/><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table><table schema="main" name="top_topref" show_row_id="0" encoding="" plot_x_axis="" unlock_view_pk=""><sort/><column_widths><column index="2" value="835"/></column_widths><filter_values/><display_formats/><hidden_columns/><plot_y_axes/></table></browse_table_settings></tab_browse><tab_sql><sql name="top_mapitems">drop view top_mapitems;
CREATE VIEW top_mapitems as
select 
t.id as ref_top,
json_group_array(
  json_object(
	'id', i.id,
	'group', g.name,
	'fn', m.fn,
	'name', i.name,
	'nr', i.nr,
	'legend', i.legend,
	'tags', i.tags,
	'map', m.line,
	'date', m.date
	)) as refs
from top t
join item i on i.ref_top = t.id
join map m on i.ref_map = m.id
join groups g on i.ref_group = g.id
where i.state &gt; 0
group by t.id
order by t.rowid</sql><sql name="top_guides">drop view top_guides;
CREATE VIEW top_guides as
select 
t.id as ref_top,
json_group_array(
  json_object(
	'altname', c.name,
	'short', b.short || ' ' || c.date,
	'page', c.page,
	'par', c.par,
	'link', b.ft_path
	)) as refs
from top t
join cit c on t.id = c.ref_top
join bib b on c.ref_guide = b.id
group by t.id
order by t.rowid, c.date, c.page
</sql><sql name="top_top">drop view top_top;
CREATE VIEW top_top as
select t.id as topref,
json_group_array(json_object('id', r.id, 'citations', json(g.guiderefs), 'objtype', r.objtype, 'toponym', r.toponym, 'reftype', r.reftype, 'notes', r.notes, 'date_from', r.date_from, 'date_to', r.date_to, 'lat', r.lat, 'lon', r.lon, 'bib', r.bib, 'origin', r.origin))
as toprefs
from top t
join top r on t.id = r.target
left join top_guides g on r.id = g.topref
group by t.id
order by t.rowid, r.rowid</sql><sql name="top_all">drop view top_all;
CREATE VIEW top_all as
select
	t.*,
	json(c.refs) as json_guides,
	json(m.refs) as json_maps,
	json(o.refs) as json_origin,
	json(b.refs) as json_bib
from top t
left join top_guides c on t.id = c.top_ref
left join top_mapitems m on t.id = m.top_ref
left join top_origin o on t.id = o.top_ref
left join top_bib b on t.id = b.top_ref
order by t.rowid</sql><sql name="top_bib">drop view top_bib;
CREATE VIEW top_bib as
select
  t.id as ref_top,
  json_object(
	'short', b.short,
	'author', b.author,
	'title', b.title,
	'publication', b.publication,
	'editor', b.editor,
	'place', b.place,
	'date', b.date,
	'pages', b.pages,
	'isbn', b.isbn,
	'notes', b.notes,
	'id_lib', b.id_lib,
	'signature', b.signature
  ) as refs
from top t
join origin b on t.ref_bib = b.id
order by t.rowid

</sql><sql name="top_origin">drop view top_origin;
CREATE VIEW top_origin as
select
  t.id as ref_top,
  json_object(
	'short', o.short,
	'name', o.name,
	'affiliation', o.affiliation,
	'place', o.place,
	'url', o.url,
	'querypath', o.querypath
	) as refs
from top t
join origin o on t.ref_origin = o.id
order by t.rowid
</sql><sql name="SQL 10">reindex;</sql><sql name="json">select m.ref_top, json_extract(j.value, '$.name', '$.legend') from top_mapitems m, json_each(m.ref_mapitems) j</sql><sql name="&amp;Optimieren">PRAGMA optimize;</sql><current_tab id="6"/></tab_sql></sqlb_project>
```

**Comment by MKleusberg** [comment] 2020-05-06 13:15
Thanks! I could reproduce a crash for ```top_all``` when that table/view doesn't have three columns, which can easily happen for views. The problem then is that the project file tries to set a filter for a column which does not exist. Your stack trace however indicates that the problem might be related to the column widths instead of the filters. I can't reproduce any crash related to that but have applied a similar fix because this might depend on the Qt version.
Can you re-compile with the latest code from the master branch and try again?

**Comment by hertzhaft** [comment] 2020-05-06 17:31
Sorry for the delay. I just recompiled after a `git pull` , but the program still crashes  in `TableBrowser.cpp`, line 789.

**Comment by hertzhaft** [comment] 2020-05-08 13:37
Some more details: The project file states that only the width for column 2 of the view `top_all` should be set to 143, which is correct and gets executed on the first iteration of the loop in line 790. Accordingly, `storedData.columnWidths` correctly contains just one element (a shown in the debugger).

Strangely, the loop continues to iterate, setting `widthIt` to garbage values which causes the crash. So there seems to be some inconsistency with `storedData.columnWidths.constEnd()` which makes the loop continue. Sorry for not being of more help, but I'm not an expert in CPP ...

**Comment by MKleusberg** [comment] 2020-05-19 10:43
That would be very weird. The ```constEnd()``` function is provided by Qt itself and I don't think they changed anything.

Here's one more idea. Can you try changing the code around line 787 like this:
```c++
for(auto widthIt=storedData.columnWidths.begin();widthIt!=storedData.columnWidths.end();++widthIt)
```
I'm suggesting this because changing the column widths might provoke some sort of chain reaction which in effect yields to other column widths to be changed. This way the ```columnWidths``` object could be modified which the ```constBegin()``` and ```constEnd()``` functions can't deal with.

**Comment by MKleusberg** [comment] 2020-05-19 10:43
Thank you so much for all your effort with this issue by the way :smile:

**Comment by hertzhaft** [comment] 2020-05-19 17:56
Thank you! Glad to contribute, it is such a useful software.

The bug _is_ weird ... With your change I can't make it crash in the debugger any longer (the loop exits as intended), but the compiled standalone program still crashes with a segfault.

I have the impression that for some tables/views `storedData.columnWidths` has garbage values because it was not initialized properly when the project file was read. But that's just a guess.

**Comment by MKleusberg** [comment] 2020-06-03 14:24
Are you sure this is not caused by some sort of build problem? Is it also crashing outside the debugger after deleting all temporary files and rebuilding the entire project?

**Comment by hertzhaft** [comment] 2020-06-05 19:56
I did a fresh checkout and a complete rebuild - the crash still happens at the same code location, in the debugger as well as outside. The problem is in `TableBrowser.cpp` line 787
```cpp
for(auto widthIt=storedData.columnWidths.constBegin();widthIt!=storedData.columnWidths.constEnd();++widthIt)
```
Although `storedData.columnWidths` has only one element, the loop continuation condition `widthIt!=storedData.columnWidths.constEnd()` evaluates to `true` after the first iteration has completed. Thus `qmap.nextNode()` is called and `widthIt` is set to a random garbage value.

**Comment by hertzhaft** [comment] 2020-06-06 11:45
I think I found the problem. It is explained [here](https://stackoverflow.com/questions/27284663/qmap-iterator-crash). Each time when called, `storedData.columnWidths` apparently returns a copy of `column_Widths`, and you can't iterate between the copies.

When I replace `Tablebrowser.cpp` line 787 with the following two lines, the program works as it should and doesn't crash:

```cpp
QMap<int, int> w = storedData.columnWidths;
for(auto widthIt=w.constBegin();widthIt!=w.constEnd();++widthIt)
```
Since there are quite a lot of analogous constructs in this file, a thorough check for this potential bug source might be appropriate. Maybe there is a better, more generic solution than mine.

**Comment by scottfurry** [comment] 2020-06-06 12:50
@hertzhaft
I just ran into this in another project but there is deprecation in the Qt libraries after 5.14.0. Upstream has decided that some of the creation methods for Qt-variant of containers are to be populated with iterators. If you're using a later version of Qt, this may be affecting things. Can you post your `about` dialog as a screen shot please?

**Comment by scottfurry** [comment] 2020-06-06 13:00
@justinclift - I think this answers your earlier query about moving to Qt 5.15. I think there's a bit of work/testing needed before we go down that road.

**Comment by hertzhaft** [comment] 2020-06-06 13:31
Indeed, I am using Qt 5.15 (Archlinux package). I wasn't aware there is a problem, as BUILDING.md says "Qt 5.5 or later, however we advise you to use 5.7 or later".

![sqlitebrowser_about](https://user-images.githubusercontent.com/5148722/83945412-c109b680-a80a-11ea-9e58-b2127ca6d977.png)

**Comment by justinclift** [comment] 2020-06-06 14:15
> I think this answers your earlier query about moving to Qt 5.15. I think there's a bit of work/testing needed before we go down that road.

Yeah, sounds like it. :frowning:

Well, we'll stick with Qt 5.12.8 for now then.  Once our release is out the door, we can upgrade the build server to Qt 5.15 and see what kind of problems that generates via our nightlies.

**Comment by justinclift** [comment] 2020-06-06 14:18
> Indeed, I am using Qt 5.15 (Archlinux package). I wasn't aware there is a problem, as BUILDING.md says "Qt 5.5 or later, however we advise you to use 5.7 or later".

If Arch has a slightly older and more tested version of Qt available (eg Qt 5.12 LTS, or maybe 5.14), that'd probably give a more stable result.  That being said, using Qt 5.15 + reporting the problems it causes will help us take care of them sooner rather than later. :smile:

**Comment by scottfurry** [comment] 2020-06-06 14:36
5.14 is okay. Again, issues with Qt version of containers (QSet, QMap, and the other usual suspects) may need to be examined and/or run through some kind of static analysis to cover our bases. The change came with 5.14.0 release. A silent but deadly trap waiting for the unaware. (insert malevolent laughter here).

I tripped over this compiling other source code and gcc9.3 spit the warnings out for 5.14.2. (NOTE to others: there's useful info in compiler logs). We can go ahead with a release, but should plan for a point-release shortly afterwards specifically for container checks/Qt 5.14|15. My $/€ 0.02.

**Comment by hertzhaft** [comment] 2020-06-06 14:37
Thanks! Other than that, I haven't encountered any problems, and this one occurred only with a project file that didn't conform to the most recent state of development. I was eager to use the new features and I'll be happy to report any problems with Qt 5.15+  :-).

Maybe you could insert a warning into `BUILDING.md` ?

**Comment by scottfurry** [comment] 2020-06-06 14:37
@hertzhaft - yup. The two lines you posted above got my attention. When you mentioned replacing something with iterators, bells and alarms went off in my head.

**Comment by MKleusberg** [comment] 2020-06-06 14:38
Interesting. Thanks for the fix, @hertzhaft! Let's just apply that for now :+1: I'll prepare the commit in a second.

I don't think the explanation is correct though. Accessing ```storedData.columnWidths``` should not create a copy. Even with all the extra stuff the Qt are doing this seems unreasonable. I still think it's the fact that ```setColumnWidth()``` modifies the ```storedData.columnWidths``` container which is what's causing the problem here. Making a copy of the container to work with would solve this problem too.

@scottfurry Do you have a link to that deprecation notice? This sounds like something we should investigate in general. Personally I'm using Qt 5.12 at the moment, so this might actually be the reason why I could not reproduce this. I have to say I'm glad now I put all this effort into using standard C++ containers more often instead of their Qt counterparts...

**Comment by scottfurry** [comment] 2020-06-06 14:39
> Maybe you could insert a warning into `BUILDING.md` ?

I think we can cover the matter with a quick blurb on a FAQ with a statement that a point release will follow.

**Comment by scottfurry** [comment] 2020-06-06 14:42
@MKleusberg - its the tinyest of notices. 
https://doc.qt.io/qt-5/qset.html#toList
Similar shows up in QList::fromSet().
There is a similar short blurb near the top of this: https://doc.qt.io/qt-5/containers.html (search for `5.14` it should pop up.)

**Comment by MKleusberg** [comment] 2020-06-06 14:44
@scottfurry Hmm, that sounds more like they have added something instead of changing old behaviour. On the other hand it does mean they have modified something in the containers which might have side effects...

**Comment by MKleusberg** [comment] 2020-06-06 14:47
@hertzhaft's fix is committed now :smile: Should we close this issue then?

**Comment by justinclift** [comment] 2020-06-06 14:48
> I think we can cover the matter with a quick blurb on a FAQ with a statement that a point release will follow.

We're using Qt 5.12.8 (and LTS release of Qt) for the Win and macOS release builds. :smile:

**Comment by scottfurry** [comment] 2020-06-06 14:49
Change came in w/ 5.14. What happens in 5.15 may be an entirely different story. FWIW, I thing Debian stable is still at 5.11? They're moving at the speed of glaciers when it comes to Qt releases.

What I did for another project was to do a version check on Qt. Anything less that 5.14.0 use the original. Else...new stuff.

```
include <QtGlobal>
...
#if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
    <original code here>
#else
    <re-worked container/iterator code>
#endif
...
```

**Comment by scottfurry** [comment] 2020-06-06 14:51
@MKleusberg - wouldn't close this just yet. You have a fix for 5.15 but is it backwards compatible?
:thinking: :thinking: (Jeopardy thinking music plays in the background)

**Comment by scottfurry** [comment] 2020-06-06 14:53
IIRC, there is also a change in a signal name for a QSpinBox for >=Qt 5.14. Yeah. Some things need examining.

**Comment by MKleusberg** [comment] 2020-06-06 14:54
Well it works with my Qt 5.12 and I don't see any reason why it should not be backwards compatible. But you're right of course, in theory there could be some issue left with this :smile:

**Comment by scottfurry** [comment] 2020-06-06 14:55
Famous last words - _If you haven't blown up an operating system lately, you're not trying hard enough._

**Comment by MKleusberg** [comment] 2020-06-06 14:57
Also, I was thinking about dropping support for the old project file format (which had binary data in it) after the 3.12 release. With support for that gone we could change this all to use standard C++ containers too which should solve this issue for good.

**Comment by justinclift** [comment] 2020-06-06 14:58
We're better put some kind of obvious deprecation notice / or pop-up or something then. :wink:

**Comment by scottfurry** [comment] 2020-06-06 15:02
I sense a 3.14 release schedule.... (we'll just skip past 3.13)

**Comment by MKleusberg** [comment] 2020-06-06 15:04
@justinclift We have. Whenever you're loading a project file with the old format you'll get this message since version 3.11:
> This project file is using an old file format because it was created using DB Browser for SQLite version 3.10 or lower. Loading this file format is still fully supported but we advice you to convert all your project files to the new file format because support for older formats might be dropped at some point in the future. You can convert your files by simply opening and re-saving them.

If you ask me we could add a note to the release notes saying that this is the last version to support project files from 3.10 or earlier and drop support for 3.13.

**Comment by MKleusberg** [comment] 2020-06-08 18:33
I've just replaced the QMap by a std::map. So we should definitely be independent of what Qt is doing now. I've left the fix in place anyway, just to make sure.

@hertzhaft Do you want to give the latest version from the master branch another try? It should still work but you never know :smile:

**Comment by hertzhaft** [comment] 2020-06-09 08:09
Yes, it still works. I see you have replaced all QMaps in the settings structure, so that should hopefully eliminate this weird kind of bug. I wonder if you would also want to reconsider line 543 in `TableBrowser.cpp`

```cpp
// Reapply the view settings. This seems to be necessary as a workaround for newer Qt versions.
        applySettings(settings);
```
which doesn't look very reassuring :-) and struck me as odd when I started investigating this issue (see the stack trace in my original bug report).

**Comment by hertzhaft** [comment] 2020-06-13 13:09
Thanks for the refactoring - looks much cleaner now! I just made a new build and everything seems to work fine.

Maybe I'll contribute when I have time :neutral_face: I'd be in favour of configurable keyboard shortcuts, and there seem to be some minor quirks in table editing. But as I said, I have no experience with cpp/qt so far ...

**Comment by chrisjlocke** [comment] 2020-06-13 13:34
> and there seem to be some minor quirks in table editing

Problem ones?  Yell what they are, and someone somewhere might be able to fix it.  Quirks aren't a good thing... 😉

**Comment by hertzhaft** [comment] 2020-06-15 11:42
Sorry, I must have remembered an older version. Just tested table editing again, now it is super slick and intuitive :smiley: - thanks to all who contribute to this really useful tool!

**Comment by MKleusberg** [comment] 2020-07-10 09:23
Looks like we can close this issue then :smile: Thanks again for all the effort you have put into this issue, @hertzhaft!

**Closed by MKleusberg** 2020-07-10 09:23 UTC
Labels: bug
