### ISSUE TITLE
Ability to have multiple instances open at the same time?

### ISSUE THREAD

**Issue by magnuswikhog** [sqlitebrowser/sqlitebrowser#1634] opened 2018-11-29 19:58 UTC
Describe the new feature
--------------------------
I really, really miss the ability to have multiple instances of the DB Browser open simultaneously on OSx! Often I want to check some stuff in two different databases "side-by-side" or just switching back and forth using ALT+TAB. I tried using the "Attach database" feature but the only way to access the attached database seems to be manually in the "Execute SQL" tab, which is far from ideal.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
SQLiteStudio has something similar, but it doesn't really open two windows, it just lets you connect to multiple databases at the same time and arrange them side-by-side/stacked/whatever inside the one single instance of the application. Not really ideal, but better than nothing. 

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No screenshot needed - just the ability to open multiple instances of the application, like most other applications.

**Comment by mgrojo** [comment] 2018-11-29 20:42
What is preventing you to run a new DB Browser process? As far as I know, we don't do anything for preventing two processes of the application running in parallel. 

Regarding attaching the other DB, it should allow you to browse the tables in that DB in the "Brwose Data" tab. The will appear as domain.table. You are asked for domain name when you open the DB. This should also allow to quickly switch the DBs but the two application instance is better suited for that.

**Comment by magnuswikhog** [comment] 2018-11-29 21:55
If I open a database in Finder and then open another one, it doesn't open a new DB Browser, it just opens the second database in the already opened window. 

And attaching another database and giving it a domain name doesn't do anything. I can only see the tables of the already opened database in the Browse tab dropdown. I can access the second one through the "Execute SQL" tab though. 

This is on OSx El Capitan 10.11.6.

**Comment by justinclift** [comment] 2018-11-29 22:52
Ahhh.  I do remember something similar from back when I used to use OSX.

From memory, it's an OSX thing rather than a behaviour we've specifically made DB4S do.  There might be a way around it (eg some setting we can change), but we haven't put any time into figuring it out yet.

As a workaround, you **should** in theory be able to open multiple instances of DB4S using the command line:

    "/Applications/DB Browser for SQLite/Contents/MacOS/DB Browser for SQLite" &

I used to do that myself for programs back in the day, when using OSX as my desktop.

This CNet article shows another way to do the same thing from the terminal:

&nbsp; &nbsp; https://www.cnet.com/news/how-to-open-multiple-instances-of-an-application-in-os-x/

If you create some kind of shortcut for launching DB4S that way, you should (again, in theory) be able to drag and drop a database file to the opened window directly, which should then load/display it in that version of DB4S.  Hopefully. :wink:

Does that help?

**Comment by mgrojo** [comment] 2018-12-03 20:17
Ok, opening a new database from the Finder in the same instance seems a MacOs thing, but what about this?

> And attaching another database and giving it a domain name doesn't do anything. I can only see the tables of the already opened database in the Browse tab dropdown. I can access the second one through the "Execute SQL" tab though.

@magnuswikhog That isn't expected. Attached database should appear in the Browse tab dropdown. Can you reproduce it with any database? Can you provide more details?

**Comment by justinclift** [comment] 2018-12-08 04:52
@magnuswikhog Ping.

**Comment by Stoyvo** [comment] 2019-03-26 22:42
I can acknowledge that this is also a pain point for me. For the past while I've been keeping my db passphrase in my clipboard, but it is very annoying.

Also, the attaching of another large DB crashes SqlBrowser, and the attached DB will auto-detach itself. Maybe related? Other than explaining the recreatable steps, I'm not sure how to help. Are logs available somewhere for when a DB auto detached itself?

I will note that my DBs are encrypted with latest release of sqlcipher and I am using 3.11.1

**Comment by Stoyvo** [comment] 2019-03-26 22:44
@justinclift You missed the ".app" in your comment about opening via command line :)

"/Applications/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite" &

**Comment by justinclift** [comment] 2019-03-27 03:21
> You missed the ".app" in your comment about opening via command line :)

Whoops.  Thanks, just fixed it. :smile:

**Comment by justinclift** [comment] 2019-03-27 03:23
With the "attaching of another large DB crashes ...", it's probably the ATTACH bug (#1758), which is fixed in our nightly builds and will be fixed in the 3.11.2 release (prob Friday) too.

Nightly builds are here, if that helps:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment] 2019-03-27 03:25
Hmmm, thinking about this, this can probably be closed.  It seems to be a Finder thing, more than something we control.

**Closed by justinclift** 2019-03-27 03:25 UTC
Labels: osx, response requested

**Comment by rebeccaXam** [comment] 2023-02-01 10:14
You could use Automator and create an Application:
<img width="991" alt="Automator" src="https://user-images.githubusercontent.com/19565685/216009636-c4cc9d68-b94e-4b1c-8b27-fddae329abb3.png">

- Save the New Application in the Applications Folder.
- Select the Original `DB Browser for SQLite` in the Applications Folder, Open `Get Info` (CMD+i)
- Select and copy the Icon (CMD+c):
<img width="261" alt="Get Info" src="https://user-images.githubusercontent.com/19565685/216010618-aa4cc3c4-09d3-4080-a100-b0cf2a6b4483.png">

- Now Select your new App, Open `Get Info` (CMD+i) and click on the `Automator Icon` then paste (CMD+v)

- To open Database default in a new Instance, select a sqlite database file, Open `Get Info` (CMD+i):
<img width="261" alt="Change Open" src="https://user-images.githubusercontent.com/19565685/216011947-0a389a1b-e028-447f-b362-1bd46a92d93f.png">

- Change `Open with` to the new App you created and click `Change All...`

Hoop this helps ;)
