### ISSUE TITLE
[Execute SQL] Undocumented: unexpected execution of selection [was: False error after applying...]

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1336] opened 2018-03-06 23:10 UTC
### Details for the issue
While editing my SQL queries, I repeatedly came across false errors which seemed to occur immediately after typing a shortcut for UPPERCASE, [Ctrl+Shift+U].
I did not see any extra characters added but did not check for hidden characters by pasting into another editor.

### Useful extra information
Maybe the UPPERCASE shortcut is undocumented but others I use in Scintilla/Notepad++, seem to work without errors. 
Ex. Duplicate = [Ctrl+D]

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_10 Pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: ___3.10.99 v180217

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment] 2018-03-07 20:19
And does it actually uppercase anything? In Linux, what I get is the Unicode input shortcut: https://en.wikipedia.org/wiki/Unicode_input#In_X11_(Linux_and_Unix_variants)

**Comment by sky5walk** [comment] 2018-03-07 21:17
Sorry, it does UPPERCASE my selected text. ( Else I would not have posted  ;) )
Just as [Ctrl+U] lowercase's my selected text.
I did not know the Linux behavior, or why it would affect my Windows use?

**Comment by mgrojo** [comment] 2018-03-07 22:45
Ok, I see now that in Linux it only uppercases the selected text if the Shift Lock is activated. Indeed, Scintilla provides the shortcut[1] but it seems eclipsed by the (Qt-Linux?) Unicode shortcut when Shift Lock is not in use.

[1] https://github.com/sqlitebrowser/sqlitebrowser/blob/bddae31bf12b3ad050104352851d7a0b25886613/libs/qscintilla/src/KeyMap.cpp

>  I did not know the Linux behavior, or why it would affect my Windows use?

Just in case Qt had implemented a cross-platform shortcut for that. But it's not even listed in http://doc.qt.io/qt-5/qkeysequence.html

> While editing my SQL queries, I repeatedly came across false errors which seemed to occur immediately after typing a shortcut for UPPERCASE, [Ctrl+Shift+U].

Could you give, copy or capture some example of the false errors? I don't reproduce it, even when the UPPERCASE shortcut works.

**Comment by sky5walk** [comment] 2018-03-07 23:06
The errors are intermittent, but I just reproduced with these steps:
```
1. Start with an SQL UPPERCASE query.
   SELECT * FROM MYTBL;
   Run = OK.
2. Select all and [Ctrl+U] = lowercase query.
   select * from mytbl;
   Run = OK.
3. Select 'from' and [Ctrl+Shift+U] = UPPERCASE 'FROM' only query.
   select * FROM mytbl;
   Run = FAIL. --> near "FROM": syntax error: FROM
4. Run same query again = OK.
```

**Comment by sky5walk** [comment] 2018-03-07 23:09
There are several variations and sometimes the query will not recover until I leave the SQL edit box and return.
It makes for confusing debugs of complex queries when/if you decide to UPPERCASE a keyword.
For now, I know not to mess with the case until I have a working query. :(

**Comment by chrisjlocke** [comment] 2018-03-08 17:04
3. Select 'from' and [Ctrl+Shift+U] = UPPERCASE 'FROM' only query.
    select * FROM mytbl;
    Run = FAIL. --> near "FROM": syntax error: FROM

Quick question.  When you run this, is the FROM still selected?
If so, DB4S is only running the highlighted text, not the full SQL query......

**Comment by sky5walk** [comment] 2018-03-08 17:14
haha, good catch. That explains why moving focus worked.
Is this a feature or bug?
I say bug, but it could be useful for complex queries where I want to test a section without commenting out the rest.
At least document this behavior or change its action on 1st fail.
Meaning, attempt to run query with selection text, but on fail, deselect all and run existing text.
If errors in this attempt, then display.

**Comment by chrisjlocke** [comment] 2018-03-08 17:22
This is a feature, and has been this case for a while.
The 'Execute current line' (button next to the 'Execute SQL') doesn't exhibit this behaviour.  It should technically be called 'Execute current statement' as it runs the statement up to the closing semicolon, not necessarily the current line.

**Comment by sky5walk** [comment] 2018-03-08 17:54
Ok, can you modify the ToolTip texts for both of the Execute SQL buttons?
```
FROM: Execute SQL [F5, Ctrl+Return, Ctrl+R]
TO:   Execute selected SQL [F5, Ctrl+Return, Ctrl+R]

FROM: Execute current line [Shift+F5]
TO:   Execute all [Shift+F5]
```

**Comment by chrisjlocke** [comment] 2018-03-08 19:55
FROM: Execute current line [Shift+F5]
    TO:   Execute all [Shift+F5]

Its not 'execute all' though - that makes it sound like it will execute everything.  It'll only execute the current statement where the cursor is.

**Comment by sky5walk** [comment] 2018-03-08 20:46
Ok, whatever you think will capture the true action?
I will definitely make use of selected text queries now that I know about them. :)

**Comment by mgrojo** [comment] 2018-03-09 16:34
It definitely makes sense to change the tooltip and the "what's this" info, because there isn't any indication of this feature.

For the "what's this" I was thinking on making this change:
* From: This button executes all the SQL statements of the current editor tab
* To: This button executes the SQL statements of the current selection. When no text is selected, it executes all the SQL statements in the editor tab.

But the tooltip should be brief and clear at the same time. And it shouldn't change from all to selected, because it is adding some information while hiding other. What about?:
* From: Execute SQL [F5, Ctrl+Return, Ctrl+R]
* To: Execute all/selected SQL [F5, Ctrl+Return, Ctrl+R]

**Comment by chrisjlocke** [comment] 2018-03-09 16:41
From: Execute SQL [F5, Ctrl+Return, Ctrl+R]
    To: Execute all/selected SQL [F5, Ctrl+Return, Ctrl+R]

Makes sense, and concise.  For more information, details should be on the Wiki.

**Comment by sky5walk** [comment] 2018-03-09 17:53
Nice. Will this be in 180309 nightly?

**Comment by justinclift** [comment] 2018-03-09 19:03
Instead of:
```
This button executes the SQL statements of the current selection. When no text is selected,
it executes all the SQL statements in the editor tab.
```

Maybe:

```
This button executes the currently selected SQL statements. If no text is selected, all SQL
statements are executed.
```

**Comment by mgrojo** [comment] 2018-03-09 21:22
@sky5walk Just committed. It will be in version from 10-Mar-2018.

@justinclift Perfect. That is on the commit.

**Comment by mgrojo** [comment] 2018-03-30 16:20
I close this, since there are not additional comments.

**Closed by mgrojo** 2018-03-30 16:20 UTC
Labels: enhancement
