### ISSUE TITLE
Range filter doesn't seem to work

### ISSUE THREAD

**Issue by DarylWM** [sqlitebrowser/sqlitebrowser#1048] opened 2017-06-29 11:16 UTC
### Details for the issue

I have an integer field, and I want to only display values 1 and 2 (for example) so I enter 1~2 in the filter field. But there are zero records displayed.

![capture](https://user-images.githubusercontent.com/1016303/27685027-d070cd96-5d0f-11e7-9b1c-f1903053a681.PNG)

![capture2](https://user-images.githubusercontent.com/1016303/27685033-d5d172a4-5d0f-11e7-8210-79441b9d7022.PNG)

### Useful extra information

EDIT - added the schema
CREATE TABLE frames (frame_id INTEGER, point_id INTEGER, mz REAL, scan INTEGER, intensity INTEGER, peak_id INTEGER)

Seems to be a problem for any integer field, using any range of integers.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: (10 Home, version 1703, build 15063.413 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-06-29 12:22
Interesting.  Just tried it here too, and yep, it doesn't seem to be working any more.  We'll definitely need to look into that.

**Comment by chrisjlocke** [comment] 2017-06-29 13:38
Just confirming - is the point_id field an integer?  I've tried it on a database here, and it 'seems' to work OK on integer fields.  Admittedly the database doesnt have a large number of records to fully test it though.

**Comment by justinclift** [comment] 2017-06-29 15:20
Yep, in the local database I tried the field type was definitely set to INTEGER. 😦

**Comment by Wikkie** [comment] 2017-06-29 16:24
I noticed this problem a while ago as well (Ubuntu: Version 3.9.1/Qt Version 5.6.1/SQLite Version 3.15.2; also on my Windows machine, 3.9.1 build, I guess)
I just forked and built sqlitebrowser literally minutes ago on Ubuntu, where the feature works as advertised. (Version 3.9.99/Qt Version 5.7.1/SQLite Version 3.16.2)

**Comment by chrisjlocke** [comment] 2017-06-29 18:23
The databases I've tested it on, I can't get it to fail. Must be a weird schema-specific bug?

**Comment by justinclift** [comment] 2017-06-29 19:32
Could be. :smile:

Just uploading a trivial database (2 columns), which for me has this problem:

&nbsp; &nbsp; https://dev1.dbhub.io/justinclift/issue1048.sqlite

You ok to try it out?

**Comment by justinclift** [comment] 2017-06-29 19:38
Ooops, just realised the version of DB4S I was testing with wasn't a recently build.  Tried the latest nightly instead and it's working fine. :smile:

Thanks for the prompt @Wikkie, you're right that was the difference.

@DarylWM If you're ok to update to the latest nightly build, that should work for you:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by MKleusberg** [comment] 2017-06-29 19:46
The reason this doesn't work in 3.9.1 by the way is that the feature was added by [this commit](a75f2dac1100c98b387ee5378bcd460b159a02c7) on Jan 27 2017 and 3.9.1 was released in October 2016 :wink: Maybe we should point this out in the Wiki page for the time being.

**Comment by justinclift** [comment] 2017-06-29 19:52
Cool.  Good thought @MKleusberg, just added a note to the wiki page in the right spot. :smile:

**Comment by karim** [comment] 2017-06-29 20:02
Just wondering when DB4S will release a new version. 😄

Everyone seems to be using the *old* official version, and there is no way for them to update/know about all the new features and bug fixes unless they got a problem and they are *willing* to report it.

**Comment by MKleusberg** [comment] 2017-06-29 20:07
Yeah, you're absolutely right, Karim. I'm thinking about getting the issue number down to a more reasonable count and then just release 3.10 no matter what. But as high as it currently is I'm afraid it's going above 300 after a new release and we'll lose track entirely 😆

**Comment by justinclift** [comment] 2017-06-29 20:36
@karim I'm also trying to get the DBHub.io bits ready for our next release too... :wink:

**Comment by DarylWM** [comment] 2017-06-29 21:34
Thanks for looking into this and for the rapid responses. I'm GMT+10 so I didn't see them sooner.

@chrisjlocke Yes the point_id field is an integer. I added the schema in the problem description.

@justinclift Thanks for the pointer to the nightly build. I will move to that.

I appreciate this very handy tool!

**Comment by karim** [comment] 2017-06-29 23:37
@justinclift I appreciate everything you do for DB4S even though you are very busy with DBHub.io, and sometimes I wonder how you find the time to even look at DB4S issues. 😄 

@MKleusberg I understand your point. However, the more we wait the more issues we will get and it will be harder to even think about releasing a new version.

Almost all answers to most of the issues here is to try the nightly build, since the last official version is too old. Problem is, most users prefer to stick with the official (stable) version and don't try to use the nightly (dev/unstable) version.

This issue here has been fixed more than 5 months ago and still didn't make it to the official release, and most users don't know about it.

I was thinking maybe you can cherry-pick some bug fixes/features (like this range operator) and apply them to the official v3.9.1 and pump the version to v3.9.2. Fixes/features that were fixed long time ago and were tested extensively.

Doing a few small/minor releases like this every week, or couple of weeks, and we will be able to move most of the users to a recent build and we will get less issues. After this, most of the issues will be about new features which we can delay to the next major release.

**Comment by justinclift** [comment] 2017-06-30 10:42
@karim From my point of view :smile:, it's mostly a question of what to put time into.

The concept of "lets make a v3.9.2" (by cherry picking bug fixes from master to the v3.9.x branch) is good.  That's what the v3.9.x branch is for.  Our users would benefit from it too. :smile:

So the question then is "who'll get that done?".

* @MKleusberg is fixing bugs
* I'm working on DBHub.io, as I'm really, really, really wanting us to have a better sustainable foundation
* @chrisjlocke is being first (and second :wink) point of contact for many of the opened questions and issues
* @revolter, @innermous, @iKlsR (etc) put time into the project as time/energy/interest permits.

If making a v3.9.2 release is something you'd be interested in doing and have time for, then definitely go for it.

You have commit access to the repo, so can get the cherry picking done.  When you've gotten the v3.9.x branch to a state you're happy with I can kick off the build scripts to generate the binaries + sign them, then we can cut a new release officially.

Thoughts? :smile:

**Comment by Wikkie** [comment] 2017-06-30 11:52
@justinclift thanks for the pointer to the nightlies. Life at work is muuuch better now ;-)

**Comment by karim** [comment] 2017-07-02 02:12
@justinclift Sorry for the late reply.

Yes, sure I can do that. I will probably create a new **v3.9.2** branch from [**v3.9.1**](https://github.com/sqlitebrowser/sqlitebrowser/tree/v3.9.1) tag and start adding to it. I will try to be careful not to make a mess since this will be the official release. You still need to be involved. You are the one who have to build and sign it. 😄

The question now is not "who" but "how" we will get it done? 😄 

As I said earlier, I'm thinking of making very small releases. Just a single bug fix/feature per version. v3.9.2 could be the same as v3.9.1 but with this commit https://github.com/sqlitebrowser/sqlitebrowser/commit/47321bc4eb867f350a374b5735ce0ed520288dac added that introduced the range filter. And when a user report a bug and it has been already fixed/tested, we identify the commit that fixed it and push 3.9.3 version instead of saying that "v3.9.1 is old, try the nightly", and then we can close the issue for good.

Or maybe this is a bad idea since it will *annoy* users when they get notified frequently about new versions of DB4S. Also, we can dedicate the 3.9.x versions to bug fixes only and leave everything else to the next major version. Which one do you prefer?

**Comment by chrisjlocke** [comment] 2017-07-02 08:17
Just a suggestion.  Monthly updates are handy.  If an issue has been fixed/tested, then that should go into the 3.9.x branch.  If a new feature has been added but is just a 'quick fix' and hasn't been tested, then that can wait for the main version.  If a user needs that feature, then they've still got the nightlies.
Monthly updates aren't 'too frequent' to annoy users, and keeps the project 'alive'.  If someone was interested in DB4S but saw 3.9.1 was released months ago, they could worry (and have sleepless nights) that it wasn't being developed much anymore.

**Comment by justinclift** [comment] 2017-07-02 10:20
@karim Yep, making a v3.9.2 branch sounds like a decent plan.  That way if the initial approach turns out to need changing or something we can do so without mucking up the v3.9.x branch.  And if the v3.9.2 approach does work out, we can merge it into the v3.9.x branch. :smile:

For the "size of releases"... I'd be more inclined to go with monthly batches-of-fixes as @chrisjlocke suggests, rather than individual ones.  That should somewhat minimise the annoyance at too many update notifications. :smile:

Hopefully many of the useful bug fix patches apply cleanly to the older v3.9.x source.  If not... well at least we investigated the option properly. :smile:

**Comment by MKleusberg** [comment] 2017-07-02 18:08
Or just go for the full 3.10 release? I've already started to prepare the release notes yesterday and could finish them easily :wink: Sure, dbhub.io integration wouldn't be as good as it could be but we can make that the main feature of 3.11. What do you think?

**Comment by justinclift** [comment] 2017-07-02 18:50
Not really bothered either way personally. :wink:

If we do go for a full 3.10 release instead, we'd want to have at least one round of beta or release candidates before making the final official release, just to be on the safe side. :smile:

**Comment by MKleusberg** [comment] 2017-07-02 19:42
I've just finished the release notes and copied them into a release draft. It's quite long. Any objections to releasing it as 3.10-beta and do the official release in a few weeks? Maybe we should move the discussion to the mailing list, too 😆

@DarylWM Sorry, for using you issue for this discussion! :wink: I hope it's working for you now.

**Comment by justinclift** [comment] 2017-07-02 19:55
@MKleusberg No objections here.  And yeah, probably a good idea to put this on the mailing list too for a more obvious central reference point for this discussion. :smile:

**Comment by justinclift** [comment] 2017-07-02 19:58
Oh, one important point.  I'm heading to London tomorrow, to attend [PGDay UK](http://www.pgconf.uk) on Tuesday.  Back home Wednesday evening.  I won't have access to the windows VM for doing builds/signing until I'm back.

**Comment by karim** [comment] 2017-07-03 04:31
Monthly updates sounds good. The problem with it, as @chrisjlocke said, is knowing which bug fixes/features to include.

@MKleusberg That's very good then. I was going to make small v3.9.x releases till v3.10 is ready. If you are going to release v3.10 then there is no need to bother with v.3.9.x now. Releasing a beta version first is fine.

After that, I hope that we find a better *release process* to make things easier for everyone. Maybe a monthly/quarterly release with everything that got fixed/added and confirmed to be working by us *and* the issue opener.

@justinclift Good luck and enjoy your time at PGDay UK. 😄

**Comment by justinclift** [comment] 2017-07-18 15:17
@MKleusberg Back from leave now.  Are we still wanting to release 3.10 soon?  I'm back home, so can sign binaries and stuff as need again. :smile:

**Comment by justinclift** [comment] 2017-08-20 18:32
Oops, we probably should have closed this one ages ago. :smile:

**Closed by justinclift** 2017-08-20 18:32 UTC
Labels: bug
