### ISSUE TITLE
BLOB

### ISSUE THREAD

**Issue by yura371** [sqlitebrowser/sqlitebrowser#229] opened 2015-03-18 18:54 UTC
When I create a BLOB in the field while maintaining it through the client software size of file twice as much than the original. Fix please.

**Comment by yura371** [comment] 2015-03-18 19:06
Here are two files https://drive.google.com/file/d/0B1rJ9TOTvh-VcHBKSWdFSFJaTFE/view?usp=sharing
One original and one saved by the client (connected to the base of this SQLITE3)

**Comment by justinclift** [comment] 2015-03-18 20:05
Which version is it happening for, and on which OS?

I've just tried it here on my desktop (OSX 10.9) using our latest nightly build.  For me it worked fine, with the export file being the exact same size as the imported file.

This is what I did to import it:

1. Open a database (a test one I often use)
2. Edited a field (type "REAL", but it should not matter)
3. Changed the type to "binary" (I do not know if that is important)
4. Imported original.jpg
5. "Write Changes" to the database, then quit

To export it, this is what I did:

1. Open the database
2. Edit the field
3. "Export" button.  Saved the image.

The exported image is the same size as original.jpg for me.

Does that help at all?

**Comment by Z4us** [comment] 2015-03-18 21:37
I downloaded your files and 'file *'-result:


clientopen.jpg: data
original.jpg:   JPEG image data, JFIF standard 1.01

Editing filetype seems a bad idea

**Comment by justinclift** [comment] 2015-03-18 22:19
@Z4us Well, by "edited a field" I mean I double clicked on it in the Browse Data tab, so it brought up the dialog with the import and export buttons.

**Comment by Z4us** [comment] 2015-03-19 08:03
Sorry, Justin, I misunderstood, my bad.
Apparently it does matter if the type is real or anything else of numeric nature.
Try one with type BLOB (eventually TEXT)

Perhaps this is helpful: https://www.sqlite.org/intern-v-extern-blob.html

As Italians express it: IBAL (i.e. "in bocca al lupo")

**Comment by justinclift** [comment] 2015-04-15 10:27
@yura371 Would you be ok to try our latest nightly build, and let us know if the problem is completely fixed for you?

In theory it should be now, due to the fix by @schdub.  But, it's always good to verify. :smile:

**Comment by MKleusberg** [comment] 2015-06-08 10:36
I've just tried to reproduce this but weren't successful. The exported file with twice the size looks like it's been treated as a Unicode text file during export. But I have no idea how to make DB4S doing this...
The only thing I noticed is that importing an image into a field and then editing the table schema destroyed the image data (but by deleting bytes rather than adding bytes).

So *I think* we can close this issue and assume it's fixed in the latest build if there's no follow-up information on this coming.

**Comment by MKleusberg** [comment] 2015-06-08 10:40
Edit: Now I'm taking back the data corruption from table schema editing, too. This probably happened because I single clicked into the cell first, thus opening the inline editor which doesn't handle binary data correctly.

**Comment by justinclift** [comment] 2015-06-08 16:38
What do we need to do, to make it handle binary data correctly? :smile:

**Comment by justinclift** [comment] 2016-08-25 13:31
@MKleusberg Any idea what the status of this one is?

**Comment by justinclift** [comment] 2016-09-05 19:11
Closing this due to lack of response.

**Closed by justinclift** 2016-09-05 19:11 UTC
Labels: bug, response requested
