### ISSUE TITLE
"The database is currently busy", but it is not

### ISSUE THREAD

**Issue by raffaem** [sqlitebrowser/sqlitebrowser#2879] opened 2021-10-23 16:45 UTC
I have a `.sqbpro` file. It looks like SQL code inside XML tags.

When I open it in "DB Browser for SQLite", the software asks me to select a database file.

I open my `.sqlite3` file, and "DB Browser for SQLite" shows me the following error message:

![image](https://user-images.githubusercontent.com/54762742/138564781-12eecc58-f6c6-43be-a90c-4f333d2f77e2.png)

The database is not open in any other application whatsoever. 

Why I get this error message?

If I select "Yes", the database is opened without problems.

I have:

DB Browser for SQLite Version 3.12.99 (Sep  1 2021)

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.15.2
SQLite Version 3.34.1.

EDIT: fixed screenshot

**Comment by chrisjlocke** [comment] 2021-11-03 18:43
Just a nod that this is a duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/2567.
With 450+ open issues there are bound to be duplicates...
I'll close this as it is a duplicate, so worth subscribing to the other issue if you need to follow up on any progress related to this issue.

**Closed by chrisjlocke** 2021-11-03 18:43 UTC
Labels: linux, opening database
