### ISSUE TITLE
cannot import CSV file into DBBrowser for sqlite

### ISSUE THREAD

**Issue by marathonsteve** [sqlitebrowser/sqlitebrowser#1714] opened 2019-01-20 16:34 UTC
### Details for the issue

Cannot import a CSV file intl SQLITE using DB Browser for SQLITE.

It DOES work fine when the CSV file has around 1000 records, including  column names in the first record. But it fails when the CSV file has around 10000 records, yet the failure is on "record 1" which is the same regardless of how many records are in the CSV file.

The error message is "Error importing data from record number 1. Failing row had 9 columns but 11 values were supplied..." and it goes on to list the 11 values showing the last 2 values as "null,null". It really does have only 9 values and the CSV file really has only 9 comma delimited fields. I have examined the csv file using HEXEDIT and after the 9th value, it is followed by a carriage control and linefeed, (0D, 0A)  as each row is.

It  is as though there is a small memory area available to load the csv file into, and when that limit is exceeded, it corrupts itself in memory. Any ideas?

The CSV file is created by a Delphi program, so I can limit the number of records. A related problem was that the csv file contains a file name, like "myfile.txt" and the dot before the "txt" file extension was being treated like a comma. I had to change the program that creates the CSV file to use an underscore instead of a period, and it worked fine until the number of csv records got somewhere around 1000.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by marathonsteve** [comment] 2019-01-20 16:36
Cannot import a CSV file intl SQLITE using DB Browser for SQLITE.

It DOES work fine when the CSV file has around 1000 records, including  column names in the first record. But it fails when the CSV file has around 10000 records, yet the failure is on "record 1" which is the same regardless of how many records are in the CSV file.

The error message is "Error importing data from record number 1. Failing row had 9 columns but 11 values were supplied..." and it goes on to list the 11 values showing the last 2 values as "null,null". It really does have only 9 values and the CSV file really has only 9 comma delimited fields. I have examined the csv file using HEXEDIT and after the 9th value, it is followed by a carriage control and linefeed, (0D, 0A)  as each row is.

It  is as though there is a small memory area available to load the csv file into, and when that limit is exceeded, it corrupts itself in memory. Any ideas?

The CSV file is created by a Delphi program, so I can limit the number of records. A related problem was that the csv file contains a file name, like "myfile.txt" and the dot before the "txt" file extension was being treated like a comma. I had to change the program that creates the CSV file to use an underscore instead of a period, and it worked fine until the number of csv records got somewhere around 1000.

**Comment by marathonsteve** [comment] 2019-01-20 16:37
it appears that the initial submission did not post the description. Apologies if it appears twicw.

**Comment by justinclift** [comment] 2019-01-21 00:52
No worries @marathonsteve.  The original submission has some tags '<!--' `-->` used for hiding stuff from the HTML display, but used to give instructions in the issue template itself.  Looks like the initial submission was accidentally inside the tags, so it didn't get included.

Just fixed that bit, and nuked the 2nd comment for good measure. :smile:

---

With the CSV import problem, what it sounds like (to me) is that somewhere after the ~1000 or so lines, there likely exists one line with field(s) that aren't being quoted correctly for some (for now unknown) reason.

There are a couple of potential ways to fix this. :wink:

* Depending on which version of DB Browser for SQLite (DB4S) you're using, you might be hitting a bug fixed in a newer release.  It should be pretty safe to try the latest nightly build, and see if that does better:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

* The CSV import dialog has various options for escaping fields.  Try the various ones out, and see if they do any better.
  * This generally helps if you know what's going wrong with the escaping.  So you might need to nail down the exact line + fields that are going wrong, and have a look what's in them.  For me, this often leads to "Aha!" moments and a solution soon after. :smile:

* Alternatively, if you're ok with using the command line (eg `cmd.exe`, powershell, etc), then trying the sqlite command line client might work.  Its approach to importing csv is slightly different to ours, so it might not have the same escaping problem you're hitting.

Hopefully some of the above helps. :smle:

**Comment by chrisjlocke** [comment] 2019-01-21 10:03
Is the data secret?  If you could email me your CSV and database, I can attempt to assist.  db4s [at] chrisjlocke [dot] co [dot] uk.
Theoretically, the nightly should do a better job of importing though.

**Comment by marathonsteve** [comment] 2019-01-21 16:33
Thanks for your offer, Chris.
I have solved the problem by not including a header line of column names as the first record in the csv file.
I made sure that none of the column names contained any special characters or any words that might be "reserved" words.
After the import, which is lightning fast for 400,000 plus records, I use DBBROWSER to rename the default column names. 
I had previously gotten it to import successfully with column names with under 10.000 records but it fails when I used over 20,000 records. Then, I changed the header line to use longer text values for the header line, and more than 30,000 records worked, but over 40,000 did not . But it works fine as long as I do not use a header line.

**Comment by chrisjlocke** [comment] 2019-01-21 16:37
Glad it worked eventually.  Again, it would be handy for the CSV and database to try and create a 'sample' case to replicate this issue - theoretically it should work, so would be good to squash this issue.
If the data is sensitive then that's fine - I'll try and create a 400,000 line CSV file.  I'm trying to work out why changing the headers (and what you changed them from and to) allowed DB4S to import more records...

**Comment by justinclift** [comment] 2019-01-22 02:03
Yeah, this does sound weird.  When testing stuff out, we sometimes use files in the 1/2 GB+ range (eg [UK postcodes](https://data.gov.uk/dataset/7ec10db7-c8f4-4a40-8d82-8921935b4865/national-statistics-postcode-lookup-uk)) just for testing.

10k records shouldn't be having a problem (size wise), so it sounds like a bug in our code somewhere is being triggered.  Which would be useful to track down and solve. :smile:

**Comment by marathonsteve** [comment] 2019-01-22 23:44
Chris,
I had emailed you a csv file with 10,000 records, and a db file  yesterday that demonstrate the problem.
I am now thinking that I should have attached the files here instead of using email. Rather than attach them now, I will hold off until I hear from you...I don't want to blast too much stuff at you.

**Comment by justinclift** [comment] 2019-01-22 23:55
Thanks @marathonsteve.  @chrisjlocke will almost definitely get to it sometime in the next day or two. :smile:

Out of curiosity, which version of DB Browser for SQLite is this happening with?

The version number can be found in `Help` -> `About` (or similar wording) from the main menu bar. :smile:

**Comment by marathonsteve** [comment] 2019-01-23 01:04
Version : 3.10.1,  QT Version 5.7.1, SQL Cipher version: 3.15.2

**Comment by justinclift** [comment] 2019-01-23 02:58
Thanks @marathonsteve, that does help. :smile:

**Comment by chrisjlocke** [comment] 2019-01-23 09:41
> I had emailed you a csv file with 10,000 records

What address did you use?  I've not received anything yet.  Can you resend it to db4s@chrisjlocke.co.uk
(The address above was an attempt to obfuscate against spammers, but I think I may have made it too complicated and unclear...)

**Comment by chrisjlocke** [comment] 2019-01-23 14:14
I've tried using the latest nightly, and it worked fine.  I increased the rows in the spreadsheet from 9999 rows to just over 1.3 million, and it imported in approx. 5 seconds.

![image](https://user-images.githubusercontent.com/7872218/51612007-81457600-1f18-11e9-8610-8f0926596d7f.png)

@marathonsteve - Can you try using the latest nightly?  Importing has been greatly improved since v3.10.1.
https://nightlies.sqlitebrowser.org/latest/

I'd probably suggest [downloading the .ZIP](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip), extracting that and run the .exe, otherwise the .MSI installer might remove your existing 3.10.1 version, and we don't want to do that yet....

**Comment by marathonsteve** [comment] 2019-01-23 16:11
Problem served! It was because  my column containing  file names had a "-" in the filename
like .....64-bit...
Easily fixed.
I will download the zip file anyway, as I want the current version. Thanks all, for your help.

**Comment by chrisjlocke** [comment] 2019-01-23 17:08
Weird that dashes would have broken the delimiting.  If you can confirm the latest version has no issues.  It seemed fine for me, but better you can confirm.

**Comment by marathonsteve** [comment] 2019-01-23 17:44
I hate to report another problem, but I did unload the zipfile, and after extracting, I moved the folders manually as I did not see an install or setup program. I had previously used control panel to uninstall the older version.

The new version seemed to work. I never tried the import again, as I had already does the import after changing all the dashes. But I get wrong results when I use the max function.

This sql worked:
select ext, fsize from broken_oracle60
This does not
select ext, max(fsize) from broken_oracle60
there is no error message but the max(fsize) shows up as the path name
and the ext value is a scrambled set of letters that no record has

**Comment by marathonsteve** [comment] 2019-01-23 17:50
sorry...false alarm.
this was caused by garbage in my csv file

**Comment by chrisjlocke** [comment] 2019-01-23 18:19
> but I did unload the zipfile, and after extracting, I moved the folders manually as I did not see an install or setup program. I had previously used control panel to uninstall the older version.

Yes, sorry - my instructions were a bit vague.  I did put 'run the .exe,' but should have been more explicit.  I also hinted at not uninstalling the previous version ("and we don't want to do that yet") but ... well, its not important.  You can always re-download v3.10.1 again.  Ideally, its not recommended you run the nightly version in a 'production' environment.  While they contain fixes for some issues, they also have their own issues...

You mentioned about changing the dashes - is that acceptable?  I assume your system for reading the filenames won't get upset about the filenames being now invalid?

**Comment by marathonsteve** [comment] 2019-01-23 19:11
The source of the dashes is from Corel and Windows accepts it as part of the file name. Here is the actual filename from a command prompt dir command:
C:\PROGRAM FILES\COREL\COREL VIDEOSTUDIO X9\ULEAD.DAT\WMV_PROFILES\ULEAD - WMV (1280X1024,25P).PRX
I recurse through all filenames in Delphi using a findfirst and findnext so they are stored in oracle as I find them. My filefind program does not care if there is no longer a dash in the filename.  It only matters if the end user (only myself so far) wants to include the dash as part of his search.
I have changed my export to csv program to change dashes to underscores, not in the physical file name, but the name being written to the csv file. An earlier posting had a reference to a link for how to export from Oracle to a csv file using SQPLUS, but it did not work for me...every other line in the csv file included a filename, repeated on another line.

My export is running now, around a million records, so I will post the results for that soon. I actually have around 400,000 files on my hard drive, but they have been loaded 3 or 4 times, each record containing the date is was loaded. Then I can use  a select where load date is most recent date and not exists 
 select where load date is previous load date, showing me what files were added to my hard drive.
I can easily change the values for the 2 dates so it shows what files were recently deleted from my hard drive.

**Comment by marathonsteve** [comment] 2019-01-23 22:03
I have had 2 or more import failures. One was causes by a comma insoder a file name, and the other was caused by a single quote in those fields. The files actually hard those characters, and db browser imports them, but the resulting fields are scrambled for those records. I changed my Oracle Export to CSV program to replace those characters with underscores.

I don't plan on retesting my export to allow dashes as now I am on the current version, because it still fails on the other 2 problems I just mentioned. I still need to test it more. I have almost a million records but I cannot be sure some of the records are still scrambled due to other special characters.

**Comment by chrisjlocke** [comment] 2019-01-23 22:06
> One was caused by a comma inside a file name

Was the filename delimited?  ie, did it have quotes around it?  "some,filename" - DB4S should be able to handle correctly delimited fields.

**Comment by justinclift** [comment] 2019-01-23 23:49
Reading over this, things are still sounding weird.  We have a bunch of code that's supposed to detect when things need escaping, and then take care of it.  Doesn't seem to be kicking in though. :frowning: 

@marathonsteve  Is there any chance you could do a screenshot of the settings you're using for the CSV import dialog?

Guessing you have that all set up correctly, but just in case, so we can look them over and maybe spot whatever is causing this weirdness. :smile:

**Comment by chrisjlocke** [comment] 2019-01-24 10:16
@justinclift - I suspect the CSV is more broken than the code.  Note there are no delimiters around the filename.
![image](https://user-images.githubusercontent.com/7872218/51671430-d6d55d80-1fc0-11e9-81a7-a2c70edfd429.png)

**Comment by justinclift** [comment] 2019-01-24 10:21
Ugh yeah.  Sounds like the Oracle exporter needs to be told to quote all fields.  If it can do that, the problem should be solved. :smile:

**Comment by chrisjlocke** [comment] 2019-01-24 17:36
Closing this, as the issue appears to be CSV related.  
@marathonsteve - feel free to comment further if you think the issue is with DB4S.

**Closed by chrisjlocke** 2019-01-24 17:36 UTC

**Comment by Mr-Ventures** [comment] 2019-05-15 08:34
Here is an example of a file I was using that threw the error. I was able to fix it on the data side but it seemed to be caused by the two adjacent apostrophes. Was not able to repro on anything but this example. Hope it helps.
https://drive.google.com/file/d/1yVsoO4ZMIDydeZ8lO3d9snQle8cgajAy/view?usp=sharing
