### ISSUE TITLE
Adding a VARCHAR data type to the selection field.

### ISSUE THREAD

**Issue by jirihunacek** [sqlitebrowser/sqlitebrowser#2525] opened 2021-01-01 18:17 UTC
Describe the new feature
--------------------------

Please add a VARCHAR data type, it's better than just using the TEXT type, because the TEXT type always shows up as a MEMO in DBGrid (when I use SELECT *) and it has to be more complicated to list all columns and the text columns have to be listed like this ( SELECT CAST (TEXTCOLUMN as string) as TEXTCOLUMN) to display the contents as a string. Thank you very much George

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
Yes, for example in [SQLite Studio](https://sqlitestudio.pl/).

#### Do you have a screenshot? Please add screenshots to help explain your idea.
[Screenshot from SQLite Studio](https://drive.google.com/file/d/18N0uUQcQx_qH8fiSQbh7WL3N3tVkAnVm/view?usp=sharing)

**Comment by chrisjlocke** [comment] 2021-01-02 00:28
SQLite doesn't support 'varchar'.  It only supports integer, text, real, numeric and blobs.  
You mention 'DBGrid'.  Is this in Visual Studio?

**Comment by jirihunacek** [comment] 2021-01-02 00:51
You are right that SQLite does not have VARCHAR. However, the column can be defined in this way ([SQLite Data Types](https://www.sqlite.org/datatype3.html) - section 3.1.1.). The proof is also a screenshot from the SQLite Studio application. In the **DB Browser for SQLite** application, it is also possible to define a column in this way, but by writing this type manually, which I do quite normally. All I wanted was to be part of the selection alongside the basic types.

The DBGrid I mentioned works like this in the LAZARUS (Free Pascal) application.

**Comment by justinclift** [comment] 2021-01-02 04:46
Hmmm, is there any chance the DBGrid people could make the change, so their application understands `TEXT` properly?

Personally, I reckon that seems like the more sensible approach.  However, if they're completely unwilling to then we **might** be able to figure something out.

**Comment by chrisjlocke** [comment] 2021-01-02 08:45
I'm sure DB4S used to 'remember' the data types entered (not permanently, but at least during the session) so if you added a type of 'banana', it did add it to the dropdown list.  It doesn't seem to do that anymore.  Going back, it doesn't look like it actually did, so might have been a temporary thing.
I still can't see the benefit though - ideally the dropdown should be a list of valid datatypes, not just a list of 'compatible' entries, otherwise it would also contain 'double', 'boolean' and 'date', etc.  
I think remembering the entered data type is the best compromise,

**Comment by justinclift** [comment] 2021-01-02 09:16
Oh, I also thought tables remembered the data type they were created with.  Didn't realise that it's no longer the case.

Wonder if that was a change we did, something from the underlying SQLite library, or we're both mis-remembering?

**Comment by jirihunacek** [comment] 2021-01-02 10:00
Yes DB4S remembers the data type that I enter for the column, but only for this column. If I create a new column, it again offers only basic types in the drop-down list.

DBGrid can be set by checking `dgDisplayMemoText` in the options to display `TEXT` correctly as a string, but other controls connected to the database (such as DBLabel, DBEdit, etc ...) do not have this functionality and always display strings as "(MEMO)".

Therefore, it would be useful to add at least this one data type to the list, or at least to remember it within the current session or within a particular database. So far, I have to manually enter this data type for each text column and it's quite inconvenient.

**Comment by chrisjlocke** [comment] 2021-01-02 11:04
"it would be useful to add at least this one data type to the list"
I'm not meaning to be a prick (honest) but it seems weird to 'break' DB4S to allow it to be compatible with another piece of software which is broken.  Someone else is going to ask to add 'ddate' as their software doesn't like 'date' or it means something else, etc.  You're then getting into the realms of custom lists (so you can have what you want and its not broken for others) but even that takes a fair bit of coding - where to add those entries, etc.  

> Oh, I also thought tables remembered the data type they were created with.

I'm 96.23% sure it did, but I went back to v3.4 and that didn't do it.  When you created a new table and added a data type, when you added a new field, that new datatype was in the list.  I remember it did, as it wasn't case sensitive, so you could have two 'text' entries.  Or tExt, Etc.  I'll have a dig back a bit further and try some older nightlies - might just be a nightly tweak.

Hopefully if we can fix/revert that issue, that'll be a workable solution.

**Comment by mgrojo** [comment] 2021-01-02 13:07
This was already discussed in #1541 and the idea was to add all the datatypes in use in the current database, but it is not currently implemented. I don't know if we've ever had something simpler for the values added in the session.

I'll close this now as duplicated because we have an overwhelming long list of suggestions. @jirihunacek you can subscribe to #1541 to get any update. The conversation here can follow, although the issue is closed.

**Closed by mgrojo** 2021-01-02 13:07 UTC

**Comment by justinclift** [comment] 2021-01-02 14:11
@jirihunacek Also, it might be worth asking the DBGrid people if they can add support / understanding for the "official" SQLite data types.  That way it should work properly throughout (hopefully) all parts of their application. :smile:

**Comment by jirihunacek** [comment] 2021-01-02 14:28
I don't know how complicated it is in DB4S, but I thought it was easier to add one line to the drop-down list than to try to remake part of a large application - the DBGrid administration part. But it's possible that it's just as (or maybe even more) complicated.

I don't know, the development goes on and someone probably bothered so many types. 😄 I'm sorry to turn away now, but apart from this, I generally don't think it was a very good idea to write SQLite as typeless. Just as in programming languages, people have to learn the types of variables that are required, so databases should follow this. A successful example is PHP, where it is not even necessary to declare variables, or the declaration takes place by assigning a value, and this seems to me to be the worst idea anyone has come up with. I think that for people who are just learning to code, it will only bring confusion and unnecessary mistakes. But it's the view of a man who learned to program around 1997 on FoxPro 2.6. 😄

**Comment by chrisjlocke** [comment] 2021-01-02 15:14
"but I thought it was easier to add one line to the drop-down list"
That's one line of code, which would take 2 seconds to do, but it would be wrong - 'varchar' is not a datatype for SQLite.  As above - if we add 'varchar', we'd also have to add 'double', 'date' and 'float' - they're all valid types too, oui?  But, what's the point - SQLite doesn't support them - it has no idea what 'date' is, but knows to treat it as text.  Text, integers, reals and blobs - that pretty much covers all types.

" I generally don't think it was a very good idea to write SQLite as typeless"
It isn't - it has four types.  

" so databases should follow this"
It does.  If I define a field as 'integer', DB4S stores `0` as `0`, and not in a textual form as `'0'`.

Again, hopefully we can solve this by simply remembering the datatype you enter, or allowing a custom list.  But adding superfluous types into the list isn't the right solution - otherwise the list would be full from the link you provided...

**Comment by jirihunacek** [comment] 2021-01-02 15:38
Statement from SQLite.org:
**SQLite is "typeless". This means that you can store any kind of data you want in any column of any table, regardless of the declared datatype of that column.**
I think it's wrong, but let's be it.

Allowing a custom list would, in my opinion, be the best choice for everyone to put in what they want.

**Comment by chrisjlocke** [comment] 2021-01-02 15:51
I'll add the 'enhancement' label so that this can be looked into once things have settled down. 😃 
Thanks for reporting it, and for your patience while this was discussed.  👍
