### ISSUE TITLE
Preference field colors reset back to black every time they are changed (macOS)

### ISSUE THREAD

**Issue by compengi** [sqlitebrowser/sqlitebrowser#852] opened 2016-10-30 21:02 UTC
### Details for the issue

Hello everyone, the latest DB Browser has a weird issue. The default field colors for showing the result table is black. I tried to change that from the app preferences, it works for the current app instance but resets back to black when the app is reopened.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version: 10.12.1)
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2016-10-30 21:39
Ahhh, this seems to be specific to Sierra.  We've had a few reports of this, but haven't yet tracked down what's causing it. 😦

**Comment by brozikcz** [comment] 2016-11-14 14:22
Same problem :/

**Comment by brozikcz** [comment] 2016-11-23 06:48
Workaround: delete pref ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist

**Comment by justinclift** [comment] 2016-11-23 22:20
Actually, I'm going to close this as it's a duplicate of #737.  So, probably best to keep an eye on progress there.

**Closed by justinclift** 2016-11-23 22:20 UTC
Labels: bug, osx
