### ISSUE TITLE
in-memory sqlite

### ISSUE THREAD

**Issue by tbayart** [sqlitebrowser/sqlitebrowser#335] opened 2015-06-03 12:18 UTC
Beside me, anyone else could find useful to be able to open an in-memory sqlite database ?
https://www.sqlite.org/inmemorydb.html

**Comment by glawrence** [comment] 2015-06-03 17:17
I understand the advantages of in-memory databases, however you will notice on that web page that "all database connections sharing the in-memory database need to be in the same process". This means you could create a database in DB4S but it would not be available to any other process and DB4S could not open one belonging to another process. So adding this feature would seem to me to be of limited use. However if you can help explain a good use case or you want to add this yourself via a pull request then please, fire away.

**Comment by tbayart** [comment] 2015-06-04 08:48
I know you can't open an existing in-memory database.
I was thinking this could be useful for testing purpose only.
Instead of creating a database file which need to be dropped / deleted when you want to test something else or test a database generation script.
Not a priority enhancement, I admit :wink:

**Comment by glawrence** [comment] 2015-06-04 11:03
Right, okay, I see what you mean now, thanks for explaining. Are you able to implement this yourself?

**Comment by tbayart** [comment] 2015-06-04 12:17
Maybe, need to take time and look into the code.
Btw, is there a howto build/compile DB4S somewhere ?
or at least a "required" list of things I need to be able to build it ?
I work with visual studio 2013 community

**Comment by justinclift** [comment] 2015-06-04 13:42
@tbayart There is https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md, which is supposed to have all of the building info in it.

I think it's out of date for Windows though, having only the previous approach listed (cross compiling from Linux using MXE).  @rp- has been working on a new build process using Visual Studio, but I don't think it's documented yet.  That being said, it may not be too hard to figure out (unsure).

**Comment by tbayart** [comment] 2015-06-04 16:30
Thanks for the link
I will check and report

**Comment by justinclift** [comment] 2016-01-07 00:31
@glawrence We should probably get the initial Windows building instructions onto the wiki, see if we can find people to test them out/fix/tweak/whatever as needed so they're correct, then possibly add them to BUILDING.md.

Any interest in getting that started, then making a call out through Twitter (main DB4S account) or similar for people to help with them? :smile:

**Comment by glawrence** [comment] 2016-01-07 22:25
As per my other recent comment, yes we should and I will have a go at this as soon as I get time, which I hope is actually soon!

**Comment by justinclift** [comment] 2016-01-08 10:01
Awesome.  Hoping so too. :wink:

**Comment by MKleusberg** [comment] 2018-08-05 13:52
Are you still around, @tbayart? It's been a long time but we finally added a new menu option for this :smile: If you're still interested, can you give tomorrow's nightly build a try and see if it works for you?

**Comment by MKleusberg** [comment] 2018-08-10 10:01
I'll close this issue because the in-memory databases have been confirmed to work in #1492 and we have way too many open issues at the moment :wink: But if you should notice any problems with this or if I have missed something, please just just reopen this issue, @tbayart :smile:

**Closed** 2018-08-10 10:01 UTC
Labels: enhancement, response requested
