### ISSUE TITLE
SQLite Browser Saving Error

### ISSUE THREAD

**Issue by ulascanerturk** [sqlitebrowser/sqlitebrowser#1008] opened 2017-05-08 09:14 UTC
Save Error for SQLite Browser

When i press the 'write changes' button, i take error : 
Error while saving the database file. This means that not all changes to the database were saved. You need to resolve the following error first.

no such savepoint: RESTOREPOINT (RELEASE RESTOREPOINT;)

I cannot fixed this problem! Please help.

#### I'm using DB4S on:

- [x] Linux: ( _distro:_ ubuntu 16.04 LTS___ )

**Comment by chrisjlocke** [comment] 2017-05-08 09:26
What version of DB4S?

**Comment by ulascanerturk** [comment] 2017-05-08 09:39
Version 3.9.99

Qt Version 5.5.1

SQLite Version 3.11.0

**Comment by MKleusberg** [comment] 2017-05-08 09:49
Does this happen whenever you try to save a database? Or is the error limited to some databases or only some changes made to a db?

**Comment by ulascanerturk** [comment] 2017-05-08 09:52
happen whenever i try to save a database. i can establish a table but after that its delete by itself because i cannot save the file. Also :
bunny@bunny-laptop:~$ sqlite -version
2.8.17
bunny@bunny-laptop:~$ sqlite3 -version
3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f

i dont know it is about or not?

**Comment by chrisjlocke** [comment] 2017-05-08 09:54
> Version 3.9.99

That means its a nightly build.  What is the date of this version?  (ie, which nightly is it?)

**Comment by ulascanerturk** [comment] 2017-05-08 09:58
I think its the latest version because i downloaded from website via instructions for ubuntu.

**Comment by MKleusberg** [comment] 2017-05-08 10:17
@ulascanerturk Looks like we link to two different PPAs for Ubuntu packages. One has a version from August 2016 and one has today's version. Can you post the output of the shell command to find out which one you're using?
```
grep sqlitebrowser /etc/apt/sources.list
```

The two different SQLite versions by the way shouldn't be the problem. We're only ever using the 3.x versions and ignore all other.

**Comment by ulascanerturk** [comment] 2017-05-08 10:25
There is nothing come from this command.

**Comment by MKleusberg** [comment] 2017-05-08 10:34
Ok sorry, my bad. Can you try this one, too?
```
grep sqlitebrowser /etc/apt/sources.list /etc/apt/sources.list.d/*
```

**Comment by ulascanerturk** [comment] 2017-05-08 10:37
@MKleusberg 

/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-testing-xenial.list:deb http://ppa.launchpad.net/linuxgndu/sqlitebrowser-testing/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-testing-xenial.list:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser-testing/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-testing-xenial.list.save:deb http://ppa.launchpad.net/linuxgndu/sqlitebrowser-testing/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-testing-xenial.list.save:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser-testing/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list:deb http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list.save:deb http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list.save:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list.save:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list.save:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main
/etc/apt/sources.list.d/linuxgndu-ubuntu-sqlitebrowser-xenial.list.save:# deb-src http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial main

**Comment by MKleusberg** [comment] 2017-05-08 12:22
Hmm... so you should have the latest version. I assume you have updated your system?

This seems to be the same issue as in #836 and maybe #878. What is still irritating me is that this is supposed to happen no matter what changes you make. Is it also happening when you're creating an entirely new database, add some test data to that, and save then?

**Comment by ulascanerturk** [comment] 2017-05-08 12:33
this is exactly the same problem with #836 but I don't understand what is the solution. Yes, i've updated the system and set up the program repeatedly but still error. By the way, i can create a new database but when I try to add data and press the save button error come then.

**Comment by justinclift** [comment] 2017-05-09 10:52
@ulascanerturk As thought, would you be ok to try compiling our program yourself?  Asking because this bug *really* should be fixed by some changes we did a while back. So I'm kind of suspecting that **somehow** the packages you've got don't include it.

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

If you're ok to compile our program yourself, that would pretty much tell us if it's a problem in the packages or if it's a problem with our latest code still. :smile:

**Comment by ulascanerturk** [comment] 2017-05-09 11:31
@justinclift I cannot compile the program myself, unfortunately.

This is the output of terminal while terminally is open. Maybe you can help me after this.

`~$ sqlitebrowser
executeSQL:  "COMMIT;" -> cannot commit - no transaction is active
Sqlite parse error:  "line 2:25: unexpected char: 'I'" ( "CREATE TABLE `list` (\n\t`Field1`\tINTEGER PRIMARY KEY AUTOINCREMENT,\n\t`Field2`\tINTEGER,\n\t`Field3`\tINTEGER,\n\t`Field4`\tINTEGER\n)" )
executeSQL:  "RELEASE RESTOREPOINT;" -> no such savepoint: RESTOREPOINT
Sqlite parse error:  "line 2:25: unexpected char: 'I'" ( "CREATE TABLE `list` (\n\t`Field1`\tINTEGER PRIMARY KEY AUTOINCREMENT,\n\t`Field2`\tINTEGER,\n\t`Field3`\tINTEGER,\n\t`Field4`\tINTEGER\n)" )
Sqlite parse error:  "line 2:25: unexpected char: 'I'" ( "CREATE TABLE `list` (\n\t`Field1`\tINTEGER PRIMARY KEY AUTOINCREMENT,\n\t`Field2`\tINTEGER,\n\t`Field3`\tINTEGER,\n\t`Field4`\tINTEGER\n)" )
executeSQL:  "INSERT INTO `` DEFAULT VALUES;" -> no such table: 
addRecord:  "no such table:  (INSERT INTO `` DEFAULT VALUES;)"
Sqlite parse error:  "line 2:25: unexpected char: 'I'" ( "CREATE TABLE `list` (\n\t`Field1`\tINTEGER PRIMARY KEY AUTOINCREMENT,\n\t`Field2`\tINTEGER,\n\t`Field3`\tINTEGER,\n\t`Field4`\tINTEGER\n)" )
`

**Comment by justinclift** [comment] 2017-05-09 14:01
@ulascanerturk Co-incidentally, I'm checking over our instructions for compiling on Debian and Ubuntu today, so I'll take a look at this problem while I'm at it.

I'll probably test out the version of "sqlitebrowser" that comes from the place you're getting it, and see if the same problem happens here.  If so, that should mean I can figure out a reasonable way forward. :smile:

**Comment by ulascanerturk** [comment] 2017-05-09 18:47
After I compiled the program with codes from here: 
[]( https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux)

Problem solved.
Still, there is an error like that ' Sqlite parse error: ' but I can create a table and add variables.

**Comment by justinclift** [comment] 2017-05-09 18:52
@ulascanerturk Thanks, that sounds like good progress.

Would you be ok to screenshot that `Sqlite parse error` if it happens again?  Just so we can check + make sure it shouldn't hurt anything. :smile:

**Comment by MKleusberg** [comment] 2017-05-12 08:13
Sounds like some problem with the PPA binaries then. I have no idea why that happens because it seems to work for most people, except for @ulascanerturk and @NicoDupont in issue #836.

By the way, I'm wondering: the version is 3.9.99 which means it's the nightly build, i.e. using the latest code. And it says Qt version 5.5.1 which makes sense because both @ulascanerturk and @NicoDupont are on Ubuntu 16.04. But from that other discussion I remember that our current code doesn't even compile with Qt 5.5. So how is that binary even compiled? If I had to make a wild guess I'd say that it probably isn't. The compilation really should fail any maybe, just maybe, the last working version is uploaded again and again to the PPA. At least that would explain everything :wink:

As for the parse error: I can't seem to reproduce this using the latest version either. The table definition looks super simple, too.
@ulascanerturk Can you send us the database that produces this error? It doesn't need to contain any data at all, just the empty ```list``` table that causes the problem :smiley:

**Comment by MKleusberg** [comment] 2017-05-12 08:57
@ulascanerturk Can you update the sqlitebrowser package tomorrow (or any later date)? If my theory proves right there should be a new version in the PPA tomorrow which might fix the problem :smiley: If not, we'll investigate further.

**Comment by ulascanerturk** [comment] 2017-05-13 06:50
@justinclift yes the error is exactly.
@MKleusberg i will update the program today, thanks for help :+1:

**Comment by NicoDupont** [comment] 2017-05-13 12:05
Hi ! I updated this morning and the error seems to be fixed :)
Thank you for your work :)

**Comment by MKleusberg** [comment] 2017-05-14 09:20
Thanks for testing, @NicoDupont :+1: I'm glad it works now :smiley:

**Comment by justinclift** [comment] 2017-05-14 15:25
@ulascanerturk Did you get a chance to try the latest nightly build out?

Just asking as I'm trying to reduce the number of open issues we have (correctly though). :wink:

**Comment by ulascanerturk** [comment] 2017-05-15 15:31
I tried but still, there is the same error. But I think now this problem is on my own computer. Because I try to delete program first. After I delete the program, still it's been.When try to delete again, I take the error which is SQLite browser not exist on this computer but I can open the program. After I will fix this problem I hope problem work regularly.

**Comment by ulascanerturk** [comment] 2017-05-15 16:10
Thank you for your help :+1: 
Should I close the issue or not? This is my first github experience :smile:

**Comment by justinclift** [comment] 2017-05-15 17:21
Probably, yeah. 😄 

Welcome to GitHub by the way, hope it was a decent experience. 👯

**Closed** 2017-05-17 08:51 UTC
Labels: linux

**Comment by MKleusberg** [comment] 2017-05-17 09:44
@ulascanerturk Maybe this is because of the manual installation. Do you still have the compile directory? If so, you can try opening a terminal in the ```build``` directory and type
```
sudo make uninstall
```

If you need any assistance, feel free to ask :smiley:

**Comment by justinclift** [comment] 2017-05-17 10:13
@MKleusberg Hmmmm, are you sure CMake includes a "make uninstall" target?  I could have sworn that was one of the things missing for it.

**Comment by MKleusberg** [comment] 2017-05-17 10:18
@justinclift Oh wow you're right. How can they have an install but no uninstall target?!

@ulascanerturk In this case just delete ```/usr/local/bin/sqlitebrowser```. That's the only (important) application file that was installed.

**Comment by ulascanerturk** [comment] 2017-05-17 19:44
for information the program works well :+1: 
Thanks for all your help :smile:
