### ISSUE TITLE
JSON mode for cell editor

### ISSUE THREAD

**Issue by wmertens** [sqlitebrowser/sqlitebrowser#1173] opened 2017-10-15 11:53 UTC
### Details for the issue

It would be really handy if the cell formatter could handle JSON, much like for example http://jsoneditoronline.org/

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 10.13 )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pamtbaau** [comment] 2017-10-17 06:48
Was just about to request the same enhancement. But simpler... beautifying the JSON text and minify  on save, would already be a great improvement.

**Comment by mgrojo** [comment] 2017-11-15 22:29
I'm working on this based on the QScintilla editor component we already use for the SQL tabs. Don't expect anything too fancy, just syntax-highlighting and folding.

Minifying is a different feature. For that the [JSON extension](https://sqlite.org/json1.html) could be used, but I think that should be left to the user. Maybe another developer can give his opinion about it.

**Comment by justinclift** [comment] 2017-11-15 22:36
Having a JSON mode "at all" would be a good start.

With the JSON1 extension, our Windows and OSX builds now all include it as it's compiled into SQLite (and SQLCipher) itself.

For Linux, *BSD, and other unix like OS's... it would likely depend on whether the JSON1 extension is included with the provided SQLite.  We can't assume it always would be, so we'd likely need to have the minifying be optional (if the extension is even present).

Does that help? :smile:

**Comment by mgrojo** [comment] 2017-11-15 23:10
It helps, thank you. By the moment I will focus on just the JSON mode, it's enough for a challenge. :smile:

**Comment by wmertens** [comment] 2017-11-16 05:25
If you just pass json to `json()` for saving, sqlite will minify for you
methinks…

**Comment by mgrojo** [comment] 2017-11-18 16:23
@wmertens and @pamtbaau the feature is implemented. Would you like to try it in the next nightly build?

**Comment by wmertens** [comment] 2017-11-18 17:31
Woohoo! I am not at my computer now but I will try it asap! ❤

**Comment by pamtbaau** [comment] 2017-11-19 05:46
Version 3.10.99 (Nov 19 2017)
I can confirm that JSON mode is there and it does do syntax colouring... 

Found the following issue: When quotes are misplaced/missing, all text turns white and turns red when windows loses focus.

![json1](https://user-images.githubusercontent.com/5120011/32987791-12153a66-ccf5-11e7-9c74-7a588ff4c9b1.jpg)

![json2](https://user-images.githubusercontent.com/5120011/32987797-4a95c4c8-ccf5-11e7-92ad-7fb96e121ef0.jpg)

**Comment by mgrojo** [comment] 2017-11-19 20:25
@pamtbaau, there was a incompatibility between our style for current line and the default style for invalid lines and unclosed strings. Now it should be solved.

**Comment by mgrojo** [comment] 2017-11-22 23:44
@wmertens and @pamtbaau, now with minify, or in other words, the JSON data can be indented on loading, and compacted on storing. Any feedback is welcome :smiley:

**Comment by pamtbaau** [comment] 2017-11-23 06:26
A much better way to deal with JSON data this way! Thanks.

I see some room for improvement though... :
- Unlike Text cell editor, JSON cell editor does not follow the font family set for the data browser.
- When opening the data in JSON everything is highlighted. Not sure if that is desired.
- When removing quotes and colons, syntax error is shown clearly. Not so when deleting (curly) brackets. An unmatched (curly) bracket only turns red when I place the mouse on it. This error is hardly noticable.
- When switching from JSON to TEXT data remains indended. It should reverse to original.
- When imported incorrect JSON:
  - Missing quote: Text turns red.
  - Missing colon or bracket, no error indication.
  - A popup notifying the user would be appropriate when importing incorrect data.

Enough homework for today I would say...

**Comment by justinclift** [comment] 2017-11-23 14:48
Sounds like real progress is being made. :smile:

**Comment by wmertens** [comment] 2017-11-23 21:50
It's already a great improvement!

My notes:
* [ ] IMHO, indent/compact can be the default. As long as you don't save, it doesn't make a difference anyway.
* [ ] It would be great if text values are automatically checked for being parseable as JSON (if they are less than e.g. 100KB), and then the editor automatically switches to JSON.
* [ ] If using the `json()` function, minification and verification is done automatically by sqlite:
  ```
  sqlite> create table t(j json);
  sqlite> insert into t values ("[5, 1,     2]");
  sqlite> insert into t values (json("[5, 1,     3]"));
  sqlite> select * from t;
  [5, 1,     2]
  [5,1,3]
  sqlite> insert into t values (json("[5, 1,     3"));
  Error: malformed JSON
  ```
* [ ] Folding seems to have issues: folding an array with a nested array will fold to the close of the nested array: 
![image](https://user-images.githubusercontent.com/54934/33189141-56580d62-d0a0-11e7-9924-2b2986121091.png) 
![image](https://user-images.githubusercontent.com/54934/33189151-6cdebd24-d0a0-11e7-894d-070c45c706ed.png)

**Comment by mgrojo** [comment] 2017-11-23 21:52
Hi, @pamtbaau. Thanks for the feedback.

> -  Unlike Text cell editor, JSON cell editor does not follow the font family set for the data browser.

The font set by default for the data browser is of variable width. I think the font for any kind of code must be monospace. That's why the SQL font is reused here and in the binary editor. The settings should be, maybe, reorganized or relabeled, but that's a bit revolutionary. Other opinions are welcome.

> -  When opening the data in JSON everything is highlighted. Not sure if that is desired.

This is for consistency to the Text editor. 

> - When removing quotes and colons, syntax error is shown clearly. Not so when deleting (curly) brackets. An unmatched (curly) bracket only turns red when I place the mouse on it. This error is hardly noticable.

That is how the Scintilla widget is working, no easy way to change it.

> - When switching from JSON to TEXT data remains indended. It should reverse to original.

I doubted about this, but probably it makes sense as you propose.

> - Saving incorrect JSON into db should be prohibited, or a warning should be shown at least.

A warning seems to me the best approach and will be easy to implement.

> - When importing incorrect JSON:
>   -  Missing quote: Text turns red.
>   -  Missing colon or bracket, no error indication.
>   -  A popup notifying the user would be appropriate when importing incorrect data.

A warning would make sense here as well.

**Comment by mgrojo** [comment] 2017-11-23 22:29
Hi, @wmertens, thanks for the feedback!

> * [ ] IMHO, indent/compact can be the default. As long as you don't save, it doesn't make a difference anyway.

I think that letting the user discover the preference is the safest approach, otherwise we can change his/her own format inadvertently.

> * [ ] It would be great if text values are automatically checked for being parseable as JSON (if they are less than e.g. 100KB), and then the editor automatically switches to JSON.

It would make sense, but currently the mode is not changing automatically, even when image and binary data is already detected. Could be considered in a global way if nobody sees a problem for that.

> * [ ] If using the `json()` function, minification and verification is done automatically by sqlite:

I've used the Qt JSON class because Qt is already a requirement. On the other hand, we cannot assume that a given extension is available.

> * [ ] Folding seems to have issues: folding an array with a nested array will fold to the close of the nested array: 

Seems a Scintilla issue. I cannot reproduced your problem. Could you provide the full JSON data? I've found this patch for a folding issue in the JSON lexer, but seems to be another one. We have the version previous to the patch. https://groups.google.com/forum/#!topic/scintilla-interest/w4sW3sM6Cek

**Comment by wmertens** [comment] 2017-11-24 07:55
> > IMHO, indent/compact can be the default. As long as you don't save, it doesn't make a difference anyway.

> I think that letting the user discover the preference is the safest approach, otherwise we can change his/her own format inadvertently.

Well, the setting is quite hidden, how about moving the setting to the preview pane? So then they can turn it on/off easily and it will be retained between sessions.

> > It would be great if text values are automatically checked for being parseable as JSON (if they are less than e.g. 100KB), and then the editor automatically switches to JSON.

> It would make sense, but currently the mode is not changing automatically, even when image and binary data is already detected. Could be considered in a global way if nobody sees a problem for that.

Good point. For sure this belongs in a different issue; perhaps the type dropdown can instead be a button group and auto-detected formats will highlight the corresponding button, and there can be a "[x] autodetect format" checkbox

> >  If using the json() function, minification and verification is done automatically by sqlite:

> I've used the Qt JSON class because Qt is already a requirement. On the other hand, we cannot assume that a given extension is available.

Oh, I thought that the JSON extension is always compiled into this app now?

> >  Folding seems to have issues: folding an array with a nested array will fold to the close of the nested array:

> Seems a Scintilla issue. I cannot reproduced your problem. Could you provide the full JSON data? 

I can even reproduce it without much nesting, as long as the json is longer than the view:

```json
{
    "accessTime": "16:00:00",
    "address": {
        "country": "ES"
    },
    "agentId": "1234",
    "bedroomCount": 3,
    "calcCapacity": 6,
    "capacity": 6,
    "contentsOld": [
        {
            "count": 1,
            "itemId": "1"
        },
        {
            "count": 1,
            "itemId": "2"
        },
        {
            "count": 1,
            "itemId": "3"
        },
        {
            "count": 1,
            "itemId": "4"
        },
        {
            "count": 1,
            "itemId": "5"
        }
  ]
}
```

Actually, it is very odd. It seems to be related to auto-indent. When I first visit a cell, the first page will look ok but when I scroll down, the range indicators break up. If I then delete the json and undo, the whole json object has correct ranges.

**Comment by pamtbaau** [comment] 2017-11-25 07:01
Feedback on Version 3.10.99 (Nov 25 2017)
- Warning on apply works fine.
- Warning on import not yet working.

**Comment by mgrojo** [comment] 2017-11-25 11:19
I've only implemented the warning on apply. Warning on import seems redundant, doesnt't it? There is no import without later apply unless the user changes mind.

**Comment by pamtbaau** [comment] 2017-11-25 11:28
There already is a clue that imported data is flawed because it doesn't expand. That behaviour might be confusing to the user.  A warning would add a bit of user-friendliness...

**Comment by wmertens** [comment] 2017-11-27 15:13
Just wanted to add that it's a real delight to walk through row results and seeing the JSON expanded like that. When the schema matches between rows it's also great to only see changes to the values, so you quickly get an idea about the changes.

Thank you!!!

**Comment by mgrojo** [comment] 2017-12-01 23:27
@wmertens @pamtbaau Could you take a look to the last change implemented to the JSON editor?

**Comment by pamtbaau** [comment] 2017-12-02 07:05
Don't know how far you want to go... I'm happy as it is. It is already a great improvement and working with JSON has become a pleasure. Thanks a lot for that!

And I can still see some area's of improvement:
- I would prefer feedback on syntax errors to be a bit more prominent. Maybe an indicator next to the 'mode' dropdown. 
- There is no syntax feedback while editing (which is consistent with the sql editor) and to see if there is an error, I have to switch to text and back to json. If immediate feedback during editing is too costly or unpractical, a 'validate' button might be handy, or periodic async background validation.

**Comment by mgrojo** [comment] 2017-12-02 19:05
Thanks, great to know that. 

I'll think something about your suggestions.

**Comment by pamtbaau** [comment] 2017-12-02 19:09
Just playing the happy nagger....

**Comment by wmertens** [comment] 2017-12-07 11:11
I've been using the nightly for a while now and I haven't encountered any
bugs.

Although I still think that the format setting belongs in the JSON viewer
pane and not hidden away in settings.

**Comment by justinclift** [comment] 2017-12-07 14:27
@wmertens Hmmm, that's an interesting thought.  On one hand we have lots of stuff in Preferences, but on the other hand we do already have some buttons in the editing dialog for other things.  Having them right where people want to use them could be better for UX, as being able to easily change them directly and see the result right away sounds useful.

From your point of view, which format settings should go in the JSON viewer? :smile:

**Comment by wmertens** [comment] 2017-12-07 22:41
Actually, I would be happy with just the autoindent option that exists now…
it is too far away, I installed the nightly for a few people and it was a
search every time to enable the indenting…

**Comment by justinclift** [comment] 2017-12-08 01:59
@wmertens Makes sense to me. :smile:

@mgrojo What do you reckon?

**Comment by mgrojo** [comment] 2017-12-08 14:52
I see that some settings are stored outside the preferences window, for example, the line type and point shape in the plot dock, so I can follow that pattern.

**Comment by mgrojo** [comment] 2017-12-08 16:57
@wmertens There is now a button for activating, deactivating the autoformat on the cell editor.

**Comment by justinclift** [comment] 2017-12-08 17:39
@mgrojo Awesome! :smile:

@wmertens Since you're running on OSX, I've just manually launched our nightly build script for OSX.  It'll recreate the latest nightly OSX builds now (including this new change), so they'll be available for testing in ~20 minutes instead of waiting until tomorrow.  Hopefully that helps. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by pamtbaau** [comment] 2017-12-09 07:15
Just had a look at the new 'settings' button. I think it shouldn't be in the cell editor...

- Moving the setting into the Cell Editor is a workaround for a Preference tab which is unclear and inconsistent compared to the tabs for General, Database and Sql.
The preference tab itself should be re-designed instead of cluttering the UI of the Cell Editor.
(NB. Database tab should be left aligned for consistancy)
- It is a setting one rarely changes, so it shouldn't clutter the UI permanently.
- It should be a checkbox. A button holds a promise for action, like "Format the json now".
- It should be invisible instead of disabled when other formats are used.

My suggestion would be to cleanup the preference tab 'Data Browser' and add the JSON setting back to it.

**Comment by justinclift** [comment] 2017-12-09 18:29
Ahhh, damn.  Sounds like it's not a clear win then.

Ok, I'll make some time over the next few days to try the JSON mode our myself, and get a better feel for how things are. :smile:

**Comment by mgrojo** [comment] 2017-12-10 17:27
> - Moving the setting into the Cell Editor is a workaround for a Preference tab which is unclear and inconsistent compared to the tabs for General, Database and Sql.
> The preference tab itself should be re-designed instead of cluttering the UI of the Cell Editor.
> (NB. Database tab should be left aligned for consistancy)

I don't have a strong opinion about whether the setting should be in Preferences or at hand in the Cell Editor, but why do you relate it to the current state of the Preference Data Browser tab? That could be improved, of course, but how would that help in finding the preference? I think the use case for having it at hand is that it won't be obvious otherwise that this capability exists. I always take a look at the Preferences in an application so I know what it offers, but there are certainly users that would prefer the configurability can be discovered while using the application. Maybe @wmertens can explain which is the use case for him.

> - It is a setting one rarely changes, so it shouldn't clutter the UI permanently.
> - It should be a checkbox. A button holds a promise for action, like "Format the json now".

This is a checkable button, indeed, because I didn't want to clutter the Cell Editor. A checkbox and label would have taken too much space. I also plan to have a button for locking the mode, being the default behaviour changing automatically the mode in accordance to the detected data type. 

> - It should be invisible instead of disabled when other formats are used.

Well, at least this would a win for everyone. It can be done if we decide to keep the button there.

> My suggestion would be to cleanup the preference tab 'Data Browser' and add the JSON setting back to it.

How would that help in finding the setting? Or is it the problem, that in fact the Editor Cell is another UI component and should have its own tab? But then, only with one setting?

**Comment by wmertens** [comment] 2017-12-11 09:03
* I think the pushbutton is a good UI choice given the limited space
* OTOH, I think it should only show up when the cell editor is in JSON mode. I notice that the Image viewer takes up more vertical space than the others, so perhaps the button can be moved to the JSON viewer itself, so below the mode/import/export line? In that case, a checkbox with label would also work.
* I think it would be good if turning off the feature reloads the cell data without indentation, so that it is abundantly clear what it does when toggling (only if there were no changes of course)
* Upon more reflection, I'm having a hard time imagining why anybody would want a setting that does not auto-indent/auto-compact. If you want that, there is the text editor. JSON is JSON, and whitespace is not significant.

**Comment by wmertens** [comment] 2017-12-11 13:43
One more: IMHO, a JSON object is more than just a cell entry, and therefore it's not something that you generally want to replace with something you type, and therefore the JSON editor should not select the whole JSON text on opening…

**Comment by mgrojo** [comment] 2017-12-11 19:27
> * I think the pushbutton is a good UI choice given the limited space
> * OTOH, I think it should only show up when the cell editor is in JSON mode. I notice that the Image viewer takes up more vertical space than the others, so perhaps the button can be moved to the JSON viewer itself, so below the mode/import/export line? In that case, a checkbox with label would also work.

That would complicate the layout. I'd rather leave it as is, or remove it from the Cell Editor.

> * I think it would be good if turning off the feature reloads the cell data without indentation, so that it is abundantly clear what it does when toggling (only if there were no changes of course)

It should be already doing that. Have you tried with a recent build?

> * Upon more reflection, I'm having a hard time imagining why anybody would want a setting that does not auto-indent/auto-compact. If you want that, there is the text editor. JSON is JSON, and whitespace is not significant.

Well, maybe I'm being too paranoid about changing the user data. I can imagine users wanting its own formatting and not wanting our own, but maybe we should go by default for the majority of users and hope this supposed minority will find the setting. Then the default value would 'enabled' and we could move the setting back to preferences? What do you reckon, @justinclift ?

> One more: IMHO, a JSON object is more than just a cell entry, and therefore it's not something that you generally want to replace with something you type, and therefore the JSON editor should not select the whole JSON text on opening…

You're absolutely right, but that is no longer happening. You're not definitely using a recent build :smile:

**Comment by justinclift** [comment] 2017-12-11 20:05
> What do you reckon, @justinclift ?

@mgrojo Let me try it out with some JSON, and I'll let you know.  Might be tonight, but more likely tomorrow.  Feeling a bit brain drained at the moment. :wink:

**Comment by wmertens** [comment] 2017-12-11 21:37
@mgrojo yey on all your replies, but the on->off on the button does not show the original in the latest nightly. 

Of course, if you will be moving the pref back and enabling it by default, it doesn't matter :)

**Comment by mgrojo** [comment] 2017-12-11 22:09
I see. It's happening when you change from the Text mode to the JSON mode. If you have already set the JSON mode before entering the cell, it performs the formatting/compacting as expected. Let's see where the setting ends before trying to fix it.

**Comment by mgrojo** [comment] 2017-12-15 23:16
With the last commit the JSON editor has the same find/replace dialog as the SQL editor.

**Comment by justinclift** [comment] 2017-12-15 23:47
Oops, I didn't get around to trying this out.  Sorry all. ☹️

**Comment by wmertens** [comment] 2017-12-21 09:38
@mgrojo I just noticed that the JSON formatting also sorts the keys. Can this be turned off? Key insertion order matters in JavaScript…

**Comment by mgrojo** [comment] 2017-12-21 19:24
@wmertens I hadn't noticed that. Apparently there is no way to tell the Qt libraries to preserve the original key order when formatting or creating JSON data. On the other hand, this is what the standard RFC7159 says, so I guess this is not uncommon:

>    JSON parsing libraries have been observed to differ as to whether or
   not they make the ordering of object members visible to calling
   software.  Implementations whose behavior does not depend on member
   ordering will be interoperable in the sense that they will not be
   affected by these differences.

The only current way to avoid this, it's to totally disable formatting.

**Comment by justinclift** [comment] 2017-12-21 20:07
@mgrojo We should probably file a bug with the Qt project too, as it's reasonably common to come across cases where the ordering of JSON fields makes a difference.  The Qt people **might** be able to suggest a workaround for keeping it unsorted too.  Not guaranteed, but they sometimes suggest useful things in the bug comments. :smile:

**Comment by mgrojo** [comment] 2017-12-21 23:13
@justinclift I've found [this Qt bug report](https://bugreports.qt.io/browse/QTBUG-56315) but unfortunately the feedback was very disappointing. Basically, 'you don't need that'. They even closed the issue and it is currently open only because the reporter insisted and reopened it.

**Comment by pamtbaau** [comment] 2017-12-22 06:47
According to [The JSON Data Interchange Syntax stardard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) (december 2017) 

> 6 Objects
> ...  and does not assign any significance to the ordering of name/value pairs

> 7 Arrays
> ... The JSON syntax does not define any specific meaning to the ordering of the values. However, the JSON array structure is often used in situations where there is some semantics to the ordering. 

According to the [Internet Engineering Task Force (IETF)](https://tools.ietf.org/html/rfc7159):

> An object is an **unordered** collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.
> 
>    An array is an **ordered** sequence of zero or more values.
> 

According to [json.org](http://json.org):

> JSON is built on two structures:
> 
> - A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
> - An **ordered** list of values. In most languages, this is realized as an array, vector, list, or sequence.

> An object is an **unordered** set of name/value pairs.

> An array is an **ordered** collection of values.

Although the response to the bugreport may be a bit harsh, it is what it is... It's up to the program to preserve the semantics of 'order'.

**Comment by justinclift** [comment] 2017-12-22 08:08
On a side note, that Qt bug report is probably the clearest case I've yet seen of a Contributor License Agreement (CLA) creating roadblocks to project growth. 😦 

Additionally, if the bug reporter had just included the sample code (it's only a few lines) directly in the bug report window, instead of including them as attachments... then the reviewer likely would have actually seen what he meant, and been able to comment constructively instead of blaming the CLA to avoid doing so.  **\*sigh\***

**Comment by wmertens** [comment] 2018-01-12 17:50
I wonder, would it be possible to use https://github.com/peteristhegreat/qt-json-editor instead? It keeps the order of the original JSON. 

There is also https://codereview.stackexchange.com/questions/11849/qjsonview-a-qwidget-based-json-explorer-for-qt but that's for Qt4, and it seems to use QJson, and I don't know if that uses source order.

Seeing the JSON objects in the original source order is very nice, because it shows the first written items at the top.

**Comment by justinclift** [comment] 2018-01-12 19:44
https://github.com/peteristhegreat/qt-json-editor is probably a bad idea.  It hadn't had any updates in 3 years, none of the 5 forks of it has any changes either.

https://github.com/dridk/QJsonmodel, mentioned in the StackExchange post seems to get the occasional update though, so **may** be feasible.  @mgrojo How does that one look to you?

**Comment by wmertens** [comment] 2018-01-15 11:09
Maybe they haven't changed in 5 years because there are no bugs😉

**Comment by mgrojo** [comment] 2018-01-28 18:01
@justinclift @MKleusberg Do you have an opinion about where should be the auto-format setting for the JSON and XML modes? I think it is a good idea to decide finally on this before the final release, so it is not changed later after been released in another way. If we decide for it to go in the cell editor, I'll try to fix the problem that  @wmertens reported on 11 Dec 2017.

**Comment by justinclift** [comment] 2018-01-28 20:33
No opinion personally, as I haven't yet gotten around to trying these out. 😇

**Comment by wmertens** [comment] 2018-03-20 10:59
I have been using this for a while now and while it's not perfect, it is already very useful.

It would be perfect if it:
* formatting is only in the editor component, so switching modes doesn't change the text
* preserves source order
* wraps long string values to be multi-line

The first one might be attainable here, the second two are really up to the JSON editor component. Sadly I am not proficient in Qt; in the browser it would not take very long to make a component like this.

So unless you think there are improvements you can do, this is good for me to close…

**Comment by mgrojo** [comment] 2018-03-20 20:07
> formatting is only in the editor component, so switching modes doesn't change the text

Do you mean switching editor modes or format mode?

> preserves source order

We rely on the Qt library for this and it is not supported, so it would be cumbersome to implement.

> wraps long string values to be multi-line

This is an option in the Scintilla editor library. We could make it a preference. It would apply to SQL, JSON and XML editors and it would wrap every line longer than the editor width (with visual indications):
http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciScintilla.html#ac04428d2f90c36458d68a673f107e40c
![imagen](https://user-images.githubusercontent.com/13812910/37679801-53689750-2c82-11e8-8351-c3c3d96cd39f.png)

Do you mean that?

**Comment by wmertens** [comment] 2018-03-20 20:19
wrapping: Yes that would be great!!!

formatting: I don't have a use for formatted JSON data in my DB, but it's wonderful while editing. Converting the cell value to formatted-with-whitespace is a bit of a hack to make the editor work, and if there are no changes, then changing the editor type should not retain the temporary spaces.

Come to think of it, the css editor in Chrome devtools is pretty nice. It looks like a text editor but it enforces strict formatting.

The editor in http://jsoneditoronline.org/ is pretty much like that, except that adding a field is a bit fiddly.

**Comment by mgrojo** [comment] 2018-03-28 19:32
>wrapping: Yes that would be great!!! I think that would require a toggle button in the editor though, sometimes you want to see keys more than values.

Sorry but I'm thinking on adding the setting to the Preferences dialog. It would apply to all the editors (SQL and cell editor) and everywhere else takes away useful space.

**Comment by karim** [comment] 2018-05-16 16:49
> https://github.com/dridk/QJsonmodel (Qt5), mentioned in the StackExchange post seems to get the occasional update though, but seems like it's a widget just for display purposes. Doesn't seem to include any editing capability.

I don't know if this is helpful to the issue or not, but [it is now editable](https://github.com/dridk/QJsonModel/pull/8).

**Comment by mgrojo** [comment] 2018-05-16 21:55
We can explore that option. The development seems still stalled, but the implementation is in fact simple, being based on the Qt classes, so no major problem if we finally need to maintain it by ourselves.

I wouldn't replace the current text editor based on QScintilla, but add a new mode to the cell editor. I think there is advantages and disadvantages in each mode.

**Comment by mgrojo** [comment] 2018-09-28 18:27
I've opened #1546 for the enhancement request that was mentioned here, but I'm going to set this as closed for our next release.

**Closed by mgrojo** 2018-09-28 18:27 UTC
Labels: enhancement, response requested
