### ISSUE TITLE
[Suggestion] Hold key while clicking on recently opened DB to open as read-only or vice versa

### ISSUE THREAD

**Issue by flleeppyy** [sqlitebrowser/sqlitebrowser#2484] opened 2020-11-20 20:00 UTC
Describe the new feature
--------------------------
I find it annoying to have to browse for the database file again if I need to open it as read-only.
So, being able to hold a key while clicking on a database from the recently opened databases, makes it open as read only, or if it was already opened as read only, open it normally.

I hope this doesn't sound too complicated

**Comment by chrisjlocke** [comment] 2020-11-20 20:05
And on which operating system are you using?  If you're on Windows, then the operating system does remember the last fifteen or so opened databases, which you can get to via the open dialog.

**Comment by flleeppyy** [comment] 2020-11-20 21:32
I'm on linux. Kubuntu 20.04.1

**Comment by chrisjlocke** [comment] 2020-11-20 23:34
Baaaaaaaaaaaaah nuts.

**Comment by lucydodo** [comment] 2020-11-21 11:54
It doesn't seem like a hugely difficult offer.
However, because it was opened in a read-only mode before,
it seems that if user open it in a read-only mode when opening it from the recent file list again, it may be less intuitive.

I think we have the following options. 😄 

1. Dialog output confirming whether to open in read-only mode when
opening a file previously opened in read-only mode from the recent file list
    - Pros: Simple and intuitive
    - Cons: Hassle of having to press once more unnecessarily
(will definitely be annoying when repeatedly opening and closing multiple files read-only)

2. Give settings an option to determine this
    - Pros: Does not display annoying dialogs
    - Cons: `PreferencesDialog` will be slightly more complicated,
and read-only files can be accidentally edited when users misunderstand the setting value.

3. Put a lock icon on the right side of the UI and use it to toggle the read-only mode to `True` or `False`.
    - Pros: Intuitive, can be used in various situations other than the same situation as this issue
    - Cons: Relatively complicated code (of course, this is not important to the user)

**Comment by chrisjlocke** [comment] 2020-11-21 19:36
A dialog that appears could be unobtrusive.  With the default button already got the focus, the user would just have to press [Enter] again.

![image](https://user-images.githubusercontent.com/7872218/99885918-5d483e00-2c30-11eb-92f1-c42cafaef4ce.png)

The only query is how do you store/remember what databases were opened in what method?  Just a text-file of filenames?  After a while, that could be a large list (imagine three years of opening databases, etc...) - needs some way of maintaining it?

**Comment by lucydodo** [comment] 2020-11-22 08:41
@chrisjlocke We already identified by appending the identifier `[ro]` in front of the file name

**Comment by lucydodo** [comment] 2020-11-22 08:48
btw, as far as I know, if the user opened a file in read-only mode before,
that it was designed to open in read-only mode even when opening the file from the recent file list.

https://github.com/sqlitebrowser/sqlitebrowser/blob/1dc7ffee4ee0012c697a6a9909fdaf40cc098c9b/src/MainWindow.cpp#L1631-L1652

**Comment by chrisjlocke** [comment] 2020-11-22 10:48
> We already identified by appending the identifier `[ro]` in front of the file name

Aah, thanks!  Didn't know that.  Don't tend to open read-only databases, so wasn't aware of that feature.

**Comment by mgrojo** [comment] 2020-11-23 20:39
It's easy to add shortcuts for that. If Ctrl+n opens the recently open file number n, then Shifth+Ctrl+n could open it inverting the read-only flag. Then Shift+Ctrl+1 would be a quick way to turn the flag for the currently open database.

**Comment by flleeppyy** [comment] 2020-11-25 02:51
> It's easy to add shortcuts for that. If Ctrl+n opens the recently open file number n, then Shifth+Ctrl+n could open it inverting the read-only flag. Then Shift+Ctrl+1 would be a quick way to turn the flag for the currently open database.

That's a good idea! 

I would try to help contribute to this myself, but I'm not that great at C++ _yet_
I could give it a shot though.

**Comment by MKleusberg** [comment] 2020-12-11 13:45
This should be implemented in the [next nightly build](https://nightlies.sqlitebrowser.org/latest/). Can you give it a try and check if it's working as expected for you, @flleeppyy? You can either use the Ctrl+Shift+n shortcut (instead of Ctrl+n) or hold Shift while clicking one of the menu items. In either case the last read-only/read-write setting is inverted.

**Comment by mgrojo** [comment] 2020-12-12 17:31
There's a problem if you have 7 or more entries in the recent files list: Ctrl+Shift+7 breaks the shortcut for Comment/uncomment in my Spanish keyboard, because it's the same as Ctrl+/.
QAction::eventFilter: Ambiguous shortcut overload: Ctrl+Shift+7

I can still use <kbd>/</kbd> from the numeric keypad, but that's inconvenient. I don't see a way to solve the ambiguity, since the shortcut for opening a recent file should be global.

Moreover, it also breaks Ctrl+" for duplicating records... Maybe Ctrl+Alt+n would be safer? Any other idea?

**Comment by chrisjlocke** [comment] 2021-03-23 15:16
@flleeppyy - *cough*

**Comment by chrisjlocke** [comment] 2021-07-13 13:55
I'll close this due to lack of response.
@flleeppyy - Feel free to comment back if needed.

**Closed by chrisjlocke** 2021-07-13 13:55 UTC
Labels: enhancement, opening database, response requested

**Comment by flleeppyy** [comment] 2021-07-13 18:54
Sorry, I've been caught up with other things and haven't had time to look at issue responses
