### ISSUE TITLE
Query duration is not printed when use printf in query

### ISSUE THREAD

**Issue by bomiyr** [sqlitebrowser/sqlitebrowser#1742] opened 2019-02-13 15:18 UTC
Details for the issue
--------------------

#### What did you do?

Execute query like this in Tab 'Execute SQL'
```
WITH a AS (SELECT 'a')
SELECT printf("%010d", 4)
```

#### What did you expect to see?

In the field that describes result of a query I want to see duration of execution:

> Query executed successfully: WITH a AS (SELECT 'a')
> SELECT printf("10d", 4) (took **10ms**)

#### What did you see instead?

> Query executed successfully: WITH a AS (SELECT 'a')
> SELECT printf("10d", 4) (took **ms%3**)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_openSUSE Tumbleweed 20190126 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [x] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2019-02-13 15:47
Heh Heh Heh.  Interesting bug, thanks for reporting it @bomiyr. :smile:

**Comment by chrisjlocke** [comment] 2019-02-13 16:41
This might be sorted in the latest version.

![image](https://user-images.githubusercontent.com/7872218/52727813-ee937680-2fad-11e9-95fe-0b437d6198c5.png)

@bomiyr - if you want to try the latest version (you're on Linux, so don't know how easy that is for you), this issue may no longer be a problem.

**Comment by MKleusberg** [comment] 2019-02-13 16:51
I can confirm it's working fine using the latest version on Linux. These issues are caused because the ```%``` character followed by a number is also a placeholder in Qt strings - so having one in the query might cause confusion when not being careful. But as I said, in the latest version it seems like we're more careful :wink:

**Comment by mgrojo** [comment] 2019-02-13 20:21
This was indeed fixed in PR #1455 (I forgot to mention it in the log), so it was included in the latest release: 3.11.0. In Linux you can try one of the [nighly options](https://nightlies.sqlitebrowser.org/latest/%2A%20README.txt) or compile by yourself.

**Comment by bomiyr** [comment] 2019-02-14 07:30
Thanks, I'm glad it's already fixed

**Closed** 2019-02-14 07:30 UTC
Labels: bug, response requested
