### ISSUE TITLE
Creating Table (Only `CREATE TABLE` Syntax and GUI) Issue

### ISSUE THREAD

**Issue by GeorgeCY2** [sqlitebrowser/sqlitebrowser#1689] opened 2018-12-26 14:57 UTC
Details for the issue
--------------------

#### What did you do?
I Tried to Create a Table into a writable database (not readable, all i did is create a database, tried to create a table using the browser and a error which isn't supposed to throw), but it doesn't work

#### What did you expect to see?
The Table Created without any issues!

#### What did you see instead?
<img src="https://cdn.discordapp.com/attachments/483941625169707009/527491774550114306/unknown.png" />

Useful extra information
-------------------------
The database isn't read only, but i get the error read only for some reason, however temporary table works and anything else, but not creating table, i even tried creating a table in Execute SQL Section but still gives same error:
```
attempt to write a readonly database: CREATE TABLE `FWGR` (
	`Field1GER`	INTEGER,
	`REG`	INTEGER
);
``` 
(this was a testing one btw, so i can see if it gives error in any other databases) and as  i said, the database isn't **Read Only** (i tried reinstalling DB4S too, but no luck on reinstalling, still same stuff!)
Also the issue seems to occurred since yesterday i tried it, the last couple of months or something, create table worked perfectly fine, when yeah, this started now! and as i said, temporary table and anything else such as inserting works!

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 Pro)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.0-alpha1 or 3.11.0-beta*
- [x] 3.10.1
- [x] Other: Latest Nightly Version

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment] 2018-12-26 15:12
There have been several fixes and improvements in the table creation code since our last stable version (3.10) and we are in the process of releasing a new one (3.11). Could you install the [latest beta](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-beta3) and check whether this problem is solved or gives a better error message?

**Comment by mgrojo** [comment] 2018-12-26 15:32
Where are you saving the DB file? Is there some hidden file or is it a special directory?

**Comment by GeorgeCY2** [comment] 2018-12-26 15:36
in desktop and the one db i wanna **actually** modify is in a folder of my desktop(the one in the arrow)
![image](https://user-images.githubusercontent.com/36137970/50450127-92f52700-0934-11e9-9942-b2858243a85f.png)
and no it isn't a special directory (not even a git one or something if that's what you also mean)

**Comment by mgrojo** [comment] 2018-12-26 15:46
No clue yet. Only happens for those two DBs in the desktop? What happens if you copy the file to another folder, like "My Documents"?

**Comment by GeorgeCY2** [comment] 2018-12-26 15:50
after i had done testings on it before i post this , it seems like in every directory and in every database the `Create Table` does not work, i have tried creating a new `*.db` about two times, but it still doesn't work @mgrojo

**Comment by mgrojo** [comment] 2018-12-26 15:57
Don't know. Have you installed recently any application related to sqlite? Do you have a sqlite3 shell so you can open the file and try creating the table?

Maybe another member with more experience in Windows can be more helpful.

**Comment by GeorgeCY2** [comment] 2018-12-26 15:58
i have a sqlite3 shell made in repo, i tried with sqlite3 and it creates the table just fine, and no i do not have any other application related to SQLite, just the DB Browser, still `help wanted`?

**Comment by GeorgeCY2** [comment] 2018-12-26 16:04
i'll take it as a yes!

**Comment by SilvioGrosso** [comment] 2018-12-26 17:59
Hello @GeorgeCY2 

I have just tried myself to create some tables both from the graphical interface (Database Structure > Create new table) and through some  SQL  code (typed into the Execute SQL panel) and everything works fine. No error whatsoever.

I have done my tests on Windows 10 (64 bit) and I have created my dabatase on the Desktop folder.
I am working with the latest nightly build, which is: Version 3.11.99 (Dec 26 2018).

**Comment by GeorgeCY2** [comment] 2018-12-26 18:34
Well @SlivioGrosso sure yours might work but yeah for me does not work, so it's nothing helpful, my create table was working about months ago since i used it or something, and my issus was occurring since yesterday, so it's sorry to say this but it's nothing helpful, because also, it won't occur for just everyone

**Comment by SilvioGrosso** [comment] 2018-12-26 18:44
Hello @GeorgeCY2 

> Also it's on every database in every destination as i said!

Sorry about that :-(

I have just tested myself to make sure this problem is not entirely related to the current nightly build on Windows (which would be easier to fix...)

**Comment by chrisjlocke** [comment] 2018-12-26 20:16
DB4S is trying to do you what you said, but can't write to the database.  Can you try and rename the file? 
If you right click the file and select 'Properties' is there an 'Unblock' option?

![image](https://images.ecosia.org/orZdxsDcjHoY4Cy47UYl4Wb-bqM=/0x390/smart/http%3A%2F%2Fcodingoutloud.files.wordpress.com%2F2010%2F02%2Fdreaded-unblock.png)

**Comment by GeorgeCY2** [comment] 2018-12-26 20:31
Where do i find the thing to unblock from? @chrisjlocke since in the database it's not showing this

**Comment by GeorgeCY2** [comment] 2018-12-26 20:32
also it's installed by binary and not from source

**Comment by GeorgeCY2** [comment] 2018-12-26 20:33
also renaimg it seems to give the same stuff

**Comment by chrisjlocke** [comment] 2018-12-26 20:36
> also renaming it seems to give the same stuff

The same error, or a different error?  I'm not fully understanding.

> Where do i find the thing to unblock from?

Find the database file using Windows Explorer.  Right click that file.  Select 'Properties'.  The 'unblock' (if available) is on the first tab.

**Comment by GeorgeCY2** [comment] 2018-12-26 20:38
yes the same error
also yes i have checked the database file and there is nothing to "unblock"
also the permission on the file seems just fine
![image](https://user-images.githubusercontent.com/36137970/50456676-e9775b00-095e-11e9-8d20-f10cdc43925f.png)

**Comment by GeorgeCY2** [comment] 2018-12-26 20:38
The Permission is basically same on SYSTEM, My User and Administrators

**Comment by chrisjlocke** [comment] 2018-12-26 20:40
You said renaming the file creates an error.  Can you screenshot that error please?

**Comment by GeorgeCY2** [comment] 2018-12-26 20:42
wait i meant as you told me to 

>  Can you try and rename the file?

i did this and when i tried creating the table, still gives the error

**Comment by chrisjlocke** [comment] 2018-12-26 20:43
Aah.  I see.  Sorry - I meant does renaming the file cause an error to be generated, but I'll assume not then.  I was under the impression that the file might be locked open by another process and so DB4S couldn't amend the database.

If you open the directory where the database is, is there a ~journal file there too?

**Comment by GeorgeCY2** [comment] 2018-12-26 20:46
nope not a journal file (its on the desktop so...)
![image](https://user-images.githubusercontent.com/36137970/50456844-fa749c00-095f-11e9-81ea-b8570d7c4053.png)

**Comment by GeorgeCY2** [comment] 2018-12-26 20:47
and talking about

> was under the impression that the file might be locked open by another process and so DB4S couldn't amend the database.

i tried restarting My PC In case for that, but it doesn't seem the issue to be it!

**Comment by chrisjlocke** [comment] 2018-12-26 20:54
Any chance you could send me the database so I could test it?  db4s@chrisjlocke.co.uk  
If needed, you could delete all the data first.  This would confirm whether its a database issue or a machine configuration issue?

**Comment by GeorgeCY2** [comment] 2018-12-26 20:54
hmm seems like a rough issue isn't it? can tell by the silence rn tbh

**Comment by GeorgeCY2** [comment] 2018-12-26 21:03
i can't send you the database, due to the one I'm using is for testing the issue, and it's empty due to that i can't create a table, so i can't send it. 😞

**Comment by GeorgeCY2** [comment] 2018-12-26 21:04
it's in 0 bytes, so i can't technically send a file in 0 bytes

**Comment by GeorgeCY2** [comment] 2018-12-26 21:04
![image](https://user-images.githubusercontent.com/36137970/50457213-9d2e1a00-0962-11e9-993d-635859bc03ac.png)

**Comment by GeorgeCY2** [comment] 2018-12-26 21:04
the Permissions are the same as always

**Comment by GeorgeCY2** [comment] 2018-12-26 21:11
test

**Comment by GeorgeCY2** [comment] 2018-12-26 21:13
_Sorry tho if it kinda struggles you not sending it, but yeah, i just can't send an empty database_

**Comment by sky5walk** [comment] 2018-12-26 21:39
After you [download a nightly installer](https://nightlies.sqlitebrowser.org/latest/), right-mouse click the msi to open properties - general(security:) - [x] Unblock.

**Comment by GeorgeCY2** [comment] 2018-12-26 21:46
ive already tried nightly, but still same stuff happening

**Comment by sky5walk** [comment] 2018-12-26 22:12
Yes, but did you unblock the msi BEFORE installing?

**Comment by SilvioGrosso** [comment] 2018-12-26 22:39
Maybe it is something related to the anti-virus softwares as well.
Judging from one of the first screenshots, on the Windows 10 desktop,  it looks like there are both BitDefender and Kaspersky anti-ransom installed on his computer...

**Comment by chrisjlocke** [comment] 2018-12-26 23:06
> it's in 0 bytes, so i can't technically send a file in 0 bytes

Interesting.  Any chance of details on what you're doing?
An empty database is 8 KB (8192 bytes) in length - the SQLite header, plus other noise.

From DB4S, click 'File' and 'New Database'.  Give it a name of 'test2.db'
DB4S should display the 'Edit Table Definition' dialog.
At that point, open Windows Explorer, and find the 'test2.db' you are creating.  How large is the file now?

Finally, is this a real Windows PC or a virtual PC?  Not that that should make a huge difference, but just for confirmation.

**Comment by GeorgeCY2** [comment] 2018-12-27 09:50
Hello sorry for not replying for a while @chrisjlocke
as i did ticked the trying out the latest nightly, im gonna try it right now, and also it's just a real windows pc, not a VM (you can also tell the way i set the background and the programs i have)

**Comment by GeorgeCY2** [comment] 2018-12-27 09:52
@sky5walk, maybe i will try this later after chri's "try"

**Comment by GeorgeCY2** [comment] 2018-12-27 10:00
@chrisjlocke Interesting, i seem to get this
![image](https://user-images.githubusercontent.com/36137970/50475903-ce443400-09ce-11e9-9291-80d83914e200.png)
but normally, **i do have Access at my desktop** as user priviliges, as you can tell by the other screenshots, my files and folders were created just fine into the desktop, maybe it's the program's problem?

**Comment by GeorgeCY2** [comment] 2018-12-27 10:03
so should i go with @sky5walk's method?

**Comment by chrisjlocke** [comment] 2018-12-27 10:21
You're in the 'user' directory, but you're logged in as who?  The security permissions you showed earlier belonged to 'georgelouk' ?

Can you create a c:\db4s directory and work from there?  You can put shortcuts on the desktop to work on that new directory.
If you do create a c:\db4s directory, go into the properties and security, and again, take a screenshot of the permissions, as you did above.

**Comment by GeorgeCY2** [comment] 2018-12-27 10:34
1. Tbh im not in the user directory, i tried to save it into the desktop
2. Normally the files created, modified on desktop is by user priviliges, which the user has access to it just fine 
@chrisjlocke

**Comment by chrisjlocke** [comment] 2018-12-27 10:46
You're in the 'user' directory.
![image](https://user-images.githubusercontent.com/7872218/50477453-5a049300-09c4-11e9-9a34-9a0c4e4751be.png)

c:\users is the directory where all the users' home files are put.  A directory for each user.  You appear to be in the 'user' directory.  c:\users\user
This may be fine, but seeing as you can't save to the desktop, I would question whats going on.  
To resolve your issue, I would save to the c:\db4s directory instead.  If you can create a c:\db4s directory and do a screenshot of the permissions, that would be useful.

**Comment by GeorgeCY2** [comment] 2018-12-27 11:04
yup any other files created in the desktop is done without issues, and ok i'll check the owner now

**Comment by GeorgeCY2** [comment] 2018-12-27 11:05
@chrisjlocke my user own the db, not anyone else 
![image](https://user-images.githubusercontent.com/36137970/50478108-259ad200-09d8-11e9-9cc8-49afa1271874.png)

**Comment by GeorgeCY2** [comment] 2018-12-27 11:07
(on the desktop the db i created recently)

**Comment by GeorgeCY2** [comment] 2018-12-27 11:12
ok so i tried to create it in C: Drive and it seems the table is created successfully, thing is, i do not want to manage my dbs in c: drive so
![image](https://user-images.githubusercontent.com/36137970/50478259-f2a50e00-09d8-11e9-9fbc-2032701f8319.png)
the perms on it are
![image](https://user-images.githubusercontent.com/36137970/50478305-1ff1bc00-09d9-11e9-9994-dff027786bd2.png)

**Comment by GeorgeCY2** [comment] 2018-12-27 11:13
and yeah it works on aany other directory, but as i said, i dont want to manage databases in my c: drive, i want it in desktop or somewhere else that can access

**Comment by chrisjlocke** [comment] 2018-12-27 11:38
The one on the desktop.  

One other test.  Can you open Task Manager, click the 'Details' tab, and take a screenshot of the DB Browser for SQLite process, showing the username?

![image](https://user-images.githubusercontent.com/7872218/50478967-ef575580-09cb-11e9-84d3-532c45368ad2.png)

**Comment by GeorgeCY2** [comment] 2018-12-27 11:45
![image](https://user-images.githubusercontent.com/36137970/50479127-b1632d00-09dd-11e9-9fa1-eefbd907ef32.png)
and then opening the task manager now

**Comment by GeorgeCY2** [comment] 2018-12-27 11:47
![image](https://user-images.githubusercontent.com/36137970/50479194-fa1ae600-09dd-11e9-9de6-ab3d0d251d78.png)
the only process running the test-issue.db

**Comment by GeorgeCY2** [comment] 2018-12-27 12:00
test2

**Comment by chrisjlocke** [comment] 2018-12-27 12:06
Thanks for your patience and screenshots.  They are helpful.
So the user running DB4S is 'user' but only 'georgelouk122' and 'administrators' have permission on that database.  Do other users use your laptop?  You can add 'users' to the desktop, or you can add 'georgelouk122'.  Getting a list of available users is quite a long set of steps.  You want to add the user to the desktop folder, not to the database.
Right click the desktop folder, select properties.  select security.  Click edit.  Click add.  Ensure the 'locations' is pointing to your PC, not a domain.  Click 'advanced'.  Click 'find now'.
![image](https://user-images.githubusercontent.com/7872218/50479569-25e29f80-09cf-11e9-864b-632f573b51e1.png)
In this list, do you see 'users' ?  Do you see 'georgelouk122'?  I assume not on the second one, but yes for 'users'.  Add users, click 'ok' and set for 'Modify'.

![image](https://user-images.githubusercontent.com/7872218/50479698-c33dd380-09cf-11e9-833f-58e36eda243e.png)


Right click the

**Comment by chrisjlocke** [comment] 2018-12-27 12:56
That is really weird.  Its a permissions thing, but without studying your PC, its hard to do remotely.
As a 'last ditch' solution, which you shouldn't need to do, can you find the shortcut to DB4S, right click and 'Run as administrator'.  If that works, we can amend the shortcut to DB4S as a fix.

**Comment by GeorgeCY2** [comment] 2018-12-27 17:33
i have tried that once, now you said above, still gives same stuff even running the app on adminstrator @chrisjlocke

**Comment by chrisjlocke** [comment] 2018-12-28 09:35
> still gives same stuff even running the app on adminstrator 

Then something is majorly wrong.  The permissions on that directory are screwy and being ignored, as you have 'Administrators' as a permission.  Not sure what those permissions are, but I would assume 'Full Control'.

![image](https://user-images.githubusercontent.com/7872218/50510419-787c9400-0a81-11e9-8437-87458a0cd793.png)

I would admit defeat in this instance.  It works if you create a directory off the C drive (and you can do the same on the D or E drive, as you mentioned about not liking the C drive - despite the desktop folder being on the C drive)
Running as Administrator should have overwritten any permission issues.  Very weird.

You have a workaround.  Its not ideal, but workable.

**Comment by chrisjlocke** [comment] 2018-12-28 09:39
> Very impressed by both of you sticking with this to achieve the result.

Its something 'silly' and I hate issues preventing a user using the application due to something 'silly'... 🔨

**Comment by sky5walk** [comment] 2018-12-28 16:17
Another thing to consider is disabling BitLocker, if it is used at all?
As a last resort, run the process as SYSTEM. That is higher than Admin.

**Comment by justinclift** [comment] 2018-12-28 21:58
From another direction, do any of the installed anti-virus or security type of things on the system, have some kind of history or logging window to show when they've blocked something?

This issue is **so weird**, it like something is actively trying to stop the application from doing it's legit stuff.  But in some strange way that even the main Windows permissions stuff isn't doing.

Kind of suspecting some security product might be doing it best here, and going wrong.  Thus the "is there a way to check?".  Kind of expecting this will turn out to be the cause. :smile:

**Comment by justinclift** [comment] 2018-12-29 11:05
Yep, definitely. :smile:

@GeorgeCY2 Looking at your [profile page](https://github.com/GeorgeCY2), you have some security related stuff listed.  Don't supposed you've got any enhanced sandboxing or similar stuff installed?  That would help explain some of the weird stuff happening here. :wink:

**Comment by GeorgeCY2** [comment] 2018-12-29 14:47
nope not a similar, and im not sure about sandbox apps, if you tell me what's this means, then i might tell @justinclift

**Comment by justinclift** [comment] 2018-12-29 18:02
"Sandbox" applications is just a phrase. :smile:

It means an application which can run stuff inside a limited environment.  One example - very "old school" these days - is Virtual Machine software like VMware, KVM, and VirtualBox.

More recently, Docker is an example of a "sandbox"-ing application.  I think Windows itself now sandboxes some stuff.  Even Chrome and Firefox (from memory) try to "sandbox" things in browser tabs.

More info here, if that helps: https://en.wikipedia.org/wiki/Sandbox_(computer_security) :smile:

**Comment by chrisjlocke** [comment] 2018-12-30 00:50
Sometimes, security / antivirus software which doesn't 'recognise' certain applications will force them to operate in their own little 'bubble'.  Bit like a holodeck on Star Trek Enterprise.  The application can see the file system, other applications, etc, but when they try to write or amend any settings, they are only writing to a virtual system which only they can see.  The theory being, if they're a malicious program, then they can't do any permanent damage to the system - only to their own virtual system.

As I said, running something as 'administrator' should be 'god mode' - full permissions to do whatever you wanted.  There is 'super god mode' (Mrs God?) but you should never have to do that in normal circumstances.  I've been using computers for the last 27 years and have never had to run a program in 'super super overlord mega hyper god plus advanced (new formula) mode'.  We've not had reports of DB4S requiring such privelages before, so its something rare on your machine.

**Comment by sky5walk** [comment] 2018-12-30 02:06
Unfortunately, on Windows at least, SYSTEM processes are impervious to a mere Admin. 🥀

**Comment by MKleusberg** [comment] 2018-12-30 11:17
I have to admit that I haven't read all 71 comments :wink: But one thing I noticed is @GeorgeCY2 writing that "anything else such as inserting works!". If that's true it doesn't look like a simple write permission thing - it's just happening when creating a new table. A lot depends on the PRAGMAs here, but maybe it's either about creating a new temporary file for the journal or about locking the database file in some way which fails here.

**Comment by chrisjlocke** [comment] 2018-12-30 11:52
Its hard to fully understand, but I think inserting/updating in one database works fine, but when @GeorgeCY2 creates a new database to test, thats when it fails.  The new database is 0 bytes, so its not even creating the database.  Its not like it has the 'shell' of a database, but pragmas are stopping table creation.  DB4S can't even create the necessary file.
Its hard to diagnose remotely, but we've created a directory off the C drive, and all works fine there.  That would indicate a permissions issue on the desktop.
It doesn't help that @GeorgeCY2 is logging in with a Microsoft account, but permissions are based on local computer accounts.  I've not played with that much with Windows 10, but it could have a bearing.

**Comment by mgrojo** [comment] 2018-12-30 12:17
The releavant difference about "Desktop" vs. "C drive" could be instead "directory already existent" vs. "directory just created by the user". @GeorgeCY2 I think you might also try this: create a directory inside Desktop and then try to save the DB file there.

**Comment by GeorgeCY2** [comment] 2018-12-31 11:03
i tried that @mgrojo but nope still same thing, i should just try doing it in documents oor soemthing and see if it makes any diffrence

**Comment by GeorgeCY2** [comment] 2018-12-31 11:06
ok i have confirmed, seems that in librarys like videos documents desktop and etc. doesn't let it save, however 3D Objects Library and User and C: Drive destination let's me create the tables

**Comment by GeorgeCY2** [comment] 2018-12-31 11:06
in the database

**Comment by GeorgeCY2** [comment] 2018-12-31 11:07
and yes @MKleusberg you are right, anything else such as creating temporary table or inserting values works, except the main.table stuff

**Comment by justinclift** [comment] 2018-12-31 12:03
Yeah, it's weird.

I guess that as long as you can find a location to use, which you're happy with, then that will at least work.

At some point the cause of the problem will hopefully become known, in which case it might be useful to document so future people can know about it too.  Just in case they hit the same problem. :smile:

**Comment by chrisjlocke** [comment] 2018-12-31 12:34
As a workaround has been found, I'll close this issue.  @GeorgeCY2 - feel free to comment further if you feel this is unresolved, and again, thanks for your patience while we looked into your issue.

**Closed by chrisjlocke** 2018-12-31 12:34 UTC
Labels: help wanted, windows
