### ISSUE TITLE
SQLite browser lags

### ISSUE THREAD

**Issue by abhilash1in** [sqlitebrowser/sqlitebrowser#761] opened 2016-09-02 06:20 UTC
I have a database of size 90 MB. SQLite browser doesn't seem to handle it too well. It has a huge lag while browsing or updating the db.

**Comment by innermous** [comment] 2016-09-02 07:25
Define "doesn't seem to handle it to well". What's exactly happening? UI freeze?

**Comment by chrisjlocke** [comment] 2016-09-02 13:40
Is it a locally attached database, or on a network?
Although only 90 MB, how many tables and rows within those tables are there?
Is it just when you change tabs? You said 'updating the db' - can you give more detailed steps to reproduce?

I created a table with four fields and filled it with 549,000 rows.  The fields just had 'a' as a content.  The only real lag I see is changing a field type, eg, from text to integer. 
Switching to the 'Browse Data' tab creates 5 SQL queries (2 of which are possibly superfluous, but may not be) or possibly more, if the connection has closed ... is this a point of delay for you?

**Comment by abhilash1in** [comment] 2016-09-02 14:16
It is a local database. I have just one table with 260 rows.

My table create statement is as follows:

```
CREATE TABLE "slides" ( 
`slide_no` INTEGER NOT NULL,
`slide_type` INTEGER NOT NULL, 
`text_size` INTEGER NOT NULL,
`heading` TEXT, 
`sub_heading` TEXT, 
`img` BLOB, 
`string1` TEXT, `string2` TEXT, `string3` TEXT, `string4` TEXT, `string5` TEXT, 
`read` INTEGER, 
 PRIMARY KEY(slide_no) );
```

All the fields are small (less than hundred characters) except `img` (of type `blob ` with approximately 33000 characters in every row) and `string1` (of type `text` with approximately a 1000 characters in every row)

By 'updating the db' I meant, adding new rows to the db.

When I open SQLite Browser and open the 'Browse Data' tab from any other tab, UI freezes and it takes about 5 seconds to load. Once it loads, when I try to scroll (up/down or left/right), it lags, UI freezes for about 4-5 seconds again (sometimes it even says 'Not responding' for a while). When I click on any field to edit it, it takes quite some time to get selected.

**Comment by justinclift** [comment] 2016-09-02 14:27
@abhilash1in Just to check, which version are you using, and which OS is it running on?

We made *some performance* enhancements with the recent 3.9.0, but if you're using that one and it's still not great it sounds like more effort is probably needed.

As a second thought, if you're on Windows or OSX, would you be ok to try the latest nightly build?  That has some internal changes which should make some operations faster, so it **might** help. :smile:

**Comment by abhilash1in** [comment] 2016-09-02 14:35
I'm using 3.9.0 on Windows 10. I've faced the lag since version 3.8.0. It was infact why I updated to 3.9.0 recently.

I shall try the latest nightly build soon and let you know!

**Comment by abhilash1in** [comment] 2016-09-02 14:36
I **must** mention that 3.9.0 has been significantly faster than 3.8.0!

**Comment by chrisjlocke** [comment] 2016-09-02 14:38
Any chance of a copy of the database?  Only ask to test it on another machine.  Such a lag sounds 'odd' so wanted to check it here...
From the schema you've provided, I could knock up a 'possible duplicate', but just wanted to cut a corner or two! :wink:

**Comment by abhilash1in** [comment] 2016-09-02 14:48
It's for a client and I can't share it publicly! Even I'm beginning to wonder now if my PC is starving for resources with Android Studio and Chrome browser open in the background! If you can email me, I might be able to share it personally! abhilash1in@gmail.com  :wink:

**Comment by justinclift** [comment] 2016-09-02 14:55
@chrisjlocke This one is yours for in-depth investigation (eg knock up the duplicate for testing, or email @abhilash1in, etc). :smile:

@abhilash1in As a thought, do you have the "Edit Database Cell" panel open?  If so, see if turning that off makes a difference.  If it doesn't something else to investigate is this:

1. Make a copy of the database
2. In the copy, empty out the image column.  eg `UPDATE slides SET img = NULL`, and see if the performance noticeably changes
3. Also try the same "empty out X column" with other ones to, just to test.  It might also be useful to just empty out **some** of the images (use a WHERE clause), to see if there's a threshold where things change

Those should at least be decent steps to gather useful info with. :smile:

**Comment by abhilash1in** [comment] 2016-09-02 15:02
I emptied the `img` column in a copy of the database and browser is lightning fast!

I cant seem to figure out a suitable `WHERE` clause to empty only **some** of the records. Assistance please?

**Comment by chrisjlocke** [comment] 2016-09-02 15:32
Feel free to ZIP the database and email it to me at chris@chrisjlocke.co.uk

I can knock up a program which wipes out blocks of X records (eg, 10 or 20) and see what happens.

**Comment by chrisjlocke** [comment] 2016-09-02 15:36
I've just amended my database with about 30,000 characters in each of the four fields, and while there was no lag, DB4S did 'cough' and thus, showed no data.

![image](https://cloud.githubusercontent.com/assets/7872218/18209358/4e6fd092-712b-11e6-93a2-c047a693f313.png)

Will try with BLOBS, as that seems to be the performance 'issue'.

**Comment by chrisjlocke** [comment] 2016-09-02 22:47
Can confirm long strings in a field make DB4S cough.  Have attached a small database.  Shove 100,000 characters in a field, and DB4S struggles browsing data or viewing records via the 'Execute SQL' tab.

It didn't make much difference having a long continuous line of text or text with spaces in it (thought the grid would prefer the latter).  As the grid can only display X characters, would it be worth the grid only showing the first X characters of the field?  Or would that have too much of a speed impact to be worth it?
Creating a SQL query without the long field (so 'select _rowid_ from a') is speedy.  'select * from a' is not.  This would point to it being a 'displaying the data' issue rather than 'DB4S can't cope with large blobs of data' issue.

[bloat1.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/453013/bloat1.zip)

**Comment by justinclift** [comment] 2016-09-03 03:11
Interesting.  As a test, it's probably worth checking whether monospaced fonts (eg Courier) make a difference.

With the hex view in the Edit Cell panel, they're noticeably faster than non-monospaced fonts.

That's unlikely to be the complete solution though. :wink:

**Comment by glawrence** [comment] 2016-09-03 07:42
I wonder whether we should default to only pulling back part of a very large field and then go back for everything only when needed. Easier said than done I know! I used to work with a database that was pretty much like that.

**Comment by chrisjlocke** [comment] 2016-09-03 09:05
Changing the font to a fixed width font has no effect - either positively or negatively.
As there is no benefit of displaying 300,000 characters in a grid cell, maybe there should be a display limit, so that the 'edit cell' pane is used for full editing.
In the above screenshot, I linked to where DB4S displayed 'Inf' instead of the cell contents.  Its worth noting that even the 'Edit Cell' pane displayed 'Inf' and said the cell contained 3 bytes, rather than the full cell contents and the correct number of bytes.

**Comment by chrisjlocke** [comment] 2016-09-03 14:23
Just a note too that the memory usage is phenomenal while using the above database.  The .exe was using about 1 GB, but on my 16 GB machine, I noticed I was using 91% of it.  Closed the database, and it all came back...

**Comment by innermous** [comment] 2016-09-03 15:01
I still didn't get answer to my question.

**Comment by abhilash1in** [comment] 2016-09-03 15:03
@innermous just the UI

**Comment by innermous** [comment] 2016-09-03 15:04
@abhilash1in can you send me a copy(or just a part) of database? That's needed to localize the trouble.

**Comment by abhilash1in** [comment] 2016-09-03 15:10
@innermous you can use @chrisjlocke's[ bloat1.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/453013/bloat1.zip) and [bloat2b.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/453013/bloat1b.zip) to reproduce it. I verified with those db's and it's the exact same problem as originally described.

**Comment by innermous** [comment] 2016-09-03 15:13
@abhilash1in alright, thanks.

**Comment by innermous** [comment] 2016-09-03 15:18
What's surprising me - paging is not helping much.

**Comment by abhilash1in** [comment] 2016-09-03 15:48
@chrisjlocke the memory usage is a bit strange! Was it with the bloat1, bloat1b or with the original one I shared? On my PC, 

1. bloat1 contantly takes about 173 MB of memory. Only the CPU usage raises from 0% initially upto about 20% (sometimes lesser) when I scroll (up/down or left/right) in the browser or if I click on a menu item (say File) or if I switch from another application to the browser. Took about 6 seconds to open the Browse Data tab once the db was opened in the browser.

2. bloat1b contantly takes about 340MB of memory. The CPU usage raises from 0% initially upto about 22 - 26% (sometimes lesser) on similar circumstances as above. Took about 12 seconds (twice as much as bloat1) to open the Browse Data tab.

3. my original db contantly takes about 75-80 MB of memory. The CPU usage goes upto about 23%. Took 3 seconds to open the Browse data tab. 

One interesting thing that I noticed is that when the field with large text is not in the viewable area of the browser (when I resize the browser and scroll away from this field), the browser is fast and CPU usage is under 5%. When I scroll right towards the field with large text, that is when all the problems seem to occur. While scrolling right, it scrolls fast till the field is encountered and then hangs/freezes for a couple of seconds and then loads and completes the scroll. Once this field is in view, the problems are as described initially.

**Comment by innermous** [comment] 2016-09-03 15:50
@abhilash1in 173 is memory taken by rows displayed on your screen. 
Honestly, it's not essential. Both your original and @chrisjlocke 's modified tables are causing troubles that should be fixed...

**Comment by innermous** [comment] 2016-09-03 16:15
Well, I found a way to optimize it. I am working on pull request. Someone won't like it though, that's why I don't push it straight to master. So we'll have a discussion.

**Comment by abhilash1in** [comment] 2016-09-03 16:16
@innermous could I know the problem and your approach? Just curious :smiley:

**Comment by innermous** [comment] 2016-09-03 18:11
@abhilash1in just adding limit. Partly solves the problem, since table still needs lots of performance improvement (not mentioning filtering and sorting, those will just hang the app when using such a big data).
But this solves the trouble for you, at least. Test it with latest commit, please.

**Comment by innermous** [comment] 2016-09-03 20:02
@abhilash1in did it work for you?

**Comment by chrisjlocke** [comment] 2016-09-04 08:39
>@chrisjlocke the memory usage is a bit strange! Was it with the bloat1, bloat1b or with the original one I shared?

It was mine, but I was playing with various tabs in the 'Execute SQL' tab, so each tab was using another 300 MB of memory.  Task Manager showed the .exe was only using about 200 MB, so Windows was using it elsewhere...

**Comment by abhilash1in** [comment] 2016-09-04 16:35
@innermous should I build from the application from source? I'm not sure how to do it

**Comment by chrisjlocke** [comment] 2016-09-05 05:04
Check the nightly from here:
http://sqlitebrowser.oldsch00l.com/

It appears to only display/retrieve the first 5,000 characters from the field.  So the good news is that it displays in the grid much quicker, but the downside is that you can no longer view/edit the full field contents.  Consider it a temporary tweak... :wink:

**Comment by justinclift** [comment] 2016-09-05 11:24
Do you reckon it would be a useful if we take small screenshots of new things (like in your post just above), and add them to a page on the wiki named something like "New features in DB4S 3.10.0" ?  It'd be useful reference info, and we could probably use it as source materials (eg cut-n-paste :wink:) for the 3.10.0 release notes. :smile:

**Comment by chrisjlocke** [comment] 2016-09-05 13:22
The wiki certainly could do with padding out... :wink:

**Comment by justinclift** [comment] 2016-09-05 19:16
@abhilash1in Did you have a chance to try out the latest Windows nightly build?  (if it helps, the download locations are listed on our front page)

**Comment by MKleusberg** [comment] 2016-09-06 12:26
@chrisjlocke I was confused by this, too :smiley: For me at least the problem was that the minimum value for this field is 1000. If you set a value below that (I was trying 5 for testing purposes) Qt recognises it as an invalid value and changes it back to 5000. Other than that I couldn't see any problem with the settings dialog.

**Comment by MKleusberg** [comment] 2016-09-06 12:35
```
It appears to only display/retrieve the first 5,000 characters from the field. So the good news is that it displays in the grid much quicker, but the downside is that you can no longer view/edit the full field contents. Consider it a temporary tweak... :wink:
```
This should be fixed by 4b79f92eaac280c621244cb36c6954f0976c5142. So the next nightly build might be worth checking out :smiley:

**Comment by justinclift** [comment] 2016-09-06 12:45
That's awesome @MKleusberg.  I was wondering how to distinguish between the two different uses for the same data() call.

As you've just shown... that's what roles are for. :smile:

**Comment by innermous** [comment] 2016-09-06 19:06
@MKleusberg because I set minimum to 1k :)
@chrisjlocke do you really think 5k symbols can be displayed handy? Editor is just for that, grid is preview stuff...

**Comment by chrisjlocke** [comment] 2016-09-06 19:37
No, I don't think 5000 characters is handy ... The grid can only show at tops 20, and as its truncated, shouldn't be edited, so I was entering low values, and it was being reset to 5000. . I didn't realise the 'edit cell' pane was showing the full text either... It only displayed '5000 characters' in its status. I didn't test it any further or deeper as I thought it was work in progress...

I assume that's what you meant by 'do you really think 5k symbols can be displayed handy?' - did you think I wanted more??

**Comment by innermous** [comment] 2016-09-06 19:43
@chrisjlocke feel free to change it?

And yeah, 1k is lower limit. As I said, feel free to change it, even via github. Say, to 1.

**Comment by justinclift** [comment] 2016-09-06 19:46
Yeah, 1 makes sense to me as a lower boundary.  If people want to choose that, we might as well let them, it's shouldn't hurt anything. :smile:

**Comment by MKleusberg** [comment] 2017-01-03 19:35
Any updates on this issue?

**Comment by justinclift** [comment] 2017-01-03 19:45
From memory of ages ago, I changed the lower limit to be 1 (as in a singular character).

Haven't followed up though to check for performance differences. :wink:

**Comment by MKleusberg** [comment] 2017-01-03 20:12
You're right, looks like the minimum is 1 now. But I'm not sure if that helps performance-wise either :wink:

**Comment by chrisjlocke** [comment] 2019-01-08 10:03
I'll close this, as this seems a lot better in the latest nightly.

**Closed by chrisjlocke** 2019-01-08 10:03 UTC
Labels: performance, response requested
