### ISSUE TITLE
[Bug]: SELECT sqlite_version() crashes the app

### ISSUE THREAD

**Issue by shutterfreak** [sqlitebrowser/sqlitebrowser#3654] opened 2024-06-08 09:33 UTC
### What did you do?

I entered the following SQLite query:
```sql
SELECT sqlite_version();
```

### What did you expect to see?

I expected to see the SQLite version

### What did you see instead?

The application crashes instantly when clicking the "execute SQL query" (play) button.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

macOS Monterey - 12.7.5 (21H1222)

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment] 2024-06-10 12:20
Ouch, that's not good. :frowning:

As a workaround, would you be ok to try our new 3.13.0 "Release Candidate 2" build, available here?

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.0-rc2

It should be pretty stable and fairly bug free, as we're preparing for our next major release. :smile:

**Comment by lucydodo** [comment] 2024-06-11 00:41
FYI: At least in my Mac, when I ran the command over RC2, I confirmed no issue.
> DB Browser for SQLite v3.13.0-rc2 on macOS Sonoma 14.5 (23F79)

**Comment by shutterfreak** [comment] 2024-06-12 06:40
I get an APPCRASH (Symbol not found: (__ZTVNSt3__13pmr25monotonic_buffer_resourceE)) when I launch RC2:

```text
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               DB Browser for SQLCipher-v3.13.0-rc2 [58355]
Path:                  /Applications/DB Browser for SQLCipher-v3.13.0-rc2.app/Contents/MacOS/DB Browser for SQLCipher-v3.13.0-rc2
Identifier:            net.sourceforge.sqlitebrowser
Version:               3.13.99 (3.13.99)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-06-10 14:38:12.3990 +0200
OS Version:            macOS 12.7.5 (21H1222)
Report Version:        12
Anonymous UUID:        6F10640A-7690-24FE-59E6-5A5D4A898347

Sleep/Wake UUID:       49DCAA7C-AE05-4149-AAC3-584DF45E30F2

Time Awake Since Boot: 200000 seconds
Time Since Wake:       107950 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: (__ZTVNSt3__13pmr25monotonic_buffer_resourceE)
Referenced from: '/Applications/DB Browser for SQLCipher-v3.13.0-rc2.app/Contents/Frameworks/QtXml.framework/Versions/5/QtXml'
Expected in: '/usr/lib/libc++.1.dylib'
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x1123509a2 __abort_with_payload + 10
1   dyld                          	       0x112366ab2 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x112366ae4 abort_with_payload + 9
3   dyld                          	       0x112314699 dyld4::halt(char const*) + 615
4   dyld                          	       0x1123105b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x11230f4e4 start + 388
...
```

**Comment by lucydodo** [comment] 2024-06-12 10:58
Thank you for your confirmation. I have confirmed that RC2 version will not run on macOS 12.
To be precise, it hasn't been running since the nightly build on June 01, so I suspect that there was an issue with the recent CI migration. I'm currently investiating the cause and hope to resolve the issue before the release final version.

**Comment by lucydodo** [comment] 2024-06-17 01:31
https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.0-rc3
Hi @shutterfreak, We have released a new RC3 version that fixes this issue. :rocket:
We have confirmed that it works on macOS Monterey 12.6 (21G115). Test it out and let us know :) Thank you.

**Comment by shutterfreak** [comment] 2024-06-17 08:20
I confirm that [DB.Browser.for.SQLite-v3.13.0-rc3.dmg](https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.13.0-rc3/DB.Browser.for.SQLite-v3.13.0-rc3.dmg) works and does not crash when executing the following SQL query:
```sql
SELECT sqlite_version()
```

Note: apparently I downloaded a different DMG disk image when testing RC2 (SQLcipher). But that shouldn't affect this bug I guess.

**Comment by lucydodo** [comment] 2024-06-17 08:23
Glad to hear it worked out for you. Thank you for checking it out. I'll close the issue. :)

**Closed by lucydodo** 2024-06-17 08:23 UTC
Labels: crash, release blocker, macOS
