### ISSUE TITLE
Footer counter bug

### ISSUE THREAD

**Issue by KirillBorunov** [sqlitebrowser/sqlitebrowser#2580] opened 2021-02-06 22:45 UTC
Details for the issue
--------------------
The counter on the footer of the Browse Data tab seems to be wrong.
I have 19 rows in the table. I see 19 rows. But the counter says I'm seeing 18 rows.
![image](https://user-images.githubusercontent.com/21219388/107131281-07f20380-68e6-11eb-9dd7-26d215853489.png)

#### What did you do?
Browsed a table data.

#### What did you expect to see?
1 - 19 of 19

#### What did you see instead?
1 - 18 of 19

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

**Comment by justinclift** [comment] 2021-02-07 02:23
Heh Heh Heh.  Sounds like a weird off-by-one bug. :wink:

**Comment by chrisjlocke** [comment] 2021-03-16 09:15
Does this happen on all databases/tables, etc?  I've not seen this issue and can't seem to reproduce it - would be interesting to know if there are steps to make it appear.

**Comment by KirillBorunov** [comment] 2021-03-17 06:00
Seems to happen only one table of the database.
Other tables on the same database works correctly.
Cannot reproduce on a new database.
I can send the DB if it helps. Does not contains sensitive information.

**Comment by KirillBorunov** [comment] 2021-03-17 06:28
I tested, and it happens on some tables only.
But I found how to reproduce.

1) create new database, with new table.
2) add some columns to the table (around 8-10).
3) browse table data and add some data.
4) press the Refresh button near the table list on the taskbar.
At this moment you may or may not see the problem, it depends on the window size.
Now try to resize the window WIDTH and make is as small as possible, and press refresh again, now you will see the problem.
Now resize the window as wide as possible and you will see the problem not shows.

Demonstration: https://youtu.be/wXaxz6kXy4c

**Comment by chrisjlocke** [comment] 2021-03-17 08:05
Aah brilliant - and thanks for the screencast - always helpful to see the issue in action.  One of our developers has a huuuuuuuuge monitor now, so he'll have fun reducing DB4S down and getting out his binoculars to see this bug.  🕶

**Comment by chrisjlocke** [comment] 2021-04-20 17:23
Just another demo as I've just seen this myself.  Whether the table is fully shown or has scrollbars seems to cause a problem.  It was fine, then I resized the panes in slightly.

https://user-images.githubusercontent.com/7872218/115438465-56d0e900-a205-11eb-853a-64237af9cd09.mp4

Adding in a screencast in case it gives more of a clue of what the issue is...

**Comment by mgrojo** [comment] 2023-09-30 08:22
@KirillBorunov, I've fixed this problem, at least for my platform and Qt version. Could you try the next [nightly version](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) and confirm it also works for you? 

Issue sorting: duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/3176

**Comment by mgrojo** [comment] 2024-08-04 15:30
Fixed in v3.13.0

**Closed by mgrojo** 2024-08-04 15:30 UTC
Labels: bug, duplicate, response requested, gui, browse data
