### ISSUE TITLE
Feature request: Add option to import JPG images (as BLOB)

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1188] opened 2017-10-22 19:02 UTC
Hello everyone,

Please, add an option to import into Sqlite databases jpeg images.

Currently, on Windows 10 - Windows 7 (64bit .exe installer) I can import - export png images.
With png everything works fine. For instance,  I can drag them into my Database through the GUI.
On the contrary, it looks like jpeg images are not  supported at all. 
At least on Windows, maybe on Linux it is different...

I am testing the 3.10.99 version (on Windows 7 - 10)
QT 5.7.1
Sqltie 3.20.0

 I have also:
Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds

Thanks a lot !

**Comment by justinclift** [comment] 2017-10-23 15:53
Ahhh.  I *think* the type of files supported depends on us including Qt plugins.

From faint memory, it might be as simple as us creating a "plugins" subdirectory in the location we install to, and copying the correct plugin pieces into it.

Haven't looked into it yet, but it might not be too hard. :smile:

**Comment by MKleusberg** [comment] 2017-10-29 14:43
Seems to be related to #579. Did we miss that for the 3.10.0 release? :smile:

**Comment by SilvioGrosso** [comment] 2017-10-29 15:26
Yep. 
My feature request is pretty much a duplicate of 579...At present, on Windows (7 - 10) you can only import .png images (and other formats).
Unfortunately, It is not possible to import jpeg images. Which, by their own nature, are easy to compress in order to store them into databases later on.
BTW, this option (store blob into database) is not available on SqliteStudio and this is one of my reasons for having switched currently to SqliteBrowser :-)
THANKS a lot for your work on SqliteBrowser !It is extremely appreciated.
 

    Il Domenica 29 Ottobre 2017 15:43, Martin Kleusberg <notifications@github.com> ha scritto:
 

 Seems to be related to #579. Did we miss that for the 3.10.0 release? 😄 —

**Comment by justinclift** [comment] 2017-10-29 17:38
Yeah, we missed that.  Figuring out this plugin thing has been on my wish list for a while... I've just not really gotten around to figuring out how to get it done. :smile:

We can probably start with (say) Windows first, and once that's been figured out it shouldn't be too hard to copy the approach to also work on OSX.  Linux/BSD though, I'm not sure about.  We might have to investigate how other Qt applications do things there.  That's a problem for a later date. :smile:

**Comment by SilvioGrosso** [comment] 2017-10-29 18:43
Hello everyone,
I suppose only Kexi, as regards other open source softwares (Qt GUI and C++ code), has this feature : store images as blob
Unfortunately, Kexi 3 is  not available on Windows and I can not truly test this option. 
Besides its development is extremely slow, to say the least...


SqliteStudio (QT GUI) does not support blob images. It has been in its roadmap for ages but never implemented so far. In addition, it looks like this software is no longer developed, which is a pity since it is extremely powerful as GUI options....

Concerning Sqlite Db, I also work with SpatiaLite (wxPython GUI) which is an open source GIS software which is able to import jpeg images as blobs.

This being noted, IMHO, since you can already store png images with SqliteBrowser, I suppose the jpeg format option should not be a top priority in the roadmap :-)




 

    Il Domenica 29 Ottobre 2017 18:38, Justin Clift <notifications@github.com> ha scritto:
 

 Yeah, we missed that. Figuring out this plugin thing has been on my wish list for a while... I've just not really gotten around to figuring out how to get it done. 😄 We can probably start with (say) Windows first, and once that's been figured out it shouldn't be too hard to copy the approach to also work on OSX. Linux/BSD though, I'm not sure about. We might have to investigate how other Qt applications do things there. That's a problem for a later date. 😄 —

**Comment by justinclift** [comment] 2017-10-29 19:01
:smile:

I'll close this as a duplicate of #579, as we're trying to keep the open issue count from exploding tooooooo much. :smile:

**Comment by MKleusberg** [comment] 2017-10-30 11:32
@SilvioGrosso If you're interested in putting some effort into this, you can try downloading the right Qt version [from here](https://www1.qt.io/download-open-source/), installing it, and trying to locate the JPEG plugin DLL. There's probably somewhere in the installation directory a directory called plugins with an imageformats directory in it. From there you should be able to just copy all files (or all you need) into a newly created sub-directory called "plugins" in your SQLiteBrowser/DB4S directory, if that makes sense :wink: I can't go into any details here because I don't have a Windows system available right now. But in theory it should just work with the right DLL in the right place.

**Comment by justinclift** [comment] 2017-10-30 14:01
If someone has time to do that, and report success/failure, that would be really helpful.

The Qt version we use for the Windows builds is Qt 5.7.1.  That can definitely still be downloaded from the Qt website. :smile:

**Comment by SilvioGrosso** [comment] 2017-10-30 19:47
Hello everyone,
Just downloaded:qt-opensource-windows-x86-winrt-msvc2015-5.7.1.exe
My system is:Windows 7 - 64 bit (Cpu Intel I7)
I have updated SqliteBrowser by installing today's new Windows x64.exe version.

I have copied-pasted the QT 5.7.1 folder with all jpeg .dlls library (renamed plugins, as requested).
Here is a Dropbox link to download this Qt folder, which I have pasted into the directory where I have installed SqliteBroweser:https://www.dropbox.com/s/yw8wzn0zuhs4vvt/plugins.zip?dl=0

Here is a MP4 video recorded, with all my steps to try to open jpeg images on Windows 7 - 64 bit:SQLITEBROWSER_QT_JPEG_PLUGINS.mp4

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
SQLITEBROWSER_QT_JPEG_PLUGINS.mp4
 Shared with Dropbox  |   |

  |

  |

 

Unfortunately, it does not work.
As usual, I can only open (import) png images.Jpeg images are not displayed...





  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
plugins.zip
 Shared with Dropbox  |   |

  |

  |

 
 

    Il Lunedì 30 Ottobre 2017 15:01, Justin Clift <notifications@github.com> ha scritto:
 

 If someone has time to do that, and report success/failure, that would be really helpful.The Qt version we use for the Windows builds is Qt 5.7.1. That can definitely still be downloaded from the Qt website. 😄 —

**Comment by SilvioGrosso** [comment] 2017-10-30 19:58
Sorry about my previous post :-(
My Yahoo provider as screwed up all my email message formattings (as usual...) on top of deleting my Dropbox link (with all my steps recorded on Windows 7 - 64 bit).
Here is the link:
https://www.dropbox.com/s/rr996pdthgvrpij/SQLITEBROWSER_QT_JPEG_PLUGINS.mp4?dl=0

**Comment by MKleusberg** [comment] 2017-10-30 20:25
Hmm, two more ideas then:
1) Can you see what happens if you rename the "plugins" directory to "imageformats"?
2) If that doesn't work, can you check if it's working if you move all the files from the "plugins"/"imageformats" directory directly into the directory where the "DB Browser for SQLite.exe" file is?

**Comment by SilvioGrosso** [comment] 2017-10-30 21:13
Nope :-)
Both suggestions do not work (imageformats renaming + paste all files into main folder).
Do not worry though. At present, I can manage without this feature (jepg support on Sqlitebrowser).
To my knowledge, only SpatiaLite, as open source software GUI, has this feature properly implemented on Windows.


At present, however, to get a real *top-notch* support for blob images on Windows you are forced to buy some commercial software (e.g. SqliteMaestro)
Thanks a lot for your work on SqliteBrowser. This software has really improved these past months ! :-)
 

    Il Lunedì 30 Ottobre 2017 21:26, Martin Kleusberg <notifications@github.com> ha scritto:
 

 Hmm, two more ideas then:   
   - Can you see what happens if you rename the "plugins" directory to "imageformats"?
   - If that doesn't work, can you check if it's working if you move all the files from the "plugins"/"imageformats" directory directly into the directory where the "DB Browser for SQLite.exe" file is?

**Comment by justinclift** [comment] 2017-10-30 22:10
Ahhh, I think it's probably a mismatch on the MSVC version.  We're still using MSVC 2013, and looking at the [Qt 5.7.1 archives](http://download.qt.io/archive/qt/5.7/5.7.1/) it has separate downloads for MSVC 2015 vs MSVC 2013.  I probably should have thought of that and checked before.

This seems like it would be the right one:

* http://download.qt.io/archive/qt/5.7/5.7.1/qt-opensource-windows-x86-msvc2013_64-5.7.1.exe

**Comment by SilvioGrosso** [comment] 2017-10-30 23:23
Hello Justin !

Just installed the Qt 5.7.1 downloaded thanks to your last link.
I have installed this different QT version on a new clean Windows computer whose version is 8.1 (previous one had 7 version). 
On this hardware I have installed today's version (3.10.99) of SqliteBrowser (x64.exe installer).

To make it short it does not work.

In essence:
1) paste the whole folder named as "imageformats" does not allow to open jpeg image (neither by dragging nor importing them) ;
2) renaming this folder as "plugins" does not work ;
3) pasting all files into the main folder of SqliteBrowser does not work either.

My best regards

**Comment by MKleusberg** [comment] 2017-10-31 17:07
One more try :wink: Can you install tomorrow's nightly build and check again if it works with the plugins directory?

**Comment by SilvioGrosso** [comment] 2017-11-01 10:08
You nailed ! :-)

Just tested on 3 different systems: Windows 7 + 8.1 + 10 (x64 bit) with today's daily build.
I can now import all jpeg images on top of other formas (tiff, gif etc not tested yet).
On top of that, I can also export jpeg images.
To do so I have pasted the imageformats folder into the directory where I have installed Db Browser for Sqlite.
It works smoothly when it is named as "imageformats" (not "plugins" as also suggested).

Here is the link to download from Dropbox these QT 5.7.1 dlls librairies:
https://www.dropbox.com/s/3qvtcgbrqbi2oty/imageformats.zip?dl=0

I have even uploaded on YouTube a short video tutorial (I hope you don't mind):
https://www.youtube.com/watch?v=CW739mop1Nc

Thanks a bunch indeed !

**Comment by justinclift** [comment] 2017-11-01 13:32
> I have even uploaded on YouTube a short video tutorial (I hope you don't mind)

That's awesome. Added it to the front page of our wiki, in a new "[Videos for Users](https://github.com/sqlitebrowser/sqlitebrowser/wiki#videos-for-users)" section.

Want to create more? 😀

**Comment by MKleusberg** [comment] 2017-11-01 17:04
Awesome 😄 I'm glad this is finally working now!

@justinclift Do you have any experience with [this part](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/CMakeLists.txt#L370-L410) of the CMakeLists.txt file to somehow include the files in the installer? We would need to copy the *.dll files (*.dll for release model, *d.dll for debug mode) from that Qt plugins/imageformats directory to the imageformats directory in our installation dir. Also we would need to include different DLLs depending on whether we're building the 32bit or the 64bit version. I'm guessing that this would just work with our current build process but I'm not sure :wink:

@SilvioGrosso Thanks for your time and effort on this 👍 Since you seem to know all the other SQLite GUIs and I have never really bothered looking into them, if you feel like we're missing some important feature or two, feel free to open an issue for that, too :wink:

**Comment by justinclift** [comment] 2017-11-01 19:18
@MKleusberg Yep.  Just finished setting up a new Win7 development VM to try things out in, as I don't want to screw up our build one (just in case).  I should be able to get this figured out... :smile:

**Comment by justinclift** [comment] 2017-11-03 16:47
Hmmm, it's probably better to continue the conversation in the other issue. :smile:

**Closed by justinclift** 2017-11-03 16:47 UTC
Labels: duplicate
