### ISSUE TITLE
Cannot create TRIGGER as shown in SQLite Example

### ISSUE THREAD

**Issue by kwasmich** [sqlitebrowser/sqlitebrowser#1470] opened 2018-07-10 12:39 UTC
Details for the issue
--------------------

#### What did you do?
I tried to create a trigger on an existing database. But without success. So instead I went over to sqlite.org and tried the [examples](https://www.sqlite.org/lang_createtrigger.html).

The executed lines are:
```
CREATE TABLE customer( cust_id INTEGER PRIMARY KEY, cust_name TEXT, cust_addr TEXT);
CREATE VIEW customer_address AS SELECT cust_id, cust_addr FROM customer;
CREATE TRIGGER cust_addr_chng INSTEAD OF UPDATE OF cust_addr ON customer_address BEGIN UPDATE customer SET cust_addr=NEW.cust_addr WHERE cust_id=NEW.cust_id; END;
```
And it fails on the last line.

#### What did you expect to see?
I expected to execute the sample code and thus successfully create a trigger.

#### What did you see instead?
incomplete input: CREATE TRIGGER cust_addr_chng INSTEAD OF UPDATE OF cust_addr ON customer_address BEGIN UPDATE customer SET cust_addr=NEW.cust_addr WHERE cust_id=NEW.cust_id

Useful extra information
-------------------------

The three statements execute successfully in the sqlite3 command line tool which is `3.24.0 2018-06-04 19:24:41 c7ee0833225bfd8c5ec2f9bf62b97c4e04d03bd9566366d5221ac8fb199a87ca`.

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( 10.11.6 )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2018-07-10 12:58
Thanks @kwasmich, that does sound like a bug.

**Comment by chrisjlocke** [comment] 2018-07-10 14:15
I believe this might be corrected in the nightlies.

![image](https://user-images.githubusercontent.com/7872218/42515567-f404b7ec-8453-11e8-9bd5-ca6080920be8.png)

It seems to work OK for me.
@kwasmich - Can you try a more recent build from here?
https://nightlies.sqlitebrowser.org/latest/

**Comment by kwasmich** [comment] 2018-07-10 14:22
Yes I've tried the nightly with the same results. BUT to further narrow it down:
I executed each line individually and not in one transaction.
It works fine in one transaction but not when stepped through every line.

**Comment by justinclift** [comment] 2018-07-10 15:36
Oh, as bugs go that definitely seems like a weird one.  It's good it's so easy to reproduce though, as it should at least make it easy to track down. :smile:

**Comment by chrisjlocke** [comment] 2018-07-10 15:36
Aah, that's probably the 'gotcha' then.  When executed as one lump, DB4S just 'eats the lot'.  When told to parse each 'line', it gets a bit confused with the last line ending with ;END, as a semi-colon is normally used to terminate a SQL statement (as in the top two lines).  So DB4S is actually treating the 3rd line as 2 separate commands...

**Comment by MKleusberg** [comment] 2018-07-12 19:09
An easier workaround would be to select the current line and click the normal ```Execute``` button which will only the current selection if there is one.

But yeah, this is definitely a bug. The easiest way to trigger it is by only having this simple statement and trying to execute it by clicking the ```Execute current line``` button:
```sql
SELECT ";"
```
As @chrisjlocke suspected, this is because we split the statement at the semicolon. See #780 for details why. I'll have to think about this a bit more - no idea how to fix this and still have the features from #780.

**Comment by MKleusberg** [comment] 2018-07-12 20:30
I believe this is fixed now. Can you try again with tomorrow's nightly build and check if it's working for you as well, @kwasmich? 

This required larger changes in the involved code. So if any strange behaviour shows up, please let me know everybody :smile:

**Comment by kwasmich** [comment] 2018-07-14 12:22
To me it looks fine! I can't reproduce the issue with the latest nightly build.

**Comment by MKleusberg** [comment] 2018-07-14 13:12
Cool, thanks for testing and thank you again for reporting this issue! I'm going to close this then :smile:

**Closed by MKleusberg** 2018-07-14 13:12 UTC
Labels: bug, response requested
