### ISSUE TITLE
Incorrect encoding for tooltip

### ISSUE THREAD

**Issue by Vort** [sqlitebrowser/sqlitebrowser#1107] opened 2017-08-28 06:59 UTC
### Details for the issue

When I type `COUNT(` at `SQL` tab, tooltip with ??? characters instead of russian text pops out:

![sqb](https://user-images.githubusercontent.com/1242858/29762334-b2b8ba5c-8bd6-11e7-8a42-ab9076708077.png)

There should be `COUNT(X) Функция count(X) возвращает количесвто строк, в которых X не равно NULL в группе.` message.

BTW, there is a typo in this text: `количесвто` should be `количество`.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 7 SP1 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-08-28 07:30
Thanks @Vort, that does look like a bug. :smile:

We probably won't have time to look at it for a few days though. 😦 

With the typo, I'll get that fixed later today.

**Comment by MKleusberg** [comment] 2017-09-01 11:27
The problem seems to be with Scintilla. [Here](http://scintilla-interest.narkive.com/qpX0vAm0/calltips-for-unicode-strings-utf-8-encoding) they say, it can be fixed by using a different font but with the two fonts I've tried so far I didn't have any luck.

**Comment by justinclift** [comment] 2017-09-01 13:14
Oops, I forgot to fix the typo too.

**Comment by justinclift** [comment] 2017-09-01 13:17
Typo now fixed: ddd08a4f9ddc09154287777bece8f88699ad9ac2

**Comment by to302** [comment] 2017-10-31 07:57
ko_KR has same problem. (version 3.10.1)

**Comment by mgrojo** [comment] 2017-11-01 17:36
The same problem is reproduced in Spanish with accented characters. I'm looking into this, but the Scintilla code related to encoding is specially convoluted. I can make the tooltip to present correctly in Spanish, but then, the text encoding in the editor is broken...

**Comment by mgrojo** [comment] 2017-11-01 19:24
Wow, I didn't know that my comment in the commit would close the Issue. Nevertheless I've tested it for Spanish, Russian and Korean and is working for me.

**Comment by justinclift** [comment] 2017-11-01 19:28
@mgrojo Yeah, that automatically-close-the-issue based on keywords has caught everyone else out a few times too already. :wink:

@Vort @to302 Would you have time to try the nightly build tomorrow?  Thanks to @mgrojo this should be fixed now. :smile:

**Comment by Vort** [comment] 2017-11-02 17:30
Fixed. Thanks.

**Comment by justinclift** [comment] 2017-11-02 17:34
Thanks for checking @Vort.  Good stuff @mgrojo. :smile:

**Closed by justinclift** 2017-11-02 17:34 UTC
Labels: bug, response requested

**Comment by MKleusberg** [comment] 2017-11-02 22:16
Glad this is finally fixed :smile: Just wanted to mention that we should probably send this to upstream QScintilla too but apparently they just fixed it yesterday: https://www.riverbankcomputing.com/static/Downloads/QScintilla/ChangeLog-2.10.2.dev1711012104. Maybe they are watching us 😆

**Comment by mgrojo** [comment] 2017-11-02 22:22
Maybe they are watching us, but I sent them yesterday a patch :sweat_smile:  I didn't want that my fix was lost for other users or for future updates of our QScintilla copy. Glad they have so soon applied it.

**Comment by MKleusberg** [comment] 2017-11-02 22:23
Cool, good thinking 😃
