### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by xangels** [sqlitebrowser/sqlitebrowser#1038] opened 2017-06-10 07:13 UTC
### Details for the issue
Open a database
go to browse
now click on the drop down and choose the first item on the list.
Crashes - Yes nightly build

**Comment by xangels** [comment] 2017-06-10 07:14
Sorry this is for DB Browser for SQLite

**Comment by justinclift** [comment] 2017-06-10 07:49
Yeah, there are definitely problems in our recent nightly builds.  Just no time for investigating the problem yet. ☹️ 

The ones **before** 19th May seem ok.  eg 18th of May and earlier

Depending on which Operating System you are using, grab an appropriate one here:

* https://nightlies.sqlitebrowser.org/win64/
* https://nightlies.sqlitebrowser.org/win32/
* https://nightlies.sqlitebrowser.org/osx/

Does that help? :smile:

**Comment by xangels** [comment] 2017-06-11 05:02
Confirmed. May 18th is fine.

**Comment by justinclift** [comment] 2017-06-11 09:29
Cool.  Hopefully we'll get the crash problem fixed in the next week or so.

**Comment by chrisjlocke** [comment] 2017-06-12 10:34
A duplicate of #1019.

**Closed by chrisjlocke** 2017-06-12 10:34 UTC
Labels: crash, duplicate
