### ISSUE TITLE
Cannot type Unicode characters in 'Execute SQL' tab.

### ISSUE THREAD

**Issue by z-rui** [sqlitebrowser/sqlitebrowser#288] opened 2015-05-02 08:37 UTC
In 'Execute SQL' tab:
Non-latin1 characters become question marks (```?```) if I try to type them.

If I copy or type the following SQL and execute it:
```sql
select unicode('α');
```
it becomes:
```sql
select unicode('?');
```
and the result is ```63``` (Unicode value for question mark(```?```)).

I'm using 3.6.0 on Windows 8.1.

**Comment by justinclift** [comment] 2015-05-02 13:01
Interesting.  We fixed a unicode bug yesterday that might also solve this problem.  Would you be ok to try the latest nightly build and see if that works? (if so, the download locations are on the front page of this repo) :smile:

**Comment by MKleusberg** [comment] 2015-05-02 17:44
Yes, this should be a duplicate of #282, so the current nightly build (https://github.com/sqlitebrowser/sqlitebrowser#windows) should fix this problem for you :)

**Comment by z-rui** [comment] 2015-05-03 05:41
All right, the nightly build fixed the problem.

**Comment by justinclift** [comment] 2015-05-03 08:03
Cool.  Thanks for letting us know @z-rui. :smile:

**Closed by justinclift** 2015-05-03 08:03 UTC
Labels: bug
