### ISSUE TITLE
Index containing expression not correctly displayed in database structure overview

### ISSUE THREAD

**Issue by hwiesmann** [sqlitebrowser/sqlitebrowser#2057] opened 2019-11-30 13:27 UTC
Details for the issue
--------------------

#### What did you do?
Created an index with an expression (e.g. max (column))

#### What did you expect to see?
Looking at the database structure and the above mentioned index I expect to see under the details of the index as the name max(column)

#### What did you see instead?
max(column

The closing bracket is missing in the name and schema column.

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-lp64] on macOS 10.14 (darwin/18.7.0) [x86_64]
> using SQLCipher Version 4.1.0 community (based on SQLite 3.27.2)
> and Qt 5.11.3

**Comment by MKleusberg** [comment] 2019-12-01 14:52
Can you check again with the latest nightly build? You can download it [here](https://nightlies.sqlitebrowser.org/latest/). We have rewritten large parts of the SQL parsing and generating code and I can't reproduce this problem with the latest code. So it's likely to be fixed in the nightly build :smile:

**Comment by hwiesmann** [comment] 2019-12-01 20:53
Hi,

indeed, bug has been fixed!

Thanks!

**Comment by justinclift** [comment] 2019-12-03 01:36
Awesome, you're welcome @hwiesmann. :smile:

**Closed by justinclift** 2019-12-03 01:36 UTC
