### ISSUE TITLE
Browse Data issue

### ISSUE THREAD

**Issue by roxx** [sqlitebrowser/sqlitebrowser#829] opened 2016-10-15 23:59 UTC
### Details for the issue

If I want to browse the data which I select from "Database Structure Tab"
It opens the first table of the database, not the one I selected. 

Also when I switching through the tabs, the table that I selected in "Browse Data" tab suddenly relocated to the first table of the db.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows: ( _version: 7 Pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by innermous** [comment] 2016-10-16 00:20
Both of those issues were fixed... Now it's broken again.

**Comment by innermous** [comment] 2016-10-16 00:28
**UPD**: 
>Also when I switching through the tabs, the table that I selected in "Browse Data" tab suddenly relocated to the first table of the db.

It works fine in gbeff43a revision. Happy hacking!

**Comment by chrisjlocke** [comment] 2016-10-16 09:29
Hi @roxx 

If you download the latest 'night;y build of DB4S:
http://sqlitebrowser.oldsch00l.com/sqlitebrowser.exe.zip

these issues should be fixed in that version.... theoretically....

**Comment by innermous** [comment] 2016-10-16 12:26
@chrisjlocke they are not.

**Comment by innermous** [comment] 2016-10-16 13:09
>If I want to browse the data which I select from "Database Structure Tab"
It opens the first table of the database, not the one I selected. 

This was working couple months ago, after some of @MKleusberg 's commits. Real question is what was that commit exactly.

**Comment by chrisjlocke** [comment] 2016-10-16 13:36
> @chrisjlocke they are not.

Aah, sorry.

**Comment by innermous** [comment] 2016-10-16 13:47
Yeah, it doesn't. But I am talking about another bug he mentioned. He mentioned 2 bugs.

**Comment by chrisjlocke** [comment] 2016-10-16 13:56
Yup, got that. Just reporting my findings... : smile:

Thanks,
Chris

**Comment by revolter** [comment] 2016-11-24 08:31
Isn't this the same as #879, which is caused by #748?

**Comment by justinclift** [comment] 2016-11-24 08:36
@revolter Sounds like it.

**Closed** 2018-10-12 22:46 UTC
Labels: duplicate
