### ISSUE TITLE
Crash when I try to create a new database

### ISSUE THREAD

**Issue by lucy9383** [sqlitebrowser/sqlitebrowser#1043] opened 2017-06-17 06:59 UTC
#### I'm opening this issue because:

- [X] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 8.1_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [X] 3.9.0
- [ ] Other: ___

#### I have also:

- [X] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2017-06-17 08:04
@lucy9383 Yeah, there are definitely problems in our recent nightly builds.  Just no time for investigating the problem yet. ☹️ 

The ones **before** 20th May seem ok.  eg 19th of May and earlier

Depending on which Operating System you are using, grab an appropriate one here:

* https://nightlies.sqlitebrowser.org/win64/
* https://nightlies.sqlitebrowser.org/win32/
* https://nightlies.sqlitebrowser.org/osx/

Does that help? :smile:

**Comment by justinclift** [comment] 2017-06-17 08:05
@chrisjlocke Do you reckon we should copy the builds for the 19th May back over our latest nightlies, and suspend the updating of them each night for now?  It's a trivial change to do.

**Comment by justinclift** [comment] 2017-06-17 08:09
@chrisjlocke As a thought for diagnosing the problem, do you have time to try making a few builds?

There are 3 commits on the 20th May, and we don't know which one of them is the trigger.  If you've time to build a DB4S from git a few times + test it, but rewinding it back to just before each of those commits... that should give us a definitive answer.

**Comment by chrisjlocke** [comment] 2017-06-17 09:04
Not until Monday.  @lucy9383 's issue isn't to do with the 'browse table' crash though, but to do with the 'new database' button.  From the looks of the intro, she has tried the latest nightly, so thought I'd just point out that the ones after 20 May were broken.
I've not seen this particular crash on Win 8.1 before, so need to find one at work.  We've several Win 8 machines, so one of those most exhibit this behaviour.

**Comment by justinclift** [comment] 2017-06-17 09:07
No worries. :smile:

**Comment by MKleusberg** [comment] 2017-06-17 20:38
@lucy9383 Unfortunately this isn't to fix because I'm unable to reproduce the issue. As @chrisjlocke already pointed out we already had one user with this problem but didn't manage to find the source of the problem. However, let's do our best to track this down this time :wink: I've just written a first draft of a Wiki page that explains how to gather more debug information in situations like these. You can find it [here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Debugging-a-crash-on-Windows). I've written it almost blindly because I don't have a Windows system available but I hope it provides some clues nonetheless. And you're always free to edit and extend the Wiki page :smile: Anyway, can you try to reproduce the crash in WinDbg and provide the information mentioned in the Wiki page? This should really help us finding the source of the problem.

**Comment by lucy9383** [comment] 2017-06-20 11:18
Hi,

Sorry for the late reply.  I have tried to run WinDbg.  Following is the information I got.  Hope it will help:

Microsoft (R) Windows Debugger Version 6.3.9600.17237 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: "C:\Program Files\DB Browser for SQLite\DB Browser for SQLite.exe"
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
ModLoad: 00007ff6`e9170000 00007ff6`e9459000   image00007ff6`e9170000
ModLoad: 00007ff8`af710000 00007ff8`af8bd000   ntdll.dll
ModLoad: 00007ff8`aef00000 00007ff8`af03e000   C:\Windows\system32\KERNEL32.DLL
ModLoad: 00007ff8`acb10000 00007ff8`acc25000   C:\Windows\system32\KERNELBASE.dll
ModLoad: 00000000`61de0000 00000000`61eeb000   C:\Program Files\DB Browser for SQLite\Qt5Network.dll
ModLoad: 00007ff8`78390000 00007ff8`784d6000   C:\Program Files\DB Browser for SQLite\sqlite3.dll
ModLoad: 00007ff8`8d900000 00007ff8`8d951000   C:\Program Files\DB Browser for SQLite\Qt5PrintSupport.dll
ModLoad: 00000000`61890000 00000000`61ddb000   C:\Program Files\DB Browser for SQLite\Qt5Widgets.dll
ModLoad: 00007ff8`77df0000 00007ff8`78387000   C:\Program Files\DB Browser for SQLite\Qt5Gui.dll
ModLoad: 00000000`61330000 00000000`61884000   C:\Program Files\DB Browser for SQLite\Qt5Core.dll
ModLoad: 00007ff8`88f60000 00007ff8`89006000   C:\Windows\SYSTEM32\MSVCP120.dll
ModLoad: 00007ff8`7b060000 00007ff8`7b14f000   C:\Windows\SYSTEM32\MSVCR120.dll
ModLoad: 00007ff8`af400000 00007ff8`af45a000   C:\Windows\system32\WS2_32.dll
ModLoad: 00007ff8`abec0000 00007ff8`abf64000   C:\Windows\SYSTEM32\DNSAPI.dll
ModLoad: 00007ff8`a7040000 00007ff8`a706a000   C:\Windows\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ff8`af460000 00007ff8`af50a000   C:\Windows\system32\ADVAPI32.dll
ModLoad: 00007ff8`ac900000 00007ff8`acadf000   C:\Windows\system32\CRYPT32.dll
ModLoad: 00007ff8`a7d70000 00007ff8`a7df2000   C:\Windows\SYSTEM32\WINSPOOL.DRV
ModLoad: 00007ff8`ad3f0000 00007ff8`ad4a6000   C:\Windows\system32\COMDLG32.dll
ModLoad: 00007ff8`ad6e0000 00007ff8`ad82b000   C:\Windows\system32\GDI32.dll
ModLoad: 00007ff8`af520000 00007ff8`af697000   C:\Windows\system32\USER32.dll
ModLoad: 00007ff8`ad9d0000 00007ff8`aeef9000   C:\Windows\system32\SHELL32.dll
ModLoad: 00007ff8`acd90000 00007ff8`acf24000   C:\Windows\system32\ole32.dll
ModLoad: 00007ff8`9cad0000 00007ff8`9caee000   C:\Windows\SYSTEM32\MPR.dll
ModLoad: 00007ff8`ad6d0000 00007ff8`ad6d9000   C:\Windows\system32\NSI.dll
ModLoad: 00007ff8`ad110000 00007ff8`ad250000   C:\Windows\system32\RPCRT4.dll
ModLoad: 00007ff8`a7030000 00007ff8`a703a000   C:\Windows\SYSTEM32\WINNSI.DLL
ModLoad: 00007ff8`af060000 00007ff8`af10a000   C:\Windows\system32\msvcrt.dll
ModLoad: 00007ff8`ad2d0000 00007ff8`ad329000   C:\Windows\SYSTEM32\sechost.dll
ModLoad: 00007ff8`ac8e0000 00007ff8`ac8f1000   C:\Windows\system32\MSASN1.dll
ModLoad: 00007ff8`ad4b0000 00007ff8`ad504000   C:\Windows\system32\SHLWAPI.dll
ModLoad: 00007ff8`8ec60000 00007ff8`8ed04000   C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.9600.17810_none_34ae2abd958aedeb\COMCTL32.dll
ModLoad: 00007ff8`af1e0000 00007ff8`af3f2000   C:\Windows\SYSTEM32\combase.dll
ModLoad: 00007ff8`acae0000 00007ff8`acb0e000   C:\Windows\system32\SspiCli.dll
ModLoad: 00007ff8`aab60000 00007ff8`aac12000   C:\Windows\SYSTEM32\SHCORE.DLL
(e34.380): Break instruction exception - code 80000003 (first chance)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
ntdll!LdrInitShimEngineDynamic+0x330:
00007ff8`af7d1c50 cc              int     3

**Comment by lucy9383** [comment] 2017-06-20 11:18
BTW, I installed the version of May 1st

**Comment by justinclift** [comment] 2017-06-20 11:57
Thanks @lucy9383. :smile:

Sorry for taking so long, we're all a bit busy at the moment with Real Life things. :wink: Hopefully we'll get time to investigate this in more depth on the weekend. :smile:

**Comment by justinclift** [comment] 2017-06-20 12:02
@lucy9383 Oh... just to check.. the version that's crashing for you... that's from the 1st May?

**Comment by MKleusberg** [comment] 2017-06-21 22:10
Thanks @lucy9383! Can you paste the call stack here as well? That's in an extra window that you can show by opening the ```View``` menu and clicking ```Call stack```. You can then just make a screen shot of that window :wink:

**Comment by MKleusberg** [comment] 2017-06-22 18:00
@lucy9383 Sorry, the Wiki page was incomplete. My bad! You'll need to open the ```Debug``` menu and click ```Go``` after loading the executable. Then you should be able to reproduce the crash in DB4S.

**Comment by justinclift** [comment] 2017-06-27 14:07
@lucy9383 Would you be ok to try out latest nightly build?  @MKleusberg fixed several crashing bugs over the last few days, so it's likely the problem you were having is now solved. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by etoxrg** [comment] 2017-07-25 13:18
I have had the same problem.
My issue was fixed by using the 32-bit and not the 64-bit.

**Comment by justinclift** [comment] 2017-07-25 13:39
Thanks @etoxrg.  That definitely sounds like a .dll conflict then.  Not sure what the cause could be, but if the 32-bit version is working ok for you... keep using it. :smile:

Out of curiosity, have you tried the recent 3.10.0-beta1 version?  Just in case the 64-bit version works ok for you.

**Comment by etoxrg** [comment] 2017-07-25 14:16
That was the first 64-bit version I attempted to use.
I then used an older version for the 32-bit, but after you asked I attempted to use the 32-bit 3.10.0-beta1.
The 32-bit 3.10.0-beta1 seems to work fine.

**Comment by justinclift** [comment] 2017-07-25 15:38
Cool.  Thanks for testing @etoxrg. :smile:

**Comment by chrisjlocke** [comment] 2017-11-09 17:36
I'll close this for now as the issue can't be reproduced and seems one of those horrible 'isolated' cases.  There is a workaround, so until it pops up again and we can debug further, this can nestle amongst the closies.

**Closed by chrisjlocke** 2017-11-09 17:36 UTC
Labels: crash, response requested
