### ISSUE TITLE
Unicode text in BLOB not copying for other aplications

### ISSUE THREAD

**Issue by gigyme** [sqlitebrowser/sqlitebrowser#724] opened 2016-08-12 07:48 UTC
### Details for the issue

![screenshot_08-12-2016-102128](https://cloud.githubusercontent.com/assets/2116400/17615903/e8bfe780-6079-11e6-8a2f-272cce93f798.png)
![screenshot_08-12-2016-102134](https://cloud.githubusercontent.com/assets/2116400/17615908/f09a96ee-6079-11e6-8c4e-438c8f67b76e.png)
![screenshot_08-12-2016-102142](https://cloud.githubusercontent.com/assets/2116400/17615910/f377ec86-6079-11e6-8443-089da0157829.png)
![screenshot_08-12-2016-102200](https://cloud.githubusercontent.com/assets/2116400/17615912/f56e5e9e-6079-11e6-89b5-9a2424448db9.png)
![screenshot_08-12-2016-102216](https://cloud.githubusercontent.com/assets/2116400/17615913/f7490674-6079-11e6-9842-1d96b3491af4.png)
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [ ] 3.7.0
- [x] 3.8.0
- [ ] Other: ___
#### I have also:
- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment] 2016-08-12 08:06
Great improvements to copy paste functionality were just added by @innermous today (#709).

Can you test the nightly build tomorrow, when these fixes will be included?

**Comment by innermous** [comment] 2016-08-13 10:04
@revolter those were not related to hex editor in Editor Dock.

**Comment by justinclift** [comment] 2016-08-13 10:29
@innermous You're off by a day. :wink:

He was meaning the code before, where you fixed the Copy/Paste handling. 😁

**Comment by innermous** [comment] 2016-08-13 12:43
@justinclift I don't understand what you are talking about.

**Comment by justinclift** [comment] 2016-08-13 12:51
@innermous No worries. :smile:

**Comment by revolter** [comment] 2016-08-13 12:57
@justinclift, @innermous is right, this issue is about the Edit Dock, sorry!

**Comment by justinclift** [comment] 2016-08-13 13:00
Oops. :smile:

**Comment by justinclift** [comment] 2016-08-13 13:01
Thinking about this a bit more... could part of the problem be how we detect BLOB's?

eg Valid unicode text with \0 inside it

**Comment by innermous** [comment] 2016-08-13 13:22
Dude, it has nothing to do with anything like blobs or nulls or whatever you are thinking. This is just not related. This is not related to my commits too.

**Comment by justinclift** [comment] 2016-08-13 13:35
Sorry @innermous. 😦

**Comment by innermous** [comment] 2016-08-16 11:53
Hm. I can't reproduce it here on archlinux.

**Comment by justinclift** [comment] 2016-08-19 11:09
It's possible this is only happening on Windows.  I can try giving it a shot here on a Windows PC in the next few days.

**Comment by mgrojo** [comment] 2019-02-09 19:16
Closing this for the reasons above explained.

**Closed by mgrojo** 2019-02-09 19:16 UTC
Labels: bug, windows
