### ISSUE TITLE
[Bug]: Error on startup in some language settings

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#3692] opened 2024-07-25 07:27 UTC
### What did you do?

Launch the app

### What did you expect to see?

Run normally

### What did you see instead?

Output an error message like below:
![image](https://github.com/user-attachments/assets/97407758-865f-49fc-a0e1-0ba08ea7986d)

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11 Pro Version 23H2 (OS Build 22631.3593)

### Prevention against duplicate issues

- #3635

**Comment by justinclift** [comment] 2024-07-25 09:05
Yeah, this is a strange error.  Wonder if the problem is the Qt language string utils (lupdate, etc) going wrong when processing language strings?

**Comment by lucydodo** [comment] 2024-07-25 09:28
I haven't looked into it yet, but my suspicion is that there's something wrong with the Korean-specific translations being handled incorrectly on the side that handles arguments.

**Comment by mgrojo** [comment] 2024-08-05 10:01
It is not visible at first sight, but it was only that the first argument was missing, because the `%` in `%L1` was indeed not there. It is fixed now. I checked the other files, and all seem to be fine.

**Comment by justinclift** [comment] 2024-08-05 10:49
Awesome.  Well done @mgrojo. :smile:

**Closed** 2024-08-14 10:14 UTC
Labels: bug, translation
