### ISSUE TITLE
Night Mode or Dark Theme

### ISSUE THREAD

**Issue by khashayarxy** [sqlitebrowser/sqlitebrowser#1493] opened 2018-08-05 21:22 UTC
Describe the new feature
--------------------------
Night Mode or Dark Theme
it would be great if you add this and I think many people want it.

**Comment by justinclift** [comment] 2018-08-05 22:47
Good news @khashayarxy.  Support for a dark mode / night theme type of thing was added a while ago by @mgrojo, in #1324.

If you're on macOS, Windows, or Ubuntu, it's in our nightly builds:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds

Would you be ok to try that out and let us know how it goes for you? :smile:

**Comment by khashayarxy** [comment] 2018-08-05 23:08
yeah, I've tried nightly builds before, but I didn't find this option.
and still can't find it...
should I use a dark theme for my windows to get this feature?

**Comment by khashayarxy** [comment] 2018-08-05 23:28
I wanted something like this so that I don't have to do that.
![officetheme](https://user-images.githubusercontent.com/42047526/43691141-c7b6e690-992c-11e8-9f8d-02b8eaa9c520.png)

**Comment by justinclift** [comment] 2018-08-06 00:10
Hmmm, yeah.  That does sound like a better approach.

@mgrojo Is it feasible to have a toggle or selection to switch between light/dark theme?

**Comment by mgrojo** [comment] 2018-08-06 13:42
> Is it feasible to have a toggle or selection to switch between light/dark theme?
If we are talking about the SQL editor, it would be feasible to have a combo box for selecting the light or the dark theme. That would allow the users to change the editor colours without restoring defaults.

But I'm unsure about the Qt widgets. They generally follow the desktop theme, as everyone would expect.

> I wanted something like this so that I don't have to do that.
What is what you wouldn't like to do? Restoring the defaults or applying a dark theme to all the system?

**Comment by justinclift** [comment] 2018-08-06 14:55
Ahhh.  Most applications that support dark and light themes seem to have either a toggle or selector.  When the user makes a change of the appropriate button or selector, the theme for the entire app changes to light or dark (as selected).  That's what @khashayarxy was likely meaning.

Saying that because I often use dark mode in applications, and that's the way I've generally seen it done.

Our current approach does work, but it has the downside of also resetting all of a users other settings too, and not just adjusting the theme.  It might be better to break out the theme adjustment into it's own button or something anyway, just to avoid resetting everything else too. :smile:

**Comment by khashayarxy** [comment] 2018-08-06 16:12
@mgrojo
Applying a dark theme to all the system

@justinclift
That is exactly my point.

**Comment by mgrojo** [comment] 2018-08-06 18:39
>  Most applications that support dark and light themes seem to have either a toggle or selector. 

But probably they don't have then options for every possible colour, like we have for the editor. That adds complexity for the settings management.

By the way, in the Linux desktop the theme is usually selected centrally. I find that the sanest approach, although one can find application that doesn't look good in dark themes.

> Our current approach does work, but it has the downside of also resetting all of a users other settings too, not just adjusting the theme. 

If we didn't let the user modify the editor colours, then it would be easy to follow the system theme without restoring the defaults. But I guess that wouldn't be very welcome.

**Comment by khashayarxy** [comment] 2018-08-06 19:02
@mgrojo 
Well, we can use this idea of having light and dark theme only in the official release.
This way everyone is happy.

**Comment by justinclift** [comment] 2018-08-06 19:58
> But probably they don't have then options for every possible colour, like we have for the editor.

Hmmm, the JetBrains IDE's do.  But yeah, that's a good point which I hadn't thought of.

I wonder if the solution would be to have the colours be stored "per profile"?  eg a "Dark" profile, and if the user edits the colours then they only affect that one.

If they switch to a (for example) "light" profile afterwards that hasn't been edited, it'd just be the default "light" profile colours.  If they change those ones, the changes get kept for the light profile only.

That way a user can have both dark and light themes, and be able to tweak them to suit.  For bonus points we could probably add some way to create extra profile/themes too.

**Comment by voltagex** [comment] 2018-08-10 08:02
Maybe I'm missing something but with Version 3.10.99 (Aug 10 2018), Qt Version 5.8.0, Windows 10's Dark mode isn't having any effect.

**Comment by mgrojo** [comment] 2018-08-10 08:09
@voltagex Is the application still in a ligth mode, or is only some widgets? Could you publish a screenshot?

**Comment by khashayarxy** [comment] 2018-08-10 08:29
@voltagex I have the latest build of Windows 10 and that Dark/Light mode is just for settings and doesn't affect applications or Windows itself. You should change the theme of Windows to see the change.

**Comment by mgrojo** [comment] 2018-08-10 15:45
My knowledge of Windows is pretty basic, but I guess that this Dark Mode will only affect to "apps", not traditional desktop applications, like DB4S is.

https://stackoverflow.com/questions/13220962/what-is-the-difference-between-windows-desktop-apps-and-windows-store-apps

**Comment by mgrojo** [comment] 2018-09-06 18:54
Let's understand this as a request for a dark theme implemented specifically for DB4S. The current implementation is adapting to the theme selected by the operating system. Maybe someone wants to contribute this.

It could be made adding a dark stylesheet like, for example: https://github.com/ColinDuquesnoy/QDarkStyleSheet

**Comment by stamminator** [comment] 2018-11-10 03:34
@voltagex Same situation for me. My Windows theme is set to dark via the Settings app, just like in your screenshot, but my DB4S 3.11.0 alpha 1 client is not picking it up. Tried toggling Windows settings and restoring defaults in DB4S several times with no success.

**Comment by wmertens** [comment] 2018-12-22 12:13
FYI, in macOS dark mode is pretty hard to read:

![image](https://user-images.githubusercontent.com/54934/50374243-5f8c6280-05eb-11e9-9113-8f5da97b9d26.png)

**Comment by mgrojo** [comment] 2018-12-22 13:49
@wmertens Could you restore the defaults in Preferences and see if it improves? I don't understand how you came to that combination. With the current version, it should either have default values, and then the it should adapt to OS theme, or have saved preferences for the editor colours, and in such case, it should have saved your colours are the defaults for the dark/llight theme that was running when you last saved the preferences. That is, the colour combination for the editor should always be coherent, even though it could be light theme in a general dark theme, or viceversa.

**Comment by wmertens** [comment] 2018-12-22 15:00
Ok, resetping defaults fixed the editor colors, that leaves the menu. I suppose I once changed an editor color to try?

**Comment by mgrojo** [comment] 2018-12-22 15:11
>  I suppose I once changed an editor color to try?

With a current version, the background and foreground colours are saved, so it doesn't explain this anormal combination. Maybe the last time that the preferences were saved was with an old version (3.10 or nightly from several months?), which didn't saved the background colours.

**Comment by fah** [comment] 2018-12-23 11:47
I tried with the Version 3.10.202 (Dec 13 2018):

Reset does not help for me. Still the headers are like in https://github.com/sqlitebrowser/sqlitebrowser/issues/1493#issuecomment-449565973

In addition: The combination dark blue on dark grey is also hard to read. 
![db browser unreadable](https://user-images.githubusercontent.com/322496/50383232-b0fe2580-06af-11e9-9af1-71caa2d7b0db.png)

For visual impaired this is really a problem. Some just can work with dark backgrounds. 

Could you offer a high contrast colors option?

**Comment by mgrojo** [comment] 2018-12-23 11:54
> I tried with the Version 3.10.202 (Dec 13 2018)

Then try using the [latest beta](https://github.com/sqlitebrowser/sqlitebrowser/releases). It has the following improvements:
* Avoid any hard coded colours and query system colours wherever possible. In practice this adds support for dark themes (#1324)
* Fix style of web links in UI (#1286)

**Comment by fah** [comment] 2018-12-23 12:16
I downloaded this beta actually. But copied the info field with the outdated info.

So this is not helping as the other apps (at my Mac) don't have this color combination. I checked the mac settings and didn't find anything to change it. So I guess these two fonts is still hard coded. (Next to the icons and the pragma tab)

**Comment by mgrojo** [comment] 2018-12-23 13:17
We aren't setting any style in the toolbars nor in the pragma tab. The links might be becuase the combination "regular window background" + "link foreground" is uncommon and that theme does not give good combination, but the text in the toolbars is very strange. That is what Qt and/or MacOS are doing. Are there other dark themes for testing?

**Comment by wmertens** [comment] 2018-12-24 03:16
@justinclift could you do a MacOS build?

**Comment by justinclift** [comment] 2018-12-24 10:57
@wmertens Done.  The macOS builds are now using Qt 5.11.3, same as the Win64 ones.  The nightly build has since re-run again, so the latest ones are using it:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Lets see if that makes any useful difference. :smile:

**Comment by wmertens** [comment] 2018-12-25 16:01
Well, it became more readable and less themed:

![image](https://user-images.githubusercontent.com/54934/50424578-f893d580-0898-11e9-88e1-6191f832401f.png)

**Comment by justinclift** [comment] 2018-12-25 21:05
**\*sigh\***

**Comment by fah** [comment] 2018-12-26 23:39
For the Mac nightly
In addition to https://github.com/sqlitebrowser/sqlitebrowser/issues/1493#issuecomment-449860143:
Still the Pragma tab screen is dark blue on black.
In Settings -> Data Browser -> All fields are white on white.

**Comment by mgrojo** [comment] 2018-12-29 18:55
>  Still the Pragma tab screen is dark blue on black.

Then the default theme colours are not prepared for the combination: foreground for hiperlinks and general window background. The link forground would have been thought for text document backgrounds. Maybe we should add an icon with the link beside the text, so we don't depend on a good combination for that unusual case.

**Comment by mgrojo** [comment] 2018-12-29 19:12
Something like this:
(Only changed the first three cases as demo. The icon could be the globe meaning WWW)

![imagen](https://user-images.githubusercontent.com/13812910/50541418-e4f0b380-0ba5-11e9-8685-68b8f9f4e922.png)

**Comment by mgrojo** [comment] 2018-12-29 19:51
> Is it something you can change in css at a central place?

No, it requires source code changes (Qt UI file). If nobody has arguments against that new style, I'll made the change in the master branch.

**Comment by justinclift** [comment] 2018-12-30 00:38
> If nobody has arguments against that new style, I'll made the change in the master branch.

No argument from me.  It's the development branch after all, who's purpose is to try stuff out in. :smile:

**Comment by mgrojo** [comment] 2018-12-30 12:47
Done. This is how it looks now:

![imagen](https://user-images.githubusercontent.com/13812910/50547330-3cd7fa80-0c38-11e9-857c-c07d1551662e.png)

![imagen](https://user-images.githubusercontent.com/13812910/50547420-6180a200-0c39-11e9-9c3d-878f13d79f0b.png)

**Comment by justinclift** [comment] 2018-12-30 13:55
Cool. :smile:

Visually that looks more welcoming to me.

Hopefully our users do find that a better approach.  Guess we'll find out over time. :grinning:

**Comment by fah** [comment] 2018-12-30 14:39
Thank you, Manuel. 
Looks really good!

**Comment by wmertens** [comment] 2019-01-07 07:55
Hmmm, even with the latest macOS nightly, the data browser looks like this, with white text on a white background: 

![image](https://user-images.githubusercontent.com/54934/50755586-c485c080-1259-11e9-9330-a2c5c2de7483.png)

Would it be possible to add a theme selector to Preferences, or at least a dark/light/system toggle?

**Comment by mgrojo** [comment] 2019-01-07 16:44
@wmertens 
> Would it be possible to add a theme selector to Preferences, or at least a dark/light/system toggle?

Yes, it would be possible, that is why this issue is still open, but it won't happen soon unless someone volunteers for developing it.

In any case the screenshots that you are pasting are worrying and can be considered a bug somewhere. Is that the norm for Qt applications in macOS? Some of the widgets have inconsistent colour combinations. Not only those that we apply our own style to, like the table cells, but also the table headers and the toolbars, which we don't alter in any way. Does the 3.11 beta look the same?

@justinclift Maybe we're missing some theme-related file in the macOS package?

**Comment by justinclift** [comment] 2019-02-09 15:53
> @justinclift Maybe we're missing some theme-related file in the macOS package?

And totally didn't see this.  That's what I get for ignoring heaps of outstanding notifications, then deleting most of my GitHub account a while back. :innocent:

It's unlikely to be some theme related file in the macOS package.  Worse, the only version of macOS (the most recent) with "proper" dark mode support... is too new for our mac mini.  So, can't even put it on that and experiment.

An alternative approach may be for someone to set up a Hackintosh with macOS Mojave on it, and experiment with that.  Not something I'm going to look into personally though. :wink:

**Comment by mgrojo** [comment] 2019-02-09 23:40
Are we affected by this: https://openradar.appspot.com/41206326 ?

Seen from https://bugreports.qt.io/browse/QTBUG-68850

> The main bug reported here - existing binaries have a mixed color palette - is something that must fixed in macOS and is out of scope for Qt. Thanks for the report though!
>
>Improved support for Dark Mode in Qt is in scope and is tracked in QTBUG-68891.

So I guess is work in progress in macOS and Qt.

**Comment by justinclift** [comment] 2019-02-09 23:46
> Are we affected by this: https://openradar.appspot.com/41206326 ?

Not 100% sure.  It does sound relevant though.

**Comment by justinclift** [comment] 2019-02-15 14:47
@wmertens @revolter @fah Would any of you have time to test an initial build of DB4S built on macOS Mojave + using Qt 5.12.1:

* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB.Browser.for.SQLite-issue1493v1.dmg

In my testing just now, on the same Mojave VM it was built in, it **seems** almost ok:

![screen shot 2019-02-15 at 2 43 26 pm](https://user-images.githubusercontent.com/406299/52863607-7636dc00-318c-11e9-9712-bfd45a1de80c.png)
![screen shot 2019-02-15 at 2 42 01 pm](https://user-images.githubusercontent.com/406299/52863627-818a0780-318c-11e9-95a8-18e6ded63a4b.png)

The only thing standing out as really wrong / hard to read (for me) are the tool bar labels along the top.  Not sure how to fix those, but it seems like the "build it on Mojave" approach might be the right direction.

**Comment by StevenMagdy** [comment] 2019-02-15 15:29
I got the Same result. I'm using Mojave 10.14.3 on a MacBook Pro.

<img width="1149" alt="screen shot 2019-02-15 at 5 25 26 pm" src="https://user-images.githubusercontent.com/18363890/52866146-fbdb6d00-3135-11e9-9aed-c9cadbdacb3f.png">

**Comment by justinclift** [comment] 2019-02-15 15:32
Excellent.  If we can figure out how to get those tool bar text colours changed, so they're readable, do you reckon it'll be ok? :smile:

**Comment by sky5walk** [comment] 2019-02-15 20:27
Dark theme is eagerly awaited by my tired eyes.
How do I implement a dark theme in DB4S on Windows?
Can I cut and paste the colors into a settings file or do I click and clack the DB4S gui?

**Comment by justinclift** [comment] 2019-02-15 23:58
@sky5walk There still seems to be a lack of Dark Mode support in Win 10 by Qt:

&nbsp; &nbsp; https://bugreports.qt.io/browse/QTBUG-72028

So, probably not much we can do about it just yet. :frowning:

**Comment by justinclift** [comment] 2019-02-16 00:07
I'll take a look through the [Qt macOS deployment guide](https://doc.qt.io/qt-5/macos-deployment.html) again, plus the Qt 5.12.1 installation on our new macOS Mojave VM, to see if there's some obvious piece I've forgotten to add to the new build.  eg possibly a .dynlib or similar for theme support

**Comment by geoidesic** [comment] 2019-02-20 10:29
Also column headings (e.g. in browse data) are black on dark grey which is hardly legible on dark theme Mojave.

**Comment by justinclift** [comment] 2019-02-20 11:13
Yeah.  Looked through docs, but it doesn't seem to be something under our control.  If there does turn out to be a way to change just those incorrect bits (even manually in our code), that'd be a win and we could probably get it into a 3.11.2 release. :smile:

**Comment by mgrojo** [comment] 2019-03-01 23:26
The next nightly will have support for a dark mode independent of the OS style, as described in https://github.com/sqlitebrowser/sqlitebrowser/issues/1493#issuecomment-419203977

@khashayarxy @voltagex @sky5walk want to give it a try? Indications to enable it in https://github.com/sqlitebrowser/sqlitebrowser/issues/1751#issuecomment-468444734

**Comment by mgrojo** [comment] 2019-03-01 23:30
Note that in the "Follow desktop style" mode, when that style is dark, there are still issues in macOS (#1751 -> [QTBUG-71020](https://bugreports.qt.io/browse/QTBUG-71020)) and in Windows 10 (#1738 -> [QTBUG-72028](https://bugreports.qt.io/browse/QTBUG-72028))

**Comment by justinclift** [comment] 2019-03-02 04:09
Just created a blog post and tweeted about it.  Hopefully gets people actively testing it and reporting any weirdness. :smile:

* https://sqlitebrowser.org/blog/dark-theme-support-in-our-nightly-builds/
* https://twitter.com/sqlitebrowser/status/1101684208597000195

**Comment by sky5walk** [comment] 2019-03-02 16:30
Just gave it a whirl. Very nice 👍 
Problem:
Browse Table Column headers are underclipped due to the dark Filter row immediately under.
Meaning, characters that dive under the baseline are obscured. lower case 'p', 'q', 'Q', etc.
Those same characters appear perfectly in the Execute SQL Results Grid where there is no Filter row.
Maybe make the Header row text center alignment higher or heighten that element?
Caution:
I am glad the Plot window was NOT changed to dark background. That causes serious toner problems when hardcopy WYSIWYG printing without inverting colors beforehand.

**Comment by mgrojo** [comment] 2019-03-02 17:05
> Browse Table Column headers are underclipped due to the dark Filter row immediately under.
Meaning, characters that dive under the baseline are obscured. lower case 'p', 'q', 'Q', etc.

I don't reproduce this, but I've already noticed that the filter box is clipped. It happens for me also in the regular style.

![imagen](https://user-images.githubusercontent.com/13812910/53685003-17896a80-3d15-11e9-8de5-9938ada08840.png)

Maybe it's the same problem. I know how to fix mine, so let's hope they have the same cause.

**Comment by sky5walk** [comment] 2019-03-02 17:11
EDIT: Actually, the Filter row is off-center, higher and smaller text. Not the same as earlier versions.
Maybe return it to original size and location?
EDIT2: Toggling between Dark and Desktop themes changes the Header row font and reduces its pitch.

**Comment by mgrojo** [comment] 2019-03-02 18:10
I see now what you mean taking a look to one of the Windows screenshots that @justinclift uploaded at https://github.com/sqlitebrowser/sqlitebrowser/issues/1751#issuecomment-468635462

![imagen](https://user-images.githubusercontent.com/406299/53635438-3df5ca00-3c71-11e9-8b4e-eb06393cbb74.png)

I've fixed the problem I have in Linux, but I'm no longer sure whether it will fix also the Windows version. 

This is how it displays now for me (compare to the screenshot in my previous comment).
![imagen](https://user-images.githubusercontent.com/13812910/53685630-823ea400-3d1d-11e9-8103-b246ea4b3461.png)

Could you check tomorrow how it is painted in Windows?

**Comment by justinclift** [comment] 2019-03-03 02:16
Interesting.  Fairly sure one of the fonts in er... one of the output result panes (maybe Execute SQL? tab) was a lot smaller than I remembered it being.

Hmmm, it looks like the nightly builds for today all failed... I'll investigate that now, then see if I can figure out which OS + tab had the sizing problem I remember seeing. :smile:

**Comment by justinclift** [comment] 2019-03-03 02:29
> Hmmm, it looks like the nightly builds for today all failed... 

And it turns out the Mac Mini rebooted overnight.  Looks like Apple has set things up to automatically install and reboot for security updates by default.  Gah.  I can see the point of automatically alerting the user... *maybe* even automatically installing the update.  But forced reboots are never ok. :frowning: 

Well, that's now turned off.  Hopefully Apple doesn't magically re-enable it later on. :wink:

**Comment by justinclift** [comment] 2019-03-03 03:41
Win64 nightlies are online now:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip

**Comment by justinclift** [comment] 2019-03-03 04:55
Found it.  On macOS, the (bottom) result pane of the Execute SQL tab seems to have a very small font.  Much smaller than the font used for typing out the SQL query:

![db4s-issue_1751v3-screenshot11](https://user-images.githubusercontent.com/406299/53690941-444a8a00-3dc8-11e9-8590-7382301959a9.png)

That's after resetting the Preferences to their default, so not a result of any kind of custom font change. :wink:

The Windows one doesn't have that problem:

![db4s-issue_1751v3-screenshot10](https://user-images.githubusercontent.com/406299/53690947-63491c00-3dc8-11e9-8423-e1f1d956c0b8.png)

It's 100% reproducible, and doesn't happen if the dark style mode isn't turned on.  Standard "follow desktop style" looks like this, with the font used in the bottom pane matching the font used for typing out the SQL query:

![db4s-issue_1751v3-screenshot12](https://user-images.githubusercontent.com/406299/53691185-81188000-3dcc-11e9-9393-b3ac5cf49d0c.png)

**Comment by sky5walk** [comment] 2019-03-03 15:56
1. Just tried [190303 Nightly](https://nightlies.sqlitebrowser.org/latest/) and the Filter row is worse 😢 
The Filter row is now a quarter character higher, obscuring all lower portion of characters in the Header row.
Was the fix to move the Filter row done with a cross platform Form viewer?
Or just done with a gadget move?
2. The font change on returning from "dark to follow desktop" remains.

**Comment by mgrojo** [comment] 2019-03-03 19:40
@sky5walk The filter row is moved programmatically. In my last commit (baaeea8844f3735c58950dc5a532edb53840d4c1) I hope to have fixed both your issue and mine in a portable way. I still think they have the same cause, the new y coordinate is calculated incorrectly. The original code seemed to assume that the filter row height and the original table header height (without filter row) were equal. 

I'll try to find time for the font problem in the following days.

**Comment by sky5walk** [comment] 2019-03-04 15:20
Ok, 190304 fixes the Filter row alignment. Dark mode is almost ready.
BUGS:
1. Cell editor has no means to alter foreground/background colors in dark mode.
All contents invisible without select all.
2. Editing color preferences dialog background takes the last chosen color.
Color dialog becomes obscured by the changing color patterns of each selection.

**Comment by mgrojo** [comment] 2019-03-04 20:21
@sky5walk 

1. Should be solved.
2. Might be solved, but it isn't happening to me, so I tried to fix it blindly.
3. Not yet analysed, but I think it isn't happening to me either.

**Comment by sky5walk** [comment] 2019-03-04 21:20
Thanks!
I guess #3. depends if you changed the default font name and size?
I set mine to Consolas 12 since I want a fixed pitch font that shows 0(with a slash inside) different from O.

**Comment by sky5walk** [comment] 2019-03-11 14:32
Nightly v190311 fixes my issues with Dark Theme while on Windows 10 Pro. 👍
The Scintilla gadget used for the cell editor now respects Dark Theme and the text is visible.

**Comment by mgrojo** [comment] 2019-03-11 20:02
Oh, it might have been the refactor that I made for loading the settings for QScintilla widgets in #1793. Nice to know. The QScintilla's behaviour regarding this is certainly convoluted.

**Comment by mgrojo** [comment] 2019-03-11 20:04
Anyone having problems with the new Dark style preference? Any maOS user? Maybe we can close this, if nobody is having problems.

**Comment by justinclift** [comment] 2019-03-23 11:41
Closing this now.  If it turns out to not be working ok, people are welcome to reopen it. :smile:

**Closed by justinclift** 2019-03-23 11:41 UTC
Labels: enhancement, response requested

**Comment by matanster** [comment] 2020-12-12 18:41
Any suggestions for a build that has this feature and is also known to be stable? On Ubuntu 20.04 this feature is not yet part of the latest package available via apt, and I'd rather not fetch a new nightly build every time my system upgrades its packages by adding the nightly PPA.

**Comment by mgrojo** [comment] 2020-12-18 20:02
@matanster Another option for you is the AppImage of the continuous build: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous
