### ISSUE TITLE
SQLite Case statement Query

### ISSUE THREAD

**Issue by rajasekardondapathi** [sqlitebrowser/sqlitebrowser#1179] opened 2017-10-18 09:24 UTC
### Details for the issue
SELECT case when max(column name) > 1000 then '0' else '1' end as result FROM tablename where condition 
Query its not working

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2017-10-18 10:31
I've never used CASE before, so took me a while to play with this.
If you look at the SQL Log window, DB4S is appending a 'limit 0,0' on the end.  Not sure why.  So its returning back one row:
![image](https://user-images.githubusercontent.com/7872218/31713921-c96058b6-b3f7-11e7-8c64-36126a60d378.png)

.... you just can't see it.  However, if you append 'limit 1' to your query, it'll show.

![image](https://user-images.githubusercontent.com/7872218/31713952-ec09b6aa-b3f7-11e7-8ca7-21a5f3b8dca0.png)

**Comment by rajasekardondapathi** [comment] 2017-10-18 10:53
in each and every time taht query shows only one output

**Comment by chrisjlocke** [comment] 2017-10-18 11:04
Thats because you've asked for max(column_name) - so you're only going to get one record - the maximum for that table.

**Comment by justinclift** [comment] 2017-10-20 12:14
That `LIMIT 0, 0` SQL fragment being added sounds like a bug.  Maybe something is mis-recognising the CASE statement? (haven't experimented to find out personally)

**Comment by rajasekardondapathi** [comment] 2017-10-20 12:28
No it's a client requirement. In Sqlite if statement is not working thats why we go for the Case Statement

**Comment by MKleusberg** [comment] 2017-10-20 13:34
Hmm, with which version is this happening? I've just tried with the latest code and it worked fine.

**Comment by rajasekardondapathi** [comment] 2017-10-23 03:30
Version 3.9.1

**Comment by justinclift** [comment] 2017-12-07 15:26
@rajasekardondapathi Do you have the time and interest to check if this is still happening from your point of view with our latest nightly build?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

There are a lot of changes and bug fixes in our code since the 3.9.1 release, so it's kind of hard for us to know how to prioritise this until we know if it's still happening with our newest code. :smile:

**Comment by chrisjlocke** [comment] 2017-12-07 15:48
> That LIMIT 0, 0 SQL fragment being added sounds like a bug.

I can't reproduce it on my work PC.  Will have to check my home PC again.  It might be a weird 'prefetch' value?

**Comment by sky5walk** [comment] 2017-12-08 16:08
Yeah, Omitting LIMIT does not show the error, but I see a minor intermittent bug depending on sequence and using LIMIT. I sometimes get 2 rows for the query which is wrong. The 2nd row is NULL. I can ignore, but it should never happen.
```
SELECT CASE WHEN max(myCol) > 8 THEN 0 ELSE 1 END AS RES
FROM myTBL
WHERE myPK = 3
LIMIT 1 OFFSET 0; --<< Run this query with Limit 0 then 1 several times to see 2nd row.
```

**Comment by justinclift** [comment] 2019-02-09 23:53
Looking back through old issues... does anyone know know if this is still a problem?  eg in 3.11.0 or the recent nightly builds?

**Comment by sky5walk** [comment] 2019-02-10 17:35
I can not reproduce the error with nightly v3.11.99(190208).
However, the SQL log uses the confusing LIMIT clause option without 'OFFSET' keyword.
[However, to avoid confusion, programmers are strongly encouraged to use the form of the LIMIT clause that uses the "OFFSET" keyword and avoid using a LIMIT clause with a comma-separated offset.](https://www.sqlite.org/lang_select.html#limitoffset)

**Comment by MKleusberg** [comment] 2021-05-22 08:37
I'll close this issue since the original problem seems to have been solved for some time now. Additionally starting with tomorrow's nightly build DB4S now generates ```LIMIT x OFFSET y```-style queries as suggested by @sky5walk :smile:

**Closed by MKleusberg** 2021-05-22 08:37 UTC
Labels: bug, response requested
