### ISSUE TITLE
Dropdown "Table" is too small

### ISSUE THREAD

**Issue by mbraeutigam** [sqlitebrowser/sqlitebrowser#1965] opened 2019-08-12 07:24 UTC
Details for the issue
--------------------

#### What did you do?
Click on Browse data > Table dropdown list

#### What did you expect to see?
Same sizing as in v3.11.2 or an auto-sized dropdown list:

![image](https://user-images.githubusercontent.com/4228180/62850291-b82b7f80-bce2-11e9-8bb0-8e5f12d8a14a.png)

#### What did you see instead?
![image](https://user-images.githubusercontent.com/4228180/62850255-98945700-bce2-11e9-9910-62f7b8a9e842.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 64bit )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: 3.11.99 (Nightly of 2019-08-11)

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment] 2019-08-12 08:01
It should adjust to the table names. Is there free space at the right end of the toolbar buttons? Another explanation could be that the size calculation is done only with some first elements and it does not reach DBABSCHN. One more: there is a bug in Qt, who calculates a size, which should be enough for DBABSCHN, but the paints it with ellipsis because it wants more margin.

**Comment by mbraeutigam** [comment] 2019-08-12 08:06
![image](https://user-images.githubusercontent.com/4228180/62852031-84ebef00-bce8-11e9-99a4-058c9a767536.png)

Yes there is plenty of space left. The  program window is maximized on the desktop.
That problem seems to be introduced with one of the nightlies.

**Comment by mgrojo** [comment] 2019-08-12 11:04
Sorry, I don't reproduce it. Can you test with other databases with diferent table names?

**Comment by mbraeutigam** [comment] 2019-08-12 11:29
That's interesting:
```
CREATE TABLE testwithaveryyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyylongname (somecolumn text);
```
It works and scales the dropdown list as expected.
![image](https://user-images.githubusercontent.com/4228180/62861354-81199600-bd03-11e9-89b4-2d2fc45dcc64.png)

When creating only a few tables, so that there is no scrollbar inside the dropdown list - everything seems alright:
![image](https://user-images.githubusercontent.com/4228180/62861553-25034180-bd04-11e9-8600-2a383faa9c5c.png)

After opening another database in the current application window (File > Open Database) with lots of tables, it will look again like this:
![image](https://user-images.githubusercontent.com/4228180/62861645-6eec2780-bd04-11e9-869e-b9625b3c51a6.png)

Please have a look at this database, maybe you will get the same weird effect: [structures.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/3492065/structures.zip)

**Comment by mbraeutigam** [comment] 2019-08-12 11:42
Maybe another note:
In the last release v3.11.2, the dropdown list had a much bigger startup size and scaled with the window size when resizing, which the ddl in the (latest) nightly doesn't.

**Comment by mgrojo** [comment] 2019-08-12 19:47
I tested with your database and it does not behave the same in Linux. The Table dropdown is displayed correctly, but, shockingly, not the Database Structure (it seems a problem related with the great number of tables):

![imagen](https://user-images.githubusercontent.com/13812910/62891739-d0cd8100-bd46-11e9-9a2d-ac77067d05ce.png)
(it happens only in the "Follow desktop" style, not in the "Dark style".)

In any case, I think your case can be improved, but take into account that there are other goals to keep. This change comes from  #1684 and #1678. It is needed that the UI displays well in all languages and resolutions. But I think that we can set a bigger minimum width, so the problems, if still present, will only be visible with long table names.

The change will be in the next nightly build. Could you try and report back how good is it?

**Comment by mbraeutigam** [comment] 2019-08-13 08:12
The new minimal size for the dropdown looks good to me.
![image](https://user-images.githubusercontent.com/4228180/62925087-d90ed600-bdb1-11e9-93ca-36fb2b4a28e0.png)

Database structure looks fine in Win10 64bit, too:
![image](https://user-images.githubusercontent.com/4228180/62925206-1d01db00-bdb2-11e9-9cba-a3093ceae1f8.png)

**Comment by mgrojo** [comment] 2019-08-13 11:44
Thanks, @mbraeutigam, we can close this, then. My problem with this database structure is the issue  #1001, so I'll comment it there.

**Closed by mgrojo** 2019-08-13 11:44 UTC
Labels: bug, gui
