### ISSUE TITLE
Import of CSV file with 42224 rows of data shows as 40001 rows in the GUI

### ISSUE THREAD

**Issue by AlanL48** [sqlitebrowser/sqlitebrowser#542] opened 2016-03-14 17:16 UTC
Wondering if there Is there a limit on the number of records imported? 
Querying the new imported table to count the row also returns a row count of 40001.

**Comment by justinclift** [comment] 2016-03-14 22:21
There shouldn't be a limit on the number of records imported.  It more sounds like there's a bug somewhere, silently ignoring some rows.

Which, if that does turn out to be the case... is pretty not-great. :frowning:

Is there some way you can tell if the rows-not-imported have something in common?  eg maybe some weird character sequence or something is throwing things off

Also as useful info, which version is are you trying with, and what OS? :smile:

**Comment by wierzba3** [comment] 2016-04-04 14:11
How certain are you that there are 42224 records? Is it possible there are extra line breaks, blank lines, etc? Can you share your .csv file?

**Comment by AlanL48** [comment] 2016-04-05 17:24
![image](https://cloud.githubusercontent.com/assets/17833200/14290322/7ce830a4-fb56-11e5-96e8-6639da68e753.png)

I've managed to isolate the problem, and I believe it is a bug...
![image](https://cloud.githubusercontent.com/assets/17833200/14290602/87bc8998-fb57-11e5-9ce3-be5975079fa5.png)

In one of the fields being imported called Summary, is from a system that users have typed in a summary of an issue or problem raised in system testing, , and when the numpty users type some thing like

Exception raised in 'Ease of Use" API when blah blah etc has been done.....

In this instance, the user has opened Ease of Use with a single quote ' , but has close off with a double quote " . It appears the file import isn't escaping these properly. And then eats up all the characters across multiple rows, until there is another occurrence of this unmatched quoting! - which also occurred in the data dump I was using.
I proved the issue by 1) Exporting the newly imported  table back out as sql, into a text file, and could see multiple rows rolled up in one insert. and 2), Removing all the single & double quote characters from the data that was being imported, after which the row count corrected displayed 42224 rows as shown on the browse data tab in the GUI.

Regards, AL.
Great app BTW, it has helped me implement some data analysis code in excel, using the DB Browser as a tool to get data into a db. Hope this helps.

**Comment by justinclift** [comment] 2016-04-05 20:11
Ahhhh.  It's good you've tracked this down. :smile:

But... (and sorry to say this), the bug isn't with this program.  It's actually supposed to wrap multi-line CSV entries according to their quoting, specifically so people can put multiple lines of data into a single field.

What you're describing really sounds more like a bug in the program which generates the CSV, as that's not escaping things correctly.  Some programs have the ability to change their behaviour in this regard, so you may be able to kick it into shape.

Now, if it's DB4S actually making the invalid CSV, then yeah, it is our bug. 😁

**Comment by justinclift** [comment] 2017-01-28 02:55
Closing this, as it really sounds like a data problem and not a bug in DB4S.

**Closed by justinclift** 2017-01-28 02:55 UTC
Labels: invalid
