### ISSUE TITLE
Unexpected window popup instead of direct grid entry

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2213] opened 2020-04-24 17:13 UTC
Details for the issue
--------------------

#### What did you do?

Example database schema:
CREATE TABLE mac(mac text unique collate nocase not null check(length(mac) = 17));

Open with https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip
(it may affect previous versions, I didn't check).

Go to the table `mac` and press the icon to insert a row.

#### What did you expect to see?

A new row to appear at the end of the grid and let me type data.
#### What did you see instead?
A popup window.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ 7__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0-(alpha or betas)
- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2020-04-24 17:24
> and press the icon to insert a row.

Was this a 'normal' click or a long click?
If you 'long click', a popup menu should appear.  Maybe you clicked this by accident?

https://screencast-o-matic.com/watch/cYfZb0A4UC

**Comment by tonypdmtr** [comment] 2020-04-25 07:07
That was a 'normal' click, and I've tried it many many times on two different PCs (Win7-32 & Win7-64) with the same results.
The problem happens only with this particular table, not any of the remaining tables in the database.
So, I suspect something about the definition of this table is causing this issue.

Table:
CREATE TABLE mac(mac text unique collate nocase not null check(length(mac) = 17));

Have you tried this schema and cannot replicate?

**Comment by chrisjlocke** [comment] 2020-04-25 08:59
When you add a new record, DB4S adds all NULL values.  I guess that fails the check you've got in place.
You'll have to do the long click method of adding specific values.

**Comment by chrisjlocke** [comment] 2020-04-25 11:01
Just created that table, and yes, the 'add new record' dialog appeared instead of adding a default record.  This makes sense due to the check.  I removed the check, and the standard method returned.

**Comment by tonypdmtr** [comment] 2020-04-25 20:31
Not sure I follow.  This works as expected even though it has NOT NULL constraint:

CREATE TABLE mac(mac text unique collate nocase not null);

**Comment by chrisjlocke** [comment] 2020-04-26 07:17
Only once.  Press the button and a new row is added.  Don't type anything, and press the button again.  The dialog appears.
If inserting a record fails, the dialog is displayed.
So this is all by design, to ensure you can enter data.

**Comment by mgrojo** [comment] 2020-04-26 10:27
The dialog opens when there is a constraint that you have to fulfilled in order to insert the new values. DB4S tries to open a new row inline adding new default values, and when it cannot accomplish the constraints, opens this dialog for you so you can insert the values taking into account the constraints. You can see the constraints in tooltips shown for each row.

You can see the rationale behind this dialog here: #1477

Yes, there could be other options, but this is the compromise we have found with the current DB4S implementation internals. We accept simple improvements if this is not clear for the user. Maybe a help button with a link to a wiki article explaining the difference between inline insertion and the dialog and why sometimes, you cannot use the inline insertion.

**Comment by tonypdmtr** [comment] 2020-04-26 22:21
@chrisjlocke Yes, but I get the error before I get a chance to type anything in the row.  So, this is conceptually wrong.  Only after attempting to write to the database can the error be possible, not before.

**Comment by chrisjlocke** [comment] 2020-04-27 07:04
I didn't know you were getting an error - you said you were getting a popup window.
What error are you getting?

**Comment by tonypdmtr** [comment] 2020-04-27 09:43
> If inserting a record fails, the dialog is displayed.

By 'error', I was referring to this.  So, if a dialog pops up there is an assumed error that triggers the popup.

> NULL values are stored. As mentioned above, this fails with your table and constraint set, so the dialog appears.

But this does not seem to happen when I have `NOT NULL` constraints.  Only with the `CHECK` constraint.

> When you add a new record, a new record is automatically added before you add any data. You can see this if you add a new record and look at the log window.

Hmm, if this is how it's done, it explains a lot but still not the `NOT NULL` constraint working.
However, I find this approach problematic.  The row data could instead be entered in an 'disconnected/virtual' row, and only when attempting to ENTER it, the database constraints should fire, and possibly trigger the popup.

If it can be done with the popup dialog this way (disconnected), why not directly on the grid?  Now, if the grid is directly attached to the database, there are work around methods.  One is to create a floating row over the grid new row to allow entry, and upon ENTER to insert into the actual grid.

This may be a bit of work to get it right (I've done it myself many years ago) so, whatever...  Thanks.

**Comment by chrisjlocke** [comment] 2020-04-27 10:59
> Hmm, if this is how it's done, it explains a lot but still not the NOT NULL constraint working.

When you insert a record, it inserts an empty record with an empty value

INSERT INTO "main"."mac"("mac") VALUES ('');

This is shown in the log.
It can't do this twice, which, again, as mentioned above, it only works once.  

> Only once (on an empty table). Press the button and a new row is added. Don't type anything,
> and press the button again. The dialog appears.
> If inserting a record fails, the dialog is displayed.

It can't create record #2 (with a blank value) as records have to be unique.  There is already a record there with a blank value so it fails.  So the dialog is displayed.

When you create a new record, DB4S tries to add NULL values, unless you've specified 'NOT NULL', in which case it adds empty values.

Hope this explains it.  :)

**Comment by tonypdmtr** [comment] 2020-04-27 11:16
>When you create a new record, DB4S tries to add NULL values, unless you've specified 'NOT NULL', in which case it adds empty values.

>Hope this explains it. :)

Yes, it does.  It's more like a hack and it also won't work if I already have an empty string in my database.  Anyway, thanks.

**Comment by chrisjlocke** [comment] 2020-04-27 12:14
> This may be a bit of work to get it right

I'm happy to tag this with 'feature request' and it can be added to the queue of things to be added. :)

**Comment by chrisjlocke** [comment] 2020-04-29 20:10
Closing this then, as its not technically 'unexpected'.  When things 'settle down' and the issues get reduced, we can re-look at this to improve it.

**Closed by chrisjlocke** 2020-04-29 20:10 UTC
