### ISSUE TITLE
FTS5

### ISSUE THREAD

**Issue by pmoorelegistek** [sqlitebrowser/sqlitebrowser#944] opened 2017-01-25 14:58 UTC
### Details for the issue

Please add support for FTS5. I'd like to be able to test performance of large databases and different queries to decide if I should upgrade my application to use it.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ 10)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by glawrence** [comment] 2017-01-25 15:14
This is a duplicate of #781 as far as I can tell

**Closed by glawrence** 2017-01-25 15:14 UTC

**Comment by justinclift** [comment] 2017-01-25 15:50
@pmoorelegistek Yep, it's already pencilled in to be added with our next major release.  That's probably not any time in the real close future though.  eg likely a few months away at least

**Comment by pmoorelegistek** [comment] 2017-01-25 16:53
Hm. Maybe I’ll fork the project then. Is the issue still related to SQLCipher?

**Comment by justinclift** [comment] 2017-01-25 17:15
As far as I remember, yeah.  Saying that because it's been a while (few months?) since I looked at that part of things, so my memory is hazy.

If it helps, this is the batch file we use for automatically building our nightlies on Windows:

  &nbsp; &nbsp;https://gist.github.com/justinclift/11cc926f214e882c8162f97c53929c07

Note, it looks more complicated than it really is, because it runs twice.  Once for the nightly without SQLCipher, and once for the nightly with SQLCipher.

It might be as simple as just adding some kind of optional switch somewhere (maybe line 41?) to include FTS5 in the build.

If you work it out, we can update our nightly build script to include the change as well. :smile:

**Comment by pmoorelegistek** [comment] 2017-01-25 17:28
Yes line 41 is exactly where it is (and line 80 for x64).

All you should need to do is define the preprocessor flag SQLITE_ENABLE_FTS5.

I’m a little unclear as to why FTS4 is even working in your current build since you don’t define those preprocessor flags anywhere, and FTS3 and FTS4 are not enabled by default either. But wherever you’re compiling SQLite, as long as you make sure SQLITE_ENABLE_FTS5 (and …_FTS3 and …_FTS4) are defined, that should be all you need to do.

**Comment by justinclift** [comment] 2017-01-25 17:34
Cool.  Does this look like a suitable replacement for line 41?
    cl sqlite3.c -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_API=_declspec(dllexport) -link -dll -out:sqlite3.dll

If that's the case, I can probably try kicking off a build now (takes 1/2 hour to finish) and put it on the nightlies server somewhere for you to try out.

**Comment by MKleusberg** [comment] 2017-01-25 17:36
@justinclift This should be the most correct version, I think:
```
cl sqlite3.c -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_API=_declspec(dllexport) -link -dll -out:sqlite3.dll
```
See [here](https://sqlite.org/fts3.html#compiling_and_enabling_fts3_and_fts4).

**Comment by MKleusberg** [comment] 2017-01-25 17:37
Line 80, too.

**Comment by justinclift** [comment] 2017-01-25 17:38
Awesome.  :smile:

Now realising we can probably include JSON1 support along with it too, as per the comment here: https://github.com/sqlitebrowser/sqlitebrowser/issues/677#issuecomment-266739629

Not sure if SQLCipher works with the same defines, but it doesn't hurt to try and see what happens. :smile:

I'll give it a go now.

**Comment by pmoorelegistek** [comment] 2017-01-25 17:40
Agreed. Although again I’m not sure why FTS is working at all in DB Browser without those flags – and it does work - so I’m curious if this makes a difference. It should though.

**Comment by pmoorelegistek** [comment] 2017-01-25 17:42
In the version that has SQLCipher, are you using SQLCipher’s implementation of SQLite even for non-encrypted databases? That would explain why FTS works in the official Windows build. And if so we would need to use the non-SQLCipher version.

**Comment by justinclift** [comment] 2017-01-25 17:45
For the SQLCipher build it's implementation gets used for both encrypted and non-encrypted databases.  So yep, you're probably right.  Lets experiment a bit with the build script now and figure out what does and doesn't work. :smile:

**Comment by justinclift** [comment] 2017-01-25 18:16
@pmoorelegistek Do you have time to try these out?

* https://nightlies.sqlitebrowser.org/win32/DB%20Browser%20for%20SQLite-2017-01-25-FTSv1-win32.exe
* https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2017-01-25-FTSv1-win64.exe

Only tried building the SQLite version (not SQLCipher) as a first go.  We can try SQLCipher things out after we're happy the straight SQLite options work. :smile:

**Comment by aludee** [comment] 2017-01-26 04:37
Both copies can work for me.
I was able to create, rebuild, search and delete the fts5 table(s).

This is great! Thanks.

**Comment by justinclift** [comment] 2017-01-26 15:45
@aludee Awesome, thanks for checking and confirming.

I've just added those options to the main nightly build script for windows.  It's only for the SQLite (not encrypted) version for now.  SQLCipher version still needs working on. :wink:

**Comment by pmoorelegistek** [comment] 2017-01-26 16:16
Also confirmed, it’s working great. Thanks so much for getting this done so quickly. And for the great piece of software; it’s a huge time saver for me in optimizing queries for my application.

**Comment by justinclift** [comment] 2017-01-26 16:20
You're welcome. :smile:

Am compiling a Win64 SQLCipher build with FTS3/4/5 & JSON1 extensions enabled right now.  Would you have time to try it out when it's finished? (assuming it doesn't break during compiling :wink:)

**Comment by pmoorelegistek** [comment] 2017-01-26 16:47
Oh great. Sure would be happy to.

(Incidentally I wish I knew SQLCipher existed two years ago because I would up making a custom SQLite VFS for encrypted databases in Windows. Works great but man was that painful…).

**Comment by justinclift** [comment] 2017-01-26 17:13
@pmoorelegistek Thanks.  Please give this a shot and let me know if the FTS bits are working ok:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-sqlcipher-2017-01-26-FTSv1-win64.exe

For that, the approach I used was adding the FTS5 and JSON1 defines to the default list for SQLCipher: https://github.com/justinclift/sqlcipher/commit/c04e7b9a8affa6cc25da9d06622e6fe28d3fdc67

But, definitely need someone to test the result. :smile:

**Comment by pmoorelegistek** [comment] 2017-01-27 15:20
Sorry for the lag. Yeah FTS5 is working perfectly! I haven’t tried out more advanced features like ranking or highlighting but I have no reason to doubt they’ll work (or if they don’t it’s an SQLite problem and nothing to do with your code).

Thanks again, seriously.

**Comment by justinclift** [comment] 2017-01-27 19:47
Thanks @pmoorelegistek, that really helps.

I'll update the nightly build pieces for Windows, so everything has FTS3/4/5 & JSON1 included. :smile:

**Comment by pamtbaau** [comment] 2017-10-05 11:06
Are there any plans to build this FTS version that is build on JAN 27 alongside newer sqlitebrowser versions?

**Comment by justinclift** [comment] 2017-10-05 11:31
@pamtbaau FTS3/4/5 support should be in all of our nightly builds on both OSX and Windows.

In theory, it should also be in the OSX and Windows builds of our recent 3.10.1 release.  Is it not working for you?

**Comment by pamtbaau** [comment] 2017-10-05 11:58
It does in 3.10.1...  I was using 3.9.1

Thanks for your swift response

**Comment by justinclift** [comment] 2017-10-05 13:02
You're welcome @pamtbaau. :smile:
