### ISSUE TITLE
About quote character

### ISSUE THREAD

**Issue by happydentist** [sqlitebrowser/sqlitebrowser#2018] opened 2019-10-06 10:51 UTC
Details for the issue
--------------------

#### What did you do?
When import csv file to db, cannot input anything character after select quote character to other

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- Windows: 10

#### What is your DB4S version?

- 3.11.2

#### Did you also

- Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2019-10-06 12:06
Have you tried the latest nightly at all?
There have been improvements since 3.11.2 was released.

https://nightlies.sqlitebrowser.org/latest/

When you select 'other' do you not get the textbox, or are you saying you get the textbox but can't input any characters into it?

![image](https://user-images.githubusercontent.com/7872218/66268917-0cae2f80-e83a-11e9-8370-e00c71c2e10b.png)

**Comment by happydentist** [comment] 2019-10-08 07:08
I can get the textbox but can't input any characters into it.
Try the latest released, but in vain.

**Comment by mgrojo** [comment] 2019-10-08 21:35
> I can get the textbox but can't input any characters into it.
> Try the latest released, but in vain.

That's weird. Try the following ideas, just to know if some works by pure chance or gives some hint:
- In which language is the application configured? Change the language setting in Preferences and try again
- Try copying the character from other application and pasting it in the box.
- Try to set the focus in the box using tab key after setting Other in the list.
- How does the text box like? Can you see the blinking cursor in it? Take a screenshot and paste it here.
- What happens if you click with the right mouse button in the text box? A contextual menu should open with an enabled paste option.
- What happens if you press Ctrl+A (Select All) inside the box? Do you see any selection?

**Comment by happydentist** [comment] 2019-10-12 13:22
Now it is OK.
I don't know why.
Thanks a lot.

**Comment by mgrojo** [comment] 2019-10-12 14:04
Some local problem then, I guess. Let's close this issue, but if you know something more or the problem is reproduced, don't hesitate to open this again.

**Closed by mgrojo** 2019-10-12 14:04 UTC
