### ISSUE TITLE
[bug] 3.6.0 32bit,64bit utf8 error

### ISSUE THREAD

**Issue by lifedomy** [sqlitebrowser/sqlitebrowser#307] opened 2015-05-11 07:51 UTC
In 3.6.0, In Exequte SQL Editor

chinese and Korean letters crash.

but 3.5.1 is normal.

for example

insert into TextureInfo values ('1','1','1','1','ADDITION','덧셈','加法','jiāfǎ','加','jiā','法','fǎ','','','','','','','1','心算加法','xīnsuànjiāfǎ','덧셈을 암산하다.','20150501','120000','','');

**Comment by justinclift** [comment] 2015-05-11 08:51
Yeah, it turns out we forgot to enable UTF support by default in our new Execute SQL code. :frowning:

It is fixed in our nighly builds though.  Are you ok to download and use that? (the download locations are on the front page of our repo)

**Comment by lifedomy** [comment] 2015-05-14 07:14
thanks, your rapid reply. I use 3.5.1 well. Later I will download upVersion.

One more question, I hope you see attch file ==> ex01.mp4.

'jiāfǎ' word display well at Editor but not well at Grid Cell.

ǎ letter is crashed.

I want to know Only my pc's font problem or bug.

There is no problem on Coding. Only showing problem.



2015-05-11 17:52 GMT+09:00 Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment] 2015-05-14 14:25
Ahhhh, no.  GitHub doesn't attach files.

You can try sending the file to my personal email address (justin@postgresql.org) though.  Hopefully it's not too big for my mail server. :smile:

**Comment by justinclift** [comment] 2015-05-24 16:23
@lifedomy I did receive the file, but was tired and then went to sleep and forgot about it.

I'll forward the file to the other guys, so they can look into it.

**Comment by justinclift** [comment] 2015-05-24 16:29
@lifedomy I have forwarded the .mp4 file to the main developers.  Hopefully they'll know what the problem is.

As a thought, have you tried version 3.6.0 of our program?  We changed some of our Unicode handling in that... and there is a chance it has already fixed the problem. :smile:

**Comment by lifedomy** [comment] 2015-05-26 05:27
Thanks to your good reply. It's good to know this problem.

I hope  you and your team go well.



2015-05-25 1:29 GMT+09:00 Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment] 2015-05-26 11:12
Have you tried version 3.6.0?

**Comment by lifedomy** [comment] 2015-05-27 05:06
In 3.6.0 editor crash but grid is good.
In 3.5.1 editor is good but grid crash.


[image: 본문 이미지 1]

2015-05-26 20:12 GMT+09:00 Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment] 2015-06-13 19:09
@lifedomy Do you have time to try our latest nightly builds?  There is a decent chance this is fixed in that. :smile:

**Comment by lifedomy** [comment] 2015-06-15 01:53
Okay, Now I downed 3.7.0 and tested.

Everything is OK. There are no problems in both editor and grid.

Thanks to your continuous cares.

Also, thanks to MKleusberg.




2015-06-14 4:09 GMT+09:00 Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment] 2015-06-15 03:42
Awesome!  Thanks for testing and letting us know. :smile:

**Closed by justinclift** 2015-06-15 03:42 UTC
Labels: duplicate
