### ISSUE TITLE
[Bug]: Can't maximize window on Linux

### ISSUE THREAD

**Issue by quintafeira** [sqlitebrowser/sqlitebrowser#3016] opened 2022-04-15 23:38 UTC
### What did you do?

- Clicked in the maximize button.
- Right clicked in the window border and then clicked in maximize.

### What did you expect to see?

The window being maximized.

### What did you see instead?

The window didn't maximize. Only after I clicked in View > Window Layout > Simplify Window Layout the maximize button worked. After resetting the window layout, the maximize button stopped working again.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Arch Linux, latest version and Ubuntu 20.04.

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment] 2022-04-16 06:53
This does seem familiar, but it seems it was a minimise bug.
We've not had similar reports, so it would appear it could be something to do with your resolution or setup?
Does the issue occur if the remote dock is open?  Click 'View' and make sure 'Remote' is not checked.

![image](https://user-images.githubusercontent.com/7872218/163665031-6d9e328c-63b1-45ed-b75e-a918b0c3654c.png)

**Comment by quintafeira** [comment] 2022-04-16 12:53
I tried to turn some of these off and resetting the layout.
When I turn 'Remote' or 'Edit Database Cell' off, maximize works.
Turning the other options off didn't affect anything.
It doesn't seem like a number issue, as if I turn one of the first options off (with the other four options on), maximize doesn't work, but when I turn 'Remote' or 'Edit Database Cell' off (again, four options on), it works.
Also, if I click in 'Simplify Layout' and then toggle only 'Remote' and 'Edit Database Cell' on, maximize works fine, but if I also turn one of the first three options on, it doesn't work.

**Comment by chrisjlocke** [comment] 2022-04-16 13:58
Thanks for reporting back.
Looks like it's something quirky with one of those docks.  So closing 'Remote' makes it work ... thats a workable workaround temporarily, I assume - you can live without that dock.  What happens if that dock is removed, DB4S is maximised, then that dock is put back?

**Comment by mgrojo** [comment] 2022-04-16 17:32
Some widgets have minimums that prevent reducing the window to that size. What's your resolution? 

Have you tried the [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)? Does reducing the main font size in (Preferences > General > Font size) change anything?

**Comment by quintafeira** [comment] 2022-04-16 21:03
> What happens if that dock is removed, DB4S is maximised, then that dock is put back?

The window is demaximized, but stay the same size (the maximize button changes).

> What's your resolution?

My resolution is 1366x768.

> Have you tried the [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)?

I tried the latest [continuous build](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous) and everything worked fine.

> Does reducing the main font size in (Preferences > General > Font size) change anything?

Reducing the font size to 7 everything works fine.

**Comment by chrisjlocke** [comment] 2022-04-17 17:07
> I tried the latest [continuous build](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous) and everything worked fine.

Thanks for confirming.
I'll close this then as the issue is 'resolved', and hopefully this fix will be in the next release.

**Closed by chrisjlocke** 2022-04-17 17:07 UTC
Labels: linux, gui
