### ISSUE TITLE
Crashes when switching tabs on macOS

### ISSUE THREAD

**Issue by zayass** [sqlitebrowser/sqlitebrowser#922] opened 2017-01-05 17:48 UTC
### Details for the issue

Crashes when changing main tabs with opened db

### Useful extra information

http://pastebin.com/K3tcLLas

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 10.12.2 )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2017-01-05 18:15
Needs more logs... ;)

**Comment by MKleusberg** [comment] 2017-01-05 18:31
Does this happen for any database or just for a specific one?

**Comment by zayass** [comment] 2017-01-05 18:35
@chrisjlocke how to grab it?
@MKleusberg I have only one

**Comment by justinclift** [comment] 2017-01-05 20:12
Interesting.  The error message it shows can **generally** be regarded as one of two things:

* Either bad hardware (for example, flaky ram), or
* Something wrong with one of the shared libraries

Let's hope it's a shared library problem. 😀 

@zayass Would you be ok to try both of our latest nightly builds, and check if either of those work without crashing?

* https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite_20170105.dmg ← Without encryption
* https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite-sqlcipher_20170105.dmg ← **WITH** encryption

Personally, I'm kind of thinking the one without encryption is most likely to work.  It could be the encryption library is behaving badly on your system for some (as yet unknown) reason.

**Comment by MKleusberg** [comment] 2017-01-05 20:17
But the crash happens in our code (see the first line in the call stack):
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   net.sourceforge.sqlitebrowser   0x000000010d33c73c DbStructureModel::rowCount(QModelIndex const&) const + 44
1   org.qt-project.QtCore           0x000000010e4f466b QAbstractItemModel::hasIndex(int, int, QModelIndex const&) const + 43
2   net.sourceforge.sqlitebrowser   0x000000010d33c60e DbStructureModel::index(int, int, QModelIndex const&) const + 46
...
```

In that function (DbStructureModel::rowCount) some pointer casting magic happens, so maybe the crash happens because of that.

**Comment by revolter** [comment] 2017-01-06 06:24
@zayass, Could you share the database with us if it's not private?

**Comment by zayass** [comment] 2017-01-10 20:29
Sorry for delay. Here is db
[meta_v2.db.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/697267/meta_v2.db.zip)

I don't have clear steps to reproduce but when I switching between Structure and Data tabs it constantly crash. May be on first switch maybe on 10th

**Comment by revolter** [comment] 2017-01-11 08:11
I can't reproduce it with a ~1 week old nightly.

**Comment by mgrojo** [comment] 2018-10-05 22:03
@zayass Did you discovered what was happening? Have you tried with a [recent build](https://nightlies.sqlitebrowser.org/latest/)? I'll close this, since it is quite old and nobody more reproduced it, but if it's still happening in your case, please reopen this.

**Closed by mgrojo** 2018-10-05 22:03 UTC
