### ISSUE TITLE
browser now wraps row content and it results in an overlapped mess 

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#1658] opened 2018-12-13 17:30 UTC
When view the contents of a table the latest release now auto wraps the contents of cells.
It overlaps and results in a mess. Is this by design? Can I change it back?

**Comment by justinclift** [comment] 2018-12-13 19:44
> latest release

The latest nightly, or the 3.11.0-beta3 I pushed out a few hours ago?  Asking because one is probably just a development thing we can adjust easily, the other I might need to panic about a bit. :smile:

**Comment by mtissington** [comment] 2018-12-13 20:00
nightly - 3.11.99

**Comment by chrisjlocke** [comment] 2018-12-13 20:07
@mtissington - you seem to be raising lots of issues recently, which is fantastic - each raised issue means another squished bug, making the application better.  Great.  However, you don't seem to be supplying the correct information.
When raising an issue, do you go to the [issues page](https://github.com/sqlitebrowser/sqlitebrowser/issues)?  If so, do you click the green 'new issues' button?

![image](https://user-images.githubusercontent.com/7872218/49963810-e2892b00-ff10-11e8-9c28-089becd17f49.png)

Or do you click 'New Issue' in DB4S?  Either way, this should create a 'template' here with information to fill in:

![image](https://user-images.githubusercontent.com/7872218/49964338-27619180-ff12-11e8-9dc2-71df88d0209f.png)

The bit at the end is the useful information:

![image](https://user-images.githubusercontent.com/7872218/49964409-51b34f00-ff12-11e8-9a4a-81857fd3d545.png)

The version you're using and your OS are important - some issues are only apparent on specific operating systems.

If you're raising issues via another method, it would be handy to know how, so we can tailor that method to include the above information.

Again, we appreciate your issues, so this isn't a moan about you raising them - just *how* you're raising them! 😉

**Comment by mtissington** [comment] 2018-12-13 20:11
Oops - sorry, I'll ready the template next time, heck I'm often moaning at our testers here for lack of correct and full information.

**Comment by chrisjlocke** [comment] 2018-12-13 20:14
> nightly - 3.11.99

If you click 'Help' and 'About', the version information can be selected, copied and pasted.  

![image](https://user-images.githubusercontent.com/7872218/49964659-f46bcd80-ff12-11e8-8fee-02445f3eedcb.png)

Sometimes what you download as the 'latest' may be different by the time we see your report.

> Oops - sorry, I'll ready the template next time,

No problem, and again, not moaning - it can just speed up the troubleshooting process if we know what you're having a problem with.  🙉

**Comment by chrisjlocke** [comment] 2018-12-13 20:18
Back to your issue though.
Any chance of a screenshot?  I can't see this in the version I'm running.

**Comment by mtissington** [comment] 2018-12-13 20:19
I'm curious - how do you manage to insert emjois - I see no ability to do so on github.

**Comment by chrisjlocke** [comment] 2018-12-13 20:34
A nightly from Nov showed just one line in a cell.

![image](https://user-images.githubusercontent.com/7872218/49965878-58dc5c00-ff16-11e8-8a2f-54ec647ce6e7.png)

We've upgraded Qt recently, so assume its something to do with that, and must be an option thats settable.

**Comment by justinclift** [comment] 2018-12-13 21:19
> We've upgraded Qt recently, so assume its something to do with that, and must be an option thats settable.

Uh oh.  The new 3.11.0-beta* builds are using Qt 5.12.0 too.  I guess we'll need to get this fixed for them too.

**Comment by chrisjlocke** [comment] 2018-12-17 10:47
> I just noticed that trigger_uuid field is shown without wrapping - they are all TEXT fields.

The UUID fields have nothing to break a line up - no spaces, commas or other punctuation.  
I'm hoping its just a default option that's changed between Qt versions - the old control defaulted to 'one line per cell' while the newer one is 'fit contents in cell'...

**Comment by justinclift** [comment] 2018-12-19 02:03
Hmmm, maybe the new 3.11.0 release should use Qt 5.11.x instead.  That's still very current, and shouldn't have this problem.

**Comment by chrisjlocke** [comment] 2018-12-20 09:57
> Line wrap is not required 

As other grids appear OK (eg, database structure grid), its probably just a setting needed for the 'Browse Data' grid.  (and Execute SQL results grid)

**Comment by MKleusberg** [comment] 2018-12-20 10:14
I don't have Qt 5.12 installed, so this is completely blind. But someone could try with this patch:

```diff
diff --git a/src/ExtendedTableWidget.cpp b/src/ExtendedTableWidget.cpp
index a7007ea8..81116249 100644
--- a/src/ExtendedTableWidget.cpp
+++ b/src/ExtendedTableWidget.cpp
@@ -374,6 +374,8 @@ ExtendedTableWidget::ExtendedTableWidget(QWidget* parent) :
     connect(printAction, &QAction::triggered, [&]() {
        openPrintDialog();
     });
+
+    setWordWrap(false);
 }
 
 void ExtendedTableWidget::reloadSettings()
```

Does that change anything?

**Comment by justinclift** [comment] 2018-12-20 21:45
Here's a Win64 build with that included:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1658v1-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1658v1-win64.zip

**Comment by sky5walk** [comment] 2018-12-21 00:03
Sorry, it still shows line wrapped content?
Version 3.11.99 (Dec 21 2018)
Qt Version 5.12.0
SQLite Version 3.26.0

**Comment by justinclift** [comment] 2018-12-21 00:41
Just double checked (to be sure), and yep the source repo branch it was built from definitely had the patch included.  Looks like an updated attempt patch is needed. :smile:

**Comment by chrisjlocke** [comment] 2018-12-21 14:34
Works for me though.... (WIn 10 x64)

![image](https://user-images.githubusercontent.com/7872218/50347396-550b9380-052d-11e9-9ced-9ddaa60fd139.png)

**Comment by chrisjlocke** [comment] 2018-12-21 14:35
...and just to check, this is with the latest nightly.

![image](https://user-images.githubusercontent.com/7872218/50347521-b895c100-052d-11e9-8ffc-c2aa47250479.png)

**Comment by mtissington** [comment] 2018-12-21 14:38
yep, still a problem here with the latest nightly too..

**Comment by chrisjlocke** [comment] 2018-12-21 14:45
Yes, the patch isn't merged into master so wouldn't be in the nightly yet - was just posting both images to confirm the fix was fixed for me.

**Comment by mgrojo** [comment] 2018-12-21 14:55
Ok, the patch works around the issue, but this is clearly a bug in Qt, so we should consider reverting the patch once it's solved. The current behaviour in my environment is: by default show one line, because that it's all that fits, but if the user makes the cell height bigger, word-wrap the content to show as many lines as fit. That works nicely and shouldn't be lost in the future.

See this example with three heigths increased:
![imagen](https://user-images.githubusercontent.com/13812910/50348104-19c29200-0538-11e9-8005-345e123c8e13.png)

**Comment by chrisjlocke** [comment] 2018-12-21 16:39
Agreed.  The variable wordwrap (wordwrap if the row is increased) doesn't work for me - how did you achieve that?

![image](https://user-images.githubusercontent.com/7872218/50353060-f7804280-053e-11e9-889c-7be3d33bb327.png)

**Comment by mgrojo** [comment] 2018-12-21 16:49
I suppose that is with Martin's patch. With the master branch, it should work, but in the case of Qt 5.12, exposing this issue. It seems that Qt thinks that more than one line fits, when it isn't the case.

**Comment by chrisjlocke** [comment] 2018-12-21 17:34
Normal behaviour is to have both.  Word wrap if the contents fit, otherwise ellipses.

![image](https://user-images.githubusercontent.com/7872218/50355440-99eff400-0546-11e9-8db5-d28b406548c1.png)

The current Qt version is broken in this regard.

**Comment by justinclift** [comment] 2018-12-21 21:56
Ok, we should file a bug about this on the upstream Qt bug tracker, if there's not one already there.

Checking just now - not exactly sure what to search for though - shows this potential candidate:

* https://bugreports.qt.io/browse/QTBUG-72568

Does it seem like the bug here?

---

When Qt 5.12 came out, the comments on the blog release post weren't very positive regarding Qt's recent release quality:

&nbsp; &nbsp; https://blog.qt.io/blog/2018/12/06/qt-5-12-lts-released/#comment-1206871

This is a bit worrying. :frowning:

**Comment by mtissington** [comment] 2018-12-21 22:12
fyi - this issue is also visible on the Remote tab too 

![annotation 2018-12-21 221116](https://user-images.githubusercontent.com/6769116/50365655-7d1ae700-056d-11e9-9192-4299f8c5733e.jpg)

**Comment by mgrojo** [comment] 2018-12-21 22:34
Couldn't be this?
https://bugreports.qt.io/browse/QTBUG-72708

It says 5.11.1 and UNRESOLVED. Have we used that version so that it can be discarded?

**Comment by justinclift** [comment] 2018-12-22 04:19
Hmmm, a few of the nightly builds, and some of the 3.11.0-beta builds were done with Qt 5.11.2.

Haven't seen mention of problems with those, but maybe people just missed those and went straight to other builds for whatever reason?

I'll rebuild today's Win64 nightly build using Qt 5.11.3, and we can check if there's a difference.  Gimme a bit, as it'll need to be downloaded on the build vm (etc). :wink:

**Comment by justinclift** [comment] 2018-12-22 12:47
The nightly Win64 builds are now using Qt 5.11.2, and today's one has just finished being rebuilt using it:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi

Anyone up for checking if the problem shows up with this too?

**Comment by sky5walk** [comment] 2018-12-22 15:35
Yay, looks much better now.  😄 
Weird, 1st install failed on a printer driver?
Had to reinstall but no reboot required.

**Comment by karim** [comment] 2018-12-22 15:52
> Weird, 1st install failed on a printer driver?

You were installing lower version of Qt DLL (5.11.3) over a newer version (5.12) so the installer didn't copy the lower DLLs. Reinstalling should work, yes. Another way is to repair the installation; right-click and select Repair.

**Comment by mtissington** [comment] 2018-12-22 16:34
much better thanks 😄

**Comment by sky5walk** [comment] 2018-12-22 16:37
> > Weird, 1st install failed on a printer driver?
> 
> You were installing lower version of Qt DLL (5.11.3) over a newer version (5.12) so the installer didn't copy the lower DLLs. Reinstalling should work, yes. Another way is to repair the installation; right-click and select Repair.

Thanks for clarification.

**Comment by justinclift** [comment] 2018-12-22 22:11
> Couldn't be this?
> https://bugreports.qt.io/browse/QTBUG-72708
> 
> It says 5.11.1 and UNRESOLVED. Have we used that version so that it can be discarded?

We could do a build with Qt 5.11.1 too (as a once off) to see if the problem shows up there.  If it does, then we know it could be that Qt bug and that it's fixed in later Qt 5.11 releases, though comes back again for Qt 5.12.

That's probably pretty easy to get done.

---

As a separate thought, I've been thinking we should put some kind of Jenkins or similar CI/CD server online to co-ordinate our automatic builds.  With that, we could have them automatically created + uploaded for every commit to the DB4S git repo.

Travis CI - we use here on GitHub already - is useful, but doesn't support building on Windows, which a majority of our users are on.  As an aside, it turns out Travis supports macOS building already.  That could be useful. :smile:

**Comment by karim** [comment] 2018-12-22 22:40
> Travis CI - we use here on GitHub already - is useful, but doesn't support building on Windows

https://blog.travis-ci.com/2018-10-11-windows-early-release
https://docs.travis-ci.com/user/reference/windows/
https://travis-ci.community/c/environments/windows

**Comment by justinclift** [comment] 2018-12-22 23:09
Nifty.  Travis CI might be useful for all our builds then. :smile:

**Comment by justinclift** [comment] 2018-12-22 23:31
Looks like installing Qt will work too:

&nbsp; &nbsp; https://travis-ci.community/t/qt-support-on-windows/370/8

That Travis CI forum comment mentions long logs for the builds due to the Qt install, but well... it works, so that's probably good enough to start with. :wink:

**Comment by justinclift** [comment] 2018-12-24 10:52
Thanks @chrisjlocke. :smile:

Looks like whatever the problem is, it's new to the Qt 5.12.0 release.

The macOS builds have been updated to use Qt 5.11.3 again now too.

**Comment by karim** [comment] 2018-12-25 02:41
So we are back to 5.11.3 till this is fixed in 5.12.x?

As a side note, should we have some kind of a list with things that doesn't work with DB4S? Like OpenSSL 1.1.x and now Qt 5.12.

**Comment by justinclift** [comment] 2018-12-25 07:18
> So we are back to 5.11.3 till this is fixed in 5.12.x?

Yep. :smile:

> As a side note, should we have some kind of a list with things that doesn't work with DB4S? Like OpenSSL 1.1.x and now Qt 5.12.

That's a decent idea.  For such a list, the OpenSSL 1.1.x entry should probably point out that it's due to the downloaded Qt version being built with OpenSSL 1.0.  If people really want to use DB4S with OpenSSL 1.1, then compiling your own version of Qt using OpenSSL 1.1 then compiling DB4S with that... should work.  (as you clarified a while back @karim :smile:)

**Comment by chrisjlocke** [comment] 2018-12-25 08:44
> should we have some kind of a list with things that doesn't work with DB4S? 
Have created an issue (#1688) as its useful to discuss and comment there, but I guess a Wiki page (sans comments and guff) would be useful.

**Comment by karim** [comment] 2018-12-25 22:15
GitHub added an option to pin issues (up to 3) so they appear on top. Should we pin this issue?

**Comment by justinclift** [comment] 2019-02-08 11:12
@MKleusberg @mgrojo Would either of you have time to file a bug for this with Qt?

I don't grok the details of QtTableView well enough to really fill out an appropriate bug. :frowning: 

On a side note - I asked about this problem today on the #qt IRC channel, but no response.  Doh.

**Comment by mgrojo** [comment] 2019-02-09 14:32
I've created a Qt bug report for the wrapping problem: https://bugreports.qt.io/browse/QTBUG-73721

I was searching a bit for one already open and It's surprising that there isn't one, because what we do is nothing particular. The wordWrap attribute is enabled by default for QTableWidget.

**Comment by justinclift** [comment] 2019-03-09 02:48
The Qt project have marked their bug for this a fixed today (target release is 5.12.3), via this patch:

&nbsp; &nbsp; https://github.com/qt/qtbase/commit/8b3463fdeb3d03fd0c87873089a6f84321eecc49

Really hoping it's a complete patch.  Not sure how we should go about testing it prior to the release.

Guessing a local build of Qt (using their development code), then compiling DB4S using that.

**Comment by mgrojo** [comment] 2019-03-09 09:42
It'd be necessary to remove the workaround that I made for disabling
wrapping for Qt greater than 5.12, or maybe better at the short term,
close the version range for which it's applied.

**Comment by justinclift** [comment] 2019-05-07 12:45
Qt 5.12.3 has been released, so we should probably test if the content wrapping works properly with it.

I won't have time for the next few days though.  Hopefully next week. :smile:

**Comment by mgrojo** [comment] 2019-05-07 20:58
The workaround (disabled word wrap) is now only applied for versions greater or equal than 5.12.0 and lower than 5.12.3. If we compile using 5.12.3 will be able to confirm whether it has been fixed.

**Comment by justinclift** [comment] 2019-05-08 02:16
Thanks @mgrojo, that's excellent. :smile:

**Comment by MKleusberg** [comment] 2019-08-10 13:23
Looks like we can close this issue then?

**Comment by MKleusberg** [comment] 2019-10-04 11:29
Since it seems like to be fixed now (in Qt itself and by a workaround in our code), I'm going to close this issue :smile: If I'm missing anything or if anybody is still having issues with this, please just reopen this issue.

**Closed by MKleusberg** 2019-10-04 11:29 UTC
