### ISSUE TITLE
Missing log

### ISSUE THREAD

**Issue by tbayart** [sqlitebrowser/sqlitebrowser#337] opened 2015-06-03 12:33 UTC
When you enter a query in "Execute SQL" tab with line-break, your query is not logged properly :
The first line is logged then
&lt;string can not be logged, contains binary data&gt;

Maybe replacing line-breaks with whitespaces could solve the issue.

**Comment by justinclift** [comment] 2015-06-03 18:37
Which operating system are you using, and which version of DB4S? :smile:

**Comment by tbayart** [comment] 2015-06-04 08:38
DB4S 3.6.0 under Windows 8.1 pro x64

**Comment by justinclift** [comment] 2015-06-13 19:17
@MKleusberg Yours? :smile:

**Comment by justinclift** [comment] 2015-06-16 03:04
@tbayart Out of curiosity, have you had a chance to try this with our recent 3.7.0 release?  I'm kind of wondering if this might have been fixed when we adjusted some of our other Unicode handling bits for the Execute SQL tab. :smile:

**Comment by tbayart** [comment] 2015-06-16 08:53
Just checked 3.7.0, not solved.

**Comment by schdub** [comment] 2015-06-16 09:06
@tbayart please give example of your requests.

**Comment by tbayart** [comment] 2015-06-16 10:14
a query which don't need a working database :
```
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000000)
SELECT x FROM cnt;
```
taken from [Recursive Query Examples](https://www.sqlite.org/lang_with.html)

**Comment by justinclift** [comment] 2015-06-16 21:51
@tbayart A potential fix for this has just been added by @schdub.  Would you be ok to try the nightly build (tomorrow), and verify if it's working properly for you now? :smile:

**Comment by justinclift** [comment] 2015-06-16 21:53
@glawrence Let's wait for confirmation by the issue reporter that things are fixed before we close the issue.  90% of the time things work as intended, but there are the occasional times they don't, so we try to catch them up front. :wink:

**Comment by glawrence** [comment] 2015-06-17 06:38
@justinclift oh I agree, it is much better to get confirmation first

**Comment by tbayart** [comment] 2015-06-17 10:56
Every line is logged correctly, no longer truncated and no
<string can not be logged, contains binary data>
in log
but...
a side effect appeared: empty lines are logged in User log
if you add 5 empty lines at the end of you sql command, User log will contains 5 empty lines

this is not the case in Application log
this issue is not present in 3.7.0 release

I notice the Application log is sightly different than User log
is this 2 different processes ?

**Comment by schdub** [comment] 2015-06-17 11:59
@tbayart about empty lines. This behaviour was previously. You don't see it under Windows because on windows each multi-line query considered to contain binary data, and of course, was truncated.

I agree with you (as I wrote in a commentary in the commit), it would be better to throw out from query meaningless extra characters like \r \n \t. If someone wants to improve this - you're welcome.

**Comment by tbayart** [comment] 2015-06-17 13:05
Just to be sure I explained the behavior clearly:
Consider this 4 lines query (3 lines + 1 empty)
```
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000000)
SELECT x FROM cnt;

```
With v3.7.0 this query creates 2 lines in User log:
```
WITH RECURSIVE
  cnt(x) AS (VAL... <string can not be logged, contains binary data> ...
```
and 3 lines in Application log:
```
SELECT COUNT(*) FROM (WITH RECUR... <string can not be logged, contains binary data> ...
WITH RECURSIVE
  cnt(x) AS (VAL... <string can not be logged, contains binary data> ...
```

With nightly build, the 4 lines of the query are copy/paste in User log:
```
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000000)
SELECT x FROM cnt;

```
And 6 lines in Application log:
```
SELECT COUNT(*) FROM (WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000000)
SELECT x FROM cnt);
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000000)
SELECT x FROM cnt LIMIT 0, 50000;
```

I would really like to help improve DB4S but I'm unable to build the source code actually.

**Comment by justinclift** [comment] 2015-06-17 22:45
Ahhh.  We've been doing some initial work to get proper instructions written up for compiling on Windows.  I can forward the email to you with the initial write up that @schdub did.  We're planning on getting it formatted nicely and onto the wiki, but haven't done so yet.

If you want, email me (justin@postgresql.org), and I'll forward the instruction email to you. :smile:

**Comment by MKleusberg** [comment] 2015-06-22 09:59
I've just pushed a commit which trims the SQL strings before logging them. This removed the additional line break at the end of @tbayart 's statement. Empty lines in the middle of the statement are still logged but this makes kind of sense because they're really part of the query and get processed by SQLite, too.

**Comment by justinclift** [comment] 2015-06-22 13:41
Awesome @MKleusberg. :grinning:

@tbayart Do you have time to grab the nightly build (tomorrow), and let us know if it's working well now from your point of view? :smile:

**Comment by tbayart** [comment] 2015-06-23 10:11
I checked the latest nightly,
the commit from @MKleusberg is working perfectly.
Well done :smile:

**Comment by justinclift** [comment] 2015-06-23 12:28
Thanks @tbayart, that's awesome too. :smile:

**Closed by justinclift** 2015-06-23 12:28 UTC
Labels: bug
