### ISSUE TITLE
iso8601

### ISSUE THREAD

**Issue by brunodepuerto** [sqlitebrowser/sqlitebrowser#2436] opened 2020-10-13 07:26 UTC
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by justinclift** [comment] 2020-10-13 11:14
Closing this, as a duplicate of #2438.

**Closed by justinclift** 2020-10-13 11:14 UTC
Labels: duplicate
