### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by BoniuNIU** [sqlitebrowser/sqlitebrowser#1975] opened 2019-08-22 03:39 UTC
What is your question
-----------------------
After copied all the required lib files to the exe directory，install the exe but having error 0xc0000007b? But when I install the DB Browser for SQLite.exe from github, it works. How to generate a exe in windows?

**Comment by justinclift** [comment] 2019-08-22 06:54
Welcome @BoniuNIU. :smile:

With that error, the number itself isn't too useful.  Does it have any other information available when the error shows up?  If there's a dialog box, maybe screenshot it?

As a thought, it can sometimes be useful to launch the program from the command line too, as some operating systems (including Windows) have a tendency to display useful error messages there if things go wrong. :smile:

Also, which version of Windows are you using, and is it 32 or 64 bit? :smile:

**Comment by chrisjlocke** [comment] 2019-08-22 07:23
> when I install the DB Browser for SQLite.exe from github, it works. How
to generate a exe in windows

Just an obvious question, but if the .exe from the website is working, why
are you trying to generate your own .exe ?  Is this to add a different
SQLite version in it?

>

**Comment by BoniuNIU** [comment] 2019-08-22 07:47
> Welcome @BoniuNIU. 😄
> With that error, the number itself isn't too useful.  Does it have any other information available when the error shows up?  If there's a dialog box, maybe screenshot it?
> As a thought, it can sometimes be useful to launch the program from the command line too, as some operating systems (including Windows) have a tendency to display useful error messages there if things go wrong. 😄
> Also, which version of Windows are you using, and is it 32 or 64 bit? 😄

Thanks for your reply. 
As you see, this is the screenshot of the dialog box.
![image](https://user-images.githubusercontent.com/43410462/63496006-a1abd200-c4f3-11e9-8c28-e9e2b8cdbae8.png)
 In addition, I am using 64bit windows, but the generated exe is 32 bit, I guess my computer  lacks the Visual Studio C++ 2005(32 bit), or my .net framework is wrong. But I tried sometimes, these methods don't work.
And I am sorry, I am not good at using command line.
Thank you!

**Comment by BoniuNIU** [comment] 2019-08-22 07:49
> when I install the DB Browser for SQLite.exe from github, it works. How
> to generate a exe in windows
> 
> Just an obvious question, but if the .exe from the website is working, why
> are you trying to generate your own .exe ?  Is this to add a different
> SQLite version in it?
> …

Thanks for your reply.
Yes, I want to improve something to use it, but I don't find useful method to fix it.

**Comment by mgrojo** [comment] 2019-08-26 20:38
Have you followed these steps?

https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S

**Comment by BoniuNIU** [comment] 2019-08-27 09:06
> Have you followed these steps?
> https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S

Yes, and I have solved the problem, it's really about vcredist_x64.exe.Thank you.

**Comment by chrisjlocke** [comment] 2019-08-27 09:14
> Yes, and I have solved the problem

A note to this effect would be appreciated when you've opened an issue, so
that time isn't spent diagnosing solved problems.

>

**Comment by justinclift** [comment] 2019-08-27 09:25
> Yes, and I have solved the problem, it's really about vcredist_x64.exe.Thank you.

You're welcome @BoniuNIU. :smile:

If the change you make to improve something works ok - and if you're ok with sharing it - then we're pretty open to accepting Pull Requests.  That way it the change can be included in our future releases. :smile:

**Comment by chrisjlocke** [comment] 2019-08-28 18:56
Closing as the issue is resolved.
We'd welcome how you solved this though, which would help others.

**Closed by chrisjlocke** 2019-08-28 18:56 UTC
Labels: windows

**Comment by skys215** [comment] 2019-10-31 12:50
So the version of  `vcredist_x64.exe` should match the version of the Visual Studio you are using? Or should match the latest Visual C++ Redistributable Package? Or it must be the 2005 version?
