### ISSUE TITLE
Loads wrong table

### ISSUE THREAD

**Issue by JayWLord** [sqlitebrowser/sqlitebrowser#879] opened 2016-11-23 21:43 UTC
### Details for the issue

After opening a database having multiple tables, then high lighting a table name OTHER than the first in the list, then RIGHT CLICKING and selecting BROWSE TABLE incorrectly loads the data of the first table in the list, and NOT the one highlighted.
If that table is huge, you have to wait for it to load and display before you can select the table you wanted from the drop down box.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_7 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2016-11-23 21:58
From memory, this is fixed in the nightly builds.  Any interest in giving one of those a shot? :smile:

**Comment by JayWLord** [comment] 2016-11-23 22:27
I didn't look thru them since I only installed the product yesterday.  
Thought it was new.  But now I see the build I have is actually months 
old, so I will investigate the nightly builds as you suggest.

Hard to believe that the author added the right click menu items then 
didn't test them.:-)

**Comment by chrisjlocke** [comment] 2016-11-24 07:23
The latest nightly works for me.  :)

> Hard to believe that the author added the right click menu items then didn't test them.:-)

More like it did work but then got broken...  this is applicable...
http://i.imgur.com/aiSRk1s.gif

**Comment by revolter** [comment] 2016-11-24 08:31
@JayWLord, It's not that it was not tested, it's seems to be caused by #748.

**Comment by justinclift** [comment] 2017-01-28 03:14
Closing this due to lack of response. 😦

**Closed by justinclift** 2017-01-28 03:14 UTC
Labels: response requested
