### ISSUE TITLE
Cannot edit records in a table with 'without rowId' set

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2582] opened 2021-02-07 17:45 UTC
Details for the issue
--------------------

#### What did you do?
Attempt to insert a new row in a WITHOUT ROWID table
#### What did you see instead?

The key is automatically inserted, the rest of the fields are ignored (become NULL).
Updating the NULL field with any value changes ALL rows with that value (database content corruption).
Attempting to delete the row fails with error attached.

I think this version should be removed not to cause harm to users' databases.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ _7_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

![image](https://user-images.githubusercontent.com/11968823/107154689-0fb0b700-697d-11eb-9b8e-fdc6ec310b43.png)

**Comment by chrisjlocke** [comment] 2021-02-07 18:11
Thanks for the report, but you haven't explained steps to reproduce the problem - just 'The key is automatically inserted, the rest of the fields are ignored', but I'm unsure how you got to that point.
I assume your table doesn't have a primary key if you're using rowIds?  Can you post the schema of the table you were having issues on?

**Comment by tonypdmtr** [comment] 2021-02-07 20:41
CREATE TABLE IF NOT EXISTS "people"(
  phone text primary key null,
  name text collate nocase null,
  notes text collate nocase null
  check (phone not null or name not null)
) without rowid;

Try to insert into this table.

**Comment by chrisjlocke** [comment] 2021-02-08 07:30
Out of interest, how can a primary key column contain nulls?  Doesn't that sound 'illegal' ?  SQLite allows pretty much anything, but how can each row be uniquely identified if the primary key contains nulls?  I could have two records (in your example) with a phone of '2' and a name of '2'.  How is DB4S going to work out which record I'm editing?  How would you do 'expect' it to work?  It would be OK if a field was UNIQUE as well (although names technically can't... unless you have 'John Smith 2', etc...)

Eg:
![image](https://user-images.githubusercontent.com/7872218/107188408-7c5c9d80-69df-11eb-9991-8b39bafbb5b2.png)

So if I edit row 3, how would it know which one I'm editing - and not row 2?

**Comment by chrisjlocke** [comment] 2021-02-08 07:35
According to the application log, updates are failing as the non-existent _row_id_ is still being used.

`UPDATE "main"."people" SET "notes"=? WHERE "_rowid_"='3'`

**Comment by chrisjlocke** [comment] 2021-02-08 07:54
> The key is automatically inserted, the rest of the fields are ignored (become NULL).

When inserting a new record, an empty record of NULLS can't be inserted, so DB4S slaps in a record with the primary key having a numeric value, and all other values as NULL.  Further edits fail due to the issue above - all other edits rely on the '_rowId_' column which isn't available.

**Comment by tonypdmtr** [comment] 2021-02-08 08:00
> Out of interest, how can a primary key column contain nulls? Doesn't that sound 'illegal' ?

Yes, but... See this recent discussion: https://sqlite.org/forum/forumpost/dd7e41a1aab0a92897ff3e3cea87f1c0bb0331244bcfd1959f338ce2f2a2ed96

**Comment by tonypdmtr** [comment] 2021-02-08 08:08
> Out of interest, how can a primary key column contain nulls? Doesn't that sound 'illegal' ? SQLite allows pretty much anything, but how can each row be uniquely identified if the primary key contains nulls? I could have two records (in your example) with a phone of '2' and a name of '2'. How is DB4S going to work out which record I'm editing? How would you do 'expect' it to work? It would be OK if a field was UNIQUE as well (although names technically can't... unless you have 'John Smith 2', etc...)
> 
> Eg:
> ![image](https://user-images.githubusercontent.com/7872218/107188408-7c5c9d80-69df-11eb-9991-8b39bafbb5b2.png)
> 
> So if I edit row 3, how would it know which one I'm editing - and not row 2?

Your example is wrong because this table won't allow you to have two rows with the same numeric content.

**Comment by chrisjlocke** [comment] 2021-02-08 08:12
> Your example is wrong

Yup, apologies - got that now.  Brain didn't work out that primary key inferred UNIQUE - thought it was a separate setting required.

**Comment by MKleusberg** [comment] 2021-02-08 17:36
Thanks, @tonypdmtr! This should be my fault :innocent: I'll look into this now.

**Comment by MKleusberg** [comment] 2021-02-08 17:46
This should be fixed in tomorrow's nightly build. Can you give that another try, @tonypdmtr?

**Comment by tonypdmtr** [comment] 2021-02-09 12:29
DB.Browser.for.SQLite-win32.zip                    09-Feb-2021 03:57            17819308
seems to work OK (with respect to this issue).

**Comment by chrisjlocke** [comment] 2021-02-09 19:19
Thanks @MKleusberg for the quick fix. 👍👍

**Closed by chrisjlocke** 2021-02-09 19:19 UTC
Labels: SQL Core, bug
