### ISSUE TITLE
Application crashed during modify table

### ISSUE THREAD

**Issue by Gandalf888** [sqlitebrowser/sqlitebrowser#1599] opened 2018-11-01 19:26 UTC
Details for the issue
--------------------

#### What did you do?

- create new database
- create new table
- add few field
- save changes
- modify created table
- add new few field
- application crashed 

#### What did you expect to see?

The application should after the save changes, add new field to table without crashed.

#### What did you see instead?

When the application crashed, console show this:

```
user@linux:~> sqlitebrowser 
kf5.kio.core: We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nLoaded services file OK.\nWARNING: The 'netbios name' is too long (max. 15 chars).\n\n"
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5092, resource id: 33971598, major code: 40 (TranslateCoords), minor code: 0
executeSQL:  "ALTER TABLE `crash` ADD COLUMN \t`Field5`\tINTEGER" -> no such table: crash
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QSocketNotifier: Invalid socket 12 and type 'Read', disabling...
QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
QSocketNotifier: Invalid socket 13 and type 'Read', disabling...
KCrash: Application 'sqlitebrowser' crashing...
KCrash: Attempting to start /usr/lib64/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0

[1]+  Stopped              sqlitebrowser
```

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X ] Linux: ( _distro: openSUSE  Tumbleweed)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha*
- [X ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2018-11-02 00:04
Thanks for the bug report @Gandalf888. :smile:

With the "create new table", "add new field" (and others), did you create the table + add fields using the window/dialog, or did you create them with SQL statement you put into the "Execute SQL" tab?

Asking because if you created them with the `Execute SQL` tab, would you be ok to cut-n-paste the commands here?  It would probably help. :smile:

**Comment by Gandalf888** [comment] 2018-11-02 06:16
I created using window/dialog.

**Comment by chrisjlocke** [comment] 2018-11-02 09:14
v3.10.1 is quite old now, and there have been lots of changes.  Any chance you could try compiling from the recent source?

**Comment by mgrojo** [comment] 2018-11-02 17:00
@Gandalf888 Or you could simply try the 3.[11.0 alpha version](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-alpha1). There is a high chance that your bug is fixed.

**Comment by Gandalf888** [comment] 2018-11-03 11:17
I compiled and testing version 3.11.99 and this bug is absent. Everything works correctly. When are you planning to realase a new version?

**Comment by justinclift** [comment] 2018-11-03 11:30
@Gandalf888 We're working on a new release at the moment.  It's taking some time though, as we need to solve a few tricky problems.  Making progress, but it's going slow atm. :frowning:

**Comment by chrisjlocke** [comment] 2018-11-03 11:31
It would be quicker if someone didn't keep stealing the travel adaptor.... 😜

**Comment by chrisjlocke** [comment] 2018-11-03 11:32
Will close this, as the issue is solved (theoretically) ...

**Closed by chrisjlocke** 2018-11-03 11:32 UTC
Labels: bug, linux

**Comment by herpertutus** [comment] 2022-07-05 02:03
i am having this issue pop up on arch linux with sqlitebrowser 3.12.2-2 except its as soon as i attempt to modify a table

**Comment by chrisjlocke** [comment] 2022-07-05 12:06
This is a duplicate of #3069 and has been fixed.
If you can build from the most current source, all will be good again.
