### ISSUE TITLE
Text and background colors

### ISSUE THREAD

**Issue by capitancooker** [sqlitebrowser/sqlitebrowser#923] opened 2017-01-08 09:52 UTC
### Details for the issue
On preferences/data browser,
 text and background color for field are all black.
I do modification but at next start this issue come back.
Thanks
![schermata 2017-01-08 alle 10 49 24](https://cloud.githubusercontent.com/assets/16868088/21748861/6a1e6fa0-d590-11e6-8132-3bd6181b3c94.jpg)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: (_version: 10.12.2)
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment] 2017-01-08 10:25
This is a duplicate of #737. The latest nightlies should fix it.

**Closed by revolter** 2017-01-08 10:25 UTC

**Comment by justinclift** [comment] 2017-05-03 22:52
Oops, somehow missed this.

@capitancooker Did the nightly builds fix this for you? 😄

**Comment by capitancooker** [comment] 2017-05-04 06:00
@justinclift yes!

**Comment by justinclift** [comment] 2017-05-04 07:15
Excellent. :smile:
