### ISSUE TITLE
"COMMIT;" -> cannot commit - no transaction is active

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#583] opened 2016-05-04 17:07 UTC
Noticing some interesting messages in the output windows on Win64 with SQLCipher compiled in:

```
executeSQL:  "COMMIT;" -> cannot commit - no transaction is active
```

As per screenshot:

![commit failure messages](https://cloud.githubusercontent.com/assets/406299/15022211/7d88dbca-1222-11e6-9060-04960dfcc2b2.png)

The first three lines were output when setting the encryption key (File → Set Encryption).

The final '"COMMIT;" -> cannot commit' line is output any time the "Write Changes" button is pressed.

I haven't traced through the code to figure out what's going on, and the data appears at cursory glance to be getting written to disk, as the database can be re-opened to find the data there.  However, this is something that bears looking into, just to be safe. :wink:

**Comment by MKleusberg** [comment] 2016-05-05 23:28
Hi Justin!
I looked into this and fixed it. This was caused by an overcautious COMMIT when saving a database. We'd save all changes and then do an extra-commit just to be sure. But since there was no need for this, SQLite would output that warning. So this isn't caused by SQLCipher but would happen with the normal version, too. Good news is that this doesn't cause any harm at all, so no chance of this causing any data loss etc. I've fixed it anyway, so the warning should be gone. Instead of just deleting the COMMIT call (which should have been ok, too) we're now checking if there is still a transaction after saving everything, and only if there is we call COMMIT.

**Comment by justinclift** [comment] 2016-05-06 00:21
Awesome :smile:, I'll verify it from my end probably tomorrow.

**Comment by justinclift** [comment] 2016-05-06 17:52
Tried this out again with the two latest commits applied.  Yep, that last commit message - generated when clicking the "Write Changes" button - is no longer happening.

But :smile:, found some other instances of it (and seemingly related).

This one is generated when creating a new database (non-encrypted).  The message appears right after choosing a filename to save the database as:

![db4s-issue583-screenshot_2](https://cloud.githubusercontent.com/assets/406299/15081362/9443c278-13ba-11e6-8f83-f6ca5ed124d0.png)

The "RELEASE RESTOREPOINT;" line after that is generated when clicking "Write Changes", directly after creating an empty table (without changing to the "Browse Data" tab yet):

![db4s-issue583-screenshot_3](https://cloud.githubusercontent.com/assets/406299/15081452/03f0c97c-13bb-11e6-9e93-f7d706d9cd80.png)

The third, fourth, and fifth lines are generated when the database file is closed.  Seems like fairly standard widget output message stuff, and is hopefully easy to address. :smile:

![db4s-issue583-screenshot_4](https://cloud.githubusercontent.com/assets/406299/15081537/5424d1d6-13bb-11e6-8885-32ac71de1297.png)

**Comment by MKleusberg** [comment] 2017-05-08 12:18
@justinclift Should be fixed, too, now :wink: Can you double check?

**Comment by justinclift** [comment] 2017-05-08 12:50
Will do.  Probably later today, but it may get pushed out to sometime this week depending on how other things go. :wink:

**Comment by MKleusberg** [comment] 2017-08-13 13:37
Any update here? :smile:

**Comment by justinclift** [comment] 2017-08-13 16:18
Ahhh, not yet.  Haven't yet tried it, and it's not high enough up the priority list just atm. :smile:

**Comment by MKleusberg** [comment] 2017-08-13 17:38
No worries :wink:

**Comment by mgrojo** [comment] 2018-10-05 18:00
I've followed the steps and I don't reproduce the messages. But I get these in my case/version:
```
edit: editing failed
edit: editing failed
```

**Comment by MKleusberg** [comment] 2021-05-22 08:39
I'll just assume this is fixed :smile: At least I didn't notice any "cannot commit" messages for a long time.

**Closed by MKleusberg** 2021-05-22 08:39 UTC
Labels: SQLCipher, response requested, windows
