### ISSUE TITLE
Double clicking a 'remote' database continually downloads that database and does not open local version

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1096] opened 2017-08-21 14:37 UTC
### Details for the issue

So I've a list of databases...

![image](https://user-images.githubusercontent.com/7872218/29523924-5a233746-8686-11e7-8503-03f38ce2154e.png)

Double clicking on them opens the local copy ...except for 'a.db' which always downloads a new 'version' (timestamped version)

![image](https://user-images.githubusercontent.com/7872218/29523867-3d43cbe0-8686-11e7-964e-d46c75a9f886.png)

and 'b' (highlighted).  The others open the local copy.

I thought this might be because they were short filenames, but I've just uploaded a long filename, and that exhibits the same behaviour - it always downloads a new version.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 x64___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2017-08-21 14:43
Oops.  Deleting 'remotedbs.db' has cured this.  Was obviously some database change between the betas and the new version.

**Comment by chrisjlocke** [comment] 2017-08-21 14:45
PS: My 'modified' column is zero.  Is this correct?

![image](https://user-images.githubusercontent.com/7872218/29524452-c612d35c-8687-11e7-8ab0-7318401f4efd.png)

(reopening this just so this comment gets noticed...)

**Comment by justinclift** [comment] 2017-08-21 14:50
Ahhh yeah, good point.  I'd forgotten about that too. :smile:

**Comment by chrisjlocke** [comment] 2017-08-22 13:58
Reopening this, as its doing it again.  Its on a database I only uploaded today, so there is an issue somewhere.

Some checksum doesn't match across the two databases.

**Comment by justinclift** [comment] 2017-08-22 14:33
Interesting.  k, we might need to wait for @MKleusberg to get back from his hiking trip. :smile:

**Comment by MKleusberg** [comment] 2017-09-01 10:59
@chrisjlocke Can you send me you remotedbs.db file along with the file name of the database that's having the problem?

**Comment by chrisjlocke** [comment] 2017-09-01 11:27
Will do.  Its doing it on 'users only.db'.  

![image](https://user-images.githubusercontent.com/7872218/29967879-c244a4c6-8f10-11e7-852b-8e13a3a25343.png)

https://db4s-beta.dbhub.io/chrisjlocke/remotedbs.db

**Comment by MKleusberg** [comment] 2017-09-01 12:03
I can't see any problem with your remotedbs.db file ☹️ I thought it might be because of the space character in the file name (' ' vs '%20' or something like that) but that bit appears to be working correctly and your initial 'a.db' file didn't have any spaces in it...

If @justinclift is okay with starting the build scripts, I could write a version with extra debug output.

**Comment by justinclift** [comment] 2017-09-01 12:04
Yep, that's no worries at all. :smile:

Hmmm, @chrisjlocke mentioned that Windows has a problem with debug output showing up.  Maybe log to a file (or database :wink:)?

**Comment by MKleusberg** [comment] 2017-09-01 12:05
Or use [this method](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Debugging-a-crash-on-Windows) :smile:

**Comment by MKleusberg** [comment] 2017-09-01 12:25
@justinclift Can you kick off the build for this branch: https://github.com/MKleusberg/sqlitebrowser/tree/debug?

@chrisjlocke Can you try again using the build Justin is going to create? Just try to open the 'users only.db' file again and hope that it's still failing to open the local copy :wink: With the debug version it should create a 'debug.log' file in the same directory as the remotedbs.db file which should hopefully give us some clue as to what is happening 😄

**Comment by justinclift** [comment] 2017-09-01 13:07
Oops, just saw this.  Yep, I'll kick it off now.

If I do a 64-bit only one... and make it say SQLite only, that'll take only 1/4 the time to do.

**Comment by justinclift** [comment] 2017-09-01 13:34
k, here it is: https://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-2017-09-01-win64.exe

**Comment by chrisjlocke** [comment] 2017-09-01 14:02
Downloading now.  I've got the WinDbg program and that works OK, so can do either method (for future reference)

**Comment by chrisjlocke** [comment] 2017-09-01 14:08
```localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match
localExists("https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db?commit=49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090", "C:/Users/chris.locke/AppData/Roaming/sqlitebrowser/DB Browser for SQLite/chrisjlocke.cert.pem1")
url_commit_id = 49dc94b74455b3891f7ed8aa17f5eaa61b0bf95a13c0cf00e359ed0b42f64090
url = https://db4s-beta.dbhub.io:5550/chrisjlocke/users only.db
identity = chrisjlocke.cert.pem1
local_commit_id = 94cbcb93bc8467b6a9cd245f2ee2fa1d47f26875f77d099d182806c93bd1e9d5
local_file = users only.db_1503398328621.remotedb
no match```


Sorry - I tried opening it several times.... ;)

**Comment by justinclift** [comment] 2017-09-01 14:11
On the server console the matching output is:

```
2017/09/01 14:01:32 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:01:33 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:01:34 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:04:49 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:04:50 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:04:51 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:04:52 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:04:53 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:04:53 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:04:54 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:05:47 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:05:47 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:05:48 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:05:49 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
2017/09/01 14:05:49 'chrisjlocke/users only.db' downloaded by user 'chrisjlocke', 7168 bytes
```

More in-depth logging can be added to the server side if that'd be useful.

**Comment by chrisjlocke** [comment] 2017-09-01 14:14
I knew i'd clicked it several times....but blimey..... ;)

**Comment by MKleusberg** [comment] 2017-09-01 16:28
Ahhh hmmm, it's sort of obvious now :wink: So thanks to both of you! The problem is basically that we don't have any version control implemented yet. I assume both the ```a.db``` and the ```users only.db``` file have multiple commits whereas the other databases don't. Correct? 😄 

There's a very easy fix and a slightly more complicated but better fix for this. I'll try the better one first and if that doesn't work as expected, I'll fall back to the easy hack-ish one for now.

**Comment by chrisjlocke** [comment] 2017-09-01 16:49
Doh.  Makes sense.  So the commit has changed, but not in the 'link', etc.  Aah.

**Comment by MKleusberg** [comment] 2017-09-01 16:58
Just pushed the 'better' solution to this 😄 The next time you're opening one of those files it's now going to ask you in a message box if you want to open the old local version or download the new remote version. If you choose to open the old local version it will just open it, downloading nothing, and ask again the next time you're opening the file. If you choose to open the new remote version it will delete your local copy, redownload, and the issue will be gone.

In your case with the many checkouts that's probably a bit confusing but in theory it should prevent this situation in the future entirely :wink:

**Comment by chrisjlocke** [comment] 2017-09-01 17:03
Will test that.  Thanks for implimenting this.  :)

**Comment by MKleusberg** [comment] 2017-09-01 17:11
It's still not perfect though 😉 Pushing a new commit and then double clicking the database file will pop up the same message box. But that's a different issue...

**Comment by justinclift** [comment] 2017-09-01 18:58
Hmmm, it should be fairly easy to add something to the server for returning the commit history for a given database branch.  Maybe something like `/commitlist/path/to/database.sqlite?branch=foo` or `/commits?owner=foo&folder=bar&db=baz.sqlite&branch=barf` (either way is probably workable).

In response it'd send back a JSON list with all of the commit history for the given branch.

It's actually pretty trivial to assemble that, as it's already stored in the database in assembled form, ready for use. 😀

**Comment by MKleusberg** [comment] 2017-09-02 08:46
I don't even think that's necessary for now. With https://github.com/sqlitebrowser/dbhub.io/issues/100 I'd have all that I need to fix that last issue (I think).

**Comment by justinclift** [comment] 2017-09-18 18:01
Should this be closed?

**Comment by MKleusberg** [comment] 2017-09-19 19:19
Yeah, I'm just going to close this :smile: I'm pretty sure it's fixed. If it's still broken it's probably a new issue :wink:

**Closed by MKleusberg** 2017-09-19 19:19 UTC
Labels: dbhub.io
