### ISSUE TITLE
[Bug]: Crash when removing a newly added CHECK constraint

### ISSUE THREAD

**Issue by joulethief97** [sqlitebrowser/sqlitebrowser#3705] opened 2024-08-13 10:49 UTC
### What did you do?

I was about to start learning SQL and created a very basic db file with nothing but a table "table" in it, the table itself containing a Field "Field1".

When I attempted to rename the table, I stumbled across the "CHECK constraints" tab, mistakenly added an entry and immediately tried to remove it.

### What did you expect to see?

The CHECK constrained being removed and the program working on as intended.

### What did you see instead?

The program crashed without providing any error message.

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11 Pro 22H2

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment] 2024-08-13 11:21
Ouch, that definitely sounds like a bug. :grimacing:

**Comment by joulethief97** [comment] 2024-08-13 11:35
Whoops, forgot to fill in the title. Sorry.

**Comment by chrisjlocke** [comment] 2024-08-13 17:09
Confirmed - can replicate.  Add a constraint, click 'remove' and application just closes (albeit after a short 'program is dying' phase)

**Comment by justinclift** [comment] 2024-10-17 00:13
@mgrojo I forgot to point this one out before the 3.13.1 release. 😦

Any interest in taking a look?

**Comment by mgrojo** [comment] 2024-10-18 23:12
I couldn't reproduce on Linux, but I think I've fixed it. Could both of you, @erickpaquin or @joulethief97, confirm it is now fixed on your platform?

**Comment by erickpaquin** [comment] 2024-10-19 11:55
@mgrojo I can confirm it did fix the issue for me on my mac M2. Thanks for the good work.

**Comment by mgrojo** [comment] 2024-10-19 11:56
@erickpaquin thanks for confirming and for the crash report.

**Comment by justinclift** [comment] 2024-10-19 15:23
@lucydodo We might want to do a 3.13.2 release in a few weeks.  There's still some bugs being fixed that'd be good to have in a stable release. :smile:

**Comment by lucydodo** [comment] 2024-10-20 00:27
Yes, I'll leave a post in the private discussion about preparing for the next release.

**Comment by joulethief97** [comment] 2024-10-22 09:37
It still crashes for me, unfortunately... Any further info I can provide?

**Comment by lucydodo** [comment] 2024-10-25 02:05
Hi @joulethief97, What version are you using?

**Comment by joulethief97** [comment] 2024-10-28 08:14
I double-checked to confirm that I updated to _3.13.1_.

**Comment by justinclift** [comment] 2024-10-28 12:59
@joulethief97 Ahhh.  I think the fix is in the latest development builds rather than in the last point release.

Would you be ok to try the build from the `continuous` release? https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

That should (in theory) work ok. :smile:

**Comment by joulethief97** [comment] 2024-10-30 10:19
Yes, that fixed it. Thank you for your effort!

**Comment by justinclift** [comment] 2024-10-30 11:49
Awesome, thanks for checking and confirming @joulethief97. :smile:

**Comment by lucydodo** [comment] 2024-11-02 10:15
The issue appears to be resolved, so we're closing this issue

**Closed by lucydodo** 2024-11-02 10:15 UTC
Labels: bug, crash
