### ISSUE TITLE
Editor locked until pressing 'x' icon - even though SQL finished running?

### ISSUE THREAD

**Issue by midijohnny** [sqlitebrowser/sqlitebrowser#2535] opened 2021-01-10 20:12 UTC
Details for the issue
--------------------

#### What did you do?
Executed some sql.

#### What did you expect to see?
The SQL to run (it did) then for the 'stop running SQL' icon to return to disabled status to allow editing to continue.

#### What did you see instead?
SQL run (good): but the 'stop running SQL' icon remains active (red) - and you cannot make edits to the SQL.
(In fact it is slightly more confusing - the SQL editor allows navigation and selection - but any changes are ignored).
If you manually press the 'stop running SQL' icon - everything is back to normal.

Useful extra information
-------------------------
> DB4S v3.12.99 (Aug 21 2020) [built for x86_64-little_endian-lp64] on Ubuntu Core 16 (linux/5.4.0-58-generic) [x86_64]
> using SQLCipher Version 4.3.0 community (based on SQLite 3.30.1)
> and Qt 5.5.1

**Comment by midijohnny** [comment] 2021-01-10 20:17
Note: the issue appears to be somewhat sporadic - further testing indicates it doesn't happen everytime.

**Comment by midijohnny** [comment] 2021-01-10 21:16
Another observation: it *seems* that when the results grid shows a wider-result sometimes - and it appears on those occasions that the icon is left in the 'running' state?

**Comment by chrisjlocke** [comment] 2021-01-11 00:00
> Note: the issue appears to be somewhat sporadic

Does it occur more if you leave DB4S for a bit?  It's happened to me a couple of times...
I believe this occurs more in the nightlies than the 'release'... do you specifically need the nightlies?

**Comment by justinclift** [comment] 2021-01-11 09:14
Interesting.  Wonder if this is a race condition?

@MKleusberg Might be your kind of thing? :smile:

**Comment by chrisjlocke** [comment] 2021-01-11 10:47
I haven't seen an reproducable case though.  I've four instances of DB4S that have been idle for days, and they're working fine.
Sometimes double-clicking F5 can trigger it (but that throws up an error - 'you are already running an SQL statement...') but sometimes it doesn't.  The issue in question is running a statement and it doesn't 'complete'.

**Comment by justinclift** [comment] 2021-01-13 02:48
Thinking about this further, the build it's happening with is one of our older nightly builds.  The problem **may** have been solved in the months since.

@midijohnny Would you be ok to try one of our newer nightly builds?  Probably the very latest would be the right choice. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by chrisjlocke** [comment] 2021-01-14 10:31
I'll try with a more up-to-date nightly.  It seems to be waiting on the count part.  That part of the code has only very recently been tweaked so this may now be resolved.  Oooh, exciting....

![image](https://user-images.githubusercontent.com/7872218/104579309-b7271c00-5653-11eb-8d39-dfda11f51c8e.png)

**Comment by i-s-o** [comment] 2021-01-21 04:46
@MKleusberg
I hadn't experienced this before. But, with the 2021-01-20 nightly, I can consistently reproduce this issue if the second query I run has more rows than the first one. The same query "terminates" properly only if I scroll all the way to the end of the results grid and then rerun it.

Also, If the subsequent query has fewer rows, the result grid shows the text "loading..." in pink cells for the non-existing rows, and the message in the log window shows incorrect row count:

![2021-01-20_23-34-26](https://user-images.githubusercontent.com/1661549/105280791-9b060c00-5b78-11eb-9820-bc4a226a10a5.gif)

**Comment by justinclift** [comment] 2021-01-21 05:14
Interesting.  Don't suppose you're able to share the database this happens on, with us?

Just thinking that might make it easier for us to replicate the problem, and then figure out how to fix it. :smile:

**Comment by chrisjlocke** [comment] 2021-01-21 08:39
I've been using an older nightly, and this didn't occur (as frequently) but thanks to @i-s-o 's steps, yes, it's easy to reproduce, even in a new table with three rows.

![image](https://user-images.githubusercontent.com/7872218/105324996-01644c00-5bc4-11eb-92d0-b86aeffcb21f.png)


https://user-images.githubusercontent.com/7872218/105325184-383a6200-5bc4-11eb-9fad-f9eec0ef3b70.mp4

**Comment by justinclift** [comment] 2021-01-21 10:09
Ouch.

@MKleusberg Sounds like your kind of thing. :smile:

**Comment by MKleusberg** [comment] 2021-01-22 12:55
Thank you all for analysing this issue. I can reproduce it super easily now by first running
```sql
select 1 union select 2;
```
and then running just
```sql
select 1
```

I'll see what I can do :smile:

**Comment by MKleusberg** [comment] 2021-01-22 13:41
Ok, this should hopefully be fixed in tomorrow's nightly build. This part of the code turns out to be super error-prone. So let me know if you notice anything else :smile:

**Comment by chrisjlocke** [comment] 2021-01-23 09:20
This one is worse for me - locks up on the first query now.

![image](https://user-images.githubusercontent.com/7872218/105574396-31deee00-5d5c-11eb-8d98-5f3eac765848.png)

(table is just the three rows from previously)

**Comment by chrisjlocke** [comment] 2021-02-03 08:05
I thought I'd commented on this, but doesn't seem to be here.  Ooh.
Anyway.  The nightly following this fix seems more broken for me.  Simply starting DB4S, running `select 1' works the first time, but gives me the red-icon-of-doom every subsequent time.

**Comment by justinclift** [comment] 2021-02-03 08:08
Uh oh, that's not good. :frowning:

**Comment by chrisjlocke** [comment] 2021-02-03 10:26
Actually, ignore me.  Just downloaded a newer nightly, and there were build errors last time I went to download, so my nightly probably wasn't the latest one.  /hands head in shame.

**Comment by chrisjlocke** [comment] 2021-03-18 23:02
@midijohnny ; @i-s-o - Can you confirm if the recent fix has fixed this for you now?  I haven't seen this issue occur lately.

**Comment by i-s-o** [comment] 2021-03-24 02:57
All good.

**Comment by justinclift** [comment] 2021-03-24 03:12
Awesome.  Thanks for confirming it's working properly now @i-s-o. :smile:

**Closed by justinclift** 2021-03-24 03:12 UTC
Labels: Execute SQL, bug

**Comment by midijohnny** [comment] 2021-04-12 08:40
Thanks for this investigation - and I can confirm that running the simplified test case above ("select 1 union select 2" - then "select 1") - replicates the issue for me: I have *not* tried the fix - because I didn't build this from source -  I am using the released version I got from Ubuntu (using the snap install - "software" app)

```
Version 3.11.2
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.12.5
SQLite Version 3.31.1
```

For this Ubuntu version: (Xubuntu actually)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

Will this fixed version be released into the s/w repositories at some point?
Thanks again!

**Comment by midijohnny** [comment] 2021-04-12 08:47
> Thinking about this further, the build it's happening with is one of our older nightly builds. The problem **may** have been solved in the months since.
> 
> @midijohnny Would you be ok to try one of our newer nightly builds? Probably the very latest would be the right choice. 
> 
>     https://nightlies.sqlitebrowser.org/latest/

Just to add : I tried this - but I'm on Linux - so the nightly builds here only seem to include windows and Mac.
I followed the instructions regarding Linux 'snap' builds - but they aren't up to date it seems.
So I can't test and confirm the fix personally.
(I'll see if I can build this from source to verify at some point).
