### ISSUE TITLE
DB4S v3.11.1 - Dark Theme issue on MacOS

### ISSUE THREAD

**Issue by lalkrishna** [sqlitebrowser/sqlitebrowser#1757] opened 2019-02-21 07:12 UTC
Details for the issue
--------------------

#### What did you do?
Open App in Mac OS

#### What did you see instead?
Database structure - Table names can't read because of background color. (Seems like new Dark theme not working well for macOS.). Also please provide option to hide dark theme in preference.

Useful extra information
-------------------------
> DB4S v3.11.1 [built for x86_64-little_endian-lp64] on macOS 10.14 (darwin/18.2.0) [x86_64]
> using SQLCipher Version 4.0.1 community (based on SQLite 3.26.0)
> and Qt 5.11.3

**Comment by karim** [comment] 2019-02-21 07:25
Duplicate of #1751 

Thanks for reporting this, we are aware of this problem. This issue is being tracked in #1751. I'm closing this one here and please use the other issue instead. Thanks you. :smiley:

**Closed by karim** 2019-02-21 07:25 UTC

**Comment by justinclift** [comment] 2019-02-21 09:07
@lalkrishna In case it helps, this is a first build with an initial fix:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_issue1751v1.dmg

But yeah, follow along with issue #1751, as @karim mentioned above. :smile:
