### ISSUE TITLE
CHECK constraint fails on NOT NULL boolean field

### ISSUE THREAD

**Issue by surik00** [sqlitebrowser/sqlitebrowser#1350] opened 2018-03-17 17:48 UTC
### Details for the issue

If I create a table with this sample query:
```SQL
CREATE TABLE "Test tbl" ( id INTEGER NOT NULL, some_check BOOLEAN NOT NULL, PRIMARY KEY (id), CHECK (some_check IN (0, 1)) )
```
(something like this is generated by SQLAlchemy, when using Boolean field)
There is no way to add any items to this table using DB4S:

![](http://telegra.ph/file/5aefffd88f02f36604a2c.png)

**But I'm still able to to add items using an SQL query**

However if I create a table allowing null in the boolean field:
```SQL
CREATE TABLE "Test nullable tbl" ( id INTEGER NOT NULL, some_check BOOLEAN, PRIMARY KEY (id), CHECK (some_check IN (0, 1)) )
```

I'm able to add items using DB4S:

![](http://telegra.ph/file/221a8e52fed501b0d55c6.png)

As I see, DB4S tries to insert an empty string to the field.

I assume this is an issue

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 10.13.3 (17D47) )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2018-03-17 21:42
Heya @surik00.  Something about this bug report is sounding really familiar, but the exact details aren't springing to mind.

As a thought, have you tried the latest nightly build for OSX?  There's a bunch of useful bug fixes (and some general improvements) since the 3.10.1 release, so it's worth trying just in case this bug is fixed already. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by surik00** [comment] 2018-03-18 05:39
Hi! I tried nightly build just before creating this issue and I did it again right now - this bug is still present (in _about_ this build is `Version 3.10.99 (Mar 18 2018)`)

**Comment by justinclift** [comment] 2018-03-18 12:10
Ok, no worries.  It's always a good idea to check, just in case. :smile:

**Comment by mgrojo** [comment] 2018-03-18 12:42
This seems the same as #530 and also related to #601 and #463. The problem is our approach for inserting new records as explained in #628. I'm not very familiar with the SQL backend of the application, but I'll try to give it a thought. Currently the application is broken for tables with constraints.

**Comment by MKleusberg** [comment] 2018-08-27 20:18
Sorry for taking so long with this but we have finally merged a change by @mgrojo which should fix this problem :smile: Can you give [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/) a try and see if it's working now, @surik00? You should see a dialog now which allows you to enter the values of the new record when the in-place inserting which we normally use doesn't work.

**Comment by justinclift** [comment] 2018-09-04 13:40
Fantastic!  Thanks for verifying @surik00. :smile:

Well done again @mgrojo, you're really getting some of the trickier stuff taken care of.  It's great. :grin:

**Closed by justinclift** 2018-09-04 13:40 UTC
Labels: bug, constraints & foreign keys, response requested

**Comment by mgrojo** [comment] 2018-09-04 20:18
> Well done again @mgrojo, you're really getting some of the trickier stuff taken care of. It's great. :grin: 

Thanks, Justin. 😊
