### ISSUE TITLE
SQLite Browser Select results 7 rows but data not displayed

### ISSUE THREAD

**Issue by nuzvid** [sqlitebrowser/sqlitebrowser#217] opened 2015-03-06 05:36 UTC
I have a DB with Table Id as text and kwd as Text

Id has values 
3.1.1.a
3.1.1.b
...

If I make a query: 
select * from Sutra where Id like '%3.%'

I see the result as:
6 Rows returned from: select * from Sutra where Id like '2.%' (took 2ms)

No records displayed.

Problem (a): When I ask for '%3.% why it is taking as '2.%' ?
Problem (b): 6 rows returned, but the records not displayed

**Comment by rp-** [comment] 2015-03-06 06:24
This is a duplicate of #203 and should already be fixed in the nightly build.

**Comment by justinclift** [comment] 2015-03-10 02:04
@nuzvid Have you had a chance to try out the nightly build, to see if it's fixed for you there? (it should be)

**Comment by justinclift** [comment] 2015-03-11 22:32
Closing this.

@nuzvid If the latest nightly build doesn't have this fixed for you, please reopen this. :smile:

**Closed by justinclift** 2015-03-11 22:32 UTC
Labels: duplicate
