### ISSUE TITLE
Startup SQL file ignored

### ISSUE THREAD

**Issue by orbisvicis** [sqlitebrowser/sqlitebrowser#504] opened 2016-01-22 22:28 UTC
Version: 3.8.0
SQLite version: 3.9.2

In the "Execute SQL" tab, I can run:

```
select load_extension("path to extension");
select new_function(...)
```

but if the startup file has

```
select load_extension("path to extension");
```

then when attempting to run `new_function` I receive:

```
no such function: new_function: new_function(...);
```

**Comment by orbisvicis** [comment] 2016-01-22 22:41
Furthermore, this startup file fails to modify the pragmas:
```
PRAGMA foreign_keys = ON;
```

**Comment by justinclift** [comment] 2016-01-22 23:59
Interesting.  That definitely sounds like a bug. :frowning:

**Comment by orbisvicis** [comment] 2016-01-23 19:34
if the database is supplied to the command line, the startup file is executed, as expected. The startup file is only ignored when the database is opened via the GUI.

**Comment by MKleusberg** [comment] 2016-01-24 17:16
Hmm, I have difficulties to reproduce this, both loading extensions and setting the pragma work for me...
By startup file you mean the Preferences dialog -> Database -> Advanced -> "SQL to execute after opening database" field? In this case there really shouldn't be any difference between opening the file via GUi and command line... So we'd have to do some more debugging on this :smile: As a start: What does it say in the SQL log area of the application when showing SQL submitted by the application? Do your commands appear there? In the meantime you can also load the extension via the Extensions tab in the preferences dialog and enable foreign keys in the Database tab.

**Comment by revolter** [comment] 2016-09-19 10:25
@orbisvicis, Do you have time to test this using the nightly build?

**Comment by justinclift** [comment] 2016-09-25 21:14
@orbisvicis Ping.  Would you be ok to try our recent 3.9.0 release?  There's a fairly decent chance the bug is fixed in that. :smile:

**Comment by justinclift** [comment] 2017-01-28 03:11
Closing this due to lack of response. 😦

**Closed by justinclift** 2017-01-28 03:11 UTC
Labels: bug, response requested
