### ISSUE TITLE
Modify Table too aggressive -- long UI hangs and waits

### ISSUE THREAD

**Issue by tlhackque** [sqlitebrowser/sqlitebrowser#1444] opened 2018-06-23 03:03 UTC
Details for the issue
--------------------

#### What did you do?
Modify table - the table has a couple of million records.  (That's my **test** database...)

(1,868,892 to be precise... with modest indexing and foreign keys.)

Specifically, I clicked "add field", then <tab> to change the type from Integer to Text.

#### What did you expect to see?
The Type dropdown open immediately

#### What did you see instead?
Busy wait loop - while the browser happily copied the table to add the field.

Then, I changed it to integer - and again, long wait while the disk bangs around.

Several minutes with Windoze saying "not responding" is not acceptable. 

What's REALLY annoying is that taking advantage of the wait, I clicked on my browser window to write this report.  After a while, the GUI noticed that my mouse wasn't over the dropdown anymore, and decided that I changed my mind, and closed the dropdown on Integer - starting another copy.

It took about 5 iterations until I held my mouse steady (buttons up) over the dropdown before the browser finally agreed that text is the "final" end state.

When I DO click OK, it takes about another minute or so to finish up - and then a shorter (but still unresponsive to windows) wait while write changes is executed.

- These changes should not cause any database activity until OK (or the missing Apply) button is clicked.

This includes changing a field type, modifying an attribute, moving it up or down...

- When OK (or Apply) is clicked, some progress indicator (and updating windoze would be a good idea - e.g. 50,000 of 1,000,000 records copied...

Here is the application SQL Log showing the transactions.  The only thing to pay attention to is the number of times that the browser tried to create a temporary table with the (new) "filedescription" field typed as "integer' - which I never wanted it to do.

````
SPRAGMA foreign_keys
ALTER TABLE `main`.`FILEs` ADD COLUMN 	`Field15`	INTEGER
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_1` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_1` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`Field15` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_1` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_2` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_2` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_2` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_3` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_3` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_3` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_4` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_4` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_4` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_5` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_5` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_5` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_6` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_6` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_6` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_7` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_7` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_7` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_8` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_8` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_8` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_9` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_9` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_9` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_10` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_10` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_10` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_11` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_11` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_11` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_12` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_12` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_12` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_13` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	INTEGER,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_13` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_13` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_14` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	TEXT,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_14` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_14` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_15` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	TEXT,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_15` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_15` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
CREATE TABLE `sqlb_temp_table_16` (
	`id`	integer,
	`cdid`	integer NOT NULL,
	`directory`	text,
	`filename`	text,
	`filesize`	integer,
	`fileallocation`	text,
	`uid`	text,
	`fileattributes`	text,
	`filecreated`	text,
	`filemodified`	text,
	`fileexpired`	text,
	`filebackup`	text,
	`fileowner`	text,
	`fileprotection`	text,
	`filedescription`	TEXT,
	FOREIGN KEY(`cdid`) REFERENCES `CDs`(`diskid`),
	PRIMARY KEY(`id`)
);
INSERT INTO `main`.`sqlb_temp_table_16` SELECT `id`,`cdid`,`directory`,`filename`,`filesize`,`fileallocation`,`uid`,`fileattributes`,`filecreated`,`filemodified`,`fileexpired`,`filebackup`,`fileowner`,`fileprotection`,`filedescription` FROM `main`.`FILEs`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `main`.`FILEs`;
ALTER TABLE `main`.`sqlb_temp_table_16` RENAME TO `FILEs`
PRAGMA defer_foreign_keys = "0";
CREATE INDEX `cdfilerefididx` ON `FILEs` (
	`cdid`
);
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM `main`.sqlite_master;
SELECT `_rowid_`,* FROM `main`.`FILEs` ORDER BY `_rowid_` ASC LIMIT 0, 49999;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `main`.`FILEs` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `main`.`FILEs` ORDER BY `_rowid_` ASC LIMIT 0, 49999;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `main`.`FILEs` ORDER BY `_rowid_` ASC);
````

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version:_ 10 pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2018-06-23 11:40
> After a while, the GUI noticed that my mouse wasn't over the dropdown anymore, and decided that I changed my mind, and closed the dropdown on Integer - starting another copy. [...]

Wow, this is definitely one of the more crappy ways things could go wrong with the UI.  Sorry for that. :frowning_face:

**Comment by MKleusberg** [comment] 2018-10-22 21:20
I'm working on this now. See PR #1589 for updates.

**Comment by justinclift** [comment] 2018-12-20 23:50
@tlhackque Any interest in testing our more recent nightly builds?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

In theory, this should be improved now (well, about a month ago). :smile:

**Comment by gozzoo** [comment] 2019-02-12 20:32
@tlhackque I tested #1734, which I think is a duplicate of this one and it seems to be working fine. If there aren't any remaining concerns it would be nice if this fix makes it into 3.11.1

**Comment by MKleusberg** [comment] 2019-02-13 17:08
This is one of the changes which require a bit more testing because it a) is changing lots of code and b) can easily lead to data loss when something goes wrong. I guess it depends on how long it takes to release 3.11.1 whether we feel safe enough to include it in there or whether we wait for 3.12.0.

**Comment by justinclift** [comment] 2019-02-14 01:02
> I guess it depends on how long it takes to release 3.11.1

We seem to have solved all of the initial bugs reported in 3.11.0, with the exception of 1595.  When that one's solved, we should probably release right away. :wink:

**Comment by MKleusberg** [comment] 2019-02-15 18:16
Considering that #1686 isn't solved yet and we had some other issues with the new alter table code, I guess this won't make it into 3.11.1 then. But you can always use the nightly builds if you need this feature :smile:

**Comment by MKleusberg** [comment] 2020-02-12 22:31
I'm closing this issue because the original problem has been solved and was reported to be working fine :smile: It's going to be in the 3.12.0 release which hopefully is ready soon enough :wink:

**Closed by MKleusberg** 2020-02-12 22:31 UTC
Labels: enhancement
