### ISSUE TITLE
The app crashes on startup if no internet connection is present

### ISSUE THREAD

**Issue by dan-unimelb** [sqlitebrowser/sqlitebrowser#1380] opened 2018-05-08 11:38 UTC
### Details for the issue

I was offline (but a particular kind of offline, the laptop was connected to one of these free WiFi networks, but the login page of the network did not work, so while I had no internet access, there was a WiFi network active - which may or may not be relevant) and I tried to start the app up, first by double clicking on an sqlite database file, then by simply starting it from the start menu.

In both scenarios, the main window was first displayed, then an error box appeared saying that it cannot get to some web URL (maybe to check for new versions?) and then upon clicking that error box away, the app crashed. 

Cheers

#### I'm opening this issue because:

- [x ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by dan-unimelb** [comment] 2018-05-08 11:39
The search for another issue was pretty frugal, sorry

**Comment by karim** [comment] 2018-05-08 12:14
This was mentioned before in #1311 and #1335 and unfortunately I am unable to reproduce the crash. I get the error (which is normal) if I have no internet connection and automatically checking for updates is enabled (the default). I'm also using v3.10.1 (on Win 7).

Have you tried the latest nightly build? You can find it here https://nightlies.sqlitebrowser.org/latest/

If it is still crashing, a possible workaround is to disable the new version check at startup as mentioned in #1335 by @chrisjlocke

**Comment by justinclift** [comment] 2018-05-08 12:14
Hey @dan-unimelb.  Take a look at #1335.

That should have all the info in it you need to get it working ok. In short, the automatic "is there a new version to tell the user about?" check needs to be disables.  Instructions are in that issue. :smile:

**Comment by chrisjlocke** [comment] 2018-05-08 12:47
Just a nod that the crash will still be present in the nightly, so the registry tweak will be your best option.  😺

**Comment by mgrojo** [comment] 2018-05-08 18:58
Let's continue the discussion in #1311 so there is no more scattered information, ok? I'll close this as duplicate. It's frustrating that so many people appear to have this problem and we are unable to reproduce it :confused:

**Closed by mgrojo** 2018-05-08 18:58 UTC
Labels: duplicate

**Comment by justinclift** [comment] 2018-05-21 11:14
@dan-unimelb Just to double check, did the workarounds in #1311 / #1335 get things working for you? :smile:

**Comment by chrisjlocke** [comment] 2018-05-21 13:17
> It's frustrating that so many people appear to have this problem and we are unable to reproduce it

I can reproduce it.
