### ISSUE TITLE
modify table dialog - adding a foreign key constraint

### ISSUE THREAD

**Issue by MattBorchers** [sqlitebrowser/sqlitebrowser#2629] opened 2021-03-14 06:04 UTC
Details for the issue
--------------------

#### What did you do?
I added a few tables and wanted to create a foreign key constraint from one table to another.
1. I click on the "Constraints" tab to show the constraints.
2. I choose 'Foreign Key' from 'Add constraint' drop-down list.
3. I choose the column of the table that will be the foreign key.
4. I do not name the constraint.

#### What did you expect to see?
5. There is no input column to specify the foreign table and column for this constraint definition.

#### What did you see instead?
In the SQL statement at the bottom of the dialog the syntax for the foreign key is incorrect:

  FOREIGN KEY("colname") REFERENCES

If I create the table using the "Execute SQL" tab and create the foreign key there, then when I come back to this dialog the SQL syntax to create the table shows correctly:

 FOREIGN KEY("colname") REFERENCES "foreign_table"("foreign_colname")

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

**Comment by chrisjlocke** [comment] 2021-03-14 08:50
Indeed.  I believe this dialog is a new one, and the developer who instigated it was seeking feedback to continue.
See this issue: https://github.com/sqlitebrowser/sqlitebrowser/issues/2444

In the meantime, you can use the 'Modify Table' dialog to create foreign key constraints.  You have to click in the textbox and press Enter to 'save' it, and double-clicking the row is a bit unintuitive, which is why the new dialog was created.

https://user-images.githubusercontent.com/7872218/111062619-e0bcc200-84a1-11eb-9232-250052ba5c40.mp4

I'll close this issue, as it's a duplicate of #2444, and I would recommend subscribing to that issue to receive updates on its progress.  Please bear with the developer during this time.

**Closed by chrisjlocke** 2021-03-14 08:50 UTC
