### ISSUE TITLE
crash on unique constraint

### ISSUE THREAD

**Issue by cederom** [sqlitebrowser/sqlitebrowser#488] opened 2016-01-10 12:43 UTC
Application crashed after I have entered id field that was already taken, then warning popped up, I pressen Esc, and application crashed.
<img width="1003" alt="screen shot 2016-01-10 at 13 44 05" src="https://cloud.githubusercontent.com/assets/3051832/12221568/1e2aebd2-b7a0-11e5-933b-0d20966c847a.png">
<img width="429" alt="screen shot 2016-01-10 at 13 44 57" src="https://cloud.githubusercontent.com/assets/3051832/12221569/1e2f98ee-b7a0-11e5-8706-2010d717cdc9.png">

**Comment by justinclift** [comment] 2016-01-10 14:58
Hmmm, that's not good.  Crashing is definitely not the correct behaviour there. :wink:

**Comment by MKleusberg** [comment] 2016-01-27 21:33
Can't reproduce this :frowning: Can you provide any extra information on this?

**Comment by cederom** [comment] 2016-01-27 21:40
That did not happen every time, randomly.. but also I got database corruption very very often.

Does OSX package depends on any external libraries or everything is included? Maybe there is a conflict with MacPorts packages/libraries?

**Comment by justinclift** [comment] 2016-01-28 11:44
On OSX, we include the needed external libraries in the .app bundle.  The app bundle is created simply using macdeployqt though, which may or may not be fantastic.  It's possible there's a conflict with installed MacPorts packages/libraries. :frowning: 

@cederom If you compile DB4S yourself (it's extremely easy), do the problems still happen?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

**Comment by lech** [comment] 2016-02-21 02:31
Getting this on Windows 7 as well. A reliable way to reproduce this would be to create a database with the following without using the wizard. Just go straight to SQL input.

```SQL
CREATE TABLE `SOME_names` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`username`	TEXT UNIQUE
);
```

Then add a few records:

```SQL
INSERT INTO SOME_names (username) VALUES
('Billybob'),
('SuzyQ'),
('Janey');
```

Now using the Add Record button for that table, try to input 'SuzyQ' again. It will throw an error detecting that SuzyQ already exists, but once you click 'OK' and head back to the main app it crashes and burns.

**Comment by justinclift** [comment] 2016-02-22 20:48
Thanks @lech that's really useful info.  Should help the guys debug this reasonably quickly, once they get the time. :smile:

**Comment by lech** [comment] 2016-02-22 22:01
No problem @justinclift, the only thing with crashing it on Win7 is that it doesn't generate a crash report for you guys. If it does, I don't know where to look for it.

**Comment by justinclift** [comment] 2016-02-22 23:26
Yeah, I don't think crash reports are going to help us at this stage. :frowning:

**Comment by AndrewADev** [comment] 2016-04-23 16:20
Able to verify on both Win 10 and OS X 10.10, but only for the most recent release version (3.8.0), and not for the nightly build from Apr-23-2016. It seems to have been fixed in the meantime.

I used the examples by Lech above to verify. The only way I could get it to reproduce was to press enter after adding an already existing row. Warning dialog appeared and could be closed normally, if simply clicking elsewhere (outside of cell being edited) to remove focus and end editing. 

The 3.8.0 version seems to be popping up a new window "Edit database cell" for detailed editing a lot more often than the nightly (Can't tell if maybe every time I end edit with enter?) If that might may have been/might be relevant? Adding a duplicate row from the detailed edit window doesn't seem to cause the crash either.

Nice app, btw :)

**Comment by justinclift** [comment] 2016-04-23 17:28
Cool, thanks for checking Andrew. :smile:

**Comment by MKleusberg** [comment] 2016-04-24 13:07
Thank you all for the combined debugging effort, @cederom, @lech and @AndrewADev :+1: 
I think I managed to reproduce this. The problem occurs in version 3.8.0 when following the instruction provided by Lech. However, you must have the ```View -> Edit cell``` option activated, otherwise the application wouldn't crash.

But as Andrew said, this bug seems to be fixed in the current master. So, as the initial reporter, would you be able to try out the latest nightly build and check if the error is fixed for you, @cederom? For download locations check the main page of our repository :smiley: 
The annoying opening of the Edit database cell window mentioned by @AndrewADev should be fixed, too, in the latest nightly build.

**Comment by justinclift** [comment] 2016-08-02 15:56
Closing this, as it's apparently fixed and we've not heard back.

**Closed by justinclift** 2016-08-02 15:56 UTC
Labels: bug, crash, osx, response requested

**Comment by cederom** [comment] 2016-08-02 16:02
TANK U 👍

**Comment by justinclift** [comment] 2016-08-02 16:27
You're welcome. :smile:

**Comment by lech** [comment] 2016-08-11 03:48
Sorry for the late response, I just tested my example against a 3.8.99 nightly under Windows 10 Pro and it appears to be behaving itself fresh out of the box.  :+1:  Thanks!

Also thanks to @MKleusberg with a work-around for 3.8.0 until the next stable version is available. :smiley:

**Comment by justinclift** [comment] 2016-08-11 11:18
Awesome @lech, that's for trying it out and letting us know. :smile:
