### ISSUE TITLE
File->Open Project opens the same project

### ISSUE THREAD

**Issue by rafalseamless** [sqlitebrowser/sqlitebrowser#404] opened 2015-08-21 14:08 UTC
When select File->Open Project opens the same project - not the one selected.
OS: Windows 8

sqlitebrowser:
Version 3.7.0
Qt Version 5.4.1
SQLite Version 3.8.10.2

**Comment by justinclift** [comment] 2015-08-22 18:23
Oh, that's strange.

**Comment by MKleusberg** [comment] 2015-08-25 21:11
Unfortunately I can't reproduce this. Can you maybe provide some step by step instructions on how to trigger that error?

**Comment by rafalseamless** [comment] 2015-08-26 07:05
Am very sorry I wasted your time - my mistake. I was about to report a new
issue, but again, could be my mistake - when try to load sqlite module see
error loading extension the same as
https://github.com/sqlitebrowser/sqlitebrowser/issues/267

No errors when do it from sqlite command line.
In the attachment is the module I want to load.

2015-08-25 23:12 GMT+02:00 Martin Kleusberg <notifications@github.com>:

> Unfortunately I can't reproduce this. Can you maybe provide some step by
> step instructions on how to trigger that error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/404#issuecomment-134743299>
> .
>



-- 
Rafal Roman
 | Integration Engineer
rafal@seamlessmedical.com


*SEAMLESS MEDICAL SYSTEMS*
seamlessmedical.com

*The information contained in this electronic e-mail transmission and
any attachments are intended only for the use of the individual or entity
to whom or to which it is addressed, and may contain information that
is privileged, confidential and exempt from disclosure under applicable
law. If the reader of this communication is not the intended recipient, or
the employee or agent responsible for delivering this communication to
the intended recipient, you are hereby notified that any dissemination,
distribution, copying or disclosure of this communication and
any attachment is strictly prohibited. If you have received this
transmission in error, please **do not forward this communication to any
third party but do notify **the sender immediately by telephone
and electronic mail, and delete the original communication and any
attachment from any computer, server or other electronic recording
or storage device or medium. Receipt by anyone other than the intended
recipient is not a waiver of any attorney-client, physician-patient or
other privilege.*

**Comment by justinclift** [comment] 2015-08-27 20:23
Sorry @rafalseamless, just noticed this (I'm focused on other stuff atm).  With GitHub, it drops attachments, so your attachment never made it to this issue.

If you want to email it to me (justin@postgresql.org), I can forward it to the other developers for investigation.

**Comment by mgrojo** [comment] 2018-08-24 16:34
What is the state of this issue? Can be closed or is the last error reported something that should be investigated?

**Comment by mgrojo** [comment] 2018-10-05 17:40
@rafalseamless, the later problem that you reported seems to be already analysed in #1290 and #267. So I'll close this as redundant. If you think we've closed this too early, you are free to reopen it again.

**Closed by mgrojo** 2018-10-05 17:40 UTC
Labels: bug, response requested
