### ISSUE TITLE
hyperlinks

### ISSUE THREAD

**Issue by dalcolmo** [sqlitebrowser/sqlitebrowser#2249] opened 2020-05-16 18:05 UTC
It would be great if text representing a hyperlink would also act as a hyperlink, when clicking on it. In particular, I use sqlite often to collect metadata about lots and lots of files on the local hard drive, and it would be great to be able to open the file by clicking on the hyperlink to the filename.
Relative locations should be supported, though, so the database can be shared between people who might not have the files in the same absolute place, but in the same place relative to the database.
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
Well, most programs nowadays have these features, starting with any browser.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No

**Comment by mgrojo** [comment] 2020-05-16 22:05
This is implemented in our [nightly builds](https://nightlies.sqlitebrowser.org/latest/) and in the [3.12 alpha release](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.12.0-alpha1). Take a look to #1597. I'm going to close  this as it is duplicate of that issue. Please, if you have any problem or comment to provide, please place it in the original issue, so the information is not scattered.

**Closed by mgrojo** 2020-05-16 22:05 UTC
