### ISSUE TITLE
Foreign Key constraint with multiple columns is ignored

### ISSUE THREAD

**Issue by OmarWKH** [sqlitebrowser/sqlitebrowser#558] opened 2016-04-08 12:33 UTC
According to [SQLite documentation](https://www.sqlite.org/syntax/table-constraint.html), a foreign key constraint could include multiple columns separated by  a ','.

If I execute:
```
CREATE TABLE to_reference_multi
(
  id1 INTEGER NOT NULL,
  id2 INTEGER NOT NULL,
  CONSTRAINT Identifier1 PRIMARY KEY (id1, id2)
);

CREATE TABLE to_reference_single
(
  single_id INTEGER NOT NULL,
  CONSTRAINT Identifier1 PRIMARY KEY (single_id)
);

CREATE TABLE test_reference
(
  id1 INTEGER NOT NULL,
  id2 INTEGER NOT NULL,
  id3 INTEGER NOT NULL,
  CONSTRAINT Identifier1 PRIMARY KEY (id1, id2, id3),
  CONSTRAINT fk_multi FOREIGN KEY (id1, id2) REFERENCES to_reference_multi (id1, id2),
  CONSTRAINT fk_single FOREIGN KEY (id3) REFERENCES to_reference_single (single_id)
);
```

The resulting test_reference table ignores fk_multi and looks like:
```
CREATE TABLE `test_reference` (
	`id1`	INTEGER NOT NULL,
	`id2`	INTEGER NOT NULL,
	`id3`	INTEGER NOT NULL,
	PRIMARY KEY(id1,id2,id3),
	FOREIGN KEY(`id3`) REFERENCES `to_reference_single`(`single_id`)
);
```

**Comment by justinclift** [comment] 2016-04-08 12:43
Yeah, foreign key constraints definitely need some work at the moment.  You're not alone in finding bugs with that part of things. :wink:

**Comment by MKleusberg** [comment] 2016-08-18 21:20
This should be fixed in the next nightly build. Do you have the time to try that build and confirm if it's working better for you, @OmarWKH ? :smiley: 
There's still a bit of work to do, like adding/editing/removing multi-column foreign keys and key names but at least foreign key with multiple columns aren't ignored anymore.

**Comment by OmarWKH** [comment] 2016-08-19 02:04
I can confirm FKs with multiple columns aren't completely ignored anymore. However, adding two FK constraints with multiple columns leads to only one mixed constraint.
I downloaded the nightly build from sqlitebrowser.oldsch00l.com and executed the same commands in the original post.
<details>
<summary>The resulting test_reference table confirms that one constraint isn't ignored:</summary>
```sql
CREATE TABLE `test_reference` (
	`id1`	INTEGER NOT NULL,
	`id2`	INTEGER NOT NULL,
	`id3`	INTEGER NOT NULL,
	PRIMARY KEY(`id1`,`id2`,`id3`),
	FOREIGN KEY(`id3`) REFERENCES `to_reference_single`(`single_id`),
	FOREIGN KEY(`id1`,`id2`) REFERENCES `to_reference_multi`(`id1`,`id2`)
);
```
</details>
<details>
<summary>To test two FK constraints with multiple columns I executed:</summary>
```sql
CREATE TABLE table1
(
  id1 INTEGER NOT NULL,
  id2 INTEGER NOT NULL,
  CONSTRAINT Identifier1 PRIMARY KEY (id1, id2)
);

CREATE TABLE table2
(
  id3 INTEGER NOT NULL,
  id4 INTEGER NOT NULL,
  CONSTRAINT Identifier1 PRIMARY KEY (id3, id4)
);

CREATE TABLE test_reference
(
  id1 INTEGER NOT NULL,
  id2 INTEGER NOT NULL,
  id3 INTEGER NOT NULL,
  id4 INTEGER NOT NULL,
  CONSTRAINT Identifier1 PRIMARY KEY (id1, id2, id3),
  CONSTRAINT fk_multi1 FOREIGN KEY (id1, id2) REFERENCES table1 (id1, id2),
  CONSTRAINT fk_multi2 FOREIGN KEY (id3, id4) REFERENCES table2 (id3, id4)
);
```
</details>
<details>
<summary>Resulting in a test_reference table with one mixed FK constraint as follows:</summary>
```sql
CREATE TABLE `test_reference` (
	`id1`	INTEGER NOT NULL,
	`id2`	INTEGER NOT NULL,
	`id3`	INTEGER NOT NULL,
	`id4`	INTEGER NOT NULL,
	PRIMARY KEY(`id1`,`id2`,`id3`),
	FOREIGN KEY(`id1`,`id2`) REFERENCES `table2`(`id3`,`id4`)
);
```
</details>
Of course, the rules aren't enforced unless I enable foreign keys. That's the expected behavior according to [sqlite documentation](https://www.sqlite.org/foreignkeys.html#fk_enable) but a warning message might be useful.

**Comment by justinclift** [comment] 2016-08-19 10:26
Thanks @OmarWKH, looks like more stuff still needs to be done for this. :smile:

As a side note, those `<detail>` and `<summary>` tags collapse nicely in your post.  Hadn't seen that before.  Definitely going to copy for future use. 😁

**Comment by MKleusberg** [comment] 2016-08-19 10:40
Hmm, I'm having difficulties reproducing this. I've created a new database using the SQL posted under ```To test two FK constraints with multiple columns I executed``` but get
```sql
CREATE TABLE `test_reference` (
	`id1`	INTEGER NOT NULL,
	`id2`	INTEGER NOT NULL,
	`id3`	INTEGER NOT NULL,
	`id4`	INTEGER NOT NULL,
	PRIMARY KEY(`id1`,`id2`,`id3`),
	FOREIGN KEY(`id1`,`id2`) REFERENCES `table1`(`id1`,`id2`),
	FOREIGN KEY(`id3`,`id4`) REFERENCES `table2`(`id3`,`id4`)
);
```
So both foreign keys appear and aren't mixed.

@justinclift Can you maybe build a once-off using Qt5? Just to check it's not a Qt version thing? The fact that I needed to add 91615f940f109d0f20f9a8fe19599f4268ea3d40 makes me a bit suspicious here.

**Comment by justinclift** [comment] 2016-08-19 10:47
Yep, can definitely create a once-off Qt5 build with this in it.  No hassle at all.

@OmarWKH Which OS are you using? (if Windows, is it 32 or 64 bit?)

**Comment by OmarWKH** [comment] 2016-08-19 18:37
Windows 10 Home 64-bit - Version 1511 - Build 10586.545
sqlitebrowser version 3.9.99 - Qt version 4.8.7 - sqlite version 3.13.0

**Comment by justinclift** [comment] 2016-08-19 18:39
@OmarWKH Thanks. :smile:

@MKleusberg Should I build this with just https://github.com/sqlitebrowser/sqlitebrowser/commit/6a4d58042c8f808498aafc5fae215aae6a010d07, or add the new foreign key stuff you've been adding today too?

**Comment by MKleusberg** [comment] 2016-08-20 19:43
Maybe include d98338ce89089755aef305f8c04ce22ac2509ee9, too. It does change a lot but it's good to get this tested :wink:

**Comment by justinclift** [comment] 2016-08-28 10:41
@OmarWKH Sorry for the delay here.  Got caught up in other stuff. 😦 

@MKleusberg Getting back around to this again.  Should a Qt5 build using master HEAD be ok?

**Comment by MKleusberg** [comment] 2016-08-29 09:24
@justinclift Yes, should be ok.

**Comment by justinclift** [comment] 2016-08-29 15:27
@OmarWKH Would you have a few minutes to try out this build?

* http://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-201608291559-win64.exe

It's our latest development code, with @MKleusberg's fixes in it.  In theory, it should be better for you now, but it's always good to check. :wink:

**Comment by OmarWKH** [comment] 2016-08-29 16:02
It works! :smile:
Output for multiple FK constraints is as expected (I also tested a single constraint and it still works fine).
```sql
CREATE TABLE `test_reference` (
	`id1`	INTEGER NOT NULL,
	`id2`	INTEGER NOT NULL,
	`id3`	INTEGER NOT NULL,
	`id4`	INTEGER NOT NULL,
	PRIMARY KEY(`id1`,`id2`,`id3`),
	CONSTRAINT `fk_multi2` FOREIGN KEY(`id3`,`id4`) REFERENCES `table2`(`id3`,`id4`),
	CONSTRAINT `fk_multi1` FOREIGN KEY(`id1`,`id2`) REFERENCES `table1`(`id1`,`id2`)
);
```

**Comment by justinclift** [comment] 2016-08-29 19:49
Awesome @OmarWKH, that's really good news. :smile:

I'll close this Issue now, as that build will remain online for people to use, and our next release will have this included also. :smile:

**Closed by justinclift** 2016-08-29 19:49 UTC
Labels: bug, constraints & foreign keys, response requested
