### ISSUE TITLE
Modify Table - Autoincrement doesn't update the table

### ISSUE THREAD

**Issue by cristilupascu** [sqlitebrowser/sqlitebrowser#2495] opened 2020-11-30 23:59 UTC
Details for the issue
--------------------

Hi,

This doesn't seem to be a big issue, but I just thought I should mention it in case people are not aware of it.

#### What did you do?
1. Create a table with a primary key and without auto-increment.
2. After the table is created, modify the table and turn on auto-increment and click Ok.

#### What did you expect to see?
The field should now be in auto-increment mode, but if you exit sqlitebrowser and open the database again, you can see that the field's autoincrement is turned off again.

There should also be a sqlite_sequence table, if the change actually worked.

At the moment, in order to get the auto-increment change to stick, I have to add a new dummy field, click Ok, and then go back and delete the dummy field.

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

**Comment by justinclift** [comment] 2020-12-01 02:55
Thanks, that definitely sounds like a bug. :wink:

**Comment by chrisjlocke** [comment] 2020-12-01 07:15
This is a duplicate of #2070.  If you click the 'Unique' option (the U column) then that should trigger the change.  DB4S just isn't spotting you have clicked the AI option.  Or something.

**Closed** 2020-12-01 07:15 UTC
Labels: bug
