### ISSUE TITLE
Minor bug - Toolbar visible state needs syncing at app start

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#664] opened 2016-07-21 11:18 UTC
Noticed a trivial bug.  The DB Toolbar (now easily toggle-able with Ctrl-T (Cmd-T on OSX)) keeps it's visible/hidden state saved across sessions.

That's a good thing.

Unfortunately, the Ctrl-T toggle isn't starting out synced to that, so sometimes just after starting the Ctrl-T has no effect for the first keystroke to two.

Should be a simple fix. :smile:

**Comment by innermous** [comment] 2016-07-21 12:33
For me it doesn't have Ctrl-T shortcut at all :worried:

**Comment by justinclift** [comment] 2016-07-21 12:37
Hmmm, that should have been added in https://github.com/sqlitebrowser/sqlitebrowser/commit/4d64951d378228a09e6fc2de13f4b99b19d99533. 😦 

It's working on OSX, though I haven't tried Windows with it yet either.  Maybe there's different key than Ctrl for your window manager?

**Comment by innermous** [comment] 2016-07-21 12:38
@justinclift what about issue I addressed in previous comment?

**Comment by justinclift** [comment] 2016-07-21 12:41
@innermous Heh Heh Heh, I thought that's what I was addressing. 😬 

Looking at the docs here, it seems Ctrl-T is also called "AddTab":

&nbsp; &nbsp; https://doc.qt.io/qt-5/qkeysequence.html#standard-shortcuts

Maybe it needs to be bound using that instead?

**Comment by innermous** [comment] 2016-07-21 12:43
>
1. Toggle "DB toolbar" to false state.
2. Close app
3. Load app
4. Toolbar is hidden, but checkbox is in true state. 

Can you try to reproduce this?

**Comment by justinclift** [comment] 2016-07-21 12:46
Yep, that's definitely reproducible.

**Comment by innermous** [comment] 2016-07-21 12:47
@justinclift maybe that's the reason why two extra Ctrl+T pressed are needed(pressing checkbox manually in my case)?
Cause when u hide toolbar and reload app, you first need to toggle that checkbox to false state(regardless toolbar is already hidden) and only then try to display it

**Comment by justinclift** [comment] 2016-07-21 12:53
Yeah, I'll investigate it properly in the next few hours. :smile:

**Comment by justinclift** [comment] 2016-07-21 12:55
@innermous Btw, any thoughts on https://github.com/sqlitebrowser/sqlitebrowser/pull/663#issuecomment-234048290 ?

**Comment by innermous** [comment] 2016-07-21 13:30
I still don't have Ctrl+T shortcut you are talking about :anguished:

**Closed** 2016-07-21 13:29 UTC
Labels: bug

**Comment by justinclift** [comment] 2016-07-21 13:31
Is that on KDE, Gnome, or something else?

**Comment by innermous** [comment] 2016-07-21 13:32
It's awesome wm.
I'll investigate the cause of a problem and will let you know.

**Comment by justinclift** [comment] 2016-07-21 13:33
Thanks @innermous.  That'll save me having to make a new VM just to investigate. 😁
