### ISSUE TITLE
Preferences mangled

### ISSUE THREAD

**Issue by thomaskilian** [sqlitebrowser/sqlitebrowser#926] opened 2017-01-09 14:10 UTC
### Details for the issue

Since today the preferences mangles colors

![pic20170109150007](https://cloud.githubusercontent.com/assets/69296/21768975/a9509a58-d67c-11e6-95e2-04018f58b5e0.png)

Obviously a change of the font was the culprit. Here is the mangled preferences file:

[com.sqlitebrowser.sqlitebrowser.plist.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/693644/com.sqlitebrowser.sqlitebrowser.plist.zip)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: 10.12.2 (16C67) 
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment] 2017-01-09 14:29
This is a duplicate of #737. The latest nightlies should fix it.

**Closed by revolter** 2017-01-09 14:29 UTC

**Comment by thomaskilian** [comment] 2017-01-09 14:51
Hmm. The link https://nightlies.sqlitebrowser.org/osx/ has mid last year as latest new build. And `brew cask install sqlitebrowser` fails with 

> Downloading https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.9.1/DB.Browser.for.SQLite-3.9.1.dmg
>
> curl: (22) The requested URL returned error: 404 Not Found

**Comment by revolter** [comment] 2017-01-09 15:25
No, there is:

> DB Browser for SQLite-sqlcipher_20170109.dmg       09-Jan-2017 04:10

**Comment by revolter** [comment] 2017-01-09 15:28
About the `cask` issue, the release's attachment name was renamed to `DB.Browser.for.SQLite-3.9.1v2.dmg`. @justinclift, Any idea how can we update the cask's url?

**Comment by thomaskilian** [comment] 2017-01-09 15:29
Are my aged eyes that bad?

![pic20170109162812](https://cloud.githubusercontent.com/assets/69296/21771704/ca3dfdee-d688-11e6-91dc-a6d95a24c54a.png)

**Comment by revolter** [comment] 2017-01-09 15:31
![screen shot 2017-01-09 at 17 31 38](https://cloud.githubusercontent.com/assets/5748627/21771796/7f3be35c-d691-11e6-91aa-ec357ad2720e.png)

**Comment by thomaskilian** [comment] 2017-01-09 15:32
Argh. Would be good to that on top :-/

**Comment by revolter** [comment] 2017-01-09 15:37
@justinclift Can you change the ordering of that please? 😄

**Comment by revolter** [comment] 2017-01-09 15:38
As for the curl error, try running `brew cask update`.

**Comment by thomaskilian** [comment] 2017-01-09 16:56
That solved it. Also the nightly build worked. Thanks!

**Comment by justinclift** [comment] 2017-01-09 19:46
@revolter The ordering is coming from Nginx... seems standard alphabetical.

I guess we can look into Nginx options and see if that can be changed. :smile:

**Comment by revolter** [comment] 2017-01-09 19:53
https://github.com/aperezdc/ngx-fancyindex this looks marvelous!

**Comment by justinclift** [comment] 2017-01-09 20:11
@revolter No worries.  Want an account on the nightlies server, so you can get that done? :smile:
