### ISSUE TITLE
Feature Request: progress indicator and cancel button for long operations

### ISSUE THREAD

**Issue by AndrewSav** [sqlitebrowser/sqlitebrowser#161] opened 2014-11-25 22:43 UTC
This Feature request comes along issues #114 and #107.

It would be nice if there would be a progress indicator when opening big databases or exporting big tables. `Cancel` button also will be welcome. Currently application freezes and becomes unresponsive until the operation ends. And you keep wondering if it's frozen for good or it's still alive and doing something.

**Comment by justinclift** [comment] 2015-03-14 12:38
Thinking about this, I suspect the right way to do this is have a pop up dialog showing progress, something like this:

![progress bar 1](https://cloud.githubusercontent.com/assets/406299/6651687/f2e2822e-ca46-11e4-8485-f3ce09abffcb.png)

**Comment by AndrewSav** [comment] 2015-03-16 07:00
Looks good to me.

**Comment by Z4us** [comment] 2015-03-16 09:06
A pop up, Justin? There are people who hate them, even block them. Better is IMNSHO a menu item called Staus or Progress with lines for all (sub)processes that take longer than let's say two or three minutes.

**Comment by justinclift** [comment] 2015-03-16 14:48
@Z4us Ahhh, hadn't thought of that as it's not a browser.  But yeah, point taken. :smile:

So, maybe a status bar thing instead then...?

**Comment by Z4us** [comment] 2015-03-16 17:00
Right, some kewl animation if technically not too hard to develop :)

**Comment by justinclift** [comment] 2015-03-16 19:43
Qt provides a "progress bar" widget, so that's probably the thing to use for the display.

Collecting the info to use with it is likely harder.  For (say) as CSV import it would probably be something like:

* Do an initial row count for the input file.  This is so we can know how far we've progressed through the total file, during the import.
* Figure out how often to update the progress bar
 * Maybe figure out how wide the progress bar is in pixels (if way). Divide total rows / # pixels
 * If figuring out the # of pixels for the progress bar isn't easy, then go with a percentage approach instead.  eg Divide total row / 100
* Now run a loop to import the CSV data, updating the progress bar every x lines (as worked out in previous step), and checking for a press of the Cancel button

That's without error handling though, and I have no solid idea on the correct behaviour if the user hits the Cancel button (eg doesn't want to wait further).  Keep the data successfully imported so far?

**Comment by justinclift** [comment] 2017-09-20 15:31
@MKleusberg We have progress dialogs + cancel on all our long operations now don't we?

**Comment by mgrojo** [comment] 2018-10-04 21:15
I can confirm that the Import CSV dialog has a progress dialog with a cancel button. But unfortunately I pressed Cancel, the progress dialog closed, but the Import dialog is left frozen. I had to kill the application.

**Comment by MKleusberg** [comment] 2020-02-13 11:43
Closing this because (I believe) we have working cancel buttons for all long operations and progress dialogs for most of them. Just tested cancelling the import CSV dialog and it did work too :smile: If I'm missing anything, just re-open this issue :smile:

**Closed by MKleusberg** 2020-02-13 11:43 UTC
Labels: enhancement, response requested
