### ISSUE TITLE
"select" request, the returned values are not displayed

### ISSUE THREAD

**Issue by valbv** [sqlitebrowser/sqlitebrowser#1384] opened 2018-05-10 10:22 UTC
Details for the issue
--------------------

#### What did you do?

1) Create dataBase.
2) Copy SQL-script and perform it [testSqlScript.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/1991230/testSqlScript.txt)
3) Make a "select" request [testSelectRequest.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/1991232/testSelectRequest.txt)

#### What did you expect to see?
Values of requested fields

#### What did you see instead?
Nothing.

But if I
1) save dataBase
2) restart application and open database
3) make "select" request

all right, values of requested fields are displayed

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?
- [x] Windows: ( version: 10 )

#### What is your DB4S version?
- [x] 3.10.1

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment] 2018-05-10 11:00
Sorry if I do not fully understand the problem. Are you saying that SELECT query in `testSelectRequest.txt` file returns nothing **if** the database is **not** saved?

I just tested it now using the same version (3.10.1) but on Win 7 and it seems to be working.

![1384](https://user-images.githubusercontent.com/8761081/39866616-a79ed586-5451-11e8-90fa-e63e208790a0.jpg)

Can you show us a screenshot to help us understand the problem?

**Comment by valbv** [comment] 2018-05-10 12:01
Steps:
1) Create DB
2) Execute SQL-code from _testSqlScript.txt_
3) Save DB (Ctrl + S)
4) Execute SQL-code from _testSelectRequest.txt_

Result:
![1](https://user-images.githubusercontent.com/14193135/39868575-6cf0ebb2-5484-11e8-86cc-fa2ab2542bbd.png)

**Comment by karim** [comment] 2018-05-10 13:00
I see now the problem, thank you. :smiley: 

Yes, I got the same result as you posted in your screenshot. It happens when you reuse the same SQL tab. If you paste the query from `testSqlScript.txt` in the first tab (SQL 1) then reused the same tab to run the SELECT query in `testSelectRequest.txt` then you get the same result.

I don't know how this happened. I'm going to label this as a bug and hopefully someone can provide an answer.

**Comment by chrisjlocke** [comment] 2018-05-10 13:05
That is odd - even if you use 'old' tabs, it works fine - but reuse that one tab, and yes, no results, even though it says it found 5 records.  Even if you change the SQL, it still doesn't create the rows....

**Comment by mgrojo** [comment] 2018-05-10 22:28
This is what I have discovered so far. The problem is exclusively on this pragma:
```sql
 pragma foreign_keys = on;
```
Execute it on any tab to break it.

This is the responsible code. Removing it eliminates *this* problem:

```c++
            // SQLite returns SQLITE_DONE when a valid SELECT statement was executed but returned no results. To run into the branch that updates
            // the status message and the table view anyway manipulate the status value here. This is also done for PRAGMA statements as they (sometimes)
            // return rows just like SELECT statements, too.
            if((query_part_type == SelectStatement || query_part_type == PragmaStatement) && sql3status == SQLITE_DONE)
                sql3status = SQLITE_ROW;
```

I' ll try to follow, unless someone has it already clear.

**Comment by mgrojo** [comment] 2018-06-10 07:42
@valbv I'm no longer able to reproduce this problem using the current code. This might have been a concurrency problem that it is now fixed by the changes done for PR #1394.

Please try with a nightly build and confirm that it is also solved for you, so we can close this issue.
https://nightlies.sqlitebrowser.org/latest/

**Comment by QweEwq2016** [comment] 2018-06-11 13:55
I'm try reproduce this bug, in the newest master branch and can't it. Maybe fixed?

**Comment by justinclift** [comment] 2018-06-11 14:22
Yeah, it's definitely possible.  We've changed a lot of stuff, and done many bug fixes since the last major release.

**Comment by valbv** [comment] 2018-06-12 06:31
Yes, thanks!

**Comment by justinclift** [comment] 2018-06-12 08:02
@valbv That's a little bit unclear (to me).  Are you meaning the problem is fixed in our nightly builds, so we should close this issue? :smile:

**Comment by valbv** [comment] 2018-06-26 05:38
Problem fixed in nightly builds ;)

**Comment by justinclift** [comment] 2018-06-26 07:30
Awesome, thanks for confirming @valbv. :smile:

**Closed by justinclift** 2018-06-26 07:30 UTC
Labels: bug, response requested
