### ISSUE TITLE
Unable to modify table in DB Browser for SQLite

### ISSUE THREAD

**Issue by s1170363** [sqlitebrowser/sqlitebrowser#3272] opened 2023-02-09 11:27 UTC
Details for the issue
--------------------

#### What did you do?
I installed DB Browser and wanted to modify the table. The first time I tried it, it worked flawlessly. The second time round, the option 'modify table' was not available (it was there but I could not click on it) in the 'edit' tab in the top-right corner of my screen.

#### What did you expect to see?
I expected to see the 'modify table' option to be available. And when right-clicking the table I wanted to modify, I was expecting to see the  'modify table' option.

#### What did you see instead?
The 'modify table' option could not be selected when using the 'edit' tab in the top right corner of my screen. Also, when I right-clicked my table that I wanted to modify, I did not see the 'modify table' option, only the 'Browse Table' option.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.22621) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment] 2023-02-09 20:21
I use 3.12.2 on Windows a lot of the time, but not seen this behaviour.  I have a vague memory of another issue resembling this, and I think it was because the table wasn't selected.  The options are only available once a table is selected.

If it occurs again (or the steps are reproducable) please document what those steps are, and please provide a screenshot.  Images can be posted directly into this issue (ie, without hosting them somewhere).

**Comment by chrisjlocke** [comment] 2023-03-20 11:35
I'll close this as it's not been responded to.
@s1170363 - feel free to comment and it can be reopened.

**Closed by chrisjlocke** 2023-03-20 11:35 UTC
