### ISSUE TITLE
SQL doesn't get saved or reminded on project exit

### ISSUE THREAD

**Issue by DaleEMoore** [sqlitebrowser/sqlitebrowser#1386] opened 2018-05-11 14:01 UTC
### Details for the issue

Opened a recent project.
Changed the SQL.
Exited the program.
No prompt for "Save your stupid changes?"
Lost all that work.
Sure would like it if it helped me more with my stupidity!

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [x] 3.9.1 (Why doesn't this bug generator build the correct version?
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment] 2018-05-11 14:39
Oh good point.  That sounds like a good idea. :smile:

Btw, what does "Why doesn't this bug generator build the correct version?" mean?

**Comment by DaleEMoore** [comment] 2018-05-11 15:27
Thanks @justinclift and @chrisjlocke for your questions, thoughts and responses!

My workstation installation of "DB Browser for SQLite" knows its own version which I can get by going to menu item Help, About. So when I select the menu item Help, Bug report and it creates a new bug report at https://github.com/sqlitebrowser/sqlitebrowser/issues/new; I would like the new bug report to contain the version of "DB Browser for SQLite" that's invoked it. Hopefully it would fill in all the appropriate versions:

    Version 3.9.1
    Qt Version 5.6.1
    SQLite Version 3.15.2
    Ubuntu 17.10 (available in /etc/issue)

Thanks for all your hard work!

**Comment by justinclift** [comment] 2018-05-11 18:10
That's a good idea too.  Shouldn't be too hard for us to figure out the right field names to embed in the link to the new issue page.

**Comment by justinclift** [comment] 2018-05-11 18:14
Actually... that might be tricky after all.  The server side isn't doing anything with values it receives, so there's no chance of the GitHub server populating fields.

To get this working, we'd likely need DB4S to fully populate the entire bug report field as that's the only way I'm thinking of we could automatically include the info.  It'd probably take a bunch of effort, and only give a mediocre result. **\*sigh\***

**Comment by DaleEMoore** [comment] 2018-05-11 19:30
Thanks tons for sharing!

Wouldn't it be nice if GitHub allowed something smarter there, then y'all
(and others) could implement much smarter ISSUE ADD routines. I wonder how
I could whine about that?

**Comment by justinclift** [comment] 2018-05-11 19:45
Hmmm, GitHub do have a contact form:

&nbsp; &nbsp; https://github.com/contact

I've used it occasionally, and they've always gotten back to me.  So it's worth a shot. :smile:

**Comment by DaleEMoore** [comment] 2018-05-11 21:37
I'll make some suggestions, thanks!!

**Comment by karim** [comment] 2018-05-13 17:36
We can use some query parameters when opening a new issue. So far I have tested `template`, `labels`, `title`, and `assignee`. You can use one or all of them.

**Example**

https://github.com/sqlitebrowser/sqlitebrowser/issues/new?template=Bug_report.md&labels=bug,windows&assignee=karim&title=New+Bug+Report

We can generate the link dynamically on the app. For example, on Windows, it should add `windows` label, etc.

**Comment by martrs** [comment] 2018-11-27 02:41
It looks like SQL queries get saved, but when loading, they don't load.

 I verified this by looking at the saved file, which seems to be XML format, with `<tab_sql><sql name="SQL 1">SQL queries</sql>..`

**Comment by justinclift** [comment] 2018-11-27 02:54
Oh, that sounds like a bug.

**Comment by mgrojo** [comment] 2019-08-10 12:40
@DaleEMoore This is already working as expected. If you want to give it a try, install one of the [nightly builds](https://nightlies.sqlitebrowser.org/latest).

I'll close this since others have already confirmed that this case and the bug mentioned by @martrs  are working, but feel free to comment or reopen it if there is still some rough case.

**Closed by mgrojo** 2019-08-10 12:40 UTC
Labels: bug, enhancement
