### ISSUE TITLE
[Feature]: ER Diagram

### ISSUE THREAD

**Issue by Harum-Fatima** [sqlitebrowser/sqlitebrowser#3521] opened 2023-12-11 04:12 UTC
### Describe the new feature

ERD in essential in this tool

### Does this feature exist in another product or project? Please provide a link

yes, it is available in sql workbench

### Do you have a screenshot? Please add screenshots to help explain your idea.

no, i dont have any

**Comment by chrisjlocke** [comment] 2023-12-11 06:48
Check out https://github.com/nestorrente/erdiagram.
It supports SQLite.

**Comment by FriedrichFroebel** [comment] 2024-01-07 19:20
Appears to be a duplicate of #2034.

**Closed** 2024-09-28 09:20 UTC
