### ISSUE TITLE
Export/Import problem

### ISSUE THREAD

**Issue by Phil1988** [sqlitebrowser/sqlitebrowser#959] opened 2017-02-07 12:18 UTC
### Details for the issue

I have 2 Databases as *.db file that I want to merge.

On the first Database I use the export function (as SQL file instead of CSV) and export all tables I want, with NO "INSERT INTO" and NO "Multiple VALUES" seleced.
In the dropdown I chose "only data export" and export it.

In the 2nd Database I try to import as SQL file and it runs without any messages/hints/problems.
After the process is completed, there is only a small part in the new Database.

For example there is one column with an ID that has 2943 entrys.
After the import is "done" it has 507 entrys.
So somehow there are a lot of entrys lost during the export/import process.

I hope you guys can give me hints what I can try to get this working or if there are any knows issues and ways around it.

#### I'm opening this issue because:

- [x] DB4S has a bug

#### I'm using DB4S on:

- [x] Windows: 7 x64

#### I'm using DB4S version:

- [x] 3.9.1

#### I have also:

- [ ]  Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Tried out the latest portable version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by Phil1988** [comment] 2017-02-07 14:07
I tried the latest nightly (3.9.99) and get this error:

![error](https://cloud.githubusercontent.com/assets/6054234/22694338/2395c35c-ed47-11e6-9d42-01dfd1703092.PNG)

**Comment by justinclift** [comment] 2017-02-07 18:52
Thinking about this, I'm not completely understanding the process you're using.  It sounds like you're exporting the first database as a SQL file (no problem there), but there's no mention of how you're exporting the 2nd one.

As a general thought, the error you're mentioning ***seems*** like the kind of thing that happens when an exported CVS file doesn't have the correct delimiters.  (eg they're not set correctly in the dialog for the export, so the import goes wrong).  It might be worth double checking your export settings, just to be on the safe side, though I don't fully grok your end-to-end process yet. :wink:

**Comment by Phil1988** [comment] 2017-02-08 05:53
hey @justinclift ,
I didnt mention of exporting the 2nd database because I didnt export this.

Maybe my way is wrong but I thought I could go like this:
1. Export the first database (as SQL file)
2. Imtort the first database (as SQL file) into the 2nd database
3. Save as new database.
4. Merging completed :)

I have no idea what to change on the export process to work properly.

If I export the first database with  "INSERT INTO" or "Multiple VALUES" seleced or choosing "Export everything" on the dropdown, the import on the 2nd database doesnt work at all because the table is already existing.
So there is no other option then just choose "Export data only" on the dropdown and try to import it like this.

Its also weird that the error on the nightly seems like an CSV file with wrong delimters as I only uses SQL files to export and import (because CSV doesnt work at all).

I hope you guys can give me hints how to merge these two databases because I am somehow lost now.

**Comment by schdub** [comment] 2017-02-08 17:35
Hello, @Phil1988. Could you send me all necessary files (*.db and/or *.sql) to reproduce this issue?

**Comment by justinclift** [comment] 2017-02-09 23:37
@Phil1988 If you're ok with sharing the files with @schdub (or any other databases that give the same problem), he's very likely able to help. :smile:

**Comment by Phil1988** [comment] 2017-02-10 14:28
The problem is that I dont have any other databases/files to reproduce this issue and the databases I am trying to merge are Whatsapp databases with a lot of private data that I dont want to share.

Is there anything else I can do, to help you helping me? :D

**Comment by schdub** [comment] 2017-02-10 16:25
@Phil1988, could you send to me only schema of your tables, without data.

**Comment by Phil1988** [comment] 2017-02-11 13:55
I deleted every record of the databases so every data should be gone (hopefully :D ).

Here are the 2 databases, I hope you can find the problem here.
![database1 db](https://cloud.githubusercontent.com/assets/6054234/22854216/df0dad3c-f069-11e6-9116-c61aa1d3bcee.png)
![database2 db](https://cloud.githubusercontent.com/assets/6054234/22854218/e1fe2152-f069-11e6-95b6-c4d0d7349320.png)

I renamed them to *.png because uploading *.db files are not allowed and *. zip file didnt work...

Just download these files and rename them to *.db (I tested it and its working).

**Comment by schdub** [comment] 2017-02-11 15:51
I believe that the problems associated with the table messages_fts (CREATE VIRTUAL TABLE messages_fts USING FTS3()), which requires support of Full Text Search 3 extension. It is an assumption.

@Phil1988 remove your files by editing last message (databases still contains some of private data). Just use email next time.

**Comment by schdub** [comment] 2017-02-11 17:19
Is data lost in any of these tables:

messages_fts
messages_fts_segments
messages_fts_segdir
messages_fts_content

?

If yes. My guess, this is because you can't merge FTS 'Shadow Tables' without understanding how full-text search is implemented.
If no. Could you please research which tables is losing data.

**Comment by Phil1988** [comment] 2017-02-12 12:49
I dont know if one of there tables has some lost data because only the "chat_list" and "messages" tables are  important for that merging and I only tried to export and import these.

**Comment by schdub** [comment] 2017-02-12 14:15
@justinclift, still not enough data to understand what is going on in a particular case, but it seems to me that the problem is that at the time of import, while inserting rows with existing PK's doesn't output any error messages.

For example, lets create a table and add the 3 rows:

    CREATE TABLE `table` (`pk` INTEGER, `text` TEXT, PRIMARY KEY(`pk`));
    INSERT INTO `table` (`pk`, `text`) VALUES (1, 'a'), (2, 'b'), (3, 'c');

trying to import:

    BEGIN TRANSACTION;
    INSERT INTO `table` (`pk`, `text`) VALUES (1, 'X'), (2, 'Y'), (3, 'Z');
    COMMIT;

The import process will take place without any error messages, although it should be an error:

    UNIQUE constraint failed: table.pk: INSERT INTO `table` (`pk`, `text`) VALUES (1, 'X'), (2, 'Y'), (3, 'Z');

@Phil1988, is `messages` table contains rows with the same PK as in imported data?

**Comment by Phil1988** [comment] 2017-02-12 16:03
What is "PK" ? Primary Key?

The exported and the imported database have both the "_id" row as "INTERGER PRIMARY KEY AUTOINCREMENT".

**Comment by mgrojo** [comment] 2020-05-16 19:39
This is very old and using the steps provided by @schdub the nightly build reports the error given by SQLite: "UNIQUE constraint failed: table.pk." So I'm going to close this issue.

**Closed by mgrojo** 2020-05-16 19:39 UTC
Labels: export, import, question
