### ISSUE TITLE
Consistent crashes when viewing data in Firefox SQLite databases

### ISSUE THREAD

**Issue by Gitoffthelawn** [sqlitebrowser/sqlitebrowser#2910] opened 2021-11-28 02:34 UTC
Details for the issue
--------------------

#### What did you do?
Opened SQLite databases located in the `storage` folder of a Firefox profile.  Then went to the `Browse Data` tab in DB Browser for SQLite and attempted to use the `Table` dropdown list to view the data.

#### What did you expect to see?
To see the data within each table.

#### What did you see instead?
DB Browser for SQLite crashes.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: Win7
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

Extra extra information
-----------------------
A simple way I found to replicate this crash bug 100% of the time was to create a new Firefox (94.0.2) profile and then use a file manager to go to `..\storage\permanent\chrome\idb` within the browser's profile.  There will typically be 6 SQLite database files located in that folder.  DB Browser for SQLite will always crash when following the above steps (in "What did you do?") on at least one of them.

**Comment by chrisjlocke** [comment] 2021-11-30 12:01
This works OK for me...

![image](https://user-images.githubusercontent.com/7872218/144043430-2057b71c-262d-429d-acba-0720110c92cf.png)

Opening these databases does create WAL/SHM files.

![image](https://user-images.githubusercontent.com/7872218/144043650-95087286-5640-483d-8e31-cbb56f8d25d4.png)

I assume you're opening these files locally?  Do you have permissions to write into this folder?
As a test, if you copy a .sqlite database to the desktop, does it open OK then? Once opened, do you then notice the .WAL and .SHM files?

**Comment by Gitoffthelawn** [comment] 2021-12-01 01:59
Thank you so much for testing this.

> Opening these databases does create WAL/SHM files.

Same here.

> I assume you're opening these files locally?

Yes.

> Do you have permissions to write into this folder?

Yes.

> As a test, if you copy a .sqlite database to the desktop, does it open OK then?

Crashes there too.

> Once opened, do you then notice the .WAL and .SHM files?

Yes.

Did you have a chance to try all the `sqlite` files in the aforementioned folder (and its subfolders)?  Within each `sqlite` file, did you try selecting each table in the `Table` dropdown?  I experience crashes on about 20% of those `sqlite` files, and when viewing only 1 of the tables within each (the table that actually contains most of the important data).

If, after testing your `sqlite` files, you still don't have any that cause a crash, I can work on seeing if I can create a test `sqlite` file for you that replicates the crash.

Thank you again for looking into this.

**Comment by chrisjlocke** [comment] 2021-12-01 11:53
Yay!  Found one.
2918063365piupsah.sqlite

Opens fine, passes an integrity check, etc, but if I browse to 'index_data', it crashes every time.
I don't know what it crashes with, or where, as I run it in Windows, and it's not very informative when it comes to errors.  But it can be reproduced.

I've tried to compact the database (which rebuilds it), but it still crashes, so unsure if it's just something wacky in the data.  Viewing it in the Execute SQL tab is fine.  It's only two records.

![image](https://user-images.githubusercontent.com/7872218/144229889-492224bc-0809-4c30-82df-01ed8e4e87a9.png)

Happens in the release and nightly.

**Comment by chrisjlocke** [comment] 2021-12-01 11:59
Database is here if anyone else wants to confirm/deny/tinker.
https://dbhub.io/chrisjlocke/2918063365piupsah.sqlite

**Comment by justinclift** [comment] 2021-12-01 14:23
Interesting.  We should definitely take a look at that with a debugging and see what's going on.

@MKleusberg @mgrojo @scottfurry Any interest? :smile:

**Comment by Gitoffthelawn** [comment] 2021-12-01 21:54
> Yay! Found one. 

Yay!

It makes it so much easier when there is independent confirmation.  Many thanks.

BTW, as one would expect, I experience the crash with the PortableApps release as well.

**Comment by chrisjlocke** [comment] 2021-12-01 22:29
The portableApps version is the same as the 3.12.2 version, but with an additional 'wrapper' program around it - it's essentially exactly the same build.  I would expect different results with the nightly though, as that's an entirely different codebase.

**Comment by mgrojo** [comment] 2021-12-23 18:20
Martin solved this in 0b1ff64138ad0ba7d3ec01e8e310f597c1425449 (issue #2832), so I'll close this as a duplicate of #2832. The problem is solved in recent nightly versions.

**Closed by mgrojo** 2021-12-23 18:20 UTC
Labels: bug, crash, browse data

**Comment by Gitoffthelawn** [comment] 2021-12-24 01:51
Thank you!

No pressure at all... just wondering... do you have a guesstimate of when the next official release will take place?

**Comment by justinclift** [comment] 2021-12-24 02:02
Hopefully in the first few months of 2022. :smile:

**Comment by Gitoffthelawn** [comment] 2021-12-24 05:25
@justinclift My thought on releases is typically to release as soon as practicable when crashes are fixed, even if it means only including some patches.  But, of course, I realize it's not always that simple and that every release certainly involves a time commitment.

Regardless of when you release, I thank you for the helpful tool.

**Comment by Gitoffthelawn** [comment] 2022-07-15 00:12
@justinclift Any chance of a release?  Got hit by these crashes again, and was finishing another bug report before I realized that the current release version is still the same as the one that was released over a year ago.

**Comment by chrisjlocke** [comment] 2022-07-15 06:24
But as you're on Windows, can't you use the nightly version?  This issue is fixed in the nightly.  The only issue with the nightly (and not sure from when) is with project files.  Have you tried the nightly at all?
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip
You can just extract this .zip and run 'as is' - no need to install, uninstall the previous version or any nonsense.

**Comment by Gitoffthelawn** [comment] 2022-07-15 06:46
@chrisjlocke Thanks Chris. Are the nightlies stable enough to use on a regular basis?  For most projects, nightlies are considered to be untested alpha-level quality, but perhaps this project is different.

Also, I use the PortableApps.com version.  Can the nightly executable be dropped into the PortableApps.com platform and work as expected?

**Comment by chrisjlocke** [comment] 2022-07-15 10:58
The nightlies are generally OK - as above, the only issue is with project files at the moment, but if that's an issue, it'd probably be possible to find a nightly that isn't broken in this regard that has the above fix from Sep 2021.  Or grab a nightly shortly after Sep 2021... ;)
The nightlies contain small regular fixes and tweaks rather than a hodge-podge of untested code.  

As for simply replacing the .exe, you _might_ have to update some of the Qt libraries or DLLs, but I'm guessing not.  I can test on my machine and let you know.

**Comment by mgrojo** [comment] 2022-07-16 17:13
> The nightlies are generally OK - as above, the only issue is with project files at the moment, but if that's an issue, it'd probably be possible to find a nightly that isn't broken in this regard that has the above fix from Sep 2021.

What's exactly that issue with project files? I'm not aware of that.

**Comment by chrisjlocke** [comment] 2022-07-16 18:25
If you create a new database, save it, create a project file, close it/everything, then open that project file again, DB4S just wobbles and falls over.
https://github.com/sqlitebrowser/sqlitebrowser/issues/3007

**Comment by justinclift** [comment] 2022-07-30 08:01
> @justinclift Any chance of a release?

Yeah.  I'm catching up some really overdue stuff first (fixing our nightly builds + M1 ARM64 macOS/Win builds).  Then we can start thinking about the next release. :smile:

**Comment by mgrojo** [comment] 2022-07-30 15:58
> If you create a new database, save it, create a project file, close it/everything, then open that project file again, DB4S just wobbles and falls over. #3007

I only reproduce this error message: 
> "Database didn't close correctly, probably still busy"
I will try to avoid that, and maybe it's the solution to the crash.

**Comment by Gitoffthelawn** [comment] 2022-07-30 23:47
@justinclift  Good to hear!  BTW, I noticed nightlies started rolling out again. 👍🏾

**Comment by justinclift** [comment] 2022-07-31 00:31
Nah, the nightlies are busted at the moment.  Working on it today. :wink:

**Comment by Gitoffthelawn** [comment] 2022-07-31 02:28
@justinclift Great! I wonder what I saw... they were some sort of automated GitHub nightly build things for this repo... I thumbed up and hearted a couple of them because I thought they were signs of successful progress! :) :) :)  Admittedly, my motto is "heart now, look closely later". Because our world needs more love. :heart: :)
