### ISSUE TITLE
Sql Log Not support Retina In Mac

### ISSUE THREAD

**Issue by ios122** [sqlitebrowser/sqlitebrowser#498] opened 2016-01-19 03:04 UTC
Sql Log Not support Retina In Mac.Any Way, It's  A great 产品!

**Comment by justinclift** [comment] 2016-01-19 03:08
Thank you for reporting it.  Would you be ok to do a screenshot, to show us? :smile:

**Comment by ios122** [comment] 2016-01-19 09:48
The area of Log , is blur 
<img width="683" alt="2016-01-19 5 45 00" src="https://cloud.githubusercontent.com/assets/14146896/12415110/b2e29aa0-bed4-11e5-99b6-c8d8e2b88c26.png">
<img width="476" alt="2016-01-19 11 03 03" src="https://cloud.githubusercontent.com/assets/14146896/12415109/b2d1bb72-bed4-11e5-9fd5-e2845e88be24.png">

**Comment by ios122** [comment] 2016-01-19 09:49
maybe the picture can't reflect it, if somebody don't see the picture in retina

**Comment by justinclift** [comment] 2016-01-19 10:34
Thank you, that helps.

Yeah, the text does look blurry. :frowning:

Is there any improvement if you use different fonts?

**Comment by ios122** [comment] 2016-01-19 11:18
苹方-简体中文  my font

**Comment by nickberry17** [comment] 2016-04-26 02:24
Hello, I seem to have a fix for this issue.

Iit's my first time submitting code to a community project, so if this is the wrong channel, I am sorry.

I use sqlitebrowser in a course at my university, and noticed the problem.  The cause of this issue was the Scintilla Editor output being drawn to a buffer which as it seems was not being scaled correctly. (Source: http://scintilla-interest.narkive.com/Yb4Qbh9h/scintilla-gtk-on-retina-displays)

I managed to fix the issue by setting `bufferedDraw = false` in `EditView.cpp`, in the Scintilla library.  I'm unsure if modifying the bundled library is this is within this project's constraints though.  (The modification to the app.plist file does not affect rendering or buffering within Scintilla).

In my fork, I also made some other changes to the default font size, bumped from 8 to 13 in the editor, and up to 12 in the data view.  Perhaps we could add a menu item for "High DPI mode" or some such so it's not the default for people on machines that lack high dpi support?

The before/after images are at the top of this, including the unit tests, which all passed.  I do hope this can be added, as I've seen a couple of other people reporting this issue.

https://github.com/nickberry17/sqlbrowser_with_Retina_support

Before:
<img width="1328" alt="screen shot 2016-04-25 at 5 11 32 pm" src="https://cloud.githubusercontent.com/assets/18670565/14804675/cba472fe-0ba8-11e6-8350-3954c48d7a55.png">
After:
<img width="1328" alt="screen shot 2016-04-25 at 5 11 59 pm" src="https://cloud.githubusercontent.com/assets/18670565/14804678/d052c274-0ba8-11e6-9868-b9ab0cf3d3db.png">
Unit Tests:
<img width="542" alt="unittests" src="https://cloud.githubusercontent.com/assets/18670565/14804684/dacde5f8-0ba8-11e6-933d-708085cf5647.png">

**Comment by justinclift** [comment] 2016-04-26 12:05
@nickberry17 Yep, that's very helpful.  The "perfect" approach here would be for you to create a "Pull Request", with the code changes you've made in it.  That lets us directly merge them into our source code here, so they become part of the main project forever. :smile:

Looking at your fork of the project, it seems like you're still coming to grips with using git.  That can be a painful experience until it "clicks" and you get the hang of it (it was for me! :frowning:).

If you're up for continuing your journey of learning git, this is how to do a Pull Request:

&nbsp; &nbsp; https://help.github.com/articles/using-pull-requests/

If you'd rather not just right now (it's ok), let us know and either @MKleusberg or myself can look at coping across the changes manually.  (we'd probably need to ask follow up questions about which bits exactly/etc)

Workable? :smile:

**Comment by nickberry17** [comment] 2016-04-26 12:47
That's awesome!  :smile:

I am working on the pull request, just going to try and squash my git commit history first, per the developer wiki.  For this commit, I'll just disable the `bufferedDraw`, so the rest of the settings stay the original defaults (they are more of a personal preference, and I wouldn't want to impose).

I'd be delighted to test out the nightlies for the next builds as well. :smile:

Cheers!

**Comment by justinclift** [comment] 2016-05-17 19:31
Closing this, as @nickberry17 fixed it in #575.

**Closed by justinclift** 2016-05-17 19:31 UTC
Labels: bug, osx
