### ISSUE TITLE
Plot when values are NULL

### ISSUE THREAD

**Issue by wolfc01** [sqlitebrowser/sqlitebrowser#512] opened 2016-02-08 13:22 UTC
Hello,

in attached database, i perform the attached query. 

[test_db.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/121597/test_db.zip)

**Comment by justinclift** [comment] 2016-02-08 19:33
This is a duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/513 isn't it?  If so, is it ok to close this one? :smile:

**Comment by MKleusberg** [comment] 2016-10-13 20:42
Closing this as duplicate.

**Closed by MKleusberg** 2016-10-13 20:42 UTC
Labels: duplicate
