### ISSUE TITLE
Execute SQL doesn't play nicely with one-line comments

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [sqlitebrowser/sqlitebrowser#1004] opened 2017-05-03 08:25 UTC
Single-line SQL comments cause peculiar behaviour if run in the "Execute SQL" tab.

Say I run the following:
`-- This comment prevents line count working and "changes the database"`
`SELECT * FROM events WHERE logid=81991 AND type='content'`
then 
- I don't get the usual "N rows returned" message
- the database is locked and Write/Revert changes are enabled
- the correct result is returned

Alternatively, if I run:
`SELECT * FROM events WHERE logid=81991 AND type='content'`
`-- This comment causes an error`
then 
- I get an "Error executing query: ..." response
- no result is returned

In this case I can see that the SQL submitted by the application has had the line breaks removed, so the extra `SELECT COUNT(*) ...` that's added to give a line count is syntactically wrong, as the terminating `);` has become commented-out.

Finally (so far), if I try to execute:
`SELECT 40+2 -- get the answer`
`AS answer`
(N.B. `AS` is at the start of the line) then 
- I get an "Error executing query: ..." response
- no result is returned

In this case the comment and newline have been removed completely, with the result that what's executed is `SELECT 40+2AS answer` (no whitespace between `2` and `AS`).

I'd suggest the quick approach is to replace single-line comments with a single space, if you don't mind them being discarded from the submitted SQL. If you want to leave them in then you can't discard the newlines, as they're syntactically significant...

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 7___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment] 2017-05-03 09:14
This should be fixed in the latest version.  v3.9.1 is quite old now (v3.10 is due soooon!)

![image](https://cloud.githubusercontent.com/assets/7872218/25654381/b7fabc94-2fe8-11e7-8bb1-bf350c3b0a16.png)

Try downloading from one of the latest nightlies:
https://nightlies.sqlitebrowser.org/win64/ or https://nightlies.sqlitebrowser.org/win32/

**Comment by justinclift** [comment] 2017-05-03 09:17
@h4yn0nnym0u5e Do you have the time & interest to try out the latest nightly build, and double check that it works properly for you? :smile:

If so, the nightly builds are here:

* https://nightlies.sqlitebrowser.org/win32/
* https://nightlies.sqlitebrowser.org/win64/

**Comment by h4yn0nnym0u5e** [comment] 2017-05-03 14:22
@justinclift: OK, I've tried the nightly win64 and it fixes the latter two, but not the first one. I'm slightly wrong now in the report title, as the first problem is also caused by a `/* block comment */` at the start, so it's not specific to the `-- line comment`. I've double-checked that the database is locked until I Revert Changes.

I've also found another case:
`SELECT '-- cause error'`
causes an error!

**Comment by chrisjlocke** [comment] 2017-05-03 14:36
>I've also found another case:

Yes, that appears to get executed as `SELECT COUNT(*) FROM (SELECT ');` - everything right of the -- is deemed part of the comment.  Ooh.

**Comment by justinclift** [comment] 2017-05-03 15:18
Awesome, so we're making progress in the right direction at least.  But, still a bit further to go. :smile:

@revolter Any interesting in following this up?  I'm kind of guessing this is related to your comment stripping regex bits from a while back?

**Comment by revolter** [comment] 2017-05-03 18:37
You can have block comments in SQL?! 😲 

@justinclift, Surely it is 😢  But I don't know how to solve other more complex cases like `SELECT 'this -- causes error'`.

**Comment by h4yn0nnym0u5e** [comment] 2017-05-03 21:08
I don't have the ability to re-compile from source, but I've been playing with regexes a bit in Python, and I think
 `^((?:(?:[^'-]|-(?!-))*|(?:'[^']*'))*)(--.*)$` 
yields two captured groups, the first is the SQL code and the second is the line comment. This relies on NOT concatenating the lines of a multi-line SQL statement (remove the line comments before concatenation, assuming this is being done).

As far as I can tell this is a legal regex in Qt. I tested it against the following:
`SELECT 'string -- not a comment '' - single quote'  -- comment 'not a string' -- not the whole comment`
Note that the regex doesn't match the SQL if there's no comment, e.g.:
`SELECT 'string -- not a comment '' - single quote'  `

@revolter  You can indeed have block comments, see [http://sqlite.org/lang_comment.html](url). I haven't played with removing those but I suspect one could construct similar tricky cases there, too!

**Comment by justinclift** [comment] 2017-05-03 22:23
Thanks @h4yn0nnym0u5e, that's awesome. :smile:

**Comment by revolter** [comment] 2017-05-04 09:54
From what I remember, it doesn't concatenate the lines prior to removing comments.

I hoped for QScintilla to have something to remove comments, knowing it already detects and highlights them, but I didn't find any function that does this.

And, nice regex you have there, could you please explain it a bit? As I only understand them best when I write them.

**Comment by h4yn0nnym0u5e** [comment] 2017-05-04 11:27
Here you go, @revolter - like any code, regexes are pretty much write-only! I think there are ways to comment them, but I'm too lazy usually...
```
^((?:(?:[^'-]|-(?!-))*|(?:'[^']*'))*)(--.*)$
^                                          $ # anchor beginning and end of string so we use it all
 (                                  )(    )  # two separate capture groups for code and comment
                                      --.*   # comment starts with -- and consumes everything afterwards
  (?:                 |           )*         # code is none or many strings alternating with non-strings
                       (?:'[^']*')           # a string is a quote, followed by none or more non-quotes, followed by a quote
     (?:[^'-]|-(?!-))*                       # non-string is a sequence of characters which aren't quotes or hyphens, 
                                               OR if they are hyphens then they can't be followed immediately by another hyphen
```

**Comment by justinclift** [comment] 2017-05-14 17:19
@revolter This is @h4yn0nnym0u5e's commit pared back to just the changes, if you've time to look through them: https://github.com/justinclift/sqlitebrowser/commit/5748daf66180d3afaf0cf8f0eebecf82575c72b1

:smile:

**Comment by justinclift** [comment] 2017-08-10 09:43
@MKleusberg Hmm, I'm kind of thinking we should probably get this fixed for the 3.10.0 release.

Thoughts?

**Comment by MKleusberg** [comment] 2017-08-10 18:33
Sure. I'll look into it :smile: Already managed to reproduce the two remaining errors.

**Comment by MKleusberg** [comment] 2017-08-10 18:54
I've just cleaned up the commit that Justin is linking to and pushed it to master. In my first tests this fixed all the remaining issues that are mentioned above and didn't break anything else :smile: Anyone interested in testing it some more?

@h4yn0nnym0u5e Thanks a lot for your work here, especially with the reg ex! 👍

**Comment by justinclift** [comment] 2017-08-10 19:27
Ahhh, interestingly this is causing the build to fail on our in built regex unit test:

```
3: Test command: /home/travis/build/sqlitebrowser/sqlitebrowser/build/src/tests/test-regex
3: Test timeout computed to be: 9.99988e+06
3: ********* Start testing of TestRegex *********
3: Config: Using QtTest library 5.7.1, Qt 5.7.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 4.8.4)
3: PASS   : TestRegex::initTestCase()
3: FAIL!  : TestRegex::sqlQueryComments(test1) Compared values are not the same
3:    Actual   (dirtyQuery): "SELECT * \n\n\nFROM \t\nqwfwqf"
3:    Expected (clearQuery): "SELECT *\nFROM\nqwfwqf"
3:    Loc: [/home/travis/build/sqlitebrowser/sqlitebrowser/src/tests/TestRegex.cpp(43)]
3: FAIL!  : TestRegex::sqlQueryComments(test2) Compared values are not the same
3:    Actual   (dirtyQuery): "SELECT *\nFROM\n\n\nqwfqwf"
3:    Expected (clearQuery): "SELECT *\nFROM\nqwfqwf"
3:    Loc: [/home/travis/build/sqlitebrowser/sqlitebrowser/src/tests/TestRegex.cpp(43)]
3: PASS   : TestRegex::cleanupTestCase()
3: Totals: 2 passed, 2 failed, 0 skipped, 0 blacklisted, 1ms
3: ********* Finished testing of TestRegex *********
3/3 Test #3: test-regex .......................***Failed    0.01 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =   0.04 sec

The following tests FAILED:
	  3 - test-regex (Failed)
Errors while running CTest
```

Seems like the whitespace is now different from expected.  In the two tests above, they seem (from eyeballing) like they'd be valid SQL though and return the same result if run. (?)

**Comment by MKleusberg** [comment] 2017-08-10 19:35
Yes, both versions of the SQL would be valid but the expected one is... well... what you would expect: no multiple line breaks in the middle of the query and no unnecessary whitespace at the end of a line. So I've just added a bit of code to make sure we produce the same expected version as before while still having the better regex by @h4yn0nnym0u5e :smile:

**Comment by MKleusberg** [comment] 2017-08-10 19:41
I've just added the problem descriptions from this issue as test cases, too. So if we change the regular expressions in future in a way that would break it again, we would get a warning.

**Comment by justinclift** [comment] 2017-08-10 19:48
Ahh, good move. :smile:

**Comment by h4yn0nnym0u5e** [comment] 2017-08-11 21:07
Hmmm - my mistake. Shouldn't have the `+ rxSQL.cap(3)` on line 649, as the SQLite rule says the -- comments include the newline. Slightly weird, but that's what they say... That should remove the need for lines 660/661.

Apologies, have totally mucked up my copy of the repository and failed to grok Git, otherwise I'd try to fix it myself.

**Comment by justinclift** [comment] 2017-08-12 10:08
No worries @h4yn0nnym0u5e, you got us most of the way. :smile:

**Comment by MKleusberg** [comment] 2017-08-12 11:13
Hmm, removing the ```+ rxSQL.cap(3)``` alone doesn't work because it generates invalid SQL commands if there is no space before the start of the comment:
```sql
SELECT *-- no space before the comment
FROM test;
```

But just adding a space doesn't seem right either because it generates multiple spaces if there are multiple one line comments. Not sure right now what the best/easiest solution would be.

**Comment by h4yn0nnym0u5e** [comment] 2017-08-13 10:11
@MKleusberg has the right of it, removing the `+ rxSQL.cap(3)` alone doesn't work. The problem is the purported SQLite comment treatment is wrong and can result in changed / invalid syntax. 

I'd vote for removing 660/661 and changing the test code to expect what it actually gets:  I can't see any particular downside in leaving multiple newlines in the output... 660-664 will also remove trailing whitespace and multiple newlines even where there was previously no comment, just the newlines, so the function name removeCommentsFromQuery() becomes fractionally misleading (albeit in a way that's probably totally unimportant!).

**Comment by justinclift** [comment] 2017-08-20 18:35
Hmm... is this still something that needs further effort (eg add this to the tracker for the next milestone), or should we close it? :smile:

**Comment by justinclift** [comment] 2017-11-17 17:03
k, closing this then. :smile:

**Closed by justinclift** 2017-11-17 17:03 UTC
Labels: response requested, windows
