### ISSUE TITLE
WHERE Name LIKE 'A%'

### ISSUE THREAD

**Issue by arsalabdollahi** [sqlitebrowser/sqlitebrowser#1907] opened 2019-05-22 20:23 UTC
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17763) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by arsalabdollahi** [comment] 2019-05-22 20:26
WHERE statement starts with this condition but returns results that do not begin with 'A' character

**Comment by chrisjlocke** [comment] 2019-05-22 21:00
Can you provide a screenshot of what you're seeing?  Images can be pasted here.
Note that the subject of this post has a closing quotation mark rather than an apostrophe, but I'm assuming that's just a typo here, and not an exact copy of what you were entering.

**Comment by chrisjlocke** [comment] 2019-05-22 21:01
Also (but hopefully the screenshot will show) where are you entering this WHERE statement - in the 'Execute SQL' tab, or as a filter?  Providing as much information as possible (preferably with steps to reproduce the error) helps us a lot in solving problems.

**Comment by arsalabdollahi** [comment] 2019-05-22 21:32
> Also (but hopefully the screenshot will show) where are you entering this WHERE statement - in the 'Execute SQL' tab, or as a filter? Providing as much information as possible (preferably with steps to reproduce the error) helps us a lot in solving problems.

Solved! 

I had the output and was asked to write a statement that generates the result. The issue was with which condition comes first and how to separate conditions with parenthesis.
Is there such a thing as "order of conditions" in SQL queries?

**Comment by justinclift** [comment] 2019-05-23 02:59
Hmmm, it kind of depends. :wink:

As a thought, have you seen this?

&nbsp; &nbsp; https://a-gentle-introduction-to-sql.readthedocs.io/en/latest/part1/querying-data.html#the-where-clause

That's the intro piece for `WHERE` clauses, so you've probably got that already.  Some of the pages after it expand things out though, which could be helpful. :smile:

**Comment by chrisjlocke** [comment] 2019-05-23 06:37
What is the answer you have to get to, and what have you tried?
Some more information would be super helpful.... you remind me of my wife
when she hands me the car and says, "can you fix it as its doing that thing
again" "What thing?" "Aah, i never told you, but it was doing it the other
week, and now its doing it again..." So do I just start with the dipstick
and work my way through to the rear windscreen? haha!

>

**Comment by chrisjlocke** [comment] 2019-05-29 05:15
Closing due to the original query (no pun intended...) being solved.

**Closed by chrisjlocke** 2019-05-29 05:15 UTC
