### ISSUE TITLE
DB Browser for SQLite crashes if browsing data of table with strange characters

### ISSUE THREAD

**Issue by gelupist** [sqlitebrowser/sqlitebrowser#2832] opened 2021-09-08 07:57 UTC
Details for the issue
--------------------

#### What did you do?
I tried to browse the fts_search6_idx table in the attached db. 
A csv export of this data is possible (see fts_search6_idx.csv)
The field term in row 212 and 384 of fts_search6_idx.csv contains strange characters.
If these lines are deleted in the table fts_search6_idx with a SQL script DB Browser for SQLite does not craches any more.
[Attachement.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/7127009/Attachement.zip)

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19043) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by justinclift** [comment] 2021-09-09 03:05
Interesting, sounds like a bug of some sort.  Hopefully one of our main developers will have a chance to look at this over the next few days/weeks. :smile:

**Comment by i-s-o** [comment] 2021-09-09 14:18
I took a quick look at the attached file. Here are my observations:

* The contents of the table `fts_search6_idx` in the attached DB do not match the contents of `fts_search6_idx.csv`.
* The attached `fts_search6_idx.csv` contains two sequences of bytes that are invalid in UTF-8:
  * Row 212: 0xEFBFBD
  * Row 384: 0xEFBFBD
  * I can use `File>Import` in DB4S to import this file, and the browse without problem. Since those two elements are invalid strings, they simply show up as � without crashing DB4S: It is likely that the existing table `fts_search6_idx` was created via different means.
* The crash is caused by the following two data elements (i.e. this is still a bug in `Browse Data`):
  * 0x30E3
  * 0x31E3
  * These can be displayed without problem (as *BLOB*) in `Execute SQL`:
    * `select *, hex(term) as term_hex from fts_search6_idx where segid = 5 and pgno in (148, 230);`
* If these two records are deleted, the `Browse Data` shows the table `fts_search6_idx` without crashing DB4S.
  * `delete from fts_search6_idx where segid = 5 and pgno in (148, 230);`

**Comment by justinclift** [comment] 2021-09-09 15:11
Awesome, that sounds like really good, thorough investigation @i-s-o. :smile:

**Comment by i-s-o** [comment] 2021-09-09 18:37
One more observation: this seems to be related to `WITHOUT ROWID` option of `CREATE TABLE`.

* To replicate the crash:
  * Start a new in-memory DB.
  * Execute the following:
    ```sql
    CREATE TABLE IF NOT EXISTS 'fts_search6_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
    INSERT INTO fts_search6_idx VALUES(5,X'30e3',148);
    ```
  * Click on `Browse Data` => crash

* No crash:
  * Start a new in-memory DB.
  * Execute the following:
    ```sql
    CREATE TABLE IF NOT EXISTS 'fts_search6_idx'(segid, term, pgno, PRIMARY KEY(segid, term));
    INSERT INTO fts_search6_idx VALUES(5,X'30e3',148);
    ```
  * Click on `Browse Data` => no crash

**Comment by gelupist** [comment] 2021-09-10 07:40
Hi i-s-o
Thank you for the fast reply. The file fts_search6_idx.csv was created by "export as csv file" of the table fts_search6_idx in  DB4S, and not vice versa. The table  fts_search6_idx is part of a fulltext functionality FTS5 of SQLite and was automatically filled by this functionlity. The db is the library.db of Emby.  rmaybe the export funktion alters the data due to the fact that the data is BLOB and not text, which ist expected by csv. Kind Regards

**Comment by chrisjlocke** [comment] 2021-09-11 10:44
> Can you give it a try? You'll find it here.

You won't find it there, so ignore that for the time being ... the nightlies are currently broken, so unless you can build them yourself, you may have to wait for a short while ....

**Comment by gelupist** [comment] 2021-09-11 18:31
@MKleusberg Thanks for the explanations. I will try as soon as I can download this build. I got a mail from Chris Locke telling that  the nightlies are currently broken,
@i-s-o You are right  the contents of the table fts_search6_idx in the attached DB do not match the contents of fts_search6_idx.csv. I must have confused the versions, sorry for that, and thanks for the analysis. 

An other thing is that the export to csv function  converts 0x30E3 to 0x30EFBFBD. I could reproduce this in a smaler db. In the attached zip file.

`select *, hex(term) as term_hex from A_fts_search6_idx`  shows 30E3 in term_hex
`select *, hex(term) as term_hex from A_ReimportCSVfts_search6_idx;` shows 30EFBFBD in term_hex. If you inspect the files A_fts_search6_idx.csv or B_fts_search6_idx.csv you will find 30 EF BF BD between the delimiters 3B (;) at the expected location.

**Comment by i-s-o** [comment] 2021-09-11 21:04
@gelupist I have a suspicion this is a glitch in Emby (or FTS5). In your original file, thiese are the sequence of rows around errors:

segid|term|pgno|term_hex
-|-|-|-
5|0window|144|3077696E646F77
5|0xx|146|307878
5||148|30E3
5|12|150|3132
5|14|152|3134

segid|term|pgno|term_hex
-|-|-|-
5|1w|226|3177
5|1x|228|3178
5||230|31E3
5|275|232|323735
5|2an|234|32616E

To me, it looks like 0x30 and 0x31 were supposed to represent "0" and "1", followed by one or more *characters*. Yet, they are both followed by 0xE3, which is an invalid byte in UTF-8 (it would have been valid byte in Windows-1252 or iso-8859-1 code pages, representing *A with tilde: ã*). Being invalid UTF-8 byte sequences, Sqlite3 interprets them as *BLOB*s.

That's why I think that this was originally a problem created by FTS5 (or Emby): they were supposed to write a valid sequence of bytes in UTF-8. It is also possible that while writing a valid sequence there was "glitch" and the data got corrupted as it was being written. I tried Emby on my system: it didn't create any records in `fts_search6_idx` that were *BLOB*s.

On a separate note, when I export `fts_search6_idx` from your original attachment, I get MOM= (0x4D4F4D3D) and MeM= (0x4D 654D3D) in the csv file. Note that these are the base64 representations of 0x30E3 and 0x31E3. Since I have never exported from DB4S before, I don't know if this is the expected behavior. Maybe this is related to the JSON conversion mentioned by @MKleusberg: if I export the table as JSON, all the values for `term` are saved as base64 values:

```js
...
    {
        "pgno": 144,
        "segid": 5,
        "term": "MHdpbmRvdw=="
    },
    {
        "pgno": 146,
        "segid": 5,
        "term": "MHh4"
    },
    {
        "pgno": 148,
        "segid": 5,
        "term": "MOM="
    },
    {
        "pgno": 150,
        "segid": 5,
        "term": "MTI="
    },
...
```

**Comment by justinclift** [comment] 2021-09-12 13:30
The window nightly builds are working again now, if that helps:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by gelupist** [comment] 2021-09-12 19:53
I could test with the version 3.12.99  (12 sept). No more crash. Thanks a lot!!!
I agree with i-s-o, the non UTF-8 caracters could be a glitch of emby or fts5.

**Comment by gelupist** [comment] 2021-09-13 15:12
For your information
I found a utility to repair the fts tables.
https://github.com/simonw/sqlite-utils
With
sqlite-utils rebuild-fts library.db
The fts_search6_idx has been  rebuilded without the non UTF-8 characters.
After a first try this had no impact to the search function in emby.

**Comment by mgrojo** [comment] 2021-12-23 18:22
This seems confirmed as fixed, so I'll close it now, but feel free to reopen it or open a new issue, if some problem is still pending.

**Closed by mgrojo** 2021-12-23 18:22 UTC
Labels: bug, browse data
