### ISSUE TITLE
CSV Import bug - final row being missed

### ISSUE THREAD

**Issue by harysutanto** [sqlitebrowser/sqlitebrowser#193] opened 2015-02-05 08:51 UTC
OS : OS X Yosemite 10.10.2
SQLiteBrowser Ver : 3.5.0

There's a bug when importing CSV files to database that the last record is not imported. Say that I have 10 records, then only 9 of them is imported, 20 records and only 19 imported. I use another SQLite browser app and the import works fine. Maybe you can work this bug out, I really love using your app for simplicity and easy to use.

This case is not always btw. I also have another CSV file that has 5 records in it, but all of them is imported. Maybe the bug occurs when the total records number exceeds certain number.

Also one more, when let's say I have 60 records in CSV file, when I click import there's a preview (when I was asked to name the table that is imported) of the records that's inside the CSV. But the preview only shows 19 of them, not all, even though the preview is in a scroll view. Maybe you can work this too so that it shows all of the records in the preview. Obviously when I import, only 59 of the records imported.

Thanks for your work on this app! Keep up the good work, and have a nice day!

**Comment by rp-** [comment] 2015-02-05 09:09
Hi!

Can you provide such a CSV file? Maybe as real download, pasting it somewhere might ruin the linebreaks.

**Comment by harysutanto** [comment] 2015-02-05 10:01
Ok. Here is the CSV file with 10 records, and only the first 9 is imported.

CSV file is generated using Apple's Numbers app on OS X.

https://www.dropbox.com/s/e8pad14efeki5e7/ZWATCHACTIVITY.csv?dl=0

**Comment by rp-** [comment] 2015-02-05 14:15
Thanks, I think I got it, looks like a stupid mistaken variable.

**Comment by rp-** [comment] 2015-02-05 14:59
should be fixed: 8d55fd5c48ef9ac5f94edfbe0af463dacf071593

**Comment by harysutanto** [comment] 2015-02-05 15:20
Thanks for the fix!

**Comment by justinclift** [comment] 2015-02-06 18:01
@harysutanto Sounds like this was just a simple mistaken variable bug, so should be fixed now.  However, just to be 100% sure, would you be ok to test with the latest nightly and confirm back if it's ok or not? :smile:

**Comment by harysutanto** [comment] 2015-02-07 04:12
Oh yeah, I already tested using the Feb 06, 2015 nightlies, and the problem is fixed but forgot to post here. Silly me!

Anyway, Thanks again for the fix!

**Comment by justinclift** [comment] 2015-02-07 13:37
Awesome. :grinning:

**Comment by T1mL3arn** [comment] 2019-10-29 13:09
Did want to create the same issue, but it is already here. Looks like it is needed to be reopen.

## The problem

Final row is missed when importing csv file.

## How to reproduce

1. create csv file with just one row, e.g
```
hello
```
2. Try to import it
3. See no rows at all in the import dialog

## Additional info

If add new empty line to the file, e.g
```
hello
# here is an empty line, the comment just to emphasize it
```
then import works.

The [csv standard](https://tools.ietf.org/html/rfc4180#section-2) says the last record may or may not have an ending line break.

## Tech info

WIndows 8.1, DB4S nightly Version 3.11.99 (Oct  3 2019)

**Comment by MKleusberg** [comment] 2019-11-14 16:47
Thanks for pointing this out, @T1mL3arn! Can you check again with tomorrow's nightly build and see if it's working for your CSV file? :smile:

**Comment by T1mL3arn** [comment] 2019-11-20 05:16
Tested. Didn't see the issue anymore.

**Comment by justinclift** [comment] 2019-11-20 08:04
Awesome.  Thanks for verifying things @T1mL3arn!  Well done @MKleusberg. :smile:

**Comment by MKleusberg** [comment] 2019-11-20 10:50
Cool, thanks for testing! I'm closing this issue again then :smile:

**Closed by MKleusberg** 2019-11-20 10:50 UTC
Labels: bug
